### ISSUE TITLE
Need new feature cts:registered-query()

### ISSUE THREAD

**Issue by cj96248** [marklogic/java-client-api#1000]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
4.1.0

### Version of MarkLogic Server
8.03

### Java version
1.8

### Need new feature

`StructuredQueryDefinition` need cts:registered-query(). 
I have the register ids. We are using the register-query like this `cts:search(//function,
    cts:registered-query(1234567890123456,"unfiltered"))`, but the current version can't support `registered-query( )` in `StructuredQueryDefinition`

**Comment by ehennum** [comment]
Registered ids are volatile and thus problematic on the client.

These days, a better approach is to encapsulate the query registration within a data service endpoint.
