### ISSUE TITLE
Getting "Internal Server Error" while trying to load the index options to an existing database.

### ISSUE THREAD

**Issue by anu3990** [marklogic/java-client-api#1009]
So we can address your issue, please include the following:
### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

### Input: 
curl --anyauth --user admin:admin -X PUT -d@"../database-config.json" -i -H "Content-type: application/json" "http://localhost:8002/manage/v2/databases/top-songs-content/properties"

### Actual output: 
![image](https://user-images.githubusercontent.com/19510878/46050168-6b997e80-c0e7-11e8-97e9-61793904b608.png)

[db-config.pdf](https://github.com/marklogic/java-client-api/files/2417576/db-config.pdf)

**Comment by anu3990** [comment]
I found this while trying to duplicate a different Java Api issue. It is a regression in the product but it is not a test regression.

**Comment by anu3990** [comment]
Added changes to the payload.
[database-config.pdf](https://github.com/marklogic/java-client-api/files/2421207/database-config.pdf)

**Comment by rjrudin** [comment]
I did a re-test of this - I created a database with the given config, an no error occurred. My guess is that the database that this was run against had something like a field or some other config that depended on an index that was removed from the given config file. Additionally, this is not a Java Client issue but would be a Manage API error if it were in fact reproducible.
