### ISSUE TITLE
allow constraining query to be a structured query on suggestions endpoint

### ISSUE THREAD

**Issue by joecrean** [marklogic/java-client-api#1013]
please overload the `SuggestDefinition` so that it allows a structured query - the implementation would then need to invoke the POST method on the `v1/suggest` and send the query in the body.

This is a customer requirement from Haufe Group (in production and now wishing to use suggestions) . In this application the MarkLogic string query syntax is not exposed to consumers hence the desire to  express the constraining query as a structured query. 

The only workaround in this case is create a REST extension in MarkLogic which implements POST semantics on search:suggest.

Java 8
ML 9.0-5/6

**Comment by joecrean** [comment]
this corresponds to internal RFE-50946

**Comment by chludwig-haufe** [comment]
Additional Info: Haufe uses the client version 4.0.4.

**Comment by ehennum** [comment]
This issue can be reopened later if needed.
