### ISSUE TITLE
provide missing configuration in DatabaseClientFactory.Bean

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1018]
Add configuration missing in com.marklogic.client.DatabaseClientFactory.Bean:

    https://github.com/marklogic/java-client-api/blob/develop/marklogic-client-api/src/main/java/com/marklogic/client/DatabaseClientFactory.java#L1205-L1486

by checking against com.marklogic.client.ext.DatabaseClientConfig:

    https://github.com/marklogic-community/ml-javaclient-util/blob/dev/src/main/java/com/marklogic/client/ext/DatabaseClientConfig.java

**Comment by georgeajit** [comment]
Refer to #1020 for tests.
