### ISSUE TITLE
Fast collection delete

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#1035]
If the conditions are right, the database can delete all of the documents in a collection much faster than anything could do it one-by-one. If those conditions are right, DMSDK should use that instead of the default batching (if it doesn’t already).

https://project.marklogic.com/jira/browse/RFE-2167

**Comment by heelix** [comment]
This using xdmp:collection-delete under the covers?  I had issues with large collections -- 100M+ or so on that hardware -- that would hit the 10 minute mark.  (ML 7, so a grain of salt with the question0
