### ISSUE TITLE
OkHttpServices::getIteratedResourceImpl ignores given mimetypes

### ISSUE THREAD

**Issue by ralfhergert** [marklogic/java-client-api#1036]
https://github.com/marklogic/java-client-api/blob/9803cca4cfdeecde4b9d8e1ab0396e45814a2b02/marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java#L3078

Method getIteratedResourceImpl(...) takes a String-array of accepted mimetypes, but never uses them.

**Comment by ehennum** [comment]
The fix will be just to refactor at the start of a release cycle to remove the superfluous parameters.

**Comment by ehennum** [comment]
Removing dead parameters is good for code quality, but this fix is a low priority because it is entirely internal.

**Comment by rjrudin** [comment]
Better late than never on this cleanup - see #1465 . Will include this in 6.0.0 so we can remove it at some point, unless we decide it's a bug that the argument exists in 6 methods in `ResourceServices`.
