### ISSUE TITLE
Deadlock detection in multi-statement transactions

### ISSUE THREAD

**Issue by maffelbaffel** [marklogic/java-client-api#1038]
# Feature Request
### Version of MarkLogic Java Client API
4.0.3
### Version of MarkLogic Server
9.0-7.2

## Description
I have already described my problem in this [StackOverflow Post](https://stackoverflow.com/questions/53458583/marklogic-java-api-deadlock-detection).

For testing purposes i locally added the following line in class `OkHttpServices` at line [1371](https://github.com/marklogic/java-client-api/blob/9803cca4cfdeecde4b9d8e1ab0396e45814a2b02/marklogic-client-api/src/main/java/com/marklogic/client/impl/OkHttpServices.java#L1371):

```java
try {
        LoggerFactory.getLogger(this.getClass()).warn("Retrying request."); // logs a message every time a request is retried
        Thread.sleep(nextDelay);
    } catch (InterruptedException e) {
}
```

Execute the following code to reproduce the problem:

```java
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.Transaction;
import com.marklogic.client.impl.OkHttpServices;
import com.marklogic.client.io.Format;
import com.marklogic.client.io.StringHandle;
import org.slf4j.LoggerFactory;

class Scratch {
    public static void main(String[] args) throws Exception {
        final Logger root = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        final Logger ok = (Logger) LoggerFactory.getLogger(OkHttpServices.class);
        root.setLevel(Level.ALL);
        ok.setLevel(Level.ALL);

        final DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, new DatabaseClientFactory.DigestAuthContext("admin", "admin"));

        final StringHandle handle = new StringHandle("<doc><name>Test</name></doc>")
            .withFormat(Format.XML);
        client.newTextDocumentManager().write("test.xml", handle);

        root.info("t1: opening");
        final Transaction t1 = client.openTransaction();
        root.info("t1: reading");
        client.newXMLDocumentManager()
            .read("test.xml", new StringHandle(), t1);

        root.info("t2: opening");
        final Transaction t2 = client.openTransaction();
        root.info("t2: reading");
        client.newXMLDocumentManager()
            .read("test.xml", new StringHandle(), t2);

        final Thread th1 = new Thread(() -> {
            root.info("t1: writing");
            try {
                client.newXMLDocumentManager().write("test.xml", new StringHandle("<doc><t>t1</t></doc>").withFormat(Format.XML), t1);
                t1.commit();
                root.info("t1: committed");
            } catch (Exception ex) {
                t1.rollback();
                root.info("t1: rollback", ex);
            }
        }, "t1");
        th1.setDaemon(false);
        th1.start();

        final Thread th2 = new Thread(() -> {
            root.info("t2: writing");
            try {
                client.newXMLDocumentManager().write("test.xml", new StringHandle("<doc><t>t2</t></doc>").withFormat(Format.XML), t2);
                t2.commit();
                root.info("t2: committed");
            } catch (Exception ex) {
                t2.rollback();
                root.info("t2: rollback", ex);
            }
        }, "t2");
        th2.setDaemon(false);
        th2.start();
    }
}
```

Log output:

```
12:29:13.038 [main] DEBUG c.m.client.impl.OkHttpServices - Connecting to localhost at 8000 as admin
12:29:13.173 [main] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for test.xml
12:29:13.175 [main] DEBUG c.m.client.impl.OkHttpServices - Sending test.xml document in transaction null
12:29:13.218 [main] INFO  ROOT - t1: opening
12:29:13.218 [main] DEBUG c.m.client.impl.OkHttpServices - Opening transaction
12:29:13.263 [main] INFO  ROOT - t1: reading
12:29:13.263 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for test.xml
12:29:13.264 [main] DEBUG c.m.client.impl.OkHttpServices - Getting test.xml in transaction 1241989957733836765
12:29:13.573 [main] INFO  ROOT - t2: opening
12:29:13.573 [main] DEBUG c.m.client.impl.OkHttpServices - Opening transaction
12:29:13.576 [main] INFO  ROOT - t2: reading
12:29:13.576 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for test.xml
12:29:13.576 [main] DEBUG c.m.client.impl.OkHttpServices - Getting test.xml in transaction 27955879753016410
12:29:13.579 [t1] INFO  ROOT - t1: writing
12:29:13.580 [t1] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for test.xml
12:29:13.580 [t1] DEBUG c.m.client.impl.OkHttpServices - Sending test.xml document in transaction 1241989957733836765
12:29:13.580 [t2] INFO  ROOT - t2: writing
12:29:13.580 [t2] INFO  c.m.client.impl.DocumentManagerImpl - Writing content for test.xml
12:29:13.580 [t2] DEBUG c.m.client.impl.OkHttpServices - Sending test.xml document in transaction 27955879753016410
12:29:13.583 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:29:13.718 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:29:13.925 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:29:14.141 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:29:14.566 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
... request of thread t2 is retried over and over again (up to ~ 120 seconds, see the timestamps) ...
12:31:01.190 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:03.315 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:05.420 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:07.490 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:09.505 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:11.537 [t2] WARN  c.m.client.impl.OkHttpServices - Retrying request.
12:31:13.589 [t2] DEBUG c.m.client.impl.OkHttpServices - Completing transaction 27955879753016410 with rollback
12:31:13.595 [t2] ERROR ROOT - t2: rollback
com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 120 seconds after 64 retries
	at com.marklogic.client.impl.OkHttpServices.putPostDocumentImpl(OkHttpServices.java:1423)
	at com.marklogic.client.impl.OkHttpServices.putDocument(OkHttpServices.java:1256)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:920)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:758)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:717)
	at Scratch.lambda$main$1(scratch.java:53)
	at java.lang.Thread.run(Thread.java:748)
12:31:13.607 [t1] DEBUG c.m.client.impl.OkHttpServices - Completing transaction 1241989957733836765 with commit
12:31:13.611 [t1] INFO  ROOT - t1: committed
```

MarkLogic java-client-api retries requests if they return a service unavailable. I guess this makes sense in most of the cases. In the linked SO post i described a case where **two parallel multi-statement transactions** required read-locks on the same document and want to update on that read-locked document (having a **deadlock situation**). MarkLogic Server sends a service unavailable error for the seocnd update. java-client-api will then pause the second thread/transaction/update and retry again for about 120 seconds (~64 times), which will again always result in an error because the deadlock is still present. The first update needs to wait long 120 seconds (until t2 can be rollbacked) to commit.
After this one of the request times out with the following error:

```
Exception in thread "Thread-1" com.marklogic.client.FailedRequestException: Service unavailable and maximum retry period elapsed: 121 seconds after 65 retries
    at com.marklogic.client.impl.OkHttpServices.putPostDocumentImpl(OkHttpServices.java:1422)
    at com.marklogic.client.impl.OkHttpServices.putDocument(OkHttpServices.java:1256)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:920)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:758)
    at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:717)
    at Scratch.lambda$main$0(scratch.java:40)
    at java.lang.Thread.run(Thread.java:748)
```

There is currently no way for the java client applications to **spot** that deadlock, **rollback** the transaction and **retry**. This would be necessary so at least one of the transactions can be commited. Currently a deadlock situation like this **blocks both threads for 120 seconds**. I would prefer not retrying in this case but instead throw an exception like "The transactions participates in a deadlock and has been rolled back by the server.". 

# Proposal
I would like to have some sort of deadlock detection for multi-statement transactions. If java-client-api detects a deadlock it should throw an error. This would allow the client application to rollback the transaction and release all locks.
Not sure if the detection can be done on client side, because the client side may not know about that other transaction and thereby cannot chose which to rollback. I guess this decision has to be done by MarkLogic Server. Maybe instead of returning a service unavailable return a "deadlock detected - suggest rollback" error to **one** of the multi-statement transactions?

**Comment by ehennum** [comment]
Note that service unavailable can also occur during failover.  Unless the server response provides a basis for distinction of deadlocks, this would have to be an opt in restricted to the specific case of multistatement transactions.

**Comment by maffelbaffel** [comment]
I updated my issue and added code and better log output. I hope this helps to understand my problem.

**Comment by ehennum** [comment]
The Java API is doing the wrong thing in attempting to retry requests that continue work in a multistatement transaction.
The transaction timeout is capped at the request timeout.
If the Java API gets a service unavailable response due to a dnode becoming unreachable (for example), the transaction is no longer valid even though the enode remains available and thus cannot be retried.
The Java API should only retry requests that execute an atomic single statement transaction and requests that open a multistatement transaction.
Footnote:  where possible, atomic requests are preferred to multistatement requests.

**Comment by maffelbaffel** [comment]
I just found some time testing the proposed fix, but it does not seem to fix the issue.
The problem still exists in the `putPostDocumentImpl` function, having a own retry mechanism (not reusing `sendRequestWithRetry`). I created a PR reusing `sendRequestWithRetry` which should fix the error. Note i can not seem to get tests running on my machine, so please check yourself if there are any regressions. This PR should, if not 100% correct, at least lead in the right direction.

**Comment by maffelbaffel** [comment]
The second commit does indeed fix the deadlock problem. I now have another problem though.
This is the execution log of my example code:
```
t1: opening
t1: reading
t2: opening
t2: reading
t1: writing
t2: writing
com.marklogic.client.FailedRetryException: Service unavailable and maximum retry period elapsed: 22 seconds after 0 retries
	at com.marklogic.client.impl.OkHttpServices.putPostDocumentImpl(OkHttpServices.java:1386)
	at com.marklogic.client.impl.OkHttpServices.putDocument(OkHttpServices.java:1220)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:920)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:758)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:717)
	at Scratch.lambda$main$1(scratch_1.java:44)
	at java.lang.Thread.run(Thread.java:748)
t2: rollback
t1: rollback
com.marklogic.client.FailedRequestException: Local message: Content version required to write document. Server Message: RESTAPI-CONTENTNOVERSION: (err:FOER0000) No content version supplied:  uri test.xml
	at com.marklogic.client.impl.OkHttpServices.putPostDocumentImpl(OkHttpServices.java:1397)
	at com.marklogic.client.impl.OkHttpServices.putDocument(OkHttpServices.java:1220)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:920)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:758)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:717)
	at Scratch.lambda$main$0(scratch_1.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

As you can see, the t2 does now rollback immediately and a service unavailable is thrown. The error message could be improved in this case, but nvm.

Somehow now the other request also fails because of a `RESTAPI-CONTENTNOVERSION` error. Not really sure what this means and how to fix that. Seems to be a client side caching problem? Any ideas?

**Comment by maffelbaffel** [comment]
Expected output:

```
t1: opening
t1: reading
t2: opening
t2: reading
t1: writing
t2: writing
com.marklogic.client.FailedRetryException: Service unavailable and maximum retry period elapsed: 22 seconds after 0 retries
	at com.marklogic.client.impl.OkHttpServices.putPostDocumentImpl(OkHttpServices.java:1386)
	at com.marklogic.client.impl.OkHttpServices.putDocument(OkHttpServices.java:1220)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:920)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:758)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:717)
	at Scratch.lambda$main$1(scratch_1.java:44)
	at java.lang.Thread.run(Thread.java:748)
t2: rollback
t1: commit
```

**Comment by laquereric** [comment]
Thanks for the ongoing progress here!
Let's get the error message right and address coverage of this in the test suite 'while we are at it...'

**Comment by ehennum** [comment]
@maffelbaffel , thanks for the fast turnaround on the additional fixes. The second error message did make me wonder whether the database is configured for optimistic locking, which shouldn't be necessary when using multi-statement transactions. Anyway, I'm glad you found a resolution for the issue.
@laquereric , it appears the server returns the service unavailable status code for a deadlock. So, a new error message will have to be pursued with a server bug.

**Comment by ehennum** [comment]
@maffelbaffel , there are definitely tests for optimistic locking, so that's a plausible explanation.
On the main issue of retry within multistatement transactions, thanks for identifying the problem and confirming the fix in your environment. We're going to try to cut a release within the next week.

**Comment by jmakeig** [comment]
Is there additional documentation that we need to consider here? I’m at a customer who ran into this by inadvertently running single transactions in multi-statement mode.

**Comment by ehennum** [comment]
Closing the loop, I filed internal documentation bug 51473
