### ISSUE TITLE
FileHandle is not streaming the response to a File

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#1055]
Found this while analyzing something else with @ehennum - I believe it's expected that when using a FileHandle with something like RowManager.resultDoc, the response from ML should be streamed to the given File. Instead, the entire response is being read in as a String and then written to the File, which is much more expensive. 

@ehennum confirmed that this is not specific to RowManager either, it's generic to FileHandle - com/marklogic/client/impl/OkHttpServices.java#5364-5373

**Comment by georgeajit** [comment]
Verified on develop branch with ML 10.0.1 server build.
