### ISSUE TITLE
add JAXB dependency in Java 9+

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1057]
JAXB is deprecated in Java 9 and moved into an external library in Java 11.

The MarkLogic Java API uses JAXB extensively for conversion of atomic data types between Java and enode representations.

When compiled or used on Java 9 or above, the MarkLogic Java API should have an explicit dependency on the JAXB libraries.

**Comment by ehennum** [comment]
I've confirmed that tests using data services run green in Java 10 with this change to build.gradle

**Comment by georgeajit** [comment]
No regressions seen.
