### ISSUE TITLE
Modify Java docs in DatabaseClientFactory newClient method for Data Services support

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1065]
### Version of MarkLogic Java Client API
develop

### Version of MarkLogic Server
9.0 nightly

### Java version

1.8 or later

### OS and version

All platforms

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
```newClient(String host, int port, String database, SecurityContext securityContext)```

The Java docs for the above overridden method signature needs to warn users not to use this signature when connecting to a REST App Server for Data Services use cases.

Java guide has the following note in the chapter titled Creating Data Services using MarkLogic Java Development Tools:

Note: You cannot specify the database explicitly when creating the DatabaseClient but, instead, must use the default database associated with the App Server.

**Comment by ehennum** [comment]
JavaDoc is done.  The bug against the User Guide should probably be filed with the internal bug tracker.

**Comment by georgeajit** [comment]
Verified the Java docs generated on the QA build environment on 06/14/2019. Fixed.
