### ISSUE TITLE
returns the version id for multiple documents in a single request

### ISSUE THREAD

**Issue by tfurukawml** [marklogic/java-client-api#1080]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server
All
### Java version
All
### OS and version
All
### Input: Some code to illustrate the problem, preferably in a state that can be independently 
I think it can be enhancement request rather than bug.

It is about Optimistic lock.
Java Client API does not have a method that returns the version id for multiple documents in a single request.
REST API can do it.
https://docs.marklogic.com/guide/rest-dev/documents#id_35882
"The following example command returns the version id for multiple documents in a single request:"

**Comment by ehennum** [comment]
Added DocumentRecord.getDescriptor() and a unit test to confirm that it works to get the version with bulk read() or search()

I'm not sure any additional testing is needed -- the only implementation change is that we get one more header out of the part (the version, which defaults to -1 as usual).

If nothing more is needed, please ship and close this issue.
