### ISSUE TITLE
remove deprecated interfaces from com.marklogic.client.type

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1090]
As noted in the JavaDoc, applications are required to switch to

    com.marklogic.client.type.ServerExpression

Because this is a backward incompatible change, the version of the Java API will need to bump to 5.0.0

The change should be contemporaneous with MarkLogic 10.0-1 so adopters are alert to the potential for backward incompatibilities.

**Comment by ehennum** [comment]
I ran the Optic functional tests as well as unit tests, so this cleanup shouldn't cause any regressions.

No new tests needed.

**Comment by georgeajit** [comment]
No regressions seen.
