### ISSUE TITLE
Calling stop() in a QueryBatcher backed by iterator shuts it down before the running listeners complete

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#1095]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt
4.2.0
### Version of MarkLogic Server
9.0-9
See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version
Java 8
Run `java -version`

### OS and version
MAC OS X 10.13.6
For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

https://github.com/marklogic/marklogic-data-hub/blob/develop/marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
```
 queryBatcher = dataMovementManager.newQueryBatcher(uris.iterator())
            .withBatchSize(batchSize)
            .withThreadCount(threadCount)
            .withJobId(runStepResponse.getJobId())
            .onUrisReady((QueryBatch batch) -> {
                try {
                    //FlowResource is REST extension that does harmonization step
                    FlowResource flowResource;
                    Map<String,Object> optsMap = new HashMap<>(options);
                    if (databaseClientMap.containsKey(batch.getClient())) {
                        flowResource = databaseClientMap.get(batch.getClient());
                    } else {
                        flowResource = new FlowResource(batch.getClient(), destinationDatabase, flow);
                        databaseClientMap.put(batch.getClient(), flowResource);
                    }
                    optsMap.put("uris", batch.getItems());

                    ResponseHolder response = flowResource.run(runStepResponse.getJobId(), step, optsMap);
                    failedEvents.addAndGet(response.errorCount);
                    successfulEvents.addAndGet(response.totalCount - response.errorCount);
                    
                } catch (Exception e) {
                    if (errorMessages.size() < MAX_ERROR_MESSAGES) {
                        errorMessages.add(e.toString());
                    }
                }
            })
            .onQueryFailure((QueryBatchException failure) -> {
                failedBatches.addAndGet(1);
                failedEvents.addAndGet(batchSize);
            });

        if(! isStopped.get()) {
            JobTicket jobTicket = dataMovementManager.startJob(queryBatcher);
            ticketWrapper.put("jobTicket", jobTicket);
        }
        JobTicket jobTicket = dataMovementManager.startJob(queryBatcher);
        queryBatcher.awaitCompletion();
```
stop() called from another thread
```

    public void stop() {
        isStopped.set(true);
        if(queryBatcher != null) {
            dataMovementManager.stopJob(queryBatcher);
        }
    }
```
### Expected output: What specifically did you expect to happen?

Once the response is obtained, the counters are updated . What I am seeing is that, when stop() is called, there are some requests (usually the last batch) that are in flight and before the response comes back and the counters get updated and the rest of the callback is executed, the QueryBatcher stops and hence the counts are not updated.
```
         ResponseHolder response = flowResource.run(runStepResponse.getJobId(), step, optsMap);
         failedEvents.addAndGet(response.errorCount);
         successfulEvents.addAndGet(response.totalCount - response.errorCount);
```

### Alternatives: What else have you tried, actual/expected?
I tried with different batch sizes and the successful count is different with different batch size.

**Comment by ehennum** [comment]
In my understanding, the contract of stop() is to terminate.

I would agree that there is a hole in the design of QueryBatcher.  QueryBatcher should have a method that sets a ceiling on uri collection either to a specified maximum or to the uris requested thus far. Possibly something along the lines of:

    void setMaxUris(long results);
    void setMaxUris();

In the short term, you might be able to register a QueryBatchListener that mediates between the QueryBatcher and the actual URI worker listeners. On cancellation, the mediator would stopping passing through uris. When the worker listeners have all finished, the mediator could stop the job.

Adding @anu3990 for additional consideration of the issue.

**Comment by georgeajit** [comment]
Can you please merge changes from anu3990 into develop?

**Comment by georgeajit** [comment]
Could you please refactor the based on the discussions we had on batch size?
