### ISSUE TITLE
Can’t tell which file has an error in EndpointProxiesGenTask

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#1102]
### Java version

```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

### OS and version

```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

### Input

```groovy
//…
task scaffoldDataServices(type: com.marklogic.client.tools.gradle.EndpointProxiesGenTask) {
	description = "Build data-services-manager"
	serviceDeclarationFile = 'src/main/ml-modules/root/dataServices/service.json'
//…
```

```shell
gradle scaffoldDataServices
```

### Actual output
I can’t tell which file has the error from the default error reporting. I need the `File` in `at [Source: (File); line: 11, column: 4]`.

Full output:

```
> Task :scaffoldDataServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scaffoldDataServices'.
> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): expected a value
   at [Source: (File); line: 11, column: 4]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

**Comment by ehennum** [comment]
@jmakeig , did you try running with --stacktrace or --info?  

In other words, is Gradle or EndpointProxiesGenTask hiding the detail?

**Comment by ehennum** [comment]
Assigning to the filer pending an answer to the question in the comment above.

**Comment by jmakeig** [comment]
Haven’t tried, but I’d strongly contend that it’s a bug if this information isn’t available in the default output.

**Comment by ehennum** [comment]
Sorry, I don't understand that response.  We're not going to customize Gradle to behave in unexpected ways.  

If we don't like standard Gradle behaviors, we should pick another tool.
