### ISSUE TITLE
Time-based bucket definition helpers

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#111]
Today, bucketed facets require explicit declaration of each bucket. That's fine for the foundational layer, however, it would be nice for the client APIs to provide some conveniences to build bucket definitions dynamically. This is especially important for dates/times.
- Given start and end, divide into even intervals
- Given start and interval size (e.g. hourly, daily, weekly, monthly, quarterly, yearly) and interval length

Calendar math can be tricky, especially things landing on month ends. [Joda Time](http://www.joda.org/joda-time/) might be something to look at here.

We should also think about numbers and strings, but those are lower priority than dates. 

See also [legacy RFE2363](https://rfetrack.marklogic.com/detail/2363).

**Comment by sammefford** [comment]
Related to #60
