### ISSUE TITLE
BufferableHandle in CallManager and CallBatcher

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1110]
Internally, CallBatcher has to use BufferableHandle to be able to retry.

BufferableHandle now implements AbstractWriteHandle and AbstractReadHandle.

Thus, CallManager and CallBatcher should require BufferableHandle instead of AbstractWriteHandle.

OutputStreamHandle can not longer be supported, but that's only important for special cases where the data cannot be acquired as an InputStream.

**Comment by ehennum** [comment]
Should remove regressions in the unit test except for the following test, which fails intermittently and may indicate a race condition in the implementation:

com.marklogic.client.test.dataservices.DataservicesPerForestTest#endpointReceivesForestName

**Comment by georgeajit** [comment]
Closed.
