### ISSUE TITLE
Support customized implementation of Data Service interface

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1111]
Specify the endpoint directory for a customized implementation for the same interface -- supporting the same contract (that is, the same list of functions each of which has the same signature) but with custom operations on the enode.

Internal issue DBMS-123

**Comment by ehennum** [comment]
Shouldn't cause any regressions -- added a test for specifying a custom endpoint directory and cleaned up the generated unit tests as part of this fix.

**Comment by georgeajit** [comment]
Closed.
