### ISSUE TITLE
Minimal supported java version for Java Client API 5.0.0? 

### ISSUE THREAD

**Issue by jdjo** [marklogic/java-client-api#1115]
What is the minimal supported java version for Java Client Api versin 5.0.0? 

I am in the process of upgrading a Marklogic project to Marklogic 10. 
This project still uses java 1.8 and I am  getting java.lang.UnsupportedClassVersionError when using the Java Client Api jar as downloaded from maven central.
Is it by intent that support for java 1.8 has been dropped?

**Comment by ehennum** [comment]
Yes, the minimum version for the Java API 5.0.0 is Java 9 -- because Java 1.8 is past end of life.

**Comment by georgeajit** [comment]
Java 9 for 5.0.0

**Comment by heelix** [comment]
You sure that is wise?  Java 8 is in extended support for several more
years depending on vendor.  We are just in the process of cutting over from
Java 8 to Java 11 (LTS) and we are likely in the front of the pack.

**Comment by ehennum** [comment]
The MarkLogic Java API 4 is formally supported on the public Oracle JDK (though expected to work on other JDKs as well).  
Oracle ended public updates for commercial users of the Java 8 JDK in January 2019.  That constrains our ability to support an API on the public Oracle JDK 8.
Oracle JDK was the defacto standard for public JDK 8. Rather than switching to non-standard public alternatives for JDK 8, much of the industry seems to be migrating off of JDK 8 to later JDKs.

**Comment by heelix** [comment]
Oracle handed RHEL (now owned by IBM)  support of the OpenJDK 8 and 11 -
the two primary Long Term Support (LTS) builds available.  Folks could use
the 'every 6 month' major version of Oracle... but most enterprises would
be crazy to do that.  (JDK 7 reaches EOL in 2020, so technically a third.)
I believe the next LTS version will be Java 17.  For those who are staying
with Oracle (I've personally got about 350k seats+server cores at our
company) an extended support license is required to use most of their JDK
offering.  If they use Oracle JDK 9, they have a license that covers access
to the current 8 and 11 LTS builds, for example.

The 'short' major releases - 9, 10 - are already EOL, without extended
support offered.  I believe 12 gets killed off this September, with the
launch of 13.  Oracle's JDK 8 EOL in 2025, JDK 11 in 2026.  The other
OpenJDK vendors are more or less doing the same EOL dates..

https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

All that said... if you were to say you are supporting JDK 9+, you likely
want to say/test JDK11 (LTS).  Oracle will do their quarterly patch on July
16th, for the next rev of JDK 7, 8, 11, and 12.  AdoptOpenJDK (default
homebrew now, for OSX developers) and RHEL's OpenJDK will likely patch on
the 18th.

Just a though, from someone updating/patching/upgrading a very large number
of Java systems.  Even those willing... it has been a slow transition to
11.  Much of the Java tooling/libraries are just not able to make the
transition to the JDK 9+ format.

**Comment by maffelbaffel** [comment]
Uff this a bummer. We are also still stuck on Java 8 and wanted to upgrade to MarkLogic 10.

I'd also reconsider the decision to require Java 9+.

**Comment by georgeajit** [comment]
Will review this with PM, even though we have Java 9 in build.gradle for last couple of releases.

**Comment by ehennum** [comment]
In the end, reverted to Java 8
