### ISSUE TITLE
Upgrade to latest OkHttp 4.x release

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#1118]
While loading modules into a DHS instance using DHF 4.3.1 (which depends on java-client 4.1.2), the following message was logged by OkHttp, though the modules were still loaded correctly:

```
A connection to https://(host redacted):8013/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
       at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
       at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
       at okhttp3.RealCall.execute(RealCall.java:73)
       at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:651)
       at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2784)
```

I did some googling on this message and found https://github.com/square/okhttp/issues/4399 , which seems related, as it involves the same bit of code as OkHttpServices line 651 - client.newCall(request).execute() . The fix for that OkHttp issue is in 3.12. 

I can't verify that OkHttp 3.12 will prevent the above warning from showing up, but it seems like a good reason to get the java-client onto the latest 3.x release - it's currently on 3.10, and 3.14.2 is available.

**Comment by ehennum** [comment]
I note that, after upgrading from 3.10.0 to 3.14.0, a unit test starts breaking because a HEAD request for a non-existent document comes back as a 201 instead of as a 404.  Mystifying.

**Comment by ehennum** [comment]
Client logging thinks the request is exactly the same before and after the upgrade to 3.14.2, but the response is different.  

Before:

request: HEAD http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml
13:00:37.479 [Test worker] DEBUG c.m.client.impl.OkHttpServices - --> HEAD http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml http/1.1
13:00:37.871 [Test worker] DEBUG c.m.client.impl.OkHttpServices - <-- 404 Not Found http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml (391ms, 0-byte body)
response: 404 Not Found

After:

request: HEAD http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml
12:58:16.034 [Test worker] DEBUG c.m.client.impl.OkHttpServices - --> HEAD http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml http/1.1
12:58:16.041 [Test worker] DEBUG c.m.client.impl.OkHttpServices - <-- 201 Created http://localhost:8012/v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml (6ms, 0-byte body)
response: 201 Created

The server sees a different request before the upgrade:

127.0.0.1 - rest-writer [09/Sep/2019:20:00:37 +0000] "HEAD /v1/documents?category=content&uri=%2Ftest%2FtestWrite1.xml HTTP/1.1" 404 0 - "okhttp/3.10.0"

and after the upgrade

127.0.0.1 - rest-writer [09/Sep/2019:19:58:16 +0000] "PUT /v1/documents?repair=none&category=content&uri=%2Ftest%2FtestWrite1.xml HTTP/1.1" 201 0 - "okhttp/3.14.2"

An empty document is, in fact, created by the request after the upgrade.

**Comment by ehennum** [comment]
I've confirmed with WireShark that OkHttp is sending the HEAD as a PUT.  Possibly the error depends on sending a PUT before the HEAD for the same URI.  I'll need to create a reproducible case for an OkHttp bug, but in the meantime, we can't upgrade.

**Comment by ehennum** [comment]
Filed a report at https://github.com/square/okhttp/issues/5447

**Comment by ehennum** [comment]
The fix went in under https://github.com/square/okhttp/pull/5474

The commit missed the 3.14.4 release in September. We can test the next 3.x release.

**Comment by georgeajit** [comment]
We now have okhttp version 4.4.0 for the upcoming Java Client API release to be tagged as 5.2.0. Tests are green.

**Comment by maxbroens** [comment]
@georgeajit when is this release planned? We encounter the same
`WARN  o.OkHttpClient - A connection to [url] was leaked. Did you forget to close a response body?`
with the 5.0.1 client

**Comment by ehennum** [comment]
@maxbroens , we're targeting early April for the 5.2.0 release.  

Note, however, that the warning is believed to be spurious.  It's not known to affect the request or response.
