### ISSUE TITLE
merge useful changes from the develop-callbatcher branch

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1121]
Related to #1120, remove the dynamic caller and static and dynamic callbatcher from the develop branch and merge the other changes from the  develop-callbatcher branch

**Comment by ehennum** [comment]
Assigning for awareness of potential regressions.  

- Merging the refactoring on the current data services generated callers from the develop-callbatcher branch shouldn't cause any regressions.

- I didn't spot any uses of CallManager or CallBatcher could in the functional tests, but if I missed any uses of the call batchers or the dynamic caller implementation, that would be expected to cause regressions, which would be fixed by removing the tests.

Under ml-development-tools, the com.marklogic.client.test.gradle.ServiceCompareTaskTest verifies the comparison of the *.api declarations between the default (aka base) service and a customized implementation of the service. Please consider whether that test is adequate for the use case.

**Comment by georgeajit** [comment]
No issues seen.
