### ISSUE TITLE
Documentation error on 5.0.0 release notes

### ISSUE THREAD

**Issue by taatuut** [marklogic/java-client-api#1122]
### Version of MarkLogic Java Client API
5.0.0

Release notes at https://github.com/marklogic/java-client-api/releases/tag/5.0.0 mention 'Release 4.2.0 coinciding with MarkLogic Server 9.0-9 or later.'

I assume this should mention 'Release 5.0.0', minimum MarkLogic version is 9.0-9 or 10.0-1?

**Comment by ehennum** [comment]
You assumption is exactly right.  Thanks for catching and correcting that mistake, Emil.

**Comment by ehennum** [comment]
We'll correct the problem in the next release of Java API.

**Comment by georgeajit** [comment]
Done on 5.0.1.
