### ISSUE TITLE
Remove references to CallManager from JavaDocs in  DatabaseClientFactory class

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1136]
### Version of MarkLogic Java Client API
develop
### Version of MarkLogic Server

10.0 nightly

### Java version

Java 9

### OS and version

NA

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
```
public static DatabaseClient newClient​(java.lang.String host,
                                       int port,
                                       java.lang.String database,
                                       DatabaseClientFactory.SecurityContext securityContext,
                                       DatabaseClient.ConnectionType connectionType)
Creates a client to access the database by means of a REST server. 

<<The CallManager interface can only call an endpoint for the configured content database of the appserver. You cannot specify the database when constructing a client for working with a CallManager.>>
```
### Expected output: What specifically did you expect to happen?
Text within angle brackets needs to be removed for most of overloads of ```newClient​()``` method in ```DatabaseClientFactory``` class.
### Alternatives: What else have you tried, actual/expected?
None.

**Comment by ehennum** [comment]
JavaDoc should now mention data service instead of CallManager

**Comment by georgeajit** [comment]
API docs on internal publishing site was verified. There are no instances to CallManager.
