### ISSUE TITLE
Modify BulkInputCallerTest to have input parameter handled in SJS module

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1150]
### Version of MarkLogic Java Client API
develop-72 branch

### Version of MarkLogic Server

10.0 nightly (post 10.0.2 release)

### Java version

9.0.4

### OS and version

Windows

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
Issue 1:
This sjs code does not have ```input``` parameter. This parameter is used to write docs to database.
```
'use strict';
var endpointState; // jsonDocument?
var workUnit;      // jsonDocument?
declareUpdate();

const state = fn.head(xdmp.fromJSON(endpointState));
state.next = state.next + 1;

const work = fn.head(xdmp.fromJSON(workUnit));

let returnValue = null;
if (state.next < work.max) {
        xdmp.documentInsert(
            '/marklogic/ds/test/bulkInputCaller/' +state.next+'.json',
            state,
            {permissions:[
                xdmp.permission('rest-reader', 'read'),
                xdmp.permission('rest-writer', 'update')
                ]});
    returnValue = state;
}
returnValue;
```
Issue 2: 
Java test case code needs to handle multiple docs. When no batch size is specified, then default size is 100. The code needs to specify batch size and then assert that those documents, i.e., streams are indeed written (bulk ingest through relevant SJS module) to database.

### Expected output: What specifically did you expect to happen?
Docs are written in batches

### Alternatives: What else have you tried, actual/expected?
N/A

**Comment by ehennum** [comment]
The changes:

*  fixed the endpoint property in bulkInputCallerImpl.api for case-sensitive accuracy
*  changed the batch size in bulkInputCallerImpl.api to 2 to send multiple and single batches 
*  added the input parameter in bulkInputCallerImpl.sjs
*  added input conversion in bulkInputCallerImpl.sjs
*  added the input and work to the serialized documents in bulkInputCallerImpl.sjs
*  reduced the maximum to the size of the inputs in BulkInputCallerTest (was throwing an exception)
*  changed the document inspection loop in BulkInputCallerTest to confirm the inputs arrived

Note that the input conversion in bulkInputCallerImpl.sjs has to handle both Sequence and Document. While the approach works, I believe it shouldn't be necessary -- that the input should always be either null or a Sequence.  If I can create a simple reproduction, I'll file a bug against the server.

**Comment by georgeajit** [comment]
Works as expected.

Here are some observations:
This controls how many inputs are in a batch
```
"$bulk":{
    "inputBatchSize":2
  }
```
This controls how many inputs are available to endpoint. 
```
"{\"max\":"+workMax+"}";
```
Might be a large number. Testing with small number produces some side effects in the SJS code such as ```2019-10-21 14:24:35.328 Info: Status 500: XDMP-ARGTYPE: xdmp.fromJSON(null) -- arg1 is not of type Node```

**Comment by ehennum** [comment]
To be clear, the max property of the workUnit data structure is part of the test -- not part of the product.

The properties of the workUnit and endpointState data structures and the processing of those data structures in the SJS or XQuery endpoint main module are entirely the responsibility of the adopter.

The test happens to use a max property because it's convenient for the test and one plausible way of using the bulk IO endpoint capability. In a production adoption, the main module would need to be much more rigorous (and do something useful).
