### ISSUE TITLE
bulk caller for input-output endpoint

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1152]
Create the bulk caller for the input-output endpoint signature per internal story JAVA-72

**Comment by ehennum** [comment]
I also did some refactoring of the Input and Output implementations so the InputOutput implementation could share code.

The unit test is in:

com.marklogic.client.test.dataservices.BulkIOEndpointTest.testInputOutputCallerImpl()

**Comment by georgeajit** [comment]
Unit test and functional test for input-output endpoint runs fine.
