### ISSUE TITLE
tweaks for greater transparency

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1165]
In particular:

*  arrays instead of streams for input and output
*  single call signatures with endpoint state and session (and thus session factory)

**Comment by ehennum** [comment]
Assigning for awareness.  This interface fixup shouldn't require any new coverage.

For the bulk callers, I believe that only the OutputEndpoint.next() method is affected. 

Other than that, the interface fixup shouldn't cause regressions on bulk callers.

**Comment by georgeajit** [comment]
No regressions seen in local run and on Jenkins CI env.
