### ISSUE TITLE
sort documents by URI for each WriteBatch

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1168]
Before writing a batch to the server, the WriteBatcher should sort the documents by URI within the batch.

That way, batches written concurrently cannot deadlock because documents will be locked in a consistent order.  That is, whichever batch gets the lock on the first document that is common between batches will get the locks on any other documents that are common between batches.

**Comment by ehennum** [comment]
This fix should apply not only to DMSDK but to any batch writer.

**Comment by ehennum** [comment]
See internal task Java-159.

**Comment by georgeajit** [comment]
Tests are running fine on Jenkins CI builds.
