### ISSUE TITLE
investigate whether session id refresh is needed

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1170]
If the session expires, the session id will likely be treated as a new session by the server.

If so, there's no need to look up the session timeout or refresh the session id before it times out.

If the timeout is useful, the client should allow for the case where the appserver is not a REST API server, maybe by catching the exception and retrying with a new session id.

**Comment by ehennum** [comment]
Merely sending for awareness that this refactoring happened. No additional coverage needed and minimal risk of regression.

**Comment by georgeajit** [comment]
No regressions seen.
