### ISSUE TITLE
broken link to <search-options> documentation reference

### ISSUE THREAD

**Issue by hansenmc** [marklogic/java-client-api#1171]
The link in the JavaDoc comments for PojoQueryBuilder:

https://github.com/marklogic/java-client-api/blob/acf60229a928abd4a8cc4b21b641d56957467da7/marklogic-client-api/src/main/java/com/marklogic/client/pojo/PojoQueryBuilder.java#L422

Is generating a broken link pointing to appendix B of the Rest Developer's guide in the JavaDocs.

http://docs.marklogic.com/javadoc/client/com/marklogic/client/query/class-use/StructuredQueryDefinition.html

The link for `<search-option>` is pointing to a page that no longer exists:

| | | |
| ---- | ---- | ---- |
| PojoQueryDefinition | PojoQueryBuilder.filteredQuery​(StructuredQueryDefinition query) | Wraps the structured query into a combined query with options containing [`<search-option>filtered</search-option>`](http://docs.marklogic.com/guide/rest-dev/appendixb#id_29496) so results are accurate though slower. |

It appears that Appendix B was removed from the Rest Developer's guide in MarkLogic 8. The last version that I see it resolving for is in the MarkLogic 7 REST Developer's guide:
http://docs.marklogic.com/7.0/guide/rest-dev/appendixb#id_29496

- http://docs.marklogic.com/8.0/guide/rest-dev/appendixb#id_29496
- http://docs.marklogic.com/9.0/guide/rest-dev/appendixb#id_29496
- http://docs.marklogic.com/10.0/guide/rest-dev/appendixb#id_29496
- http://docs.marklogic.com/guide/rest-dev/appendixb#id_29496

It appears that the new link for `<search-options>` can be found in the Search Developer's guide:
https://docs.marklogic.com/guide/search-dev/appendixa#id_77801

Maybe an HTTP 301 redirect could be put in place on the docs.marklogic.com website in order to redirect requests for http://docs.marklogic.com/guide/rest-dev/appendixb#id_29496 to https://docs.marklogic.com/guide/search-dev/appendixa#id_77801 ?

**Comment by ehennum** [comment]
Thanks, @hansenmc , for identifying both the issue and the correct link that should appear in the source code for the JavaDoc.

**Comment by georgeajit** [comment]
Verified on both 9.0 and 10.0 branches (SVN) on internal pubs site. The fixes are available.
