### ISSUE TITLE
broken link for sql:weekday

### ISSUE THREAD

**Issue by hansenmc** [marklogic/java-client-api#1172]
The types JavaDoc has a broken link in the Server Doc column for `sql:weekday`

http://docs.marklogic.com/javadoc/client/doc-files/types/item.html

https://github.com/marklogic/java-client-api/blob/b5350b2cfcf09c45422817bb25a37d2ed37f8eb3/marklogic-client-api/src/main/javadoc/doc-files/types/item.html#L343

http://docs.marklogic.com/sql:weekday returns an HTTP 404 and is not listed as one of the MarkLogic SQL functions: http://docs.marklogic.com/sql

**Comment by ehennum** [comment]
I think this is a documentation bug on the server.

In Query Console, sql:weekday(fn:current-date()) seems to work just fine.

**Comment by hansenmc** [comment]
Okay, there are a number of sql:* functions (sql:datepart, sql:dateadd, sql:datediff) that seem to be referenced in various site pages, but don't have a documentation page available. I'll file an internal bug to get them investigated and resolved.

**Comment by ehennum** [comment]
Thanks, @hansenmc , for the scrupulous attention here.

Stating the obvious, if we don't document a function, that makes it hard to use...

**Comment by ehennum** [comment]
Issues for /javadoc/ reported in internal bugs should be gone once the documentation build picks up the Java doc generated from this fix.

**Comment by georgeajit** [comment]
Verified a local Java docs build. Available from ```Interface SqlExpr``` at marklogic-client-api/build/docs/javadoc/index.html?overview-summary.html,  ```weekday``` link. 

Broken link at docs.marklogic.com tracked via internal bug tracking system; reference BT 53936.
