### ISSUE TITLE
Add JSONSplitter

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1197]
For reference, https://project.marklogic.com/jira/browse/JAVA-165

From Jira task,

"

> Large sets of records are often serialized as a single JSON data structure (typically, an array containing an object for each record).
> 
> For that reason, adopters should be able to split an JSON file into separate payloads for writing to the database.
> 
> Each payload must be buffered because the application might accumulate a batch of payloads before sending the payloads to the server. 
> 
> The design should resemble the design of the XML splitter in that the JSON splitter will walk the data structure tree, notifying a visitor about container nodes so the visitor can decide whether to split out the container node as a separate payload and how to represent that payload (which can matter if the application needs to change or inspect the payload downstream).
> 
> One important difference is that a JSON data structure tree has two kinds of container nodes (arrays and objects) where XML only has one (elements). When an array contains other arrays, the visitor might need to know the depth to decide whether or not to split out the container node as a payload. The developer should track array depth within multidimensional arrays in their visitor. 

"
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API 5
See Readme.txt

### Version of MarkLogic Server 10

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version 8

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by georgeajit** [comment]
Tests are written and they are part of all splitter tests.
