### ISSUE TITLE
PojoRepository read method on a POJO object with default value returns null

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#120]
The testPOJORepoReadWithDefaultId() unit test fails because pojoReposProducts.read() returns a null.

Issue seen: The assert fails.

Conditions used to setup:
=====================
A POJO instance with default value is used to write it to the database. In this case the Id field is used and the POJO instance has 0L (data type is long).

ML Server o/p:
===========
Here is the Query Console document contents after the write. Note that the id is 0.

{
"com.marklogic.javaclient.Artifact":
{
"id": 0,
"name": "Cogs -1000",
"manufacturer":
{
"com.marklogic.javaclient.Company":
{
"name": "Acme -1000, Inc.",
"website": "http://www.acme-1000.com",
"latitude": -958.002,
"longitude": -1087.966
}
}
,
"inventory": 1000
}
}

============== POJO classes used=================
package com.marklogic.javaclient;
import com.marklogic.client.pojo.annotation.Id;
public class Artifact {
	 @Id
	    public long id;
	    private String name;
	    private Company manufacturer;
	//    @IndexClassField
	    private int inventory;
	  
	    public long getId() {
	        return id;
	    }
	    public void setId(long id) {
	        this.id= id;
	    }
	    public String getName() {
	        return name;
	    }
	    public void setName(String name) {
	        this.name = name; 
	    }
	    public Company getManufacturer() {
	        return manufacturer;
	    }
	    public void setManufacturer(Company manufacturer) {
	        this.manufacturer= manufacturer;
	    }
	    public int getInventory() {
	        return inventory;
	    }
	    public void setInventory(int inventory) {
	        this.inventory= inventory; 
	    }
}

package com.marklogic.javaclient;

public class Company {
//	@IndexClassField
    private String name;
    private String website;
 //   @GeospatialLatitude 
    private double latitude;
//    @GeospatialLongitude
    private double longitude;
 
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getWebsite() {
        return website;
    }
    public void setWebsite(String website) {
        this.website = website;
    }
    public double getLatitude() {
        return latitude;
    }
    public void setLatitude(double latitude) {
        this.latitude = latitude; 
    }
    public double getLongitude() {
        return longitude;
    }
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
 
}
=====================end of POJO classes used===============

Junit test

package com.marklogic.javaclient;

import static org.junit.Assert.*;

import java.util.Iterator;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.Authentication;
import com.marklogic.client.pojo.PojoPage;
import com.marklogic.client.pojo.PojoRepository;

/*
 * Purpose : To test the following special cases for PojoRepository class methods
 * POJO instance @Id field value with Negative numbers.
 * POJO instance @Id field value with default values.
 * POJO instance @Id field value with nulls.
 * POJO instance @Id field value with special characters.
 * POJO instance @Id field value with Unicode characters.
 */

public class TestPOJOSpecialCharSearch extends BasicJavaClientREST {
	private static String dbName = "TestPOJOSpecialCharSearchDB";
	private static String [] fNames = {"TestPOJOSpecialCharSearchDB-1"};
	private static String restServerName = "REST-Java-Client-API-Server";
	private static long NEGATIVEIDONE = -1000L;
	private static long NEGATIVEIDTWO = -2000L;
	private static int restPort = 8011;
	private  DatabaseClient client ;

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
		//		System.setProperty("org.apache.commons.logging.simplelog.log.org.apache.http.wire", "debug");
		System.out.println("In setup");
		setupJavaRESTServer(dbName, fNames[0], restServerName,restPort);
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		System.out.println("In tear down" );
		tearDownJavaRESTServer(dbName, fNames, restServerName);
	}
	@Before
	public void setUp() throws Exception {
		client = DatabaseClientFactory.newClient("localhost", restPort, "rest-admin", "x", Authentication.DIGEST);
	}
	@After
	public void tearDown() throws Exception {
		// release client
		client.release();
	}
	
	public Artifact setArtifact(long counter) {
		Company acme = new Company();
		acme.setName("Acme "+ counter +", Inc.");
		acme.setWebsite("http://www.acme"+ counter +".com");
		acme.setLatitude(41.998 + counter);
		acme.setLongitude(-87.966+counter);
		Artifact cogs = new Artifact();
		cogs.setId(counter);
		cogs.setName("Cogs "+ counter);
		cogs.setManufacturer(acme);
		cogs.setInventory(1000);

		return cogs;
	}
	
	/*
	 * This method is used to test POJO Repository read / search with default values.
	 * This method does not set the Id field in the Artifact class explicitly.
	 * Hence Id field should be holding 0L as the default value. 
	 * Test should pass 0L and POJORepository read should handle this request just fine.
	 */
	public Artifact setArtifactWithDefault(long counter) {
		Company acme = new Company();
		acme.setName("Acme "+ counter +", Inc.");
		acme.setWebsite("http://www.acme"+ counter +".com");
		acme.setLatitude(41.998 + counter);
		acme.setLongitude(-87.966+counter);
		Artifact cogs = new Artifact();
		//cogs.setId(counter);
		cogs.setName("Cogs "+ counter);
		cogs.setManufacturer(acme);
		cogs.setInventory(1000);

		return cogs;
	}
	
	/*
	 * This method is used when there is a need to validate one read and search.
	 */
	public void validateArtifact(Artifact artifact) {
		assertNotNull("Artifact object should never be Null", artifact);
		assertNotNull("Id should never be Null",artifact.id);
		assertEquals("Id of the object is ",-1000, artifact.getId());
		assertEquals("Name of the object is ","Cogs -1000", artifact.getName());
		assertEquals("Inventory of the object is ",1000, artifact.getInventory());
		assertEquals("Company name of the object is ","Acme -1000, Inc.", artifact.getManufacturer().getName());
		assertEquals("Web site of the object is ","http://www.acme-1000.com", artifact.getManufacturer().getWebsite());
		assertEquals(-1087.966, artifact.getManufacturer().getLongitude(), 0.00);
		assertEquals(-958.002, artifact.getManufacturer().getLatitude(), 0.00);
	}
	
	/*
	 * This method is used when there is a need to validate one read and search with default Id field value.
	 */
	public void validateArtifactWithDefault(Artifact artifact) {
		assertNotNull("Artifact object should never be Null", artifact);
		assertNotNull("Id should never be Null",artifact.id);
		assertEquals("Id of the object is ",0, artifact.getId());
		assertEquals("Name of the object is ","Cogs -1000", artifact.getName());
		assertEquals("Inventory of the object is ",1000, artifact.getInventory());
		assertEquals("Company name of the object is ","Acme -1000, Inc.", artifact.getManufacturer().getName());
		assertEquals("Web site of the object is ","http://www.acme-1000.com", artifact.getManufacturer().getWebsite());
		assertEquals(-1087.966, artifact.getManufacturer().getLongitude(), 0.00);
		assertEquals(-958.002, artifact.getManufacturer().getLatitude(), 0.00);
	}
	
	/*
	 * This method is used when there is a need to validate multiple reads and searches.
	 */
	public void validateArtifactTwo(Artifact artifact) {
		assertNotNull("Artifact object should never be Null", artifact);
		assertNotNull("Id should never be Null",artifact.id);
		assertEquals("Id of the object is ",-2000, artifact.getId());
		assertEquals("Name of the object is ","Cogs -2000", artifact.getName());
		assertEquals("Inventory of the object is ",1000, artifact.getInventory());
		assertEquals("Company name of the object is ","Acme -2000, Inc.", artifact.getManufacturer().getName());
		assertEquals("Web site of the object is ","http://www.acme-2000.com", artifact.getManufacturer().getWebsite());
		assertEquals(-2087.966, artifact.getManufacturer().getLongitude(), 0.00);
		assertEquals(-1958.002, artifact.getManufacturer().getLatitude(), 0.00);
	}
 
    /*
     * Purpose : This test is to validate read documents using read(Id)
     * POJO instance @Id field value with Negative numbers.
     */
    
	@Test
	public void testPOJORepoReadWithNegativeId() {
		PojoRepository<Artifact,Long> pojoReposProducts = client.newPojoRepository(Artifact.class, Long.class);		
		
		//Load two objects into database
		pojoReposProducts.write(this.setArtifact(NEGATIVEIDONE),"odd","numbers");
			
		assertEquals("Total number of object records", 1, pojoReposProducts.count("numbers"));
		
		// Validate the artifact read back.
		Artifact artifact = pojoReposProducts.read(NEGATIVEIDONE);
		validateArtifact(artifact);				
	}
	
	/*
     * Purpose : This test is to validate read documents using read(ID) with default value.
     * POJO instance @Id field value with Negative numbers.
     * Artifact class instance's Id field should be holding the 0L value. 
     */
	@Test
	public void testPOJORepoReadWithDefaultId() {
		PojoRepository<Artifact,Long> pojoReposProducts = client.newPojoRepository(Artifact.class, Long.class);		
		
		//Load two objects into database
		pojoReposProducts.write(this.setArtifactWithDefault(NEGATIVEIDONE),"odd","numbers");
			
		assertEquals("Total number of object recods", 1, pojoReposProducts.count("numbers"));
		
		// Validate the artifact read back.
		Artifact artifact = pojoReposProducts.read(NEGATIVEIDONE);
		validateArtifactWithDefault(artifact);				
	}	
}

**Comment by DavidGorbet** [comment]
Per Triage: If this is a bulk operation and there are no results, then empty result set is appropriate (i.e. it should return 1 less item than it would if there were 1 result). If this is not a bulk operation, then resource not found is appropriate.

**Comment by georgeajit** [comment]
Moved to ship. Have updated TestPOJOSpecialCharSearch.java with a test method to check for ResourceNotFound Exception when no documents are found.
