### ISSUE TITLE
default configuration of JacksonCSVParser

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1204]
The intent of the default configuration in JacksonCSVParser is to work with the widest set of CSVs.

CsvParser.Feature.SKIP_EMPTY_LINES seems to break on quoted multiline strings that contain empty lines and that don't escape the newlines.

This configuration may, however, be beneficial in cases with empty lines between record lines.

In the short term, the configuration can always be overridden, but we should tune the configuration in response to feedback.

Also, CsvParser.Feature.IGNORE_TRAILING_UNMAPPABLE is set twice.

**Comment by georgeajit** [comment]
Assigned to Anu. Will be reviewing this issue.
