### ISSUE TITLE
Cookbook example bridging from QueryBatcher to Data Services

### ISSUE THREAD

**Issue by anu3990** [marklogic/java-client-api#1209]
JIRA story - https://project.marklogic.com/jira/browse/JAVA-166
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
5.1.0

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by georgeajit** [comment]
Reviewed and there is a new test for this example.
