### ISSUE TITLE
ContentHandle.getContentClass() 

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1218]
On an instance of a ContentHandle, provide a getter for the class of the content.

**Comment by ehennum** [comment]
A small addition needed for RowBatcher.  Doesn't require coverage and shouldn't cause any regressions, but assigning the issue for awareness.

**Comment by georgeajit** [comment]
All handles except these DOM4JHandle, GSONHandle, JDOMHandle have it. No regressions found.
