### ISSUE TITLE
default QueryBatcher to 2 * forests

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1228]
When processing document URIs in query mode QueryBatcher will be more efficient with two threads per forest (one to collect the document URIs and one to processing the documents).  The change affects these lines:

https://github.com/marklogic/java-client-api/blob/master/marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/QueryBatcherImpl.java#L371-L372

Doesn't require any new coverage.  Running the unit tests would be sufficient.

**Comment by georgeajit** [comment]
Will test this as part of new auto scaling story Java 194 (Jira task).

**Comment by llinggit** [comment]
There's no server-side change in this issue.

**Comment by ehennum** [comment]
@rjrudin, I believe that @llinggit  already implemented a better solution that supports multiple processors per collector.

If that's correct, this one can be closed with extreme prejudice.

**Comment by rjrudin** [comment]
Confirmed that a separate feature to address this has been implemented
