### ISSUE TITLE
MetadataExtraction with DocumentWriteSet not extracting properties

### ISSUE THREAD

**Issue by kghmanuel** [marklogic/java-client-api#1238]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
5.2.0

### Version of MarkLogic Server
10.0-4

### Java version
9.0.4

### OS and version
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
This works:
```
        // create a manager for binaries
        BinaryDocumentManager manager = client.newBinaryDocumentManager();

        // tell the manager to extract document information and store them as properties.
        manager.setMetadataExtraction(BinaryDocumentManager.MetadataExtraction.PROPERTIES);

        DocumentWriteSet set = manager.newWriteSet();
        ClassLoader loader = CreateMultipleBinaries.class.getClassLoader();

        final DocumentMetadataHandle imageMeta = new DocumentMetadataHandle();
        imageMeta.getCollections().addAll("photos");

        final String target = "data/images";
        URL url = loader.getResource(target);
        Files
            .find(Paths.get(url.toURI()), Integer.MAX_VALUE, (filePath, fileAttr) -> fileAttr.isRegularFile() && filePath.toFile().getName().endsWith(".jpg"))
            .forEach(file -> {
                String path = file.toFile().getAbsolutePath().replaceAll("\\\\", "/");
                String uri = path.substring(path.indexOf(target) + target.length());
                FileHandle content = new FileHandle(file.toFile());
                //set.add(uri, imageMeta, content);

                manager.write(uri, imageMeta, content);
            });

        //manager.write(set);
```
This does not:
```
        // create a manager for binaries
        BinaryDocumentManager manager = client.newBinaryDocumentManager();

        // tell the manager to extract document information and store them as properties.
        manager.setMetadataExtraction(BinaryDocumentManager.MetadataExtraction.PROPERTIES);

        DocumentWriteSet set = manager.newWriteSet();
        ClassLoader loader = CreateMultipleBinaries.class.getClassLoader();

        final DocumentMetadataHandle imageMeta = new DocumentMetadataHandle();
        imageMeta.getCollections().addAll("photos");

        final String target = "data/images";
        URL url = loader.getResource(target);
        Files
            .find(Paths.get(url.toURI()), Integer.MAX_VALUE, (filePath, fileAttr) -> fileAttr.isRegularFile() && filePath.toFile().getName().endsWith(".jpg"))
            .forEach(file -> {
                String path = file.toFile().getAbsolutePath().replaceAll("\\\\", "/");
                String uri = path.substring(path.indexOf(target) + target.length());
                FileHandle content = new FileHandle(file.toFile());
                set.add(uri, imageMeta, content);

                //manager.write(uri, imageMeta, content);
            });

        manager.write(set);
```

first approach does a direct write, while the second uses a DocumentWriteSet

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)

No properties are loaded using the DocumentWriteSet approach. you would need to clear the created documents created by direct write (first/working approach) to compare.

### Expected output: What specifically did you expect to happen?

properties should have been extracted and stored as part of the document's properties

### Alternatives: What else have you tried, actual/expected?
None

**Comment by ehennum** [comment]
I'll have to check whether the bulk write requests of the REST API have ever supported extracting metadata from binaries.

The typical use case for extracting metadata from binaries has been large documents that are written individually instead of in batches.

**Comment by ehennum** [comment]
The implementation of bulk write in the REST API does appear to support extraction of metadata from binaries. 

I'll investigate whether the Java client is neglecting to construct the parameter in the Content-Disposition headers for the part.

**Comment by ehennum** [comment]
I've modified a unit test to reproduce the issue.

So far as I can tell, this has never worked in the Java client but could and should work.

**Comment by ehennum** [comment]
Revised the unit test for binary documents to verify the extract parameter when writing multiparts as well as when writing single documents. Also revised the unit test for XML documents to verify the repair parameter (which had the same issue). 

@georgeajit , please consider whether these unit tests provide sufficient coverage.

Thanks, @kghmanuel , for identifying the issue.

**Comment by georgeajit** [comment]
The tests are sufficient.
