### ISSUE TITLE
refactor URIHandle example to use OkHttp

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1241]
The URIHandleTest has started throwing org.apache.http.client.ClientProtocolException, so we may as well fix by acting on the long-deferred refactoring of com.marklogic.client.example.handle.URIHandle to OkHttp.

**Comment by ehennum** [comment]
Should remove the regression in Jenkins.  No additional coverage needed.

**Comment by ehennum** [comment]
Belatedly, one potential regression occurs to me:  I've only made the example work with the HTTP protocol.  In my reading, the previous version only worked with HTTP as well, but if I've misread the prior code, the example would start breaking on HTTPS.

**Comment by georgeajit** [comment]
No regressions seen as of 07/31/2020.
