### ISSUE TITLE
Document Manager write failed after XSLT transformation in MarkLogic Java API

### ISSUE THREAD

**Issue by chenfiona** [marklogic/java-client-api#1257]
### Version of MarkLogic Java Client API
MarkLogic Java API v5.2.0

### Version of MarkLogic Server
MarkLogic Server v10.0-4.4

### Java version
Java build 11.0.8

### Problem
> MarkLogic throws error during the document manager consumes the XSLT transformed data.

`Transaction failure: Local message: failed to apply resource at documents: Internal Server Error. 
Server Message: XDMP-AS: (err:XPTY0004) $content as document-node()? 
-- Invalid coercion: 
(document{<Test/>}, 
document{<Provenance >&#10;   <id value="Patient..."/>...</Provenance>}) as document-node()? . 
See the MarkLogic server error log for further detail.
`
> The transformation will envelope a new element called Provenance at the root ClinicalDocument.

> What is the specific setting | solution to get around the failure?

**Comment by ehennum** [comment]
Based on the error message, it looks like the transform is trying to return a sequence of two XML documents:

1. <Test/>
2.  <Provenance >&#10; <id value="Patient..."/>...</Provenance>

In the REST API, a transform can only return a single document.  Please see:

https://docs.marklogic.com/guide/rest-dev/transforms#id_67705

**Comment by ehennum** [comment]
@chenfiona , if you modify the transform to return a single document as suggested in the previous comment, does that fix the problem?

**Comment by chenfiona** [comment]
My apology, Erik, for the late response!  
Yes, I have resolved the issue by transforming it into one single document using XSLT.  
BUT I have something more INTERESTING for you, LATER...

**Comment by chenfiona** [comment]
@ehennum: Can you look into this?   Thank you!
[https://stackoverflow.com/questions/64142328/java-xquery-xslt-transformation-during-ingestion]

**Comment by ehennum** [comment]
Closing because this issue is resolved.
