### ISSUE TITLE
upgrade  Gradle wrapper

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1268]
Use the latest Gradle wrapper that runs on Java 8

**Comment by ehennum** [comment]
Should cause no regressions for any builds that use the Gradle wrapper

Could cause regressions for builds that use older Gradle versions that don't understand the build.gradle instructions preferred for Gradle 6.7

**Comment by georgeajit** [comment]
Tests and builds are working fine with new wrapper (Gradle downloaded).
