### ISSUE TITLE
Dependent jars not available in distribution zip file.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#1272]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
develop (after 5.3.1 release)

### Version of MarkLogic Server

10.0-5.1

### Java version

JDK 1.8 u 261

### OS and version

Windows and Linux

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Run ``` ./gradlew marklogic-client-api:distZip``` from ```develop``` branch.
### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
Open up zip file inside the build folder and verify if all dependencies (3rd party Jars) are available. They are not available as of now. Java client API jar is only one available.
### Expected output: What specifically did you expect to happen?
All dependencies should be available.
### Alternatives: What else have you tried, actual/expected?
A checkout of tagged release was done. In this case we have all required jars to support a client application.

**Comment by ehennum** [comment]
I've confirmed that the master branch (and thus the master-1274 branch) builds the downloadable distribution whether the distZip task is run from the IDE or from the gradlew Gradle wrapper.  Thus, this bug is **not** a blocker for #1274

The develop branch uses archiveFileName instead of archiveName.  Possibly that's incorrect or other configuration properties are also needed.

**Comment by ehennum** [comment]
It seems that gradle changed the runtime property to runtimeClasspath --  in my testing, that change was enough to add the dependency jars to the lib directory.

I also incremented the year in the copyright for the JavaDoc.

**Comment by georgeajit** [comment]
Jars are available in the distribution. Tested with a checkout with JCenter removed as a source repository for the release.

**Comment by llinggit** [comment]
There's no server-side change in this issue.
