### ISSUE TITLE
Unhelpful error message when connecting to an app server requiring SSL but without an SSLContext

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#1284]
So we can address your issue, please include the following:

### Version of MarkLogic Java Client API

5.3.2

### Version of MarkLogic Server

10.0-5

### Java version

Java 8 and 11

### OS and version

Mac, but N/A

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

Below is a program that can be used to connect to a DHS app server, or any app server that requires SSL. The SimpleX509TrustManager is from ml-javaclient-util and just creates an basic SSLContext. This program will run fine as-is (after setting host/username/password to something valid).

```
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.ext.modulesloader.ssl.SimpleX509TrustManager;

public class SslTest {

    public static void main(String[] args) {
        String host = "changeme";
        String username = "changeme";
        String password = "changeme";

        DatabaseClientFactory.BasicAuthContext context = new DatabaseClientFactory.BasicAuthContext(username, password);
        context.withSSLContext(SimpleX509TrustManager.newSSLContext(), new SimpleX509TrustManager());
        context.withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier.ANY);

        DatabaseClient client = DatabaseClientFactory.newClient(host, 8011, context);
        System.out.println(client.newDocumentManager().exists("/entities/Customer.entity.json"));
    }
}
```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)

However, if you comment out the withSSLContext line, you get this error (and this is connecting to a REST server using the OOTB rewriter - /MarkLogic/rest-api/error-handler.xqy 

```
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: Document existence check failed: Bad Request. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.
	at com.marklogic.client.impl.OkHttpServices.headImpl(OkHttpServices.java:1243)
```

It's very unlikely that a user will realize that this error is due to not having an SSLContext. The error makes it sound like something is wrong with the app server and it's returning improper error messages.

This is a common problem with DHS instances, where if a user doesn't have an SSL-related property set correctly, the user will get the above error message. And the user will likely not have any idea what their problem is. 

### Expected output: What specifically did you expect to happen?

The error should make it clear that SSL is expected, but no SSLContext was provided.

For example, if I instead comment out the withHostnameVerifier line, I get this much more helpful error message:

```
Exception in thread "main" com.marklogic.client.MarkLogicIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname changeme not verified:
```

### Alternatives: What else have you tried, actual/expected?

N/A

**Comment by ehennum** [comment]
This bug can't be fixed in the Java API client or even in the REST API.

The appserver would need to provide an error message that indicates an SSL appserver is available on the same port.

An RFE for that enhancement would need to be filed on the server.
