### ISSUE TITLE
5.4.0: Constructing a QueryBatcher fails with docBatchSize cannot be less than 1

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#1290]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API

5.4.0

### Version of MarkLogic Server

10.0-5 (this seems important, as looking at newQueryBatcherImpl in DMM, this only happens if ML is 10.0-5 or higher)

### Java version

Java 8

### OS and version

N/A

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

This will reproduce the bug:

```
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.datamovement.DataMovementManager;
import com.marklogic.client.datamovement.QueryBatcher;

public class QueryBatcherTest {

    public static void main(String[] args) {
        DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8010, new DatabaseClientFactory.DigestAuthContext("admin", "admin"));
        DataMovementManager dmm = client.newDataMovementManager();
        QueryBatcher qb = dmm.newQueryBatcher(client.newQueryManager().newStringDefinition().withCriteria("")).withBatchSize(10);
        qb.onUrisReady(batch -> System.out.println("Just testing: " + batch));
        dmm.startJob(qb);
        qb.awaitCompletion();
        dmm.stopJob(qb);
        System.out.println("All done!");
    }
}
```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)

I get this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: docBatchSize cannot be less than 1
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl.withBatchSize(QueryBatcherImpl.java:319)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl.<init>(QueryBatcherImpl.java:122)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl.<init>(QueryBatcherImpl.java:92)
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.newQueryBatcherImpl(DataMovementManagerImpl.java:136)
	at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.newQueryBatcher(DataMovementManagerImpl.java:117)
	at QueryBatcherTest.main(QueryBatcherTest.java:13)
```

### Expected output: What specifically did you expect to happen?

No error. 

### Alternatives: What else have you tried, actual/expected?

I don't see any workaround. newQueryBatcherImp is being called with the defaultDocBatchSize of -1, which throws the error before withBatchSize can be called. 

Now, if I use this line instead:

```
QueryBatcher qb = dmm.newQueryBatcher(client.newQueryManager().newStructuredQueryBuilder().collection("hub-core-artifact"));
```

Then the error does not occur. So I believe the bug is in DataMovementServices.initConfig, which branches on the type of query.

**Comment by rjrudin** [comment]
To clarify then - I think the bug is specific to newQueryBatcher(StringQueryDefinition), though it may impact other constructors as well.

**Comment by georgeajit** [comment]
I see that using empty ```withCriteria("")``` throws ```IllegalArgumentException```. But with a valid string, there is no ```IllegalArgumentException```.

This snippet does not throw an error with Java client code being on develop branch (post 5.4.0 tagged release) and MarkLogic Server Windows build being 10.0-6.1.

```
 public void testDHFIssue() throws IOException, InterruptedException {
    System.out.println("Running testDHFIssue");
    QueryBatcher qb = dmManager.newQueryBatcher(client.newQueryManager().newStringDefinition().withCriteria("John AND Bob")).withBatchSize(10);
    qb.onUrisReady(batch -> System.out.println("Just testing: " + batch));
    dmManager.startJob(qb);
    qb.awaitCompletion();
    dmManager.stopJob(qb);
    System.out.println("All done!");
  }
```
Output
```
...
...
10:38:46.456 [Test worker] INFO  c.m.c.d.impl.QueryBatcherImpl - Starting job docBatchSize=10, docToUriBatchRatio=31, threadThrottleFactor= 0, threadCount=31, onUrisReady listeners=2, failure listeners=3
10:38:47.288 [Test worker] INFO  c.m.c.d.impl.QueryBatcherImpl - Job complete, jobBatchNumber=0, jobResultsSoFar=0
All done!
In tearDown
```

Will try to cover other cases when this case is fixed.

**Comment by ehennum** [comment]
Thanks, @georgeajit , for the isolation on the necessary condition.

@rjrudin , can you expand on the motivation for passing in an empty string?  I'm thinking that, absent a good use case, an empty string should be an error.

**Comment by rjrudin** [comment]
@ehennum  It was some older pre-DHF 5 code where the intent was to query for everything. I changed it into a serialized form of "cts:true-query()", and that works fine.

**Comment by rjrudin** [comment]
@ehennum  I can agree to an error, but I think the message should indicate what a user should do. The current message mentions "docBatchSize", which is an implementation term, not a user-facing one. If the user thinks this is controlled by "withBatchSize", they'll check what they're setting that to, but in this scenario, that method wasn't even being called. So the user has no idea how to fix the problem - i.e. the user has no idea that an empty string is the source of the error.

**Comment by llinggit** [comment]
When setting an empty string to withCriteria, it is treated as no $constructedQuery in forest-info-model.xqy file. Therefore, no defaultDocBatchSize is returned and defaultDocBatchSize is -1. I'll throw an error in withCriteria method to prevent using an empty string as a parameter.

**Comment by llinggit** [comment]
There's no server-side change in this issue.
