### ISSUE TITLE
Reusing DatabaseClient in combination with loadbalancer session cookies are not resent by Client

### ISSUE THREAD

**Issue by KOOPMog** [marklogic/java-client-api#1292]
### Version of MarkLogic Java Client API
5.2.0

### Version of MarkLogic Server
10.0.4-4

### Java version
11

### OS and version
Linux Red Hat

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Keep in mind that you need a loadbalancer that supports affinity through session cookies.

```
package nl.overheid.koop.cup.blcomponents.optic;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.BasicAuthContext;
import com.marklogic.client.Transaction;
import com.marklogic.client.extra.okhttpclient.OkHttpClientConfigurator;
import com.marklogic.client.io.StringHandle;
import okhttp3.ConnectionPool;
import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import org.apache.commons.net.util.TrustManagerUtils;

import javax.net.ssl.SSLContext;
import java.security.NoSuchAlgorithmException;
import java.util.concurrent.TimeUnit;

public class PoCLoadbalancedAddress {

  public static void main(String[] args) throws Exception {
    DatabaseClientFactory.addConfigurator(new LoggingInspectorConfigurator());
    new PoCLoadbalancedAddress().doit();
  }

  //TODO config
  private static int threadCount = 20;
  private static int requestCount = 100000/threadCount;
  private static ConnectionPool connectionPool = new ConnectionPool(5,5,TimeUnit.MINUTES);
  private static String user = "admin"; //User can be variable per thread/databaseclient
  private static String pw = "admin";
  private static String address = "lb.example.com";
  private static int port = 8040;
  private static boolean reuseClient = true; //Set to true for reproducing issue
  private static BasicAuthContext context = new BasicAuthContext(user, pw);

  public void doit() throws Exception {
    try {
      ReusableClientNewTransactionSingleRequest task = new ReusableClientNewTransactionSingleRequest();

      for (int i = 0; i < threadCount; i++) {
        new Thread(task, "Thread" + i).start();
        Thread.sleep(100);
      }

    } finally {
      System.out.println("End");
    }
  }

  private static class LoggingInspectorConfigurator implements OkHttpClientConfigurator {
    public boolean isConfigured = false;
    @Override
    public void configure(OkHttpClient.Builder httpClientBuilder) {
      if (httpClientBuilder != null) {
        isConfigured = true;
        httpClientBuilder.connectionPool(connectionPool);
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor();
        httpLoggingInterceptor.level(HttpLoggingInterceptor.Level.HEADERS);
        httpLoggingInterceptor.redactHeader("Authorization");
        httpClientBuilder.addInterceptor(httpLoggingInterceptor);
      }
    }
  }

  private static class ReusableClientNewTransactionSingleRequest implements Runnable {
    private ThreadLocal<DatabaseClient> threadLocal = new ThreadLocal<>();

    @Override
    public void run() {
      try {
        context.withSSLContext(SSLContext.getDefault(), TrustManagerUtils.getValidateServerCertificateTrustManager());

        DatabaseClient client = DatabaseClientFactory.newClient(address, port, context, DatabaseClient.ConnectionType.GATEWAY);
        threadLocal.set(client);
        printActionInfo("Create client");

        for (int i = 0; i < requestCount; i++) {
          newTransactionSingleRequest(threadLocal.get());
        }

      } catch (NoSuchAlgorithmException noSuchAlgorithmException) {
        noSuchAlgorithmException.printStackTrace();
      } finally {
        threadLocal.get().release();
        printActionInfo("Release client");
      }
    }

    private void newTransactionSingleRequest(DatabaseClient client) {

      if (!reuseClient) client = DatabaseClientFactory.newClient(address, port, context, DatabaseClient.ConnectionType.GATEWAY);
      Transaction transaction = client.openTransaction("lb-tester" + Thread.currentThread().getName(), 3500);

      try {
        printActionInfo("Open transaction", transaction);
        client.newXMLDocumentManager().read("/document.xml", new StringHandle(), transaction);

      } catch (Exception e) {
        e.printStackTrace();
        System.out.flush();
        System.exit(2);
      }
      try {
        printActionInfo("Rollback transaction", transaction);
        transaction.rollback();
        if (!reuseClient) client.release();

      } catch (Exception e) {
        e.printStackTrace();
        System.out.flush();
        System.exit(3);
      }
    }
  }

  private static void printActionInfo(String action) {
    System.out.print("\n" + action
            + "\n  connection count: " + connectionPool.connectionCount() + "/" + connectionPool.idleConnectionCount()
            + "\n  thread          : " + Thread.currentThread().getName());
    System.out.flush();
  }

  private static void printActionInfo(String action, Transaction transaction) {
    System.out.print("\n" + action
            + "\n  connection count: " + connectionPool.connectionCount() + "/" + connectionPool.idleConnectionCount()
            + "\n  thread          : " + Thread.currentThread().getName()
            + "\n  transactionId   : " + transaction.getTransactionId()
            + "\n  hostId          : " + transaction.getHostId()
            + "\n  cookies         : " + transaction.getCookies());
    System.out.flush();
  }
}
```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
We see that when using multiple statement transactions when reusing the DatabaseClient with a loadbalancer that supports session affinity through cookies, no cookies are being resent by the Java client, which finally results in 'XDMP-NOTXN: No transaction with identifier' in a multithreaded environment. We reuse the DatabaseClient as recommended here: https://help.marklogic.com/Knowledgebase/Article/View/435/0/notes-on-using-the-java-client-api-effciently

Attached log:
[github1292.txt](https://github.com/marklogic/java-client-api/files/6170664/github1292.txt)

### Expected output: What specifically did you expect to happen?
We expected that when using multliple statement transactions when reusing the database client that cookies are still being resent by the Java-client so the loadbalancer knows where the transactions lives and can correctly route the request to the transaction node.

### Alternatives: What else have you tried, actual/expected?
When not reusing the database client we see the expected results (set reuseClient to false in the above example to create a client on each request), however this is not our use case, because we want to have a database client per user and sharing across threads, as recommended here: https://help.marklogic.com/Knowledgebase/Article/View/435/0/notes-on-using-the-java-client-api-effciently, .

To clarify the underlying issue I am facing is that some requests end up on the wrong node and failing in 'No transaction with identifier', and that is the issue I want to solve.

**Comment by ehennum** [comment]
Observation about the code:

-  The run() function executed by each thread is creating a separate database client on the local stack for the thread on line 51; there's no reuse of the client across threads.

-  200 threads could send more requests than some clusters can handle (depending on the load and number of enodes); it would be appropriate to monitor the enodes during the test if that is a possibility.

- The calls to openTransaction() are assigning the same name to every transaction.  That doesn't seem to be a problem, given that most transactions are rolled back.  Assigning a different name to each transaction, however, might produce better entries in the server error log.

Observations based on the error log:

- All transactions are rolled back except the following 4895303025913789952 (thread 12, host 3), 5564397635149712290 (thread 2, host 2), and 9057211232598482163 (thread 13, host 2).  Each is the last logged transaction for the thread, so they were likely still in flight.

- The transaction id in the error message (15675564030349745572) doesn't appear in any other log message, so we don't know which cookies it is associated with.  Based on the stack trace, it seems to be coming from the client.newXMLDocumentManager().read() call.

@KOOPMog , I'm wondering whether adding a System.out.flush() call after each System.out.print() call could ensure that the log entry from each transaction open is logged including the cookies for the transaction that fails.  It might even be necessary to wrap the read and rollback in a try that has a catch that executes System.out.flush() followed by System.exit().

It would be useful to correlate the failing request with its access log entry on the enode.

Set the OKHTTP_LOGGINGINTERCEPTOR_LEVEL system property to BASIC or maybe HEADERS to ask OKHttp to log the cookies.

**Comment by KOOPMog** [comment]
Hello,

Thank you for your quick reply. The code I added is to illustrate a issue we experienced when using a loadbalancer in our application in production-environment. We configured the loadbalancer to keep sticky sessions based on session cookies. Our Java-application (hosted in Tomcat) caches the database client per host (when configured is the loadbalanced address of the cluster) and user. We have multiple users that each has their own 'space' so opening a transaction do some stuff reading/writing documents and commiting or rolling back the transaction. That is why I somehow wanted to simulate the same situation with multiple threads locally and just using rollbacks. As you can imagine we do not use the loadbalancer now in production, and we have pinned our application to one node which is unwanted for several reasons. 
However we have a production-like environment where we are testing this out. Load does not seem to be the problem, as I can reproduce the issue with 20 threads.
I have updated the code as you suggested, and attached the log where I only obfuscated the address.
I hope the information provided is more helpful.
Thanks again.

Bob.

**Comment by ehennum** [comment]
@KOOPMog , please open a support ticket so the support team can try to reproduce the problem.  Reproducing the issue will be essential for the investigation.

We have tested the Java API with load balancer and do have production adoptions that use load balancers (including every DHS instance that uses the Java API).  While it is possible there is a bug, the other possibility is that there's configuration issue with the load balancer.
