### ISSUE TITLE
Java API Plugin mlcp tasks

### ISSUE THREAD

**Issue by chenfiona** [marklogic/java-client-api#1295]
>## Transform Models, Input and Output
MODEL   | F1: e2e transform XML  | F2:  e2e flatten JSON  | F3:  partial flatten JSON
------------- | --------------------------- | ------------------------- | --------------------------
Input XML   | Output: full XML transform  | Output: full flatten to JSON | Output: custom flatten to JSON
[proto.zip](https://github.com/marklogic/java-client-api/files/6370772/proto.zip)|[proto-e2e-transform-XML.zip](https://github.com/marklogic/java-client-api/files/6370774/proto-e2e-transform-XML.zip)|[proto-e2e-flatten-JSON.zip](https://github.com/marklogic/java-client-api/files/6370783/proto-e2e-flatten-JSON.zip)|[proto-extract-flatten-JSON.zip](https://github.com/marklogic/java-client-api/files/6370775/proto-extract-flatten-JSON.zip)

### Version of MarkLogic Java Client API
`com.marklogic:marklogic-client-api:5.3.1`
### Version of MarkLogic Server
`10.0-4.4`
### Java version
`11.0.9`
### OS and version
`Win: Windows 10 Pro`
`Linux: CentOS Stream 8`

>## Solution One — Java API plugin MLCP
[java-gradle-df-transform.zip](https://github.com/marklogic/java-client-api/files/6370870/java-gradle-df-transform.zip)

I use Gradle task to transform the same input XML(s) to three environments based on my three MODELs:
 `gradle mlcpE2ETransformFxdEqdProductXML -PenvironmentName=local`  (result: `proto-e2e-transform-XML.xml`)
`gradle mlcpE2EFlattenFxdEqdProductJSON -PenvironmentName=dev`  (result:  `proto-e2e-flatten-JSON.json`)
`gradle mlcpExtractFlattenFxdProductJSON -PenvironmentName=production` (result: `proto-extract-flatten-JSON.json`)
>> 
What could be the invocation of mlcp `ServerTransform` in the Java API?  It is something like:
```
   ServerTransform transform = new ServerTransform()
      .addParameter("file-path", {data-dir})                         // mlcp => input_file_path 
       .addParameter("module", {module-name})                    // mlcp =>  transform_module
        .addParameter("namespace", {module-namespace})      // mlcp => transform_namespace
```
(NOTE: For this method, I prefer NOT resort to Java Data Services transform which I use for document search engine | update operations.)

> ## Solution Two — Gradle Groovy plugin MLCP
What is the working example of converting and applying MLCP custom task class via ml-gradle API? It is something like:
>>
```Package: com.marklogic.gradle.task.*```
```
class MlcpPlugin implements <project-interface> {
============
      project.task("mlcpE2ETransformFxdEqdProductXML", group: mlcpGroup, type: com.marklogic.gradle.task.MlcpTask)
      project.task("mlcpE2EFlattenFxdEqdProductJSON", group: mlcpGroup, type: com.marklogic.gradle.task.MlcpTask)
      project.task("mlcpExtractFlattenFxdProductJSON", group: mlcpGroup, type: com.marklogic.gradle.task.MlcpTask)
============
}
```
> ## Solution Three — DMSDK plugin transform (Resolved)

**Comment by ehennum** [comment]
The REST API (and thus the Java API) supports a simpler transform than mlcp.

I believe that ml-gradle supports invocation of mlcp.  That question is best asked on the ml-gradle repository.

https://github.com/marklogic-community/ml-gradle

(Copying @ling for awareness.)

**Comment by chenfiona** [comment]
Thanks!  
I believe Solution One(doesn't exist) will be the same mechanism as Solution Three which is the **rest-api/transform**.  
I am happy about the DMSDK performance. But the invocation and packaging is not as straightforward as command line MLCP.  Solution Two should solve that problem.
