### ISSUE TITLE
Upgrade to Jackson 2.12.4

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#1309]
I'm using Java Client 5.5.0, and it's using Jackson 2.11.1, which is a little on the old side now:

https://search.maven.org/artifact/com.fasterxml.jackson.core/jackson-databind

2.12.4 was released on July 6, 2021 and is the latest stable release. I'm thinking it's worth upgrading this as it's such a widely used library, and it seems better to be on the latest release.

**Comment by rjrudin** [comment]
Release notes - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12 

And list of bugfix releases since 2.12 was released:

- https://github.com/FasterXML/jackson-databind/issues?q=is%3Aclosed+milestone%3A2.12.1
- https://github.com/FasterXML/jackson-databind/issues?q=is%3Aclosed+milestone%3A2.12.2
- https://github.com/FasterXML/jackson-databind/issues?q=is%3Aclosed+milestone%3A2.12.3
- https://github.com/FasterXML/jackson-databind/issues?q=is%3Aclosed+milestone%3A2.12.4

One benefit of going up to 2.12.4 is that the ml-gradle stack is now on Spring 5.3.9. And then to get DHF on Spring 5.3.9, we need to update the Spring Boot version that DHF Hub Central uses to its latest version. And that latest version of Spring Boot depends 2.12.4 of jackson-databind . 

I am thinking that a 5.5.1 Java Client release could do this upgrade, assuming that the upgrade from 2.11 to 2.12 doesn't cause any issues.

**Comment by llinggit** [comment]
Hi @rjrudin, do you mean you would like a new release 5.5.1 which contains only this Jackson upgrading?

**Comment by rjrudin** [comment]
I'm only proposing that if a 5.5.1 release was an option, I think it would be consistent with semver (some conversation on the topic is at https://github.com/semver/semver/issues/148 ) to produce a new release that only upgrades a thirdparty dependency, assuming that doing so doesn't require additional improvements that would then necessitate a 5.6.0 release.

**Comment by georgeajit** [comment]
No regressions seen.
