### ISSUE TITLE
Expose the 3rd parameter of op.fromSPARQL

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1316]
This is for bug 56465. The new 3rd parameter is options, which could be dedup or base. Need to expose this parameter in Java Client API.

const op = require('/MarkLogic/optic');
    op.fromSPARQL('PREFIX ad: <http://marklogicsparql.com/addressbook#> '+
                    'SELECT ?firstName '+
                    'WHERE {<#5555> ad:firstName ?firstName .}'
                 , 'sparql', {dedup:'on',base:'http://marklogicsparql.com/id#'})
                .result();

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by ehennum** [comment]
I believe that the only thing missing is to write a unit test using PlanBuilder.sparqlOptions()

**Comment by llinggit** [comment]
OK, will add.

**Comment by llinggit** [comment]
When setting duplicate to true, it works, but when setting it to false, it returns 6 results instead of 2.

PlanSparqlOptions options = pb.sparqlOptions().withDeduplicated(false).withBase("http://marklogicsparql.com/id#");
