### ISSUE TITLE
regenerate Optic expression functions

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#1317]
pick up the latest changes

**Comment by ehennum** [comment]
Added sql.bucket() and cts.columnRangeQuery()
Fixed the data types and documentation on some existing methods.

**Comment by ehennum** [comment]
Should cause no regressions.

**Comment by georgeajit** [comment]
Verified Jenkins nightly build on Oct 10, 2021 with 10.0 MarkLogic Server build. Able to see ```com.marklogic.client.test.PlanGeneratedTest.testSqlBucket2Exec```, but not ```columnRangeQuery```. 

Maybe I am missing something here. Could you please clarify?

**Comment by ehennum** [comment]
Sorry for the delay:  The CtsExpr interface has the columnRangeQuery() method:

https://github.com/marklogic/java-client-api/blob/develop/marklogic-client-api/src/main/java/com/marklogic/client/expression/CtsExpr.java#L303

Is there an issue with using it?
