### ISSUE TITLE
Any plans for Java 17?

### ISSUE THREAD

**Issue by lonesloane** [marklogic/java-client-api#1321]
We have a strong policy in our company to stay up to date with the latest releases of Java, i.e. the new LTS Java 17. 

While preparing the upgrade, I ran into an issue related to the move from javax.* namespace to jakarta.* namespace

Do you know if it is actually possible to use the java-client-api with a Java 17 JDK ? And if not, are there plans to upgrade the api ?

**Comment by anu3990** [comment]
We do not have this in the roadmap for now.

**Comment by rjrudin** [comment]
@lonesloane  As noted in #1469, we believe this is addressed by resolving a gap in our docs that didn't explain the need to explicitly declare the JAXB dependency when using Java 11 or higher. If you're able to, please try out the approach noted at the bottom of #1469 and reply back on that ticket if it works for you.

**Comment by lonesloane** [comment]
@rjrudin I'll give it a try asap...can't promise it will be done quickly though ;-)
