### ISSUE TITLE
API doc wrong - PlanBuilder.count 3rd parameter

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1325]
"option - The options can take a values key with a 'distinct' value to average the distinct values of the column."

It should be "count", not "average".

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by ehennum** [comment]
I believe the change to the enode documentation will show up in the JavaDoc when the client is next regenerated.

**Comment by llinggit** [comment]
Got it. Thanks, Erik. I'll close this issue then.
