### ISSUE TITLE
Testing new optic APIs in Java Client

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1328]
Newly added optic APIs including

op.columnInfo (TBD)
3rd parameter for op.xpath

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by rjrudin** [comment]
Closing, as we have dozens of tests for new Optic APIs - particularly Optic Update.
