### ISSUE TITLE
Project description is incorrect on Maven Central

### ISSUE THREAD

**Issue by hansenmc** [marklogic/java-client-api#1335]
On Maven Central, the MarkLogic Client API description is: `$project.description`.
https://mvnrepository.com/artifact/com.marklogic/marklogic-client-api

It had a more descriptive description when we had published under https://mvnrepository.com/artifact/com.marklogic/java-client-api. 

We might need to check the pom and deployment scripts used to publish to Maven Central.

**Comment by hansenmc** [comment]
https://github.com/marklogic/java-client-api/blob/master/marklogic-client-api/build.gradle#L85
It seems that 

    textdescription '$project.description'

isn't being resolved the same way that the name is:

    name '$rootProject.describedName'

**Comment by hansenmc** [comment]
May need to change single quotes to double-quotes, so that it's a GString that will expand the variable:

    textdescription "$project.description"

**Comment by georgeajit** [comment]
Thank you @hansenmc . Have made changes as suggested by you in ```build.gradle``` file.
