### ISSUE TITLE
Generate code for 3rd parameter of op.xpath

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1336]
Need to modify optic-defs.json under xdmp/src/makefiles/optic first.
Then run code generation again to refresh the change in Java Client API

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by rjrudin** [comment]
We have a PR for this; we're tracking items in JIRA, so closing this as we don't need it to be tracked in github.
