### ISSUE TITLE
Transfer Encoding has non-emtpy body when no result in returned through okhttp

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1346]
While transfer encoding(chunking) is enabled, I found that when no result is returned, okhttp returns non-empty body. This doesn't happen when transfer encoding is disabled. This causes some trouble and we have an hack to solve this. 
Need to investigate this further. 

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by llinggit** [comment]
Line 4509 in OkHttpServices.java

**Comment by rjrudin** [comment]
Transferring to JIRA to determine what the actual issue is and if we need to take action.

**Comment by llinggit** [comment]
https://github.com/marklogic/java-client-api/commit/63db03f189c3bb23f517ae70cad9143a25ba5cc0#diff-440ed75d65b0122edbdc9ea8b7e3f58099043a08af847992215304f682ab7cba
