### ISSUE TITLE
Incorrectly return empty query result

### ISSUE THREAD

**Issue by Cynthia-77** [marklogic/java-client-api#1460]
### Version of MarkLogic Java Client API
 5.5.3 

### Version of MarkLogic Server

 10.0-9.5 

### Java version

java 11.0.16.1 2022-08-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode) 

### OS and version

OS name: Microsoft Windows 11
OS version: 10.0.22000 

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end

Executing the following SparQL query for example will cause a empty query result:

```SPARQL
SELECT *
WHERE { ?s ?p ?o .
	FILTER ( 805964266*1719307142*805964270 )
      }
```

 Corresponding Java code: 

```java
import java.io.File;
import java.io.IOException;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.io.*;
import com.marklogic.client.semantics.*;

public class MarkLogic_Test {
    static DatabaseClient client = DatabaseClientFactory.newClient(
            "localhost", 8000, "Documents",
            new DatabaseClientFactory.DigestAuthContext(
                    "root", "123"));
    static private GraphManager graphMgr = client.newGraphManager();
    static private String graphURI = GraphManager.DEFAULT_GRAPH;
    static private String tripleFilename = "./example.ttl";

    // Load managed triples from a file into a graph in MarkLogic
    public static void loadGraph(String filename, String graphURI, String format) {
        FileHandle tripleHandle = new FileHandle(new File(filename)).withMimetype(format);
        graphMgr.write(graphURI, tripleHandle);
    }

    // Evaluate a SPARQL query.
    public static void sparqlQuery() throws IOException {
        SPARQLQueryManager qm = client.newSPARQLQueryManager();
        SPARQLQueryDefinition query = qm.newQueryDefinition(
                "SELECT *\n" +
                        "WHERE { ?s ?p ?o .\n" +
                        "FILTER ( 805964266*1719307142*805964270 )\n" +
                        "}"
        );
        JacksonHandle results = new JacksonHandle();
        results.setMimetype(SPARQLMimeTypes.SPARQL_JSON);
        results = qm.executeSelect(query, results);
        results.write(System.out);
    }

    public static void main(String[] args) throws IOException {
        loadGraph(tripleFilename, graphURI, RDFMimeTypes.TURTLE);
        sparqlQuery();
        client.release();
    }
}
```

 Triple file:
example.ttl 

```turtle
<http://JohnSmith> <http://livesIn> "London".
<http://JohnSmith> <http://ages> 12 .
```

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)

The query result is empty:

```
{"head":{"vars":[]},"results":{"bindings":[]}}
```

### Expected output: What specifically did you expect to happen?

The following query result is returned:

| ?s                             | ?p                           | ?o      |
| ------------------------------ | ---------------------------- | -------- |
| \<http://JohnSmith> | \<http://livesIn> | "London" |
| \<http://JohnSmith> | \<http://ages> | 12 |

### Alternatives: What else have you tried, actual/expected?

Executing the SparQL query in Query Console will get empty query result as well.

This query can return the expected query result in Apache Jena and RDF4j.

It may be caused by the out-of-bounds calculation result of FILTER?

**Comment by rjrudin** [comment]
I've pinged some of our SPARQL experts about this. Because you're able to reproduce your question in qconsole, I recommend using stackoverflow and the "marklogic" tag for a question like this - https://stackoverflow.com/search?tab=newest&q=marklogic - as it's not specific to the MarkLogic Java Client.

**Comment by hansenmc** [comment]
https://stackoverflow.com/a/74477041/14419
