### ISSUE TITLE
Remove "ML-Check-ML11-Headers" for ML11 java client api

### ISSUE THREAD

**Issue by llinggit** [marklogic/java-client-api#1582]
We added flag "ML-Check-ML11-Headers" to enable compression and chunking for ML10. Now we need to remove this flag for ML11 java client connector. Removing it in the server rest code as well.
https://project.marklogic.com/jira/browse/DBQ-79

Original issue in java client as below
https://github.com/marklogic/java-client-api/issues/1342
https://github.com/marklogic/java-client-api/pull/1343/files

So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server

See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version

Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

**Comment by rjrudin** [comment]
Will track internally.
