### ISSUE TITLE
Wrong timeout conversion in awaitCompletion

### ISSUE THREAD

**Issue by hapeka72** [marklogic/java-client-api#1637]
Hi,

the conversion of the timeout in this line is wrong:
https://github.com/marklogic/java-client-api/blob/b68bab95f566c48efe37bda76de531cc7f21924f/marklogic-client-api/src/main/java/com/marklogic/client/datamovement/impl/WriteBatcherImpl.java#L890

It should be like this:
`long duration = TimeUnit.MILLISECONDS.convert(timeout, unit);`

**Comment by rjrudin** [comment]
Thanks for the report @hapeka72 , we'll look into this today.

**Comment by hapeka72** [comment]
Perfect, thank you!

**Comment by rjrudin** [comment]
This will be in the 6.6.0 release this week.
