### ISSUE TITLE
Use rich argument marshaling for Java API eval and invoke

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#166]
XDBC protocol is tricky but allows specification of types, whereas REST API eval has a simpler API which accepts a JSON payload.  Since the types are inferred in the REST API it does not have all the functionality of the XDBC protocol.  This is not an issue for REST eval nor Node.js eval which is primarily intended to be used with JSON data payloads.  However, the goal for the Java Client API is to eventually replace XCC, including all capabilities with XML and XQuery.  To do that we will use XDBC as transport protocol to have all the features available to XCC.

**Comment by sammefford** [comment]
Charles, I'm hoping #268 helps somewhat to answer your question.  I've completed the implementation for this and I'm just waiting on a dependency in the server layer to push my changes.  Now that my head is back in this I can see clearly that this change unlocks the ability to do #268.

**Comment by sammefford** [comment]
Commit 1e38454 resolves this issue.

**Comment by georgeajit** [comment]
Need to monitor eval tests and make sure that there are no regressions.

**Comment by georgeajit** [comment]
Modified xquery-modules-with-diff-variable-types.xqy module that had incorrect declarations.
