### ISSUE TITLE
Include method and parameter descriptions in resource metadata

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#17]
As a developer using the REST API
I want to include method and parameter descriptions in resource metadata
So that clients of the resources I provide can look at /v1/config/resources (or perhaps an HTML view of this content) and get information not just about the resource itself, but also about each method and each parameter, thereby making it easier for the developer to invoke the resource correctly. 

Notes:
- In theory this can be done by describing each of the methods and parameters in the resource description, but that becomes very unwieldy for resources with multiple methods and parameters.
- This is an enhancement to the REST API itself; the Java API would then to expose this capability in ResourceExtensionsManager::writeServices. A new data structure would be needed instead of the simple map that MethodParameters currently is, as each method and parameter would need something like a "setDescription(String)" method.

**Comment by ehennum** [comment]
Superseded by Data Service endpoints.
