### ISSUE TITLE
Java API provides defaults that override configured options

### ISSUE THREAD

**Issue by grechaw** [marklogic/java-client-api#182]
As a general rule, if you store options on the server and provide no explicit settings in the Java Client API, then the options stored on the server should take precedence.

I found that the Java API does not respect page-length or values/aggregate if they are set in the options node.

To reproduce, load samplestack data and store this options node:

"values": [
            {
                "name": "tags",
                "aggregate":{"apply":"count"},
                "range": {
                    "json-property": "tags",
                    "type": "xs:string"
                },
                "values-option": [
                    "frequency-order",
                    "descending",
                    "limit=5"
                ]
            }

The Java .values call will not return the count aggregate.  It only will return aggregates that you set explicitly in the Java client.

**Comment by sammefford** [comment]
Srinath, I'm believing we probably need to fix this for bulk search.  Looking at the history here, I don't think I ever made any fixes--I just tried and failed to validate. So I wonder if there are still cases where this is happening for values calls.  I'm wondering if you could design some tests to understand where we override server options and where we don't.  I think we need to test DocumentManager.search (bulk search), QueryManager.search, QueryManager.values, and QueryManager.tuples.  And let's at least test persisted options versus specified view, category, pageLength/limit, frequency, direction, aggregatePath, and aggregate.

**Comment by georgeajit** [comment]
QueryManager.values, and QueryManager.tuples along with frequency, aggregatePath, and aggregate to be handled after team discussions,  in 4.0.2 in a separate task.

I am not sure how to override/overwrite options for ```queryMgr.newValuesDefinition()```, since it works only with a constraint name and previously saved options name.

**Comment by sammefford** [comment]
Agreed.  @georgeajit , go ahead and saved a named options config, then test using that and make sure it's used, not overridden by any internal Java default.
