### ISSUE TITLE
URI for ID of type Calendar is not what we expect

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#183]
It can be seen that using the DateTime as an annotated class member causes a long DB URI for the inserted object.

@Test
       public void testPOJORepoReadWithDateTime() {
              PojoRepository<SpecialArtifactDateTime,Calendar> pojoReposProducts = client.newPojoRepository(SpecialArtifactDateTime.class, Calendar.class);          

```
          //Load object into database
          long longId = getOneNegativeLongId();
          // Create a calendar object.
          Calendar calTime = Calendar.getInstance();
          String artifactName = new String("Acme");
          pojoReposProducts.write(this.setSpecialArtifactWithDateTime(longId, artifactName, calTime),"odd","numbers");        

          // Validate the artifact read back.
          SpecialArtifactDateTime artifact = pojoReposProducts.read(calTime);
          validateSpecialArtifactWithDateTime(artifact, artifactName, longId, calTime);
   }
```

And this is POJO class annotated:

/*
         \* This class is used to test writing and reading date-time
         \* Class member  expiryDate has been annotated with @Id.
         */
       public static class SpecialArtifactDateTime {  
               @Id
              public Calendar expiryDate;

```
          private String name;
          private long id;
          private Company manufacturer;
          private int inventory;

          public Calendar getExpiryDate() {
                 return expiryDate;
          }
          public SpecialArtifactDateTime setExpiryDate(Calendar expiryDate) {
                 this.expiryDate = expiryDate; return this;
          }

          public long getId() {
                 return id;
          }
          public SpecialArtifactDateTime setId(long id) {
                 this.id= id; return this;
          }
          public String getName() {
                 return name;
          }
          public SpecialArtifactDateTime setName(String name) {
                 this.name = name; return this;
          }
          public Company getManufacturer() {
                 return manufacturer;
          }
          public SpecialArtifactDateTime setManufacturer(Company manufacturer) {
                 this.manufacturer= manufacturer; return this;
          }
          public int getInventory() {
                 return inventory;
          }
          public SpecialArtifactDateTime setInventory(int inventory) {
                 this.inventory= inventory; return this;
          }
   }
```

I see the DB URI as this:

com.marklogic.javaclient.TestPOJOSpecialCharRead$SpecialArtifactDateTime/java.util.GregorianCalendar%5Btime%3D1415297206761%2CareFieldsSet%3Dtrue%2CareAllFieldsSet%3Dtrue%2Clenient%3Dtrue%2Czone%3Dsun.util.calendar.ZoneInfo%5Bid%3D%22America%2FLos_Angeles%22%2Coffset%3D-28800000%2CdstSavings%3D3600000%2CuseDaylight%3Dtrue%2Ctransitions%3D185%2ClastRule%3Djava.util.SimpleTimeZone%5Bid%3DAmerica%2FLos_Angeles%2Coffset%3D-28800000%2CdstSavings%3D3600000%2CuseDaylight%3Dtrue%2CstartYear%3D0%2CstartMode%3D3%2CstartMonth%3D2%2CstartDay%3D8%2CstartDayOfWeek%3D1%2CstartTime%3D7200000%2CstartTimeMode%3D0%2CendMode%3D3%2CendMonth%3D10%2CendDay%3D1%2CendDayOfWeek%3D1%2CendTime%3D7200000%2CendTimeMode%3D0%5D%5D%2CfirstDayOfWeek%3D1%2CminimalDaysInFirstWeek%3D1%2CERA%3D1%2CYEAR%3D2014%2CMONTH%3D10%2CWEEK_OF_YEAR%3D45%2CWEEK_OF_MONTH%3D2%2CDAY_OF_MONTH%3D6%2CDAY_OF_YEAR%3D310%2CDAY_OF_WEEK%3D5%2CDAY_OF_WEEK_IN_MONTH%3D1%2CAM_PM%3D0%2CHOUR%3D10%2CHOUR_OF_DAY%3D10%2CMINUTE%3D6%2CSECOND%3D46%2CMILLISECOND%3D761%2CZONE_OFFSET%3D-28800000%2CDST_OFFSET%3D0%5D.json

**Comment by gvaidees** [comment]
Should there be a milestone associated with this issue?

**Comment by sammefford** [comment]
When we fix this, just make sure we also check that #237 is fixed.
