### ISSUE TITLE
Add test coverage for bitemporal against enhanced app server port

### ISSUE THREAD

**Issue by gvaidees** [marklogic/java-client-api#208]
Add test coverage for bitemporal against enhanced app server port

**Comment by sammefford** [comment]
Ganesh, does this still need to be done?

**Comment by gvaidees** [comment]
I believe so. I am cc'ing @sravanr to confirm

**Comment by sravanr** [comment]
we should change the milestone, i will take a look at the test in 8.0-2 time frame.

**Comment by sammefford** [comment]
@georgeajit can you take a look at this and see if it still needs to be done?

**Comment by georgeajit** [comment]
TestBiTemporal has the support for the app server port.
 private static int uberPort = 8000;
evalClient = DatabaseClientFactory.newClient("localhost", uberPort, dbName,
        "eval-user", "x", Authentication.DIGEST);
