### ISSUE TITLE
Support type attribute in structured queries

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#215]
Erik Hennum sent the following:

Previously (EA3 and before), structured query expressed the type for a values query on JSON like so:

        <search:query>
            <search:value-query>
                <search:json-property>running</search:json-property>
                <search:boolean>true</search:boolean>
             </search:value-query>
         </search:query> 

Now, you express it this way:

        <search:query>
            <search:value-query type="boolean">
                <search:json-property>running</search:json-property>
                <search:text>true</search:text>
             </search:value-query>
         </search:query> 

We had to make that change to allow search criteria against a constraint over JSON, as in:

    running:true

    <constraint name="running">
        <value type="boolean">
            <json-property>running</json-property>
        </value>
    </constraint>

**Comment by georgeajit** [comment]
Moved to ship.

Have testQueryBuilderValueWithString method in TestPOJOWithStrucQD.java to test for StructuredQueryBuilder.JSONProperty path range indexed on string - POJORepository.

Have 3 methods in TestBulkSearchWithStringQueryDef.java to test String, Boolean in XML files.
