### ISSUE TITLE
Unit test BulkReadWriteTest.xml failed in nightly regression at test_171

### ISSUE THREAD

**Issue by sravanr** [marklogic/java-client-api#228]
Here is the failure trace

<testcase time="1.401" classname="com.marklogic.client.test.BulkReadWriteTest" name="test_171">
    <failure message="Count of documents inside of the transaction expected:&lt;2&gt; but was:&lt;1&gt;" type="java.lang.AssertionError">java.lang.AssertionError: Count of documents inside of the transaction expected:&lt;2&gt; but was:&lt;1&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.marklogic.client.test.BulkReadWriteTest.test_171(BulkReadWriteTest.java:588)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
    <system-out>10:54:16.594 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8012
10:54:16.594 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8012 as rest-evaluator
10:54:16.670 [main] DEBUG c.m.client.impl.JerseyServices - Opening transaction
10:54:17.925 [main] DEBUG c.m.client.impl.JerseyServices - Posting multipart for documents
10:54:17.942 [main] DEBUG c.m.client.impl.JerseyServices - Searching for null
10:54:17.963 [main] DEBUG c.m.client.impl.JerseyServices - Searching for null
10:54:17.985 [main] DEBUG c.m.client.impl.JerseyServices - Completing transaction 2847992484655785719 with rollback
</system-out>
    <system-err>[DEBUG] wire - &gt;&gt; "POST /v1/transactions HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 401 Unauthorized[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "WWW-Authenticate: Digest realm="public", qop="auth", nonce="a6c9e175f5c8e28a668d5f972e00da67", opaque="f59b72c6a6c5bf96"[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Type: application/json; charset=utf-8[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 104[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "{"errorResponse":   {"statusCode":401,[\n]"
[DEBUG] wire - &lt;&lt; "   "status":"Unauthorized",[\n]"
[DEBUG] wire - &lt;&lt; "   "message":"401 Unauthorized"[\n]"
[DEBUG] wire - &lt;&lt; "  }[\n]"
[DEBUG] wire - &lt;&lt; "}"
[DEBUG] wire - &gt;&gt; "POST /v1/transactions HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/transactions",cnonce="67d07ec0",nc=00000001,response="e4de82003015b6301c7cdac866afc054"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 303 See Created Transaction[\r][\n]"
[DEBUG] wire - &lt;&lt; "Set-Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &lt;&lt; "Location: /v1/transactions/2847992484655785719[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "DELETE /v1/search?directory=/test_bulk_171/&amp;database=Documents HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/search",cnonce="bf49349f",nc=00000002,response="a27ffc144ec1bcdb40b0539fa853bf29"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie2: $Version=1[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 204 Deleted[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "POST /v1/documents?txid=2847992484655785719&amp;database=Documents HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Type: multipart/mixed; boundary=Boundary_43_1015387411_1418410457925[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/documents",cnonce="d09c29e5",nc=00000003,response="32e957d48e47422821394850dae33cdf"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie2: $Version=1[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "8e[\r][\n]"
[DEBUG] wire - &gt;&gt; "--Boundary_43_1015387411_1418410457925[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Disposition: attachment; filename="/test_bulk_171/sec0.xml"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Type: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "a0[\r][\n]"
[DEBUG] wire - &gt;&gt; "&lt;xml&gt;test0&lt;/xml&gt;[\r][\n]"
[DEBUG] wire - &gt;&gt; "--Boundary_43_1015387411_1418410457925[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Disposition: attachment; filename="/test_bulk_171/sec1.xml"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Type: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "3c[\r][\n]"
[DEBUG] wire - &gt;&gt; "&lt;xml&gt;test1&lt;/xml&gt;[\r][\n]"
[DEBUG] wire - &gt;&gt; "--Boundary_43_1015387411_1418410457925--[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &gt;&gt; "0[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 200 Bulk Change Written[\r][\n]"
[DEBUG] wire - &lt;&lt; "Set-Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &lt;&lt; "vnd.marklogic.document-format: xml[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 477[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "&lt;rapi:documents xmlns:rapi="http://marklogic.com/rest-api"&gt;&lt;rapi:document&gt;&lt;rapi:uri&gt;/test_bulk_171/sec0.xml&lt;/rapi:uri&gt;&lt;rapi:category&gt;metadata&lt;/rapi:category&gt;&lt;rapi:category&gt;content&lt;/rapi:category&gt;&lt;rapi:mime-type&gt;application/xml&lt;/rapi:mime-type&gt;&lt;/rapi:document&gt;&lt;rapi:document&gt;&lt;rapi:uri&gt;/test_bulk_171/sec1.xml&lt;/rapi:uri&gt;&lt;rapi:category&gt;metadata&lt;/rapi:category&gt;&lt;rapi:category&gt;content&lt;/rapi:category&gt;&lt;rapi:mime-type&gt;application/xml&lt;/rapi:mime-type&gt;&lt;/rapi:document&gt;&lt;/rapi:documents&gt;[\n]"
[DEBUG] wire - &gt;&gt; "GET /v1/search?directory=/test_bulk_171/&amp;database=Documents HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Type: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "Accept: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/search",cnonce="5b96e322",nc=00000004,response="e4ae3372a5656e838ef5af139046fa2c"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie2: $Version=1[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 200 OK[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 494[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "&lt;search:response snippet-format="snippet" total="0" start="1" page-length="10" xmlns:search="http://marklogic.com/appservices/search"&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;search:qtext/&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;search:metrics&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:query-resolution-time&gt;PT0.004299S&lt;/search:query-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:facet-resolution-time&gt;PT0.000098S&lt;/search:facet-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:snippet-resolution-time&gt;PT0S&lt;/search:snippet-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:total-time&gt;PT0.004796S&lt;/search:total-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;/search:metrics&gt;[\n]"
[DEBUG] wire - &lt;&lt; "&lt;/search:response&gt;[\n]"
[DEBUG] wire - &gt;&gt; "GET /v1/search?directory=/test_bulk_171/&amp;txid=2847992484655785719&amp;database=Documents HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Type: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "Accept: application/xml[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/search",cnonce="fce76adb",nc=00000005,response="c3978bc132deb92adb34906d88ebd998"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie2: $Version=1[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 200 OK[\r][\n]"
[DEBUG] wire - &lt;&lt; "Set-Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 897[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "&lt;search:response snippet-format="snippet" total="1" start="1" page-length="10" xmlns:search="http://marklogic.com/appservices/search"&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;search:result index="1" uri="/test_bulk_171/sec1.xml" path="fn:doc(&amp;quot;/test_bulk_171/sec1.xml&amp;quot;)" score="0" confidence="0" fitness="0" href="/v1/documents?uri=%2Ftest_bulk_171%2Fsec1.xml" mimetype="application/xml" format="xml"&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:snippet&gt;[\n]"
[DEBUG] wire - &lt;&lt; "      &lt;search:match path="fn:doc(&amp;quot;/test_bulk_171/sec1.xml&amp;quot;)/xml"&gt;test1&lt;/search:match&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;/search:snippet&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;/search:result&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;search:qtext/&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;search:metrics&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:query-resolution-time&gt;PT0.00438S&lt;/search:query-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:facet-resolution-time&gt;PT0.000085S&lt;/search:facet-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:snippet-resolution-time&gt;PT0.000449S&lt;/search:snippet-resolution-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "    &lt;search:total-time&gt;PT0.005914S&lt;/search:total-time&gt;[\n]"
[DEBUG] wire - &lt;&lt; "  &lt;/search:metrics&gt;[\n]"
[DEBUG] wire - &lt;&lt; "&lt;/search:response&gt;[\n]"
[DEBUG] wire - &gt;&gt; "POST /v1/transactions/2847992484655785719?result=rollback HTTP/1.1[\r][\n]"
[DEBUG] wire - &gt;&gt; "Authorization: Digest username="rest-evaluator",realm="public",nonce="a6c9e175f5c8e28a668d5f972e00da67",opaque="f59b72c6a6c5bf96",qop=auth,uri="/v1/transactions/2847992484655785719",cnonce="d1ed9424",nc=00000006,response="42830c9a8c377dbc8bc3f93d73a4a5b1"[\r][\n]"
[DEBUG] wire - &gt;&gt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &gt;&gt; "Host: localhost:8012[\r][\n]"
[DEBUG] wire - &gt;&gt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie: HostId=6262038599340480486[\r][\n]"
[DEBUG] wire - &gt;&gt; "Cookie2: $Version=1[\r][\n]"
[DEBUG] wire - &gt;&gt; "[\r][\n]"
[DEBUG] wire - &lt;&lt; "HTTP/1.1 204 Rolled Back[\r][\n]"
[DEBUG] wire - &lt;&lt; "Server: MarkLogic[\r][\n]"
[DEBUG] wire - &lt;&lt; "Content-Length: 0[\r][\n]"
[DEBUG] wire - &lt;&lt; "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - &lt;&lt; "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - &lt;&lt; "[\r][\n]"
</system-err>
  </testcase>
  <testcase time="0.351" classname="com.marklogic.client.test.BulkReadWriteTest" name="test_78"/>
</testsuite>

**Comment by sammefford** [comment]
Looks like this was re-opened mistakenly.  It's been resolved for a while.
