### ISSUE TITLE
POJO Search with PathIndexProperty on Integer type property has timing issues.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#238]
Please refer to testArtifactIndexedOnInteger method for the issue. This test method was used to validate Git Issue reported in #222. We have POJO that has an Integer property annotated with INT scalarType value.

@PathIndexProperty(scalarType = ScalarType.INT)
private Integer inventory;

Issue seen: Without the timing delay (Thread.sleep), a local run in Windows Eclipse environment, we see "com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request."

The test method has the complete exception explanation as produced in the Eclipse console (no trace). Search for Thread.sleep in the testArtifactIndexedOnInteger()  method.

This is the POJO class:
==================

package com.marklogic.client.functionaltest;

import com.marklogic.client.pojo.annotation.Id;
import com.marklogic.client.pojo.annotation.PathIndexProperty;
import com.marklogic.client.pojo.annotation.PathIndexProperty.ScalarType;

/*
 * This class is similar to the Artifact class. It is used to test path range index 
 * using the inventory field with Integer type.
 * Property name been annotated with @Id.
 */
public class ArtifactIndexedOnInteger {
	@Id
	public String name;
	public long id;
	private Company manufacturer;

	@PathIndexProperty(scalarType = ScalarType.INT)
	private Integer inventory;
	private int inventory1;
	
	public int getInventory1() {
		return inventory1;
	}

	public ArtifactIndexedOnInteger setInventory1(int inventory1) {
		this.inventory1 = inventory1;
		return this;
	}

	public long getId() {
		return id;
	}

	public ArtifactIndexedOnInteger setId(long id) {
		this.id = id;
		return this;
	}

	public String getName() {
		return name;
	}

	public ArtifactIndexedOnInteger setName(String name) {
		this.name = name;
		return this;
	}

	public Company getManufacturer() {
		return manufacturer;
	}

	public ArtifactIndexedOnInteger setManufacturer(Company manufacturer) {
		this.manufacturer = manufacturer;
		return this;
	}

	public Integer getInventory() {
		return inventory;
	}

	public ArtifactIndexedOnInteger setInventory(Integer inventory) {
		this.inventory = inventory;
		return this;
	}
}

End of POJO class definition.
======================

Here is the complete test class (Note some of the other POJO objects/methods  may be deleted.

package com.marklogic.client.functionaltest;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import org.apache.http.HttpResponse;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.Authentication;
import com.marklogic.client.io.JacksonHandle;
import com.marklogic.client.pojo.PojoPage;
import com.marklogic.client.pojo.PojoQueryBuilder;
import com.marklogic.client.pojo.PojoQueryBuilder.Operator;
import com.marklogic.client.pojo.PojoQueryDefinition;
import com.marklogic.client.pojo.PojoRepository;
import com.marklogic.client.pojo.util.GenerateIndexConfig;

/*
 * Purpose : To test the following data type range path index can be created in a database.
 * 
 * int - Verifies that the configuration file is generated, which is then used by MarkLogic Admin user to generate range index. 
 * String - Verifies that the configuration file is generated.
 * dateTime- Verifies that the configuration file is generated.
 * daytimeduration* - This needs Java SE 8. Not tested in this class
 * URI- Verifies that the configuration file is generated.
 * Numerals as Strings* - Verifies that the configuration file is generated.
 * Integer - This class has additional range index search test methods for Integer type (Git issue # 222). 
 * Float - Same as for Integer type. This class has additional range index search test methods for Float type (Git issue # 222).
 */

public class TestAutomatedPathRangeIndex extends BasicJavaClientREST {
	private static String dbName = "TestAutomatedPathRangeIndexDB";
	private static String[] fNames = { "TestAutomatedPathRangeIndexDB-1" };
	private static String restServerName = "REST-Java-Client-API-Server";

	private static int restPort = 8011;
	private DatabaseClient client;
	
	
	@BeforeClass
	public static void setUpBeforeClass() throws Exception {		
		System.out.println("In setup");
		setupJavaRESTServer(dbName, fNames[0], restServerName, restPort);
		//
		BasicJavaClientREST.addRangePathIndex(dbName, "long", "com.marklogic.client.functionaltest.ArtifactIndexedOnInteger/inventory", "", "reject",true);

	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		System.out.println("In tear down");	    
		tearDownJavaRESTServer(dbName, fNames, restServerName);
	}

	@Before
	public void setUp() throws Exception {
		client = DatabaseClientFactory.newClient("localhost", restPort,
				"admin", "admin", Authentication.DIGEST);
	}

	@After
	public void tearDown() throws Exception {
		 //release client
		 client.release();
	}
	
	/*
	 * This Method takes the property name and value strings and verifies if
	 * propName exist and then extracts it from the response.
	 * The propValue string needs to be available in the extracted JsonNode's path-expression property.
	 */
	public static void validateRangePathIndexInDatabase(String propName, String propValue) throws IOException {
		InputStream jsonstream = null;
		boolean propFound = false;
		String propertyAvailable = null;
		try {
			DefaultHttpClient client = new DefaultHttpClient();
			client.getCredentialsProvider().setCredentials(
					new AuthScope("localhost", 8002),
					new UsernamePasswordCredentials("admin", "admin"));
			HttpGet getrequest = new HttpGet("http://localhost:8002"
					+ "/manage/v2/databases/" + dbName
					+ "/properties?format=json");
			HttpResponse response1 = client.execute(getrequest);
			jsonstream = response1.getEntity().getContent();
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readTree(jsonstream);

			if (!jnode.isNull()) {

				if (jnode.has(propName)) {
					propFound = true;
					List<JsonNode> jsonStringList = jnode.findValues(propName);
					
					String pathExpressValue = (jsonStringList.get(0)).findValues("path-expression").toString();
					String propValueJsonDecorated = "[\"" + propValue + "\"]";					
					
					boolean contains = pathExpressValue.contains(propValueJsonDecorated);
					propertyAvailable = contains==true ? (" contains " + propValue): (" does not contain " + propValue);						
					assertTrue(new StringBuffer("Database : " + dbName +  propertyAvailable).toString(), contains);
				}

			} else {
				assertTrue("Path range property not available or database properties not avilable",	propFound);
			}
		} catch (Exception e) {
			// writing error to Log
			e.printStackTrace();
		}
	}
	
	/*
	 * This Method takes the property name and multiple value strings and verifies if
	 * propName exist and then extracts it from the response.
	 * The propValue string needs to be available in the extracted JsonNode's path-expression property.
	 */
	public static void validateMultipleRangePathIndexInDatabase(String propName, String[] propValue) throws IOException {
		InputStream jsonstream = null;
		boolean propFound = false;
		String propertyAvailable1 = null;
		String propertyAvailable2 = null;
		try {
			DefaultHttpClient client = new DefaultHttpClient();
			client.getCredentialsProvider().setCredentials(
					new AuthScope("localhost", 8002),
					new UsernamePasswordCredentials("admin", "admin"));
			HttpGet getrequest = new HttpGet("http://localhost:8002"
					+ "/manage/v2/databases/" + dbName
					+ "/properties?format=json");
			HttpResponse response1 = client.execute(getrequest);
			jsonstream = response1.getEntity().getContent();
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readTree(jsonstream);

			if (!jnode.isNull()) {

				if (jnode.has(propName)) {
					propFound = true;
					List<JsonNode> jsonStringList1 = jnode.findValues(propName);
					// Validate the first propValue at index 0
					String pathExpressValue1 = (jsonStringList1.get(0)).findValues("path-expression").toString();
					String propValueJsonDecorated1 = "[\"" + propValue[0];	
										
					boolean contains1 = pathExpressValue1.contains(propValueJsonDecorated1);
					propertyAvailable1 = contains1==true ? (" contains " + propValue[0]): (" does not contain " + propValue[0]);						
					assertTrue(new StringBuffer("Database : " + dbName +  propertyAvailable1).toString(), contains1);
					
					// Validate the second propValue at index 1. we have only two
					String pathExpressValue2 = (jsonStringList1.get(1)).findValues("path-expression").toString();
					String propValueJsonDecorated2 = propValue[1] + "\"]";					
					
					boolean contains2 = pathExpressValue2.contains(propValueJsonDecorated2);
					propertyAvailable2 = contains2==true ? (" contains " + propValue[1]): (" does not contain " + propValue[1]);						
					assertTrue(new StringBuffer("Database : " + dbName +  propertyAvailable2).toString(), contains2);
				}

			} else {
				assertTrue("Path range property not available or database properties not avilable",	propFound);
			}
		} catch (Exception e) {
			// writing error to Log
			e.printStackTrace();
		}
	}
	
	@Test
	public void testArtifactIndexedOnInt() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnInt",
					"-file", "TestAutomatedPathRangeIndexInt.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexInt.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnInt/inventory");
			} else {
				assertTrue(
						"testArtifactIndexedOnInt - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {				
				e.printStackTrace();
			}
		}
	}
	
	/*
	 * This method validates configuration file creation and also the search. 
	 */
	
	@Test
	public void testArtifactIndexedOnInteger() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		PojoRepository<ArtifactIndexedOnInteger,String> products = client.newPojoRepository(ArtifactIndexedOnInteger.class, String.class);
		PojoPage<ArtifactIndexedOnInteger> pojoPage;
		
		// Load POJO into database.
		loadSimplePojos(products);
		
		PojoQueryBuilder<ArtifactIndexedOnInteger> qb = products.getQueryBuilder();
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnInteger",
					"-file", "TestAutomatedPathRangeIndexInteger.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexInteger.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnInteger/inventory");
			} else {
				assertTrue(
						"testArtifactIndexedOnInteger - No Json node available to insert into database",
						succeeded);
			}

			PojoQueryDefinition qd = qb.range("inventory", Operator.GE,1055);
			
			JacksonHandle jh = new JacksonHandle();
			products.setPageLength(56);
			
			// The sleep below is a temporary fix.
			/* The following exception was seen when there was no sleep. (broken into multiple lines for easy reading):
			 * 
			 * com.marklogic.client.FailedRequestException: 
			 * Local message: search failed: Bad Request. Server Message: XDMP-PATHRIDXNOTFOUND: 
			 * cts:search(fn:collection(), cts:and-query((cts:path-range-query("com.marklogic.client.functionaltest.ArtifactIndexedOnInteger/inv...", ">=", xs:int("1055"), (), 1), 
			 * cts:collection-query("com.marklogic.client.functionaltest.ArtifactIndexedOnInteger")), ()), ("unfiltered", cts:score-order("descending")), xs:double("0"), ()) 
			 * -- No int path range index for com.marklogic.client.functionaltest.ArtifactIndexedOnInteger/inventory
			 *  
			 */
			Thread.sleep(5000);
			pojoPage = products.search(qd, 1,jh);
			
			assertEquals("total no of pages",1,pojoPage.getTotalPages());

			long pageNo=1,count=0;
			do{
				count = 0;
				pojoPage = products.search(qd,pageNo);
				while(pojoPage.hasNext()){
					ArtifactIndexedOnInteger a = pojoPage.next();
					validateArtifact(a);
					assertTrue("Verifying document id is part of the search ids",a.getId()>=55);
					count++;
				}
				assertEquals("Page size",count,pojoPage.size());
				pageNo=pageNo+pojoPage.getPageSize();
			}while(!pojoPage.isLastPage() && pageNo<=pojoPage.getTotalSize());
			
			
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {				
				e.printStackTrace();
			}
		}
	}
	
	
	@Test
	public void testArtifactIndexedOnString() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnString",
					"-file", "TestAutomatedPathRangeIndexString.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexString.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnString/name");
			} else {
				assertTrue(
						"testArtifactIndexedOnString - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnDateTime() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnDateTime",
					"-file", "TestAutomatedPathRangeIndexDateTime.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexDateTime.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnDateTime/expiryDate");
			} else {
				assertTrue(
						"testArtifactIndexedOnDateTime - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnFloat() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnFloat",
					"-file", "TestAutomatedPathRangeIndexFloat.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexFloat.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnFloat/price");
			} else {
				assertTrue(
						"testArtifactIndexedOFloat - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnAnyURI() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnUri",
					"-file", "TestAutomatedPathRangeIndexUri.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexUri.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnUri/artifactUri");
			} else {
				assertTrue(
						"testArtifactIndexedOnUri - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnIntAsString() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnIntAsString",
					"-file", "TestAutomatedPathRangeIndexIntAsString.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexIntAsString.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedOnIntAsString/inventory");
			} else {
				assertTrue(
						"testArtifactIndexedOnIntAsString - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {				
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnMultipleFields() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnMultipleFields",
					"-file", "TestAutomatedPathRangeIndexMultipleFields.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexMultipleFields.json");
			//Array to hold the range path index values. Refer to the class for the annotated class members.
			String[] propValueStrArray = {"com.marklogic.client.functionaltest.ArtifactIndexedOnMultipleFields/name",
					                      "com.marklogic.client.functionaltest.ArtifactIndexedOnMultipleFields/inventory"};
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateMultipleRangePathIndexInDatabase("range-path-index", propValueStrArray);
			} else {
				assertTrue(
						"testArtifactIndexedOnIntAsString - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {				
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactIndexedOnStringInSuperClass() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedOnStringSub",
					"-file", "TestAutomatedPathRangeIndexStringInSuperClass.json" });

			jsonFile = new File("TestAutomatedPathRangeIndexStringInSuperClass.json");
			//Array to hold the range path index values. Refer to the class for the annotated class members.
			String[] propValueStrArray = {"com.marklogic.client.functionaltest.ArtifactIndexedOnStringSub/name",
					                      "com.marklogic.client.functionaltest.ArtifactIndexedOnStringSub/artifactWeight"};			
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateMultipleRangePathIndexInDatabase("range-path-index", propValueStrArray);
			} else {
				assertTrue(
						"testArtifactIndexedOnStringInSuperClass - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	@Test
	public void testArtifactMultipleIndexedOnInt() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactMultipleIndexedOnInt",
					"-file", "TestAutomatedPathRangeMultipleIndexOnInt.json" });

			jsonFile = new File("TestAutomatedPathRangeMultipleIndexOnInt.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactMultipleIndexedOnInt/inventory");
			} else {
				assertTrue(
						"testArtifactMultipleIndexedOnInt - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	

	/*
	 * Test for unsupported data type: This was meant as a negative test case.
	 * The annotation declared on user defined data type will ONLY accept types
	 * from scalarType class. Assigning a scalarType.Company to the class member
	 * in the annotation like below, WILL NOT COMPILE:
	 * 
	 * @PathIndexProperty(scalarType = ScalarType.Company) public Company
	 * manufacture;
	 * 
	 * However, for the following, we can declare for example for class property
	 * Company (which is user defined type), the scalarType.STRING in the class.
	 * 
	 * @PathIndexProperty(scalarType = ScalarType.STRING) public Company
	 * manufacture;
	 * 
	 * MarkLogic server accepts this range path index and this was verified
	 * manually through the MarkLogic administration GUI on the database also. 
	 */
	
	@Test
	public void testArtifactIndexedOnUnSupportedAsString() throws Exception {
		boolean succeeded = false;
		File jsonFile = null;
		try {
			GenerateIndexConfig.main(new String[] { "-classes",
					"com.marklogic.client.functionaltest.ArtifactIndexedUnSupportedDataType",
					"-file", "TestArtifactIndexedOnUnSupportedAsString.json" });

			jsonFile = new File("TestArtifactIndexedOnUnSupportedAsString.json");
			ObjectMapper mapper = new ObjectMapper();
			JsonNode jnode = mapper.readValue(jsonFile, JsonNode.class);

			if (!jnode.isNull()) {
				setPathRangeIndexInDatabase(dbName, jnode);
				succeeded = true;
				validateRangePathIndexInDatabase("range-path-index", "com.marklogic.client.functionaltest.ArtifactIndexedUnSupportedDataType/manufacturer");
			} else {
				assertTrue(
						"testArtifactIndexedOnUnSupportedAsString - No Json node available to insert into database",
						succeeded);
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				jsonFile.delete();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	/*
	 * The following three methods are used to validate "search on range index" when POJO class ArtifactIndexedOnInteger
	 * has been annotated for path range index as below:
	 * 
	 *  @PathIndexProperty(scalarType = ScalarType.INT)
	 *  private Integer inventory;
	 *  
	 *  These methods are used to validate Git Issue # 222.
	 *
	 */
	public void loadSimplePojos(PojoRepository<ArtifactIndexedOnInteger,String> products)
	{
		for(int i=1;i<111;i++){
			if(i%2==0){
				products.write(this.getArtifact(i),"even","numbers");
			}
			else {
				products.write(this.getArtifact(i),"odd","numbers");
			}
		}
	}

	public ArtifactIndexedOnInteger getArtifact(int counter){

		ArtifactIndexedOnInteger cogs = new ArtifactIndexedOnInteger();
		cogs.setId(counter);
		if( counter % 5 == 0){
			cogs.setName("Cogs special");
			if(counter % 2 ==0){
				Company acme = new Company();
				acme.setName("Acme special, Inc.");
				acme.setWebsite("http://www.acme special.com");
				acme.setLatitude(41.998+counter);
				acme.setLongitude(-87.966+counter);
				cogs.setManufacturer(acme);

			}else{
				Company widgets = new Company();
				widgets.setName("Widgets counter Inc.");
				widgets.setWebsite("http://www.widgets counter.com");
				widgets.setLatitude(41.998+counter);
				widgets.setLongitude(-87.966+counter);
				cogs.setManufacturer(widgets);
			}
		}else{
			cogs.setName("Cogs "+counter);
			if(counter % 2 ==0){
				Company acme = new Company();
				acme.setName("Acme "+counter+", Inc.");
				acme.setWebsite("http://www.acme"+counter+".com");
				acme.setLatitude(41.998+counter);
				acme.setLongitude(-87.966+counter);
				cogs.setManufacturer(acme);

			}else{
				Company widgets = new Company();
				widgets.setName("Widgets "+counter+", Inc.");
				widgets.setWebsite("http://www.widgets"+counter+".com");
				widgets.setLatitude(41.998+counter);
				widgets.setLongitude(-87.966+counter);
				cogs.setManufacturer(widgets);
			}
		}
		cogs.setInventory(1000+counter);
		cogs.setInventory1(1000+counter);
		return cogs;
	}
	
	public void validateArtifact(ArtifactIndexedOnInteger art)
	{
		assertNotNull("Artifact object should never be Null",art);
		assertNotNull("Id should never be Null",art.id);
		assertTrue("Inventry is always greater than 1000", art.getInventory()>1000);
	}
	
}

**Comment by sravanr** [comment]
I don't think this is a bug, creating a range index after loading documents will take little time to fill the indexes so it is expected.
