### ISSUE TITLE
Minor issue -- a misleading WARN log message.

### ISSUE THREAD

**Issue by grechaw** [marklogic/java-client-api#241]
If I call values with a JSON handle, then for some reason the getCollections() method on query definition returns an empty array rather than null.

I think the test is just wrong in JerseyServices, line 2353 or thereabouts:

```
            if (queryDef.getCollections() != null) {
                if (logger.isWarnEnabled())
                    logger.warn("collections scope ignored for values query");
            }
```

This needs to be a non-empty test in addition to or instead of this null test.  I'm not sure which.

There is a (also minor) bug blocked in samplestack https://github.com/marklogic/marklogic-samplestack/issues/383

**Comment by grechaw** [comment]
This is the code that exposes this bug:

```
DateTime[] dates = new DateTime[2];
		QueryManager queryManager = clients.get(role).newQueryManager();
		ValuesDefinition valdef = queryManager
				.newValuesDefinition("lastActivityDate");
		valdef.setAggregate("min", "max");
		valdef.setView("aggregate");
		JacksonHandle handle = new JacksonHandle();
		handle.set(structuredQuery);
		RawCombinedQueryDefinition qdef = queryManager
				.newRawCombinedQueryDefinition(handle, QUESTIONS_OPTIONS);
		valdef.setQueryDefinition(qdef);
		ValuesHandle responseHandle = null;
		try {
			responseHandle = queryManager.values(valdef, new ValuesHandle());
		} catch (com.marklogic.client.FailedRequestException ex) {
			throw new SamplestackSearchException(ex);
		}
```

Although nowhere is a collection set, somehow it ends up in Jersey Services as not null.    I think a few minutes of debugging will show where the issue is.

**Comment by grechaw** [comment]
And an options node that should work (the QueryOptionsManager method we used last week should work for this)

```
{"options":
 "values": [
            {
                "name": "lastActivityDate",
                "range": {
                    "json-property": "lastActivityDate",
                    "type": "xs:dateTime"
                }
            }
        ]
}
```

**Comment by sammefford** [comment]
Sorry for the long delay on this.  It's fixed now.  Given how minor it is, let's skip additional testing.
