### ISSUE TITLE
javadoc should refer to JSON properties, not JSON keys

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#244]
Like it or not, we settled on calling these properties in ML8. The javadoc is the last refuge of the old "JSON key" terminology.

We should clean this up, but IMO it can wait until the more general javadoc cleanup/improvement we've previously discussed.

Assigning this to Sam and 8.0-2 for now, but I expect it'll really end up being me and some later 8.0-x milestone.

**Comment by kcoleman-marklogic** [comment]
The nightly build isn't pulling the right branch right now, I think, so I'm not able to verify this thoroughly by conducting a search on pubs. I've sent Sravan a note about the build and will circle back to this when we have a resolution.

**Comment by kcoleman-marklogic** [comment]
Totally forgot about this until now. My apologies.

There are definitely still references to JSON keys in the javadoc. You can find them with this search:

http://developer.marklogic.com/search?q=cat%3Ajava-api%20%28json%20NEAR%2F2%20key%29&api=true&v=8.0

I'm going to leave this assigned to me and move it back to fix for 3.0.3.

**Comment by sammefford** [comment]
Kim, what's the status on this?  We're trying to close out all 3.0.4 issues.

**Comment by kcoleman-marklogic** [comment]
Thanks for the nudge, Sam. It was needed. I have had no time at all for Java this release, so this still needs doing. I think the right thing to do is to change the milestone, which I shall do.
