### ISSUE TITLE
DocumentPatchBuilder.replaceValue cannot replace boolean values

### ISSUE THREAD

**Issue by grechaw** [marklogic/java-client-api#249]
This is probably actually a bug in the REST API but I found it in Java.

```
patchBuilder.replaceValue("/accepted", true);
patchBuilder.replaceValue("/accepted", new Boolean(true));
```

Both of these insert a string value into the JSON property rather than a boolean.

A workaround is to use replaceFragment
patchBuilder.replaceFragment("/accepted",  true)   

but this is a hackish workaround -- it works because the string "true", unquoted, evaluates to a boolean in constructing the patch.

**Comment by grechaw** [comment]
I neglected this bug beyond code freeze, as I did not see it in my regular triage of 8.0-2 bugs.  I think I have to set it to the next version, as QA really doesn't want any new fixes for 8.0-2 anymore in the server.

**Comment by grechaw** [comment]
I'll make a REST API bug for this.

**Comment by grechaw** [comment]
So this is not at all a REST API bug.  It's a bug with any non-string value in replaceValue.
I've got tests written for the fix, and will have no problem delivering the fix.

**Comment by grechaw** [comment]
I just assigned @sammefford  and back to me so that you'll have visbility

**Comment by grechaw** [comment]
I've got a fix to review.

**Comment by grechaw** [comment]
This is all merged in, should be pretty straightforward test, as the unit test shows how.
@sammefford , isn't this in 3.0.3?   I saw that you changed the milestone, just curious about that

**Comment by grechaw** [comment]
Committed to develop and 3.0-develop

**Comment by georgeajit** [comment]
Added tests for PatchBuilder's replaceValue on boolean for JSON and XML docs to TestPartialUpdate.java.

The tests have both boolean primitives and Boolean object.
