### ISSUE TITLE
Add "What's new in Java Client API 3.0" section on README

### ISSUE THREAD

**Issue by nikos** [marklogic/java-client-api#254]
It would be great to have mentioned the highlights of the Java Client API 3.0 (in comparison to 2.0) summarized on the README / start page of the project.

**Comment by sammefford** [comment]
Great suggestion, Niko.  I'll put that together.  In the meantime, you can find the new features in 3.0 summarized [here](http://developer.marklogic.com/features/java-client-api-2).  Or a broad overview [here](http://developer.marklogic.com/features/java-client-api).

**Comment by sammefford** [comment]
Oh, and I should point out there is also an overview of all that's new in MarkLogic 8.0 [here](http://developer.marklogic.com/).  It's pretty exciting!

**Comment by kcoleman-marklogic** [comment]
There is also a summary here:

http://docs.marklogic.com/guide/relnotes/chap3#id_32290

**Comment by nikos** [comment]
Great stuff, thanks a lot for taking care @sammefford
