### ISSUE TITLE
Update SearchHandle to expect search:extracted elements

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#262]
The REST API has added search:extracted elements when options include extract-document-data and the accept header is application/json or application/xml (not multipart/mixed).  In this case we need the SearchHandle to be ready for the new elements.

**Comment by sammefford** [comment]
MatchDocumentSummary adds a new method:

    public ExtractedResult getExtracted()


ExtractedResult is a new class:

    public ExtractedResult {
        public boolean isExtractedNone();
        public Format getFormat();
        public String getContext();
        public String getKind();
        public int size();
    }

ExtractedItem is a new class:

    /** Access the extracted XML or JSON node using any AbstractReadHandle
     * or class registered by a ContentHandle. */
    public interface ExtractedItem {
        public <T extends AbstractReadHandle> T get(T handle);
        public <T> T getAs(Class<T> as);
    }


Example usage:

        String combinedSearch = 
          "<search:search xmlns:search=\"http://marklogic.com/appservices/search\">" +
            "<search:qtext>my search terms</search:qtext>" +
            "<search:options>" +
                "<search:extract-document-data>" +
                    "<search:extract-path>/some/path</search:extract-path>" +
                    "<search:extract-path>/another/path/*</search:extract-path>" +
                "</search:extract-document-data>" +
            "</search:options>" +
          "</search:search>";
        StringHandle queryHandle = new StringHandle(combinedSearch).withMimetype("application/xml");
        QueryDefinition query = queryMgr.newRawCombinedQueryDefinition(queryHandle);
        SearchHandle results = queryMgr.search(query, new SearchHandle());
        MatchDocumentSummary[] summaries = results.getMatchResults();
        for (MatchDocumentSummary summary : summaries) {
            ExtractedResult extracted = summary.getExtracted();
            if ( Format.XML == summary.getFormat() ) {
                for (ExtractedItem item : extracted) {
                    Document extractItem = extracted.next().getAs(Document.class);
                    ...
                }
            }
        }

**Comment by kcoleman-marklogic** [comment]
I've updated the Java dev guide for this and will send it to you for review once I know it's working in the doc build, Sam.
