### ISSUE TITLE
 GraphSPARQLExampleTest fails - XDMP-TRPLIDXNOTFOUND

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#277]
Attached is the standard output and stack trace:
Standard output:
05:59:43.419 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8000
05:59:43.419 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as rest-admin
05:59:43.445 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:59:43.446 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:59:43.446 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:59:43.446 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
installing extensions
05:59:43.459 [main] INFO  c.m.c.impl.ResourceExtensionsImpl - Writing resource services source for graph
05:59:43.459 [main] DEBUG c.m.client.impl.JerseyServices - Putting config/resources/graph
05:59:44.746 [main] INFO  c.m.c.impl.ResourceExtensionsImpl - Writing resource services source for sparql
05:59:44.746 [main] DEBUG c.m.client.impl.JerseyServices - Putting config/resources/sparql
installed extensions
05:59:45.754 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:59:45.754 [main] DEBUG c.m.client.impl.JerseyServices - Releasing connection
05:59:45.754 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8000
05:59:45.755 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as rest-writer
inserting graph
05:59:45.796 [main] DEBUG c.m.client.impl.JerseyServices - Posting resources/graph
inserted graph
running query
05:59:47.132 [main] DEBUG c.m.client.impl.JerseyServices - Posting resources/sparql

Stack Trace:

Local message: failed to apply resource at resources/sparql: Bad Request. Server Message: SEM-SYNTAXERROR (err:FOER0000): XDMP-TRPLIDXNOTFOUND1.0-mlTriple index not enabledXDMP-TRPLIDXNOTFOUND: sem:sparql($query, (), $options) -- Triple index not enabledfalsesem:sparql($query, (), $options)/MarkLogic/rest-api/models/semantics-model.xqy619semmod:sparql(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}})paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)bodydocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}query"prefix foaf: <http://xmlns.com/foaf/0.1/>&#10;&#10;select distin..."options()1.0-ml/MarkLogic/rest-api/models/semantics-model.xqy4610semmod:sparql-query(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="accept"><map:value xsi:type="xs:string">applicat...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}})headersmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="accept"><map:value xsi:type="xs:string">applicat...</map:map>)paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)bodydocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}content-type()isUpdatefn:false()1.0-ml/marklogic.rest.resource/sparql/assets/resource.xqy5820xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy")(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}})contextmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>)paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)inputdocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}format"nquad"default-graph-uri()nameed-graph-uri()headersmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="accept"><map:value xsi:type="xs:string">applicat...</map:map>)mime()1.0-ml/MarkLogic/rest-api/lib/extensions-util.xqy85324extut:call-service("sparql", "POST", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}})extension-name"sparql"method"POST"servicexdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy")contextmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>)service-paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)inputdocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}1.0-ml/MarkLogic/rest-api/lib/extensions-util.xqy76614extut:invoke-service("sparql", "POST", "query", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}, fn:false())extension-name"sparql"method"POST"default-txn-mode"query"servicexdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy")contextmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>)service-paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)inputdocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}in-txnfn:false()txn-curr"query"annotation()txn-mode"query"1.0-ml/MarkLogic/rest-api/models/resource-model-query.xqy2548rsrcmodqry:resource-post("sparql", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}, fn:false(), local:rsrcmod-callback#6)resource-name"sparql"contextmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="output-types"><map:value xsi:type="xs:string">ap...</map:map>)resource-paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="format"><map:value xsi:type="xs:string">nquad</m...</map:map>)inputdocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}in-txnfn:false()responderlocal:rsrcmod-callback#6servicexdmp:function(fn:QName("http://marklogic.com/rest-api/resource/sparql","post"), "/marklogic.rest.resource/sparql/assets/resource.xqy")1.0-ml/MarkLogic/rest-api/models/resource-model-query.xqy2194rsrcmodqry:exec-post(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="content-type"><map:value xsi:type="xs:string">te...</map:map>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="rs:format"><map:value xsi:type="xs:string">nquad...</map:map>), document{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}, local:rsrcmod-callback#6)headersmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="content-type"><map:value xsi:type="xs:string">te...</map:map>)endpoint-paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="rs:format"><map:value xsi:type="xs:string">nquad...</map:map>)inputdocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}responderlocal:rsrcmod-callback#61.0-ml/MarkLogic/rest-api/endpoints/resource-service-query.xqy658paramsmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="rs:format"><map:value xsi:type="xs:string">nquad...</map:map>)headersmap:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="content-type"><map:value xsi:type="xs:string">te...</map:map>)method"POST"bodydocument{text{"prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt;&#10;&#10;select ..."}}1.0-ml

**Comment by sammefford** [comment]
I created this by setting example.port=8000 in src/main/resources/Example.properties.  That doesn't work yet because GraphSPARQLExample (and thus GraphSPARQLExampleTest) run sparql which requires a triple index which isn't there by default on the Documents db which is the default db for port 8000.  Right now GraphSPARQLExample depends on running on a db with the triple index enabled, which is the case for java-unittest once TestServerBootstrapper has run.  I'm thinking I'll just internalize that into GraphSPARQLExample so it does its own bootstrapping of index like it does of extensions.

**Comment by grechaw** [comment]
You could add a database parameter in addition to port 8000 -- if you use that to run against whatever database the tests do otherwise, the results should be the same.

Charles

________________________________

**Comment by sammefford** [comment]
great idea.  That's what I ended up doing.
