### ISSUE TITLE
jersey-client dependency

### ISSUE THREAD

**Issue by tjslone** [marklogic/java-client-api#282]
I am using the java-client-api in a Java application that is using dropwizard(http://www.dropwizard.io/) and has a dependency on org.glassfish.jersey.core:jersey-client:2.16.

There is a clash at runtime between org.glassfish.jersey.core:jersey-client:2.16 (dropwizard) and com.sun.jersey:jersey-client-1.17 (java-client-api). 

It appears that the com.sun.jersey:jersey-client-1.17 is not needed as if it is commented out from the pom.xml the project and tests still compile and I can use the JAR with my Java application that uses dropwizard.

Please can you confirm if the jersey-client is still needed and if not remove it in a future release?

**Comment by sammefford** [comment]
Jersey client is definitely needed.  It's the core library used to communicate with the server via the REST API.  Perhaps when you commented it from the pom.xml it's still somehow on the classpath in your IDE or some other way.  You should not be able to compile the Java client api without Jersey.

**Comment by rvarttinen** [comment]
Just a follow up on this: which version of DropWizard is compatible with MarkLogic Java API 3.0.6?

**Comment by sammefford** [comment]
We don't test or certify any version of DropWizard.  Can you elaborate on what you've tried and what issues you've encountered?

**Comment by jmakeig** [comment]
@rvarttinen, as this issue indicates, most incompatibilities that we’ve seen are the result of the differences between Jersey version 1 and 2. We’re looking at a more general solution to isolate our Jersey dependency from the app that includes the MarkLogic client as a dependency. I don’t have a timetable right, now, but it’s something we’re actively evaluating.

**Comment by rvarttinen** [comment]
Yes - that is my experience in this matter. As mentioned I managed to make it build, eventually, but to no avail as there still was some kind of conflict at runtme when it comes to versions of Jersey. Anyhow; I managed to get it woking using a different approach by using OSGi instead. Thus I made use of the built in classloader isolation feauters of OSGI and got a simple REST-service running executing calls to the MarkLogic Java-api. Then, my REST-service can use the latest and greatest version of Jersey. 

You could say I dropped Dropwizard as I adopted OSGi instead, it uses Jersey as well out-of-the-box so the changes I had to employ where minimal. 
I think I prefer the OSGi approch, for several reasons: 
- classloader isolation and ... 
- it is componentbased, opening up for a more effecient re-use and ... 
- better control over what dependencies are really needed and thus ...
- there will probably be slightly smaller footprint as I can leave out those parts (components or bundles) not needed

The OSGi implementation I used for my little experiment is the framework that comes with Eclipse; Equinox or more correctly: Eclispe RT, as it called nowdays. Knoplerfish Apache Felix should also work.
