### ISSUE TITLE
Mishandling eval TxnId cookie causing errors under stress

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#286]
We found multiple errors that only manifest in 8.x under stress tests and only when eval is used and a d-node is stopped and restarted.  The errors are:
- REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of: 'text/xml', 'text/json', 'application/xml', 'application/json', Received: text/plain
- XDMP-UPDATEFUNCTIONFROMQUERY or 'Operation not allowed on the currently executing transaction with identifier declareUpdate'
- documents not retrieved even though they're in the db

These all appear to stem from a TxnID cookie which is coming from the /v1/eval or /v1/invoke endpoints and inappropriately applied to subsequent HTTP requests which should not send that cookie with the TxnID cookie from the previous request.

**Comment by georgeajit** [comment]
Did not see these errors in the last run on 02/22/2017.
