### ISSUE TITLE
Mishandling eval TxnId cookie causing errors under stress

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#287]
This is a back-port of https://github.com/marklogic/java-client-api/issues/286  See it for discussion.

**Comment by georgeajit** [comment]
Run a Java/REST API Stress Test on MarkLogic Server Build 8.0 20150422 having the following configuration:

1 E Node
2 D Nodes

Java Client running on a separate machine which had a increase the file handle available set to 20,000 and turned OFF “Transparent Huge Pages"

The client also had Java JRE 1.7.

100 threads were used and the REST APP Server had a thread count set to 105. The E val group had file logging set to "Info".

The two D nodes were configured with cron jobs to do failover.

Result :

The Java client program's log file did not contain the Exception reported in the bug even after 3 failovers/recoveries of D Nodes.
