### ISSUE TITLE
Add close() method to InputSourceHandle, SourceHandle, and JacksonParserHandle

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#295]
InputSourceHandle, SourceHandle, and JacksonParserHandle often encapsulate an InputStream but have no way to close it properly.  Let's add a close method which closes the underlying stream.  Currently a user can probably call InputSourceHandle.get().getByteStream().close() or SourceHandle.get().getInputStream().close() or ((Closeable) JacksonParserHandle.getInputSource()).close(), but those are less obvious and undocumented.  Rather than document those, let's just add a close method to each handle.

**Comment by sammefford** [comment]
As part of this task, remember to document how to properly close these handles.  Also look for other handles or resources which might need documentation.

**Comment by georgeajit** [comment]
Made changes and committed to develop and 3.0-develop branches.
