### ISSUE TITLE
Document server affinity and load balancing considerations

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#299]
Multi-statement transactions and eval/invoke with server fields require E-node affinity. We should document this.

**Comment by kcoleman-marklogic** [comment]
The multi-statement transaction requirement is already documented.

**Comment by kcoleman-marklogic** [comment]
After a brief discussion with Erik, I'm pushing this one, too, with the same caveat that I will pull it into 3.0-4 if everyone runs out of other things to do and has time to think about this. Reason is that sorting out even just the eval/invoke context across all the layers (REST,XDBC, Node.js, Java) isn't going to be a quickie.

**Comment by kcoleman-marklogic** [comment]
I do not have the information necessary to address this bug. If you wish to provide those details, Sam, I can tart it up and it to the documentation. Otherwise, this will continue unaddressed indefinitely.

**Comment by sammefford** [comment]
Let me know if this gives you everything you need: [https://wiki.marklogic.com/x/OQxEAg](https://wiki.marklogic.com/x/OQxEAg)

**Comment by georgeajit** [comment]
@kcoleman-marklogic 
Any update on this?

**Comment by kcoleman-marklogic** [comment]
PDF sent to Sam for review. If you would also like to review it, Ajit, please let me know.
