### ISSUE TITLE
implement and unit test delete / deleteGraphs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#304]
In GraphManager:
```
 public void delete(String uri)
 public void delete(String uri, Transaction transaction)

 public <T extends QuadsWriteHandle> void deleteGraphs();

```

**Comment by grechaw** [comment]
It seems to me that testing this will be all part of the same as CRUD...
It's also surprising to see a return value, so I'll update the spec as needed.
I agreed to take this on in any event, so I'll be looking at this code soon and see how it works into the tests with write/merge/read

**Comment by grechaw** [comment]
I've got delete implemented and enough testing to ensure it works, insides and out of transactions.

**Comment by grechaw** [comment]
delete is all set in develop and develop-3.0

**Comment by sammefford** [comment]
I think you mean "develop and 3.0-develop"
