### ISSUE TITLE
implement and unit test select

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#306]
In SPARQLQueryManager:
```
 public SPARQLTuplesResult executeSelect(SPARQLQueryDefinition qdef);
```

**Comment by sammefford** [comment]
This is done as part of 4d2aa6af88e534a49550f18b7a7905f1bdbdaaf6 and e626a3856a56ce49857cacddedd3a6c89e7063b5

**Comment by georgeajit** [comment]
The following test methods are used to /* This test checks if Exceptions are throw when qdef is null.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * Expected Result : IllegalArgumentException Exception thrown
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testExecuteSelectQueryNullQDEF() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteSelectQueryNullQDEF method");
		SPARQLQueryManager sparqlQmgr = readclient.newSPARQLQueryManager();		
		
		String expectedException = "IllegalArgumentException";
		String exception = "";
		try {
			  sparqlQmgr.executeSelect(null, new JacksonHandle()).get();
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println(exception);
		assertTrue(" Test testExecuteSelectQueryNullQDEF method exception is not thrown", exception.contains(expectedException));
	}
	
	/* This test checks if Exceptions are throw when qdef is empty.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * Expected Result : FailedRequestException Exception thrown
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testExecuteEmptySelectQuery() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteEmptySelectQuery method");
		SPARQLQueryManager sparqlQmgr = readclient.newSPARQLQueryManager();
		StringBuffer sparqlQuery = new StringBuffer().append("");
				
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		
		String expectedException = "FailedRequestException";
		String exception = "";
		try {
			 sparqlQmgr.executeSelect(qdef, new JacksonHandle()).get();
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println(exception);
		assertTrue("Test testExecuteEmptySelectQuery method exception is not thrown", exception.contains(expectedException));
	}
	
	/* This test verifies query clauses with OPTIONAL and FILTER keywords.
	 * The database should contain triples from testcustom graph.
	 * 
	 * Expected Result : 1 solution contaiining person with id 4444
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testQueryClauseOptionalFilter() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryClauseOptionalFilter method");
	    // Form a query
   	
	    StringBuffer sparqlQuery = new StringBuffer().append("prefix ad: <http://marklogicsparql.com/addressbook#>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix id:  <http://marklogicsparql.com/id#>");
		sparqlQuery.append(newline);
		sparqlQuery.append("SELECT DISTINCT ?person FROM <testcustom> ");
	    sparqlQuery.append(newline);
	    sparqlQuery.append("WHERE { ?person ad:firstName ?firstname ;");
	    sparqlQuery.append(newline);
	    sparqlQuery.append(" ad:lastName ?lastname . ");
	    sparqlQuery.append("OPTIONAL {?person ad:homeTel ?phonenumber .} ");
	    sparqlQuery.append("FILTER (?firstname = \"Ling\")");
	    sparqlQuery.append("}");
	    
	    SPARQLQueryManager sparqlQmgr = readclient.newSPARQLQueryManager();
	    SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Select in a transaction with start = 1 and page length = 1.
		String jsonStrResults = sparqlQmgr.executeSelect(qdef, new StringHandle()).get();
		ObjectMapper mapper = new ObjectMapper();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(jsonStrResults);
		System.out.println(jsonStrResults);
		JsonNode jsonBindingsNodes = jsonNodesFromStr.path("results").path("bindings");
		// Should have 1 node returned. 
		assertEquals("Result returned from testQueryClauseOptionalFilter query is incorrect ", 1, jsonBindingsNodes.size());
		assertEquals("Element person's value incorrect", "http://marklogicsparql.com/id#4444", jsonBindingsNodes.path("person").path("value").asText());
		System.out.println("testQueryClauseOptionalFilter query result size is " + jsonBindingsNodes.size());
	    
	}
