### ISSUE TITLE
implement and unit test pagination

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#307]
In SPARQLQueryManager:
```
 public SPARQLTuplesResult executeSelect(SPARQLQueryDefinition qdef, long start, long pageLength, Transaction tx);
```

**Comment by georgeajit** [comment]
The following test method was written and reviewd to verify pagination.
/* This test checks a simple SPARQL query pagination from named graph in a transaction.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * The query should be returning states where population is greater than 5 million ordered by population count ascending.
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testPaginationInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testPaginationInTransaction method");
		SPARQLQueryManager sparqlQmgr = readclient.newSPARQLQueryManager();
		Transaction t = readclient.openTransaction();

		StringBuffer sparqlQuery = new StringBuffer().append("PREFIX usgovt: <tag:govshare.info,2005:rdf/usgovt/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix dc: <http://purl.org/dc/elements/1.1/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("SELECT ?stateCode ?population ?statename from <http://marklogic.com/qatests/n3/geo-states.n3> ");
		sparqlQuery.append("WHERE { ?stateCode census:population ?population . ");
		sparqlQuery.append("?stateCode dc:title ?statename . ");
		sparqlQuery.append("filter (?population > 5000000) }");
		sparqlQuery.append(" ORDER by (?population)");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Select in a transaction with start = 1 and page length = 1.
		String jsonStrResults = sparqlQmgr.executeSelect(qdef, new StringHandle(), 1, 1, t).get();
		ObjectMapper mapper = new ObjectMapper();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(jsonStrResults);
		System.out.println(jsonStrResults);
		JsonNode jsonBindingsNodes = jsonNodesFromStr.path("results").path("bindings");
		// Should have 1 node returned. Details of State - Arizona.
		assertEquals("Result returned from testPaginationInTransaction query 1 has incorrect size ", 1, jsonBindingsNodes.size());
		System.out.println("testPaginationInTransaction query 1 result size is " + jsonBindingsNodes.size());
		
		// Verify results.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/az", jsonBindingsNodes.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5130632", jsonBindingsNodes.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Arizona", jsonBindingsNodes.path("statename").path("value").asText());
		
		// Select in a transaction with start = 2 and page length = 1. 
		/* Order of states returned are : AZ, MD, WS, MS, TN, WA, IN, MA, VR, NC, GA, NJ, MI, OH, PA, IL..... 
		 * We have set page length = 1 and start from result 2. Should skip Arizona and return only Maryland
		 */
		String jsonStrResults2 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 2, 1, t).get();
		
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr2 = mapper.readTree(jsonStrResults2);
		System.out.println(jsonStrResults2);
		JsonNode jsonBindingsNodes2 = jsonNodesFromStr2.path("results").path("bindings");
		
		assertEquals("Result returned from testPaginationInTransaction query 2 has incorrect size ", 1, jsonBindingsNodes2.size());
		System.out.println("testPaginationInTransaction query 2 result size is " + jsonBindingsNodes2.size());
		
		// Verify results - Details of State - Maryland.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/md", jsonBindingsNodes2.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5296486", jsonBindingsNodes2.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Maryland", jsonBindingsNodes2.path("statename").path("value").asText());

		// Select in a transaction with start = 2 and page length = 3. 
		/* Order of states returned are : AZ, MD, WS, MS, TN, WA, IN, MA, VR, NC, GA, NJ, MI, OH, PA, IL..... 
		 * We have set page length = 3 and start from result 2. Should skip Arizona and return Maryland, Wisconsin, Missouri
		*/
		String jsonStrResults3 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 2, 3, t).get();

		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr3 = mapper.readTree(jsonStrResults3);
		System.out.println(jsonStrResults3);
		
		assertEquals("Result returned from testPaginationInTransaction query 3 has incorrect size ", 3, jsonNodesFromStr3.path("bindings").size());
		System.out.println("testPaginationInTransaction query 3 result is " + jsonNodesFromStr3.path("bindings").size());
		
		Iterator<JsonNode> jsonBindingsNodesItr3 = jsonNodesFromStr3.path("results").path("bindings").elements();
		JsonNode jsonItrNode1 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Maryland.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/md", jsonItrNode1.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5296486", jsonItrNode1.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Maryland", jsonItrNode1.path("statename").path("value").asText());
		
		JsonNode jsonItrNode2 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Wisconsin.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/wi", jsonItrNode2.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5363675", jsonItrNode2.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Wisconsin", jsonItrNode2.path("statename").path("value").asText());
		
		JsonNode jsonItrNode3 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Wisconsin.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/mo", jsonItrNode3.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5595211", jsonItrNode3.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Missouri", jsonItrNode3.path("statename").path("value").asText());
				
		// Test negative cases.
		
		// Select in a transaction with (java index) start = 21 and page length = 2. Out of results' bounds
		String jsonStrResultsNeg1 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 21, 2, t).get();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStrNeg1 = mapper.readTree(jsonStrResultsNeg1);
		System.out.println(jsonStrResultsNeg1);
		JsonNode jsonBindingsNodesNeg1 = jsonNodesFromStrNeg1.path("results").path("bindings");
		// Should have 1 node returned. Details of United States.
		assertEquals("Result returned from testPaginationInTransaction negative query 1 has incorrect size ", 1, jsonBindingsNodesNeg1.size());
		System.out.println("testPaginationInTransaction negative query 1 result size is " + jsonBindingsNodesNeg1.size());
		// Verify results - Details of United States.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us", jsonBindingsNodesNeg1.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "281421906", jsonBindingsNodesNeg1.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "United States", jsonBindingsNodesNeg1.path("statename").path("value").asText());

		// Select in a transaction with (java index) start = 100 and page length = 100.
		String jsonStrResultsNeg2 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 100, 100, t).get();

		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStrNeg2 = mapper.readTree(jsonStrResultsNeg2);
		System.out.println(jsonStrResultsNeg2);
		JsonNode jsonBindingsNodesNeg2 = jsonNodesFromStrNeg2.path("results").path("bindings");
		// Should have 0 nodes returned. 
		assertEquals("Result returned from testPaginationInTransaction negative query 2 has incorrect size ", 0, jsonBindingsNodesNeg2.size());
		System.out.println("testPaginationInTransaction negative query 2 result size is " + jsonBindingsNodesNeg2.size());
		
		// Select in a transaction with (java index) start = -1 and page length = -1.
		String jsonStrResultsNeg3 = sparqlQmgr.executeSelect(qdef, new StringHandle(), -1, -1, t).get();

		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStrNeg3 = mapper.readTree(jsonStrResultsNeg3);
		System.out.println(jsonStrResultsNeg1);
		JsonNode jsonBindingsNodesNeg3 = jsonNodesFromStrNeg3.path("results").path("bindings");
		// Should have 0 nodes returned. 
		assertEquals("Result returned from testPaginationInTransaction negative query 3 size is incorrect ", 0, jsonBindingsNodesNeg3.size());
		System.out.println("testPaginationInTransaction negative query 3 result size is " + jsonBindingsNodesNeg3.size());
				
		// Handle the transaction.
		t.commit();		
	}
