### ISSUE TITLE
implement transactions for semantics

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#308]
In GraphManager:

```
 public <T extends TriplesReadHandle> T read(String uri, T handle, Transaction transaction)
 public <T extends R> T readAs(String uri, Class<T> clazz, Transaction transaction)
 public GraphPermissions getPermissions(String uri, Transaction transaction);
 public void deletePermissions(String uri, GraphPermissions permissions, Transaction transaction);
 public void writePermissions(String uri, GraphPermissions permissions, Transaction transaction);
 public void mergePermissions(String uri, GraphPermissions permissions, Transaction transcation);
 public void merge(String uri, W handle, GraphPermissions permissions, Transaction transaction)
 public void mergeAs(String uri, Object graphData, GraphPermissions permissions, Transaction transaction)
 public void write(String uri, TriplesWriteHandle handle, GraphPermissions permissions, Transaction transaction)
 public void writeAs(String uri, Object graphData, GraphPermissions permissions, Transaction transaction)
 public void delete(String uri, Transaction transaction)
```

In SPARQLQueryManager:

```
 public SPARQLTuplesResult executeSelect(SPARQLQueryDefinition qdef, long start, long pageLength, Transaction tx);
 public <T extends TriplesReadHandle> executeConstruct(SPARQLQueryDefinition qdef,, T triplesReadHandle Transaction tx);
 public <T extends TriplesReadHandle> executeDescribe(SPARQLQueryDefinition qdef, T triplesReadHandle, Transaction tx);
 public Boolean executeAsk(SPARQLQueryDefinition qdef, Transaction tx);
 public void executeUpdate(SPARQLQueryDefinition qdef, Transaction tx);
```

**Comment by grechaw** [comment]
We discussed, found that this might "just work" but needs unit testing around it.  I agreed to take that on.

**Comment by grechaw** [comment]
Transactions appear to be working fine in the endpoints implemented so far.  I've unit tested them.  I'll keep this issue though (taking it back) to ensure that I add to the tests as the rest of the functionality is completed.

**Comment by kkanthet** [comment]
Graph manager tests committed as part of da14b47d6b2de9946d21d57fd04a662116db03d8

**Comment by georgeajit** [comment]
The following sparql test methods work with transaction objects.

/* This test checks a simple SPARQL query results from named graph in a transaction.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * The query should be returning one result.
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testExecuteQueryInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteQueryInTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();

		StringBuffer sparqlQuery = new StringBuffer().append("PREFIX usgovt: <tag:govshare.info,2005:rdf/usgovt/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix dc: <http://purl.org/dc/elements/1.1/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("SELECT ?stateCode ?population ?statename from <http://marklogic.com/qatests/n3/geo-states.n3> ");
		sparqlQuery.append("WHERE { ?stateCode usgovt:censusStateCode \"63\" .");
		sparqlQuery.append("?stateCode census:population ?population .");
		sparqlQuery.append("?stateCode dc:title ?statename . }");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Select in a transaction.
		String jsonStrResults = sparqlQmgr.executeSelect(qdef, new StringHandle(), t).get();
		ObjectMapper mapper = new ObjectMapper();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(jsonStrResults);
		System.out.println(jsonStrResults);
		JsonNode jsonBindingsNodes = jsonNodesFromStr.path("results").path("bindings");
		// Should have 1 node returned.
		assertEquals("Result returned from testExecuteQueryInTransaction method size is incorrect ", 1, jsonBindingsNodes.size());									
		
		// Verify results.
		assertEquals("Element statecode value is incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/al", jsonBindingsNodes.get(0).path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "4447100", jsonBindingsNodes.get(0).path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Alabama", jsonBindingsNodes.get(0).path("statename").path("value").asText());
		// Handle the transaction.
		t.commit();				
	}
	
	/* This test checks a simple SPARQL query pagination from named graph in a transaction.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * The query should be returning states where population is greater than 5 million ordered by population count ascending.
     * 
     * Uses StringHandle (XMLReadHandle)
	 * 
	 */
	@Test
	public void testPaginationInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testPaginationInTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();

		StringBuffer sparqlQuery = new StringBuffer().append("PREFIX usgovt: <tag:govshare.info,2005:rdf/usgovt/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix dc: <http://purl.org/dc/elements/1.1/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("prefix census: <tag:govshare.info,2005:rdf/census/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("SELECT ?stateCode ?population ?statename from <http://marklogic.com/qatests/n3/geo-states.n3> ");
		sparqlQuery.append("WHERE { ?stateCode census:population ?population . ");
		sparqlQuery.append("?stateCode dc:title ?statename . ");
		sparqlQuery.append("filter (?population > 5000000) }");
		sparqlQuery.append(" ORDER by (?population)");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Select in a transaction with start = 1 and page length = 1.
		String jsonStrResults = sparqlQmgr.executeSelect(qdef, new StringHandle(), 1, 1, t).get();
		ObjectMapper mapper = new ObjectMapper();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(jsonStrResults);
		System.out.println(jsonStrResults);
		JsonNode jsonBindingsNodes = jsonNodesFromStr.path("results").path("bindings");
		// Should have 1 node returned. Details of State - Arizona.
		assertEquals("Result returned from testPaginationInTransaction query 1 has incorrect size ", 1, jsonBindingsNodes.size());
		System.out.println("testPaginationInTransaction query 1 result size is " + jsonBindingsNodes.size());
		
		// Verify results.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/az", jsonBindingsNodes.get(0).path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5130632", jsonBindingsNodes.get(0).path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Arizona", jsonBindingsNodes.get(0).path("statename").path("value").asText());
		
		// Select in a transaction with start = 2 and page length = 1. 
		/* Order of states returned are : AZ, MD, WS, MS, TN, WA, IN, MA, VR, NC, GA, NJ, MI, OH, PA, IL..... 
		 * We have set page length = 1 and start from result 2. Should skip Arizona and return only Maryland
		 */
		String jsonStrResults2 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 2, 1, t).get();
		
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr2 = mapper.readTree(jsonStrResults2);
		System.out.println(jsonStrResults2);
		JsonNode jsonBindingsNodes2 = jsonNodesFromStr2.path("results").path("bindings");
		
		assertEquals("Result returned from testPaginationInTransaction query 2 has incorrect size ", 1, jsonBindingsNodes2.size());
		System.out.println("testPaginationInTransaction query 2 result size is " + jsonBindingsNodes2.size());
		
		// Verify results - Details of State - Maryland.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/md", jsonBindingsNodes2.get(0).path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5296486", jsonBindingsNodes2.get(0).path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Maryland", jsonBindingsNodes2.get(0).path("statename").path("value").asText());

		// Select in a transaction with start = 2 and page length = 3. 
		/* Order of states returned are : AZ, MD, WS, MS, TN, WA, IN, MA, VR, NC, GA, NJ, MI, OH, PA, IL..... 
		 * We have set page length = 3 and start from result 2. Should skip Arizona and return Maryland, Wisconsin, Missouri
		*/
		String jsonStrResults3 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 2, 3, t).get();

		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr3 = mapper.readTree(jsonStrResults3);
		System.out.println(jsonStrResults3);
		
		assertEquals("Result returned from testPaginationInTransaction query 3 has incorrect size ", 3, jsonNodesFromStr3.path("results").path("bindings").size());
		System.out.println("testPaginationInTransaction query 3 result is " + jsonNodesFromStr3.path("results").path("bindings").size());
		
		Iterator<JsonNode> jsonBindingsNodesItr3 = jsonNodesFromStr3.path("results").path("bindings").elements();
		JsonNode jsonItrNode1 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Maryland.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/md", jsonItrNode1.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5296486", jsonItrNode1.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Maryland", jsonItrNode1.path("statename").path("value").asText());
		
		JsonNode jsonItrNode2 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Wisconsin.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/wi", jsonItrNode2.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5363675", jsonItrNode2.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Wisconsin", jsonItrNode2.path("statename").path("value").asText());
		
		JsonNode jsonItrNode3 = jsonBindingsNodesItr3.next();
		// Verify results - Details of State - Wisconsin.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us/mo", jsonItrNode3.path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "5595211", jsonItrNode3.path("population").path("value").asText());
		assertEquals("Element city is incorrect", "Missouri", jsonItrNode3.path("statename").path("value").asText());
				
		// Test negative cases.
		
		// Select in a transaction with (java index) start = 21 and page length = 2. Out of results' bounds
		String jsonStrResultsNeg1 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 21, 2, t).get();
	   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStrNeg1 = mapper.readTree(jsonStrResultsNeg1);
		System.out.println(jsonStrResultsNeg1);
		JsonNode jsonBindingsNodesNeg1 = jsonNodesFromStrNeg1.path("results").path("bindings");
		// Should have 1 node returned. Details of United States.
		assertEquals("Result returned from testPaginationInTransaction negative query 1 has incorrect size ", 1, jsonBindingsNodesNeg1.size());
		System.out.println("testPaginationInTransaction negative query 1 result size is " + jsonBindingsNodesNeg1.size());
		// Verify results - Details of United States.
		assertEquals("Element statecode value incorrect", "http://www.rdfabout.com/rdf/usgov/geo/us", jsonBindingsNodesNeg1.get(0).path("stateCode").path("value").asText());
		assertEquals("Element lives is incorrect", "281421906", jsonBindingsNodesNeg1.get(0).path("population").path("value").asText());
		assertEquals("Element city is incorrect", "United States", jsonBindingsNodesNeg1.get(0).path("statename").path("value").asText());

		// Select in a transaction with (java index) start = 100 and page length = 100.
		String jsonStrResultsNeg2 = sparqlQmgr.executeSelect(qdef, new StringHandle(), 100, 100, t).get();

		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStrNeg2 = mapper.readTree(jsonStrResultsNeg2);
		System.out.println(jsonStrResultsNeg2);
		JsonNode jsonBindingsNodesNeg2 = jsonNodesFromStrNeg2.path("results").path("bindings");
		// Should have 0 nodes returned. 
		assertEquals("Result returned from testPaginationInTransaction negative query 2 has incorrect size ", 0, jsonBindingsNodesNeg2.size());
		System.out.println("testPaginationInTransaction negative query 2 result size is " + jsonBindingsNodesNeg2.size());
        // Pass negative values. 
		String expectedException = "IllegalArgumentException";
		String exception = "";
		try {
			// Select in a transaction with (java index) start = -1 and page length = -1.
			String jsonStrResultsNeg3 = sparqlQmgr.executeSelect(qdef, new StringHandle(), -1, -1, t).get();
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println("Exception thrown from testQueryBindingsNullString is \n"+ exception);
		assertTrue("Test testQueryBindingsNullString method exception is not thrown", exception.contains(expectedException));
					
		// Handle the transaction.
		t.commit();		
	}
	
	
	/* This test checks a SPARQL CONSTRUCT query results.
	 * The database should contain triples from foaf1.nt file. The data format in this file is XML.
	 * Results are returned in a sequence of sem:triple values as triples in memory.
	 * 
	 * The query should be returning one result.
     * 
     * Uses StringHandle (TriplesReadHandle)
	 * 
	 */
	@Test
	public void testExecuteConstructInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteConstructInTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();

		StringBuffer sparqlQuery = new StringBuffer().append(" PREFIX foaf: <http://xmlns.com/foaf/0.1/>");
		sparqlQuery.append(newline);
		sparqlQuery.append("CONSTRUCT {<http://www.ucsb.edu/random-alum> foaf:knows ?alum }");
		sparqlQuery.append(newline);
		sparqlQuery.append("where");
		sparqlQuery.append(newline);
		sparqlQuery.append("{ ?alum foaf:schoolHomepage <http://www.ucsb.edu/> }");		
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		// Execute Construct query 	with RDFMimeTypes.NTRIPLES	
		String[] jsonResults = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.NTRIPLES), t).get().split(" ");
		
		// Account for the dot at the end of the triple. Hence size is 4.
		assertEquals("Method testExecuteConstructInTransaction in-memory Triple part size is incorrect", 4, jsonResults.length);
		assertEquals("Method testExecuteConstructInTransaction in-memory subject is incorrect", "<http://www.ucsb.edu/random-alum>", jsonResults[0]);
		assertEquals("Method testExecuteConstructInTransaction in-memory predicate is incorrect", "<http://xmlns.com/foaf/0.1/knows>", jsonResults[1]);
		assertEquals("Method testExecuteConstructInTransaction in-memory object is incorrect", "<1bfbfb8:ff2d706919:-7fa9>", jsonResults[2]);		
		
		// Tests for additional MIME Type.
		
		ObjectMapper mapper = new ObjectMapper();
		
		String strRDFJSON = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.RDFJSON), t).get().toString();
		System.out.println("\n RDFJSON format is " + strRDFJSON);
				   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(strRDFJSON);
		String strValue =  jsonNodesFromStr.path("http://www.ucsb.edu/random-alum").path("http://xmlns.com/foaf/0.1/knows").get(0).path("value").asText();
		assertEquals("RDFJSON value output is incorrect ", "1bfbfb8:ff2d706919:-7fa9", strValue);
		
		String strRDFXML = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.RDFXML), t).get().toString();
		
		System.out.println("\n RDFXML Format is " + strRDFXML);
		assertTrue("RDFXML subject value output is incorrect ", strRDFXML.contains("rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\""));
		assertTrue("RDFXML predicate value output is incorrect ", strRDFXML.contains("rdf:Description rdf:about=\"http://www.ucsb.edu/random-alum\""));
		assertTrue("RDFXML object value output is incorrect ", strRDFXML.contains("knows rdf:resource=\"1bfbfb8:ff2d706919:-7fa9\""));

		String strTRIPLEXML = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.TRIPLEXML), t).get().toString();
		System.out.println("\n TRIPLEXML format is " + strTRIPLEXML);
		assertTrue("TRIPLEXML subject value output is incorrect ", strTRIPLEXML.contains("<sem:subject>http://www.ucsb.edu/random-alum</sem:subject>"));
		assertTrue("TRIPLEXML predicate value output is incorrect ", strTRIPLEXML.contains("<sem:predicate>http://xmlns.com/foaf/0.1/knows</sem:predicate>"));
		assertTrue("TRIPLEXML object value output is incorrect ", strTRIPLEXML.contains("<sem:object>1bfbfb8:ff2d706919:-7fa9</sem:object>"));
		
		String strTURTLE = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.TURTLE), t).get().toString();
		System.out.println("\n TURTLE format is " + strTURTLE);
		assertTrue("TURTLE subject value output is incorrect ", strTURTLE.contains("<http://www.ucsb.edu/random-alum>"));
		assertTrue("TURTLE predicate value output is incorrect ", strTURTLE.contains("<http://xmlns.com/foaf/0.1/knows>"));
		assertTrue("TURTLE object value output is incorrect ", strTURTLE.contains("<1bfbfb8:ff2d706919:-7fa9>"));
		
		//String strN3 = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.N3), t).get().toString();
		//System.out.println("\n N3 format is " + strN3);
		
		String strNTriples = sparqlQmgr.executeConstruct(qdef, new StringHandle().withMimetype(RDFMimeTypes.NTRIPLES), t).get().toString();
		System.out.println("\n NTRIPLES format is " + strNTriples);
		assertTrue("NTRIPLES subject value output is incorrect ", strNTriples.contains("<http://www.ucsb.edu/random-alum>"));
		assertTrue("NTRIPLES predicate value output is incorrect ", strNTriples.contains("<http://xmlns.com/foaf/0.1/knows>"));
		assertTrue("NTRIPLES object value output is incorrect ", strNTriples.contains("<1bfbfb8:ff2d706919:-7fa9>"));
			
		// Handle the transaction.
		t.commit();
	}
	
	/* This test checks a simple SPARQL DESCRIBE results from named graph in transaction.
	 * The database should contain triples from geo-states.n3.
	 * 
	 * The DESCRIBE query should be returning result. Result includes all triples which have the IRI as a subject.
     * 
     * Uses Stringhandle
	 * 
	 */
	@Test
	public void testExecuteDescribeInTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteDescribeInTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();
		StringBuffer sparqlQuery = new StringBuffer().append("DESCRIBE <http://www.rdfabout.com/rdf/usgov/geo/us/wi>");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		String jsonResults = sparqlQmgr.executeDescribe(qdef, new StringHandle(), t).get();
		// Split the string containing series of triples on the last characters i.e a space and dot. 		
		
     	// Verify result 1 value.
		System.out.println(jsonResults);		
		assertEquals("Method testExecuteDescribeInTransaction size is incorrect for WI", 13, jsonResults.split(" \\.").length);
		
		// Negative test cases.
		// Have Invalid URI
		StringBuffer sparqlInvalidQuery = new StringBuffer().append("DESCRIBE <http://www.rdfabout.com/rdf/usgov/geo/us/blahblah>");

		SPARQLQueryDefinition qdefInvalid = sparqlQmgr.newQueryDefinition(sparqlInvalidQuery.toString());
		String jsonInvalidResults = sparqlQmgr.executeDescribe(qdefInvalid, new StringHandle(), t).get();
		ObjectMapper mapper = new ObjectMapper();
		   
		// Parsing results using JsonNode. 
		JsonNode jsonNodesFromStr = mapper.readTree(jsonInvalidResults);
		JsonNode jsonBindingsNodes = jsonNodesFromStr.path("results").path("bindings");

		// Verify result 0 elements exists.
		System.out.println("DESCRIBE with Invalid URI size is : "+ jsonBindingsNodes.size());
		assertEquals("Method testExecuteDescribeInTransaction size is incorrect ", 0, jsonBindingsNodes.size());
		
		// Have missing enclosing 
		StringBuffer sparqlInvalidQuery1 = new StringBuffer().append("DESCRIBE http://www.rdfabout.com/rdf/usgov/geo/us/wi");
		String expectedException = "FailedRequestException";
		String exception = "";
		SPARQLQueryDefinition qdefInvalid1 = sparqlQmgr.newQueryDefinition(sparqlInvalidQuery1.toString());		
		try {
			  sparqlQmgr.executeDescribe(qdefInvalid1, new StringHandle(), t).get();
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println("Exception thrown from testExecuteDescribeInTransaction is \n" +exception);
		assertTrue("Test testExecuteDescribeInTransaction method exception is not thrown",
				    exception.contains(expectedException));
		   
		// Handle the transaction.
		t.commit();
	}
	
	/* This test checks a simple SPARQL ASK results from named graph ina transaction.
	 * The database should contain triples from foaf1.nt file. The data format in this file is XML.
	 * 
	 * The ASK query should be returning result in boolean.
	 * 
	 */
	@Test
	public void testExecuteAskTransaction() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteAskTransaction method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		Transaction t = writeclient.openTransaction();
		
		StringBuffer sparqlQuery = new StringBuffer().append("PREFIX foaf: <http://xmlns.com/foaf/0.1/>");
		sparqlQuery.append(newline) ;
		sparqlQuery.append("ASK { ?alum foaf:schoolHomepage <http://www.ucsb.edu/> }");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(sparqlQuery.toString());
		boolean  bAsk = sparqlQmgr.executeAsk(qdef, t);
			
     	// Verify result 1 value.
		System.out.println(bAsk);
		
		assertTrue("Method testExecuteAskTransaction result is incorrect", bAsk);
		// Handle the transaction.
		t.commit();		
	}
	/* This test verifies read and write of Triples within transactions using executeUpdate method.
	 * 
	 * Insert data ina transaction using write client.
	 * Read using read client outside - No results should be returned.
	 * Read using write client within transaction (transaction object passed in) - Should have results.
	 * Read using write client without transaction object in executeUpdate - No results returned.
	 * Rollback.
	 * Read using write client - No results returned.
	 * Open a new transaction and Commit the data.
	 * Read using read client and write client. - Both returns data.
     * Uses JacksonHandle.
	 * 
	 */
	@Test
	public void testExecuteUpdateInTransactions() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testExecuteUpdateInTransactions method");
		SPARQLQueryManager sparqlReadQmgr = readclient.newSPARQLQueryManager();
		SPARQLQueryManager sparqlWriteQmgr = writeclient.newSPARQLQueryManager();
		
		// Insert data into Graph in a transaction.
		Transaction tWrite = null;
		SPARQLQueryDefinition qdefWrite = sparqlWriteQmgr.newQueryDefinition();
		qdefWrite.setSparql("INSERT DATA { GRAPH <TransactionTest> { <Bob> <LivesIn> <London> . } }");
		try {
			tWrite = writeclient.openTransaction();
			sparqlWriteQmgr.executeUpdate(qdefWrite, tWrite);
			
			// Try to do a read outside and before committing on tWrite. Should not see the results.
			SPARQLQueryDefinition qdefRead = sparqlReadQmgr.newQueryDefinition("select ?s ?p ?o from <TransactionTest> where { ?s ?p ?o }");
			
			JsonNode jsonResults = sparqlReadQmgr.executeSelect(qdefRead,  new JacksonHandle()).get();					
			JsonNode jsonBindingsNodes = jsonResults.path("results").path("bindings");
			
			// Should have 0 nodes returned.
			assertEquals("No result should have returned from testNamedExecuteSelectQuery method on read client", 0, jsonBindingsNodes.size());
			jsonResults = null;
			jsonBindingsNodes = null;
			
			// Try to do a read with transaction and before committing on tWrite. Should see the results.
			SPARQLQueryDefinition qdefFromWriteMgr = sparqlWriteQmgr.newQueryDefinition("select ?s ?p ?o from <TransactionTest> where { ?s ?p ?o }");
			jsonResults = sparqlWriteQmgr.executeSelect(qdefFromWriteMgr,  new JacksonHandle(), tWrite).get();					
			jsonBindingsNodes = jsonResults.path("results").path("bindings");

			// Should have 1 nodes returned.
			assertEquals("Result should have been returned from testNamedExecuteSelectQuery method ", 1, jsonBindingsNodes.size());
			jsonResults = null;
			jsonBindingsNodes = null;
			
			// Try to do a read with no transaction using Write User. Should not see the results.
			jsonResults = sparqlWriteQmgr.executeSelect(qdefFromWriteMgr,  new JacksonHandle()).get();					
			jsonBindingsNodes = jsonResults.path("results").path("bindings");

			// Should have 0 nodes returned.
			assertEquals("No result should have returned from testNamedExecuteSelectQuery method ", 0, jsonBindingsNodes.size());
			jsonResults = null;
			jsonBindingsNodes = null;
						
			//Verify if Graph without triples does not Exists on rollback.
			tWrite.rollback();
			tWrite = null;
			// Try to do a read with no transaction using Write User. Should not see the results.
			jsonResults = sparqlWriteQmgr.executeSelect(qdefFromWriteMgr,  new JacksonHandle()).get();					
			jsonBindingsNodes = jsonResults.path("results").path("bindings");

			// Should have 0 nodes returned.
			assertEquals("No result should have returned from testNamedExecuteSelectQuery method ", 0, jsonBindingsNodes.size());
			jsonResults = null;
			jsonBindingsNodes = null;
			tWrite = writeclient.openTransaction();
			
			// Write the triple and commit transaction.
			sparqlWriteQmgr.executeUpdate(qdefWrite, tWrite);
			tWrite.commit();
			
			//Read using both clients. Both should return results.
			
			//Using read client.
			 jsonResults = sparqlReadQmgr.executeSelect(qdefRead,  new JacksonHandle()).get();					
			 jsonBindingsNodes = jsonResults.path("results").path("bindings");
			
			// Should have 1 nodes returned.
			assertEquals("Result should have returned from testNamedExecuteSelectQuery method after commit for read client", 1, jsonBindingsNodes.size());
			assertEquals("Value Data from read client is incorrect", "Bob",jsonBindingsNodes.get(0).path("s").path("value").asText());
			assertEquals("Value Data from read client is incorrect", "LivesIn",jsonBindingsNodes.get(0).path("p").path("value").asText());
			assertEquals("Value Data from read client is incorrect", "London",jsonBindingsNodes.get(0).path("o").path("value").asText());
			jsonResults = null;
			jsonBindingsNodes = null;			
			
			//Using write client.
			
			jsonResults = sparqlWriteQmgr.executeSelect(qdefFromWriteMgr,  new JacksonHandle()).get();					
			jsonBindingsNodes = jsonResults.path("results").path("bindings");

			// Should have 1 nodes returned.
			assertEquals("Result should have been returned from testNamedExecuteSelectQuery method after commit for write client", 1, jsonBindingsNodes.size());
			assertEquals("Value Data from read client is incorrect", "Bob",jsonBindingsNodes.get(0).path("s").path("value").asText());
			assertEquals("Value Data from read client is incorrect", "LivesIn",jsonBindingsNodes.get(0).path("p").path("value").asText());
			assertEquals("Value Data from read client is incorrect", "London",jsonBindingsNodes.get(0).path("o").path("value").asText());
			tWrite = null;

			// Execute a write with Read Client to validate the error message.
			SPARQLQueryDefinition qdefWriteError = sparqlReadQmgr.newQueryDefinition();
			qdefWriteError.setSparql("INSERT DATA { GRAPH <TransactionTestErr> { <Bob> <LivesIn> <London> . } }");
			String expectedException = "ForbiddenUserException";
			String exception = "";
			String localMessage = "Local message: User is not allowed to apply resource at /graphs/sparql.";
			
			try	{
				sparqlReadQmgr.executeUpdate(qdefWriteError);
			}
			catch (Exception e) {
				exception = e.toString();
			}
			System.out.println(exception);
			assertTrue("Test testExecuteEmptySelectQuery method exception is not thrown", exception.contains(expectedException));
			assertTrue("Test testExecuteEmptySelectQuery method exception is not thrown", exception.contains(localMessage));
		}
		catch(Exception ex) {
			tWrite=null;
			throw ex;
		}
		finally {
			if (tWrite != null)
				tWrite.rollback();
			tWrite=null;
		}		
	}
