### ISSUE TITLE
implement and unit test SPARQLTupleResults

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#309]
```
public interface SPARQLTupleResults extends Iterable<SPARQLTuple>, SPARQLReadHandle {
    public String[] getBindingNames();
}
public interface SPARQLTuple extends Map<String, SPARQLBinding> {
}
public interface SPARQLBinding {
    public String getName();
    public String getValue();
    public String getType();
    public Locale getLanguageTag();
}
```

**Comment by sammefford** [comment]
This is done as part of 4d2aa6a and e626a38

**Comment by sammefford** [comment]
Charles pointed out that type on results doesn't mean the same thing as bindings when we send, so I need to change it so on results I can accept the type property which will be 'uri', 'literal', or 'bnode'

**Comment by grechaw** [comment]
And if "type" is literal, then there's also 'datatype' which has the URI of the type.  

The thing I don't like here is how we've overloaded 'type' to mean 'datatype' for variable binding, and 'type' for output variable type.

**Comment by sammefford** [comment]
We decided today that we can just go without SPARQLTupleResults and thereby SPARQLQueryManager.executeSelect.  Our docs will point out that they can use JacksonHandle or their favorite XML handle to get and iterate through results.  Or they can use the new Jena or Sesame handles we're creating which will be marked with SPARQLReadHandle.

**Comment by xquery** [comment]
give me a shout when SPARQLReadHandles shows up (I will presume either you or Charles will update spec).

**Comment by xquery** [comment]
ignore my comment, SPARQL Read handle is on the sesame/jena side ... grok me
