### ISSUE TITLE
implement and unit test Ruleset 

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#310]
Something like:

```
public class Ruleset {
 public static Ruleset ALL_VALUES_FROM = ruleSet("allValuesFrom.rules")
 public static Ruleset DOMAIN = ...
 public static Ruleset EQUIVALENT_CLASS
 public static Ruleset RANGE
 public static Ruleset EQUIVALENT_PROPERTY
 public static Ruleset FUNCTIONAL_PROPERTY
 public static Ruleset HAS_VALUE
 public static Ruleset INTERSECTION_OF
 public static Ruleset INVERSE_FUNCTIONAL_PROPERTY
 public static Ruleset INVERSE_OF
 public static Ruleset ON_PROPERTY
 public static Ruleset OWL_HORST_FULL
 public static Ruleset OWL_HORST
 public static Ruleset RDFS_FULL
 public static Ruleset RDFS_PLUS_FULL
 public static Ruleset RDFS_PLUS
 public static Ruleset RDFS
 public static Ruleset SAME_AS
 public static Ruleset SOME_VALUES_FROM
 public static Ruleset SUBCLASS_OF
 public static Ruleset SUBPROPERTY_OF
 public static Ruleset SYMMETRIC_PROPERTY
 public static Ruleset TRANSITIVE_PROPERTY

 public static Ruleset ruleSet(String name);
}
```

**Comment by grechaw** [comment]
I agreed to take this on.

**Comment by grechaw** [comment]
Hi @georgeajit this functionality is all checked into develop and 3.0-develop

**Comment by georgeajit** [comment]
The following test method verifies MarkLogic ruleset and inference capabilities. 

/* This test verifies MarkLogic Java API support for Inference and Ruleset.
	 * 
     * No default ruleset, no inference triples
     * Add one ruleset, verify inference triples
     * Add two rulesets, verify inference triples
	 * 
	 */
	@Test
	public void testInferenceAndRuleSet() throws IOException, SAXException, ParserConfigurationException
	{	
	System.out.println("In SPARQL Query Manager Test testInferenceAndRuleSet method");
	SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
	SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition();	
	
    // Create graph and COPY
	StringBuffer sparqlInferQuery = new StringBuffer();
	sparqlInferQuery.append("SELECT *");
	sparqlInferQuery.append(newline);
	sparqlInferQuery.append("FROM <");
	sparqlInferQuery.append(inferenceGraph);
	sparqlInferQuery.append(">");
	sparqlInferQuery.append(newline);
	sparqlInferQuery.append("WHERE ");		
	sparqlInferQuery.append("{ ?s ?p ?o . }");
	sparqlInferQuery.append(newline);
	
	qdef.setSparql(sparqlInferQuery.toString());
	qdef.setIncludeDefaultRulesets(false);
	
	
	JacksonHandle jacksonHandle = new JacksonHandle();
	jacksonHandle.setMimetype("application/json");
	JsonNode jsonResults18 = sparqlQmgr.executeSelect(qdef,  jacksonHandle).get();		
	
	JsonNode jsonBindingsNodes18 = jsonResults18.path("results").path("bindings");
	
	// Should have 18 nodes returned. No inference triples returned.
	assertEquals("18 results not returned from testInferenceAndRuleSet method ", 18, jsonBindingsNodes18.size());
	qdef = null;
	jacksonHandle = null;
	
	// Add subClassOf.rules as default ruleset
	qdef = sparqlQmgr.newQueryDefinition();
	qdef.setRulesets(SPARQLRuleset.SUBCLASS_OF);
	qdef.setIncludeDefaultRulesets(true);
	qdef.setSparql(sparqlInferQuery.toString());
	assertEquals("One Ruleset should have been returned from testInferenceAndRuleSet method ", 1, qdef.getRulesets().length);
	SPARQLRuleset[] rulesets = qdef.getRulesets();
	assertEquals("Ruleset name returned from testInferenceAndRuleSet method is incorrect", "subClassOf.rules", rulesets[0].getName());
	
	// Execute with default Rulesets enabled. - We need to get Inference triples now.
	jacksonHandle = new JacksonHandle();
	jacksonHandle.setMimetype("application/json");
	JsonNode jsonResultsSubClass = sparqlQmgr.executeSelect(qdef, jacksonHandle).get();
		
	// Should have 31 nodes returned.
	assertEquals("31 results not returned from testInferenceAndRuleSet method ", 31, jsonResultsSubClass.path("results").path("bindings").size());
	
	// Enable two rulesets
	qdef = null;
	jacksonHandle = null;
	rulesets = null;
	
	// Add subClassOf.rules and subPropertyOf.rules as default ruleset
	qdef = sparqlQmgr.newQueryDefinition();
	qdef.setRulesets(SPARQLRuleset.SUBCLASS_OF, SPARQLRuleset.SUBPROPERTY_OF);
	qdef.setIncludeDefaultRulesets(true);
	qdef.setSparql(sparqlInferQuery.toString());
	assertEquals("Two Rulesets should have been returned from testInferenceAndRuleSet method ", 2, qdef.getRulesets().length);
	// Have an ordered collection. 
	Collection<SPARQLRuleset> list = Arrays.asList(qdef.getRulesets());
	//Iterate over the list two times. Items more or less would have asserted by now.
	Iterator<SPARQLRuleset> itr = list.iterator();
	assertEquals("First Ruleset name from testInferenceAndRuleSet is incorrect", "subClassOf.rules", itr.next().getName());
	assertEquals("Second Ruleset name from testInferenceAndRuleSet is incorrect", "subPropertyOf.rules", itr.next().getName());
	jacksonHandle = new JacksonHandle();
	jacksonHandle.setMimetype("application/json");
	JsonNode jsonResultsTwoRules = sparqlQmgr.executeSelect(qdef, jacksonHandle).get();
		
	// Should have 44 nodes returned.
	assertEquals("44 results not returned from testInferenceAndRuleSet method ", 44, jsonResultsTwoRules.path("results").path("bindings").size());
	}
