### ISSUE TITLE
implement and unit test bindings

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#311]
```
public interface SPARQLQueryDefinition extends QueryDefinition {
    ...
    public void setBindings(SPARQLBindings bindings);
    public SPARQLBindings getBindings();
    public SPARQLQueryDefinition withBinding(String name, String value);
    public SPARQLQueryDefinition withBinding(String name, String value, String type);
    public SPARQLQueryDefinition withBinding(String name, String value, Locale languageTag);
    public SPARQLQueryDefinition clearBindings();
    ...
}
public interface SPARQLBindings extends Map<String, List<SPARQLBinding>> {
    public SPARQLBindings bind(String name, String value);
    public SPARQLBindings bind(String name, String value, String type);
    public SPARQLBindings bind(String name, String value, Locale languageTag);
}
```

**Comment by sammefford** [comment]
This is mostly done, but waiting on a fix in the server before I can unit test

**Comment by georgeajit** [comment]
The following test methods validate bindings.

/* This test verifies query definition with bindings on string.
	 * The database should contain triples from TestCustomeGraph.
	 * 
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsOnString() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingString method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("}");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding
		SPARQLBindings bindings = qdef1.getBindings();
		bindings.bind("firstname", "Ling", "string");
		qdef1.setBindings(bindings);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println(jsonStrResults);
		
		//Verify the bindings.
		assertTrue("Bindings Map do not have expected key ", qdef1.getBindings().containsKey("firstname"));
				
		assertEquals("Result count from  testQueryBindingsOnString is incorrect", 1, jsonStrResults.path("results").path("bindings").size());
		JsonNode jsonBindingsNodes = jsonStrResults.path("results").path("bindings").get(0);
		
		assertEquals("Element person's value incorrect", "http://marklogicsparql.com/id#4444", jsonBindingsNodes.path("person").path("value").asText()); 	
	}
	
	/* This test verifies query definition with bindings on string. Verify with withBindings method
	 * The database should contain triples from TestCustomeGraph.
	 * 
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryWithBindingsOnString() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryWithBindingsOnString method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("}");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding
		SPARQLBindings bindings = qdef1.getBindings();
		qdef1.withBinding("firstname", "Ling", "string");
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println(jsonStrResults);
		
		//Verify the bindings.
		assertTrue("Bindings Map do not have expected key ", qdef1.getBindings().containsKey("firstname"));
				
		assertEquals("Result count from  testQueryWithBindingsOnString is incorrect", 1, jsonStrResults.path("results").path("bindings").size());
		JsonNode jsonBindingsNodes = jsonStrResults.path("results").path("bindings").get(0);
		
		assertEquals("Element person's value incorrect", "http://marklogicsparql.com/id#4444", jsonBindingsNodes.path("person").path("value").asText()); 	
	}
	
	/* This test verifies query definition with bindings on integer.
	 * The database should contain triples from TestCustomeGraph.
	 * 
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsOnInteger() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingsOnInteger method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname ?lastname ?cost");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("FILTER (?cost < 10)");
		queryStr.append(newline);
		queryStr.append("}");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding
		SPARQLBindings bindings = qdef1.getBindings();
		bindings.bind("cost","8","integer");
		qdef1.setBindings(bindings);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println(jsonStrResults);
		
		//Verify the bindings.
		assertTrue("Bindings Map do not have expected key ", qdef1.getBindings().containsKey("cost"));
		assertEquals("Result count from  testQueryBindingsOnInteger is incorrect", 5, jsonStrResults.path("results").path("bindings").size());	
	}
	
	/* This test verifies ASK query definition with bindings on multiple string values.
	 * The database should contain triples from TestCustomeGraph.
     * 
     * Expected return : true
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsAskOnStrings() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingsAskOnStrings method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("ASK");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("FILTER (?firstname = \"Ling\")");
		queryStr.append(newline);
		queryStr.append("}");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding
		SPARQLBindings bindings = qdef1.getBindings();
		bindings.bind("firstname","John","string");
		qdef1.setBindings(bindings);
		bindings.bind("firstname","Ling","string");
		qdef1.setBindings(bindings);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println(jsonStrResults);		
		//Verify the bindings.
		assertEquals("Bindings Map do not have expected number of values ", 1, qdef1.getBindings().entrySet().size());
		assertEquals("Result count from  testQueryBindingsAskOnStrings is incorrect", "true", jsonStrResults.path("boolean").asText());	
	}
	
	/* This test verifies query definition with bindings on string variable with null value.
	 * The database should contain triples from TestCustomeGraph.
	 * 
	 * Expected result : IllegalArgumentException
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsNullString() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingsNullString method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("}");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding
		SPARQLBindings bindings = qdef1.getBindings();
		
		String expectedException = "IllegalArgumentException";
		String exception = "";
		try {
			bindings.bind("firstname", null,"string");
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println("Exception thrown from testQueryBindingsNullString is \n"+ exception);
		assertTrue("Test testQueryBindingsNullString method exception is not thrown", exception.contains(expectedException));
	}
	
	/* This test verifies query definition with bindings on string.
	 * The database should contain triples from TestCustomeGraph.
	 * 
	 * Expected result : SPARQL considers that there is no binding and all results are returned.
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsDifferentVariableName() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingsDifferentVariableName method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("}");
		queryStr.append(newline);
		queryStr.append("ORDER BY ?firstname ?lastname");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding with wrong name
		SPARQLBindings bindings = qdef1.getBindings();
		bindings.bind("blahblah", "Ling","string");
		qdef1.setBindings(bindings);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println(jsonStrResults);
		
		//Verify the bindings.
		assertTrue("Bindings Map do not have expected key ", qdef1.getBindings().containsKey("blahblah"));		
		
		assertEquals("Result count from  testQueryBindingsDifferentVariableName is incorrect", 5, jsonStrResults.path("results").path("bindings").size());
		JsonNode jsonBindingsNodes = jsonStrResults.path("results").path("bindings");
		// The results are ordered.
		assertEquals("First person's value incorrect", "http://marklogicsparql.com/id#3333", jsonBindingsNodes.get(0).path("person").path("value").asText()); 	
		assertEquals("Second person's value incorrect", "http://marklogicsparql.com/id#5555", jsonBindingsNodes.get(1).path("person").path("value").asText());
		assertEquals("Third person's value incorrect", "http://marklogicsparql.com/id#1111", jsonBindingsNodes.get(2).path("person").path("value").asText());
		assertEquals("Fourth person's value incorrect", "http://marklogicsparql.com/id#4444", jsonBindingsNodes.get(3).path("person").path("value").asText());
		assertEquals("Fifth person's value incorrect", "http://marklogicsparql.com/id#2222", jsonBindingsNodes.get(4).path("person").path("value").asText());
	}
	
	/* This test verifies query definition with bindings on SPARQL Update query with integer data type.
	 * The database should contain triples from TestCustomeGraph.
	 * 
	 * Expected result : Id should have 30 in query results returned.
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testSparqlUpdateInsertDataBinding() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testSparqlUpdateInsertDataBinding method");
        SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryInsStr = new StringBuffer();

		queryInsStr.append("prefix df: <http://marklogic.com/default-data>");
		queryInsStr.append(newline);
		queryInsStr.append("prefix su-api: <http://marklogic.com/SparqlUpdate-API#>");
		queryInsStr.append(newline);
		queryInsStr.append("prefix bb: <http://marklogic.com/baseball/players#>");
		queryInsStr.append(newline);
		queryInsStr.append("prefix xs: <http://www.w3.org/2001/XMLSchema#>");
		queryInsStr.append(newline);
		queryInsStr.append("INSERT DATA");
		queryInsStr.append("{");
		queryInsStr.append(newline);
		queryInsStr.append("GRAPH <BindingsGraph>");
		queryInsStr.append(newline);
		queryInsStr.append("{");
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:playerid	\"XX\" .");
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:lastname		\"LASTNAME\" .");
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:firstname	\"FIRSTNAME\" .");	
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:position		\"POSITION\" .");
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:number		\"NUMBER\" .");
		queryInsStr.append(newline);
		queryInsStr.append("#bb:XX	bb:team			\"Athletics\" .");
		queryInsStr.append(newline);
		queryInsStr.append("bb:35	bb:playerid	?playerid .");
		queryInsStr.append(newline);
		queryInsStr.append("}");
		queryInsStr.append(newline);
		queryInsStr.append("}");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(queryInsStr.toString());
		
		// Set up the integer variable binding 
		SPARQLBindings bindings = qdef.getBindings();
		bindings.bind("playerid", "30","integer");
		qdef.setBindings(bindings);
				
		sparqlQmgr.executeUpdate(qdef);
		// Wait for index 
		try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
		//Query the graph and make sure we have 30 in the id
		
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition().withSparql("select ?s ?p ?o from <BindingsGraph> where {?s ?p ?o. }");
		JsonNode jsonBindingsNodes = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get().path("results").path("bindings").get(0);

		// Should have 1 nodes returned.
		assertEquals("Number of nodes returned from testSparqlUpdateInsertDataBinding method after query is incorrect", 3, jsonBindingsNodes.size());
		assertEquals("Subject is incorrect", "http://marklogic.com/baseball/players#35",jsonBindingsNodes.path("s").path("value").asText());
		assertEquals("Predicate is incorrect", "http://marklogic.com/baseball/players#playerid",jsonBindingsNodes.path("p").path("value").asText());
		assertEquals("Object is incorrect", "30",jsonBindingsNodes.path("o").path("value").asText());
	}
	
	/* This test verifies query definition bindings on SPARQL UPDATE command.
	 * The test inserts a graph with triples and then verifies the binding value.
	 * 
	 * Expected result : IllegalArgumentException and Invalid parameter: Bind variable type parameter requires XSD type message
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testQueryBindingsIncorrectDataType() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testQueryBindingsIncorrectDataType method");
        SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?firstname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("}");
		queryStr.append(newline);
		queryStr.append("ORDER BY ?firstname ?lastname");
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString());
		
		// Set up the String variable binding with wrong data type.
		SPARQLBindings bindings = qdef1.getBindings();
		bindings.bind("firstname", "Ling","dateTimeStamp");
		qdef1.setBindings(bindings);

		String expectedException = "FailedRequestException";
		String exception = "";
		try {
			JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		} catch (Exception e) {
			exception = e.toString();
		}
		System.out.println("Exception thrown from testQueryBindingsIncorrectDataType is \n"+ exception);
		assertTrue("Test testQueryBindingsIncorrectDataType method exception is not thrown", exception.contains(expectedException));
	    assertTrue("Message Incorrect", exception.contains("Invalid parameter: Bind variable type parameter requires XSD type"));
	}

**Comment by sammefford** [comment]
Ajit, great tests!  You cover string types.  You cover integer types with a "less than" comparison which is great.  You cover negative case of null variable name.  You cover bindings on sparql update.  And you cover negative case using an invalid type.  That's pretty good coverage as far as I can tell.  

I'm thinking we need to revisit the last test, on invalid type.  The reason is dateTimeStamp should be a valid type if we support all the types here: http://www.w3.org/TR/rdf11-concepts/#xsd-datatypes  So I'm thinking we need a bug against the REST API for not supporting dateTimeStamp.  And you could make your test work by changing "dateTimeStamp" to "someCustomType" or "blahblah".

Oh, and one minor comment: I really struggled to understand testSparqlUpdateInsertDataBinding() until I realized you'd commented most of the lines in the SPARQL.  Would it make sense to remove the commented lines?
