### ISSUE TITLE
implement and unit test constraining queries

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#312]
In SPARQLQueryDefinition:
```
public void setConstrainingQueryDefinintion(QueryDefinition query);
public QueryDefinition getConstrainingQueryDefinintion();
public SPARQLQueryDefinition withConstrainingQuery(QueryDefinition query);
```

**Comment by georgeajit** [comment]
The following test methods verify ConstrainingQueryDefinition with SPARQL query:
/* This test verifies setConstrainingQueryDefinition method on SPARQLQueryDefinition class. 
	 * 
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testConstrainingQuery() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testConstrainingQuery method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?fn ?lastname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("BIND (?firstname as ?fn)");
		queryStr.append("}");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(queryStr.toString());
		QueryManager queryMgr = writeclient.newQueryManager();
		
		// Set up the String variable binding.
		SPARQLBindings bindings = qdef.getBindings();
		
		bindings.bind("firstname","Lei","string");
		qdef.setBindings(bindings);
		
		// create query def.
		StringQueryDefinition querydef = queryMgr.newStringDefinition();
		querydef.setCriteria("Meng AND 8888");
		
		qdef.setConstrainingQueryDefinition(querydef);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef, new JacksonHandle()).get();
		System.out.println(jsonStrResults);	
		JsonNode jsonBindings = jsonStrResults.path("results").path("bindings").get(0);
		
		//Verify the results.
		assertEquals("Result value from  testConstrainingQuery is incorrect", "http://marklogicsparql.com/id#6666", jsonBindings.path("person").path("value").asText());	
		assertEquals("Result fn from  testConstrainingQuery is incorrect", "Lei", jsonBindings.path("fn").path("value").asText());
		assertEquals("Result lastname from  testConstrainingQuery is incorrect", "Pei", jsonBindings.path("lastname").path("value").asText());	
	}
	
	/* This negative test verifies setConstrainingQueryDefinition method on SPARQLQueryDefinition class with null. 
	 * Pass a null to setConstrainingQueryDefinition
	 * Pass invalid data as criteria
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testConstrainingQueryNull() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testConstrainingQueryNull method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();
		
		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?fn ?lastname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append("BIND (?firstname as ?fn)");
		queryStr.append("}");
		
		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(queryStr.toString());
		QueryManager queryMgr = writeclient.newQueryManager();
		// create query def.
		StringQueryDefinition strquerydef = queryMgr.newStringDefinition();
		strquerydef.setCriteria("Foo AND bar");
		// Set up the String variable binding.
		SPARQLBindings bindings = qdef.getBindings();
		
		bindings.bind("firstname","Lei","string");
		qdef.setBindings(bindings);
		qdef.setConstrainingQueryDefinition(null);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef, new JacksonHandle()).get();
		System.out.println("Null in ConstrainingQueryDefinition \n");
		System.out.println(jsonStrResults);	
		JsonNode jsonBindings = jsonStrResults.path("results").path("bindings");
		
		//Verify the results. Returns results.
		assertEquals("Result size from  testConstrainingQueryNull is incorrect", 1, jsonBindings.size());
		assertEquals("Result value from  testConstrainingQueryNull is incorrect", "http://marklogicsparql.com/id#6666", jsonBindings.get(0).path("person").path("value").asText());	
		assertEquals("Result fn from  testConstrainingQueryNull is incorrect", "Lei", jsonBindings.get(0).path("fn").path("value").asText());
		assertEquals("Result lastname from  testConstrainingQueryNull is incorrect", "Pei", jsonBindings.get(0).path("lastname").path("value").asText());
		
		SPARQLQueryDefinition qdef1 = sparqlQmgr.newQueryDefinition(queryStr.toString()).withConstrainingQuery(strquerydef);
		// Parsing results using JsonNode. 
		JsonNode jsonStrResults1 = sparqlQmgr.executeSelect(qdef1, new JacksonHandle()).get();
		System.out.println("Invalid Data \n");
		System.out.println(jsonStrResults1);	
		JsonNode jsonBindings1 = jsonStrResults1.path("results").path("bindings");
				
		//Verify the results. Returns No results.
		assertEquals("Result size from  testConstrainingQueryNull is incorrect", 0, jsonBindings1.size());
	}
	
	/* This test verifies SPARQL query with cts:contains 
	 * 
     * Uses JacksonHandle
	 * 
	 */
	@Test
	public void testSparqlQueryCtsContains() throws IOException, SAXException, ParserConfigurationException
	{	
		System.out.println("In SPARQL Query Manager Test testSparqlQueryCtsContains method");
		SPARQLQueryManager sparqlQmgr = writeclient.newSPARQLQueryManager();

		StringBuffer queryStr = new StringBuffer();
		queryStr.append("PREFIX ad: <http://marklogicsparql.com/addressbook#>");
		queryStr.append(newline);
		queryStr.append("PREFIX d:  <http://marklogicsparql.com/id#>");
		queryStr.append(newline);
		queryStr.append("PREFIX cts: <http://marklogic.com/cts#>");
		queryStr.append(newline);
		queryStr.append("SELECT ?person ?fn ?lastname");
		queryStr.append(newline);
		queryStr.append("FROM <");
		queryStr.append(customGraph);
		queryStr.append(">");
		queryStr.append(newline);
		queryStr.append("WHERE");
		queryStr.append(newline);
		queryStr.append("{");
		queryStr.append(newline);
		queryStr.append("?person ad:firstName ?firstname ;");
		queryStr.append(newline);
		queryStr.append("ad:lastName ?lastname.");
		queryStr.append(newline);
		queryStr.append("OPTIONAL {?person ad:homeTel ?phonenumber .}");
		queryStr.append(newline);
		queryStr.append(" FILTER cts:contains(?firstname, cts:or-query((\"Ling\", \"Lei\")))");
		queryStr.append("}");
		queryStr.append("ORDER BY ?firstname");

		SPARQLQueryDefinition qdef = sparqlQmgr.newQueryDefinition(queryStr.toString());
		JsonNode jsonStrResults = sparqlQmgr.executeSelect(qdef, new JacksonHandle()).get();
		System.out.println(jsonStrResults);	
		JsonNode jsonBindings1 = jsonStrResults.path("results").path("bindings").get(0);
		JsonNode jsonBindings2 = jsonStrResults.path("results").path("bindings").get(1);

		//Verify the results.
		assertEquals("Result 1 value from  testSparqlQueryCtsContains is incorrect", "http://marklogicsparql.com/id#6666", jsonBindings1.path("person").path("value").asText());			
		assertEquals("Result 1 lastname from  testSparqlQueryCtsContains is incorrect", "Pei", jsonBindings1.path("lastname").path("value").asText());
		
		assertEquals("Result 2 value from  testSparqlQueryCtsContains is incorrect", "http://marklogicsparql.com/id#4444", jsonBindings2.path("person").path("value").asText());
		assertEquals("Result 2 lastname from  testSparqlQueryCtsContains is incorrect", "Ling", jsonBindings2.path("lastname").path("value").asText());		
	}
