### ISSUE TITLE
Error not parsed from REST for missing base-uri when inserting triples with application/rdf+xml mimetype

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#319]
Insert triples of rdf mimetype which does not have a base uri specified.

Expected Error message :: message":"XDMP-BASEURI (err:FOER0000): Undeclared base URI . See the MarkLogic server error log for further detail.

Current Error:: com.marklogic.client.FailedRequestException: Local message: failed to write resource at graphs: Internal Server Error. Server Message: Request failed. Error body not received from server
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4581)
	at com.marklogic.client.impl.JerseyServices.putResource(JerseyServices.java:3324)
	at com.marklogic.client.impl.JerseyServices.writeGraph(JerseyServices.java:5377)
	at com.marklogic.client.impl.GraphManagerImpl.write(GraphManagerImpl.java:216)
	at com.marklogic.client.impl.GraphManagerImpl.write(GraphManagerImpl.java:198)

Ex Code snippet::
File file = new File("src/test/java/com/marklogic/client/functionaltest/data/semantics/relative4.rdf");
		FileHandle filehandle = new FileHandle();
filehandle.set(file);
writerClient = DatabaseClientFactory.newClient("localhost", restPort,
				dbName, "rest-writer", "x", Authentication.DIGEST);
gmWriter = writerClient.newGraphManager();
gmWriter.write("htp://test.kiran.graph/G4", filehandle.withMimetype("application/rdf+xml"));

**Comment by sammefford** [comment]
Kiran, can you share with me src/test/java/com/marklogic/client/functionaltest/data/semantics/relative4.rdf

I think I need it to duplicate.

**Comment by kkanthet** [comment]
Fixed by #323

**Comment by AleksandarSavic95** [comment]
For anyone who encountered this error:

> XDMP-BASEURI (err:FOER0000): Undeclared **base URI** . See the MarkLogic server error log for further detail.

here is a solution that worked for me: Check that Your `about` attribute has an absolute URI as the value.
My mistake is that I had:

> <root ... about="/thing"> ...

And the correct way of setting the `about` attribute is like this:

> about="http://some-domain.com/path/to/the/thing"

By writing it this way, You are giving the full path, i.e. the **base URI** + the relative part.
It's a dumb error, but [it could happen to You](https://www.youtube.com/watch?v=44qWY83iW54) :)
