### ISSUE TITLE
Throw an exception when DatabaseClient is closed with an open transaction

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#329]
An exception should be thrown when a DatabaseClient is closed without a rollback or commit of an open transaction.

Steps to reproduce::
Open a transaction 
Forget to commit/rollback(well ..  pretend to forget)
Clear Forest
Release DatabaseClient instance

Current::
No exception thrown.

**Comment by sammefford** [comment]
As a group we discussed and decided we should also rollback the transaction before throwing the exception.  That way it won't tie up server resources since we know the client code is not attempting to close it.

**Comment by sammefford** [comment]
I think this should be done as part of ML 9.0-1 since it could be a breaking change if users mistakenly coded databaseClient.release() then transaction.commit() or transaction.rollback().
