### ISSUE TITLE
Could not read resource at graphs/things Exception for things & thingsAs

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#336]
Getting Exception for below test for thingsAs with writeUser permission.

file relative1.nt has below content::
<#electricVehicle2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://people.aifb.kit.edu/awa/2011/smartgrid/schema/smartgrid#ElectricVehicle> .

public void test001Things() throws Exception{
		gmWriter.setDefaultMimetype(RDFMimeTypes.NTRIPLES);
		File file = new File(datasource + "relative1.nt");
		FileHandle filehandle = new FileHandle();
		filehandle.set(file);
		gmWriter.write("http://test.things.com/", filehandle);
		  String things = gmWriter.thingsAs(String.class, "http://test.things.com/");
		assertTrue("Did not return Expected graph Uri's",
				things.contains("#electricVehicle2"));
	}

StackTrace::
com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at graphs/things. Server Message: 
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4585)
	at com.marklogic.client.impl.JerseyServices.getResource(JerseyServices.java:3183)
	at com.marklogic.client.impl.JerseyServices.getThings(JerseyServices.java:5509)
	at com.marklogic.client.impl.GraphManagerImpl.things(GraphManagerImpl.java:321)
	at com.marklogic.client.impl.GraphManagerImpl.thingsAs(GraphManagerImpl.java:327)
	at com.marklogic.client.functionaltest.TestSemanticsGraphManager.test001Things(TestSemanticsGraphManager.java:839)

Wire Trace:;
2015/07/31 13:36:14:021 PDT [DEBUG] DefaultClientConnection - Sending request: GET /v1/graphs/things?iri=http://test.things.com/&database=SemanticsDB-JavaAPI HTTP/1.1
2015/07/31 13:36:14:021 PDT [DEBUG] wire - >> "GET /v1/graphs/things?iri=http://test.things.com/&database=SemanticsDB-JavaAPI HTTP/1.1[\r][\n]"
2015/07/31 13:36:14:022 PDT [DEBUG] wire - >> "Authorization: Digest username="rest-writer",realm="public",nonce="3900325542e8e176525105ddd94fd4f5",opaque="8e542629df6225df",qop=auth,uri="/v1/graphs/things",cnonce="a3839f3b",nc=00000002,response="21674c274a41a7d2a5e9a4b082b8340b"[\r][\n]"
2015/07/31 13:36:14:022 PDT [DEBUG] wire - >> "Host: localhost:8011[\r][\n]"
2015/07/31 13:36:14:022 PDT [DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
2015/07/31 13:36:14:023 PDT [DEBUG] wire - >> "[\r][\n]"
2015/07/31 13:36:14:023 PDT [DEBUG] headers - >> GET /v1/graphs/things?iri=http://test.things.com/&database=SemanticsDB-JavaAPI HTTP/1.1
2015/07/31 13:36:14:023 PDT [DEBUG] headers - >> Authorization: Digest username="rest-writer",realm="public",nonce="3900325542e8e176525105ddd94fd4f5",opaque="8e542629df6225df",qop=auth,uri="/v1/graphs/things",cnonce="a3839f3b",nc=00000002,response="21674c274a41a7d2a5e9a4b082b8340b"
2015/07/31 13:36:14:024 PDT [DEBUG] headers - >> Host: localhost:8011
2015/07/31 13:36:14:024 PDT [DEBUG] headers - >> Connection: Keep-Alive
2015/07/31 13:36:14:430 PDT [DEBUG] wire - << "HTTP/1.1 404 Not Found[\r][\n]"
2015/07/31 13:36:14:431 PDT [DEBUG] wire - << "Server: MarkLogic[\r][\n]"
2015/07/31 13:36:14:431 PDT [DEBUG] wire - << "Content-Length: 0[\r][\n]"
2015/07/31 13:36:14:431 PDT [DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
2015/07/31 13:36:14:432 PDT [DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
2015/07/31 13:36:14:432 PDT [DEBUG] wire - << "[\r][\n]"
2015/07/31 13:36:14:432 PDT [DEBUG] DefaultClientConnection - Receiving response: HTTP/1.1 404 Not Found
2015/07/31 13:36:14:433 PDT [DEBUG] headers - << HTTP/1.1 404 Not Found
2015/07/31 13:36:14:433 PDT [DEBUG] headers - << Server: MarkLogic
2015/07/31 13:36:14:433 PDT [DEBUG] headers - << Content-Length: 0
2015/07/31 13:36:14:433 PDT [DEBUG] headers - << Connection: Keep-Alive
2015/07/31 13:36:14:434 PDT [DEBUG] headers - << Keep-Alive: timeout=5
2015/07/31 13:36:14:434 PDT [DEBUG] DefaultHttpClient - Connection can be kept alive for 5000 MILLISECONDS
2015/07/31 13:36:14:435 PDT [DEBUG] ThreadSafeClientConnManager - Released connection is reusable.
2015/07/31 13:36:14:435 PDT [DEBUG] ConnPoolByRoute - Releasing connection [HttpRoute[{}->http://localhost:8011]][null]
2015/07/31 13:36:14:436 PDT [DEBUG] ConnPoolByRoute - Pooling connection [HttpRoute[{}->http://localhost:8011]][null]; keep alive for 5000 MILLISECONDS
2015/07/31 13:36:14:436 PDT [DEBUG] ConnPoolByRoute - Notifying no-one, there are no waiting threads

**Comment by sammefford** [comment]
While the docs/spec don't make this clear (yet--we're fixing that), /v1/graphs/things is not looking for a graph uri.  It's looking for a uri that is a subject, predicate, or object.
