### ISSUE TITLE
Better Eclipse support

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#34]
The project must not require Eclipse to build/run/test. However, there should be an easy way for a developer using Eclipse to easily set up her environment. This likely includes, but isn’t limited to, `.project`, `.classpath`, and perhaps, `.settings/`. 

The resulting configuration should compile and build with zero warnings.

Should we require the [m2e](https://www.eclipse.org/m2e/) plugin? [egit](http://www.eclipse.org/egit/).

**Comment by sammefford** [comment]
I added .classpath, .project, and .settings.  Let me know if it works or doesn't for you, Ajit & Kiran.

**Comment by georgeajit** [comment]
Was able to import the project (java-client-api-dev) into a new Eclipse project workspace. 
Eclipse built the workspace automatically and was able to see all dependencies resolved.

Tasks Done:

Performed the necessary MarkLogic setup to run unit tests.
Run the DOM4JHandleExample class from Eclipse as "Java Application" successfully.
The documents database had the documents written from the example.
