### ISSUE TITLE
Remove mvn-repo branch

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#340]
The mvn-repo branch is outdated and therefore ready to be removed.  It was for 8.x early access releases.  It contains large binaries which could impact clones.

We will likely recreate an mvn-repo branch when we begin the Early Access releases for 9.x.

**Comment by sammefford** [comment]
Charles, can you confirm sample stack and anything else that you know of does not currently depend on the mvn-repo branch?

**Comment by grechaw** [comment]
Only development snapshots and EA relied on it.  I think its acceptable to remove.  @laurelnaiad may have an opinion too.

**Comment by grechaw** [comment]
I think you're good to go with this removal-- however will you also purge it somehow?  It might require a push -f somewhere to actually prune the .git directory

**Comment by sammefford** [comment]
I deleted it on github with

    git push origin --delete mvn-repo

I can't find any indication that there's an additional purge needed.  But everyone who's pulled this  project will still have the remote tracking branch until they do:

    git fetch --all --prune

Which will clean their local repo of branches we've removed from github.
