### ISSUE TITLE
Searching for non-existing uri using things should throw proper exception 

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#342]
Search for non existing URI using things/thingsAs throws 
com.marklogic.client.ResourceNotFoundException: Local message: Could not read resource at graphs/things. Server Message: 

Should throw proper exception 

Steps to reproduce::
public void test001Things_fileNomatch() throws Exception {
        gmWriter.setDefaultMimetype(RDFMimeTypes.TRIPLEXML);
        String tripleGraphUri="http://test.things.com/file";
        File file = new File(datasource + "relative5.xml");
        gmWriter.write(tripleGraphUri, new FileHandle(file) );
        StringHandle things = gmWriter.things(new StringHandle(), "noMatch");
        assertTrue("Things did not return expected Uri's", things == null);
        gmWriter.delete(tripleGraphUri);
    }

relative5.xml::
<sem:triples xmlns:sem="http://marklogic.com/semantics">
<sem:triple xmlns:sem="http://marklogic.com/semantics">
<sem:subject>about</sem:subject>
<sem:predicate>http://purl.org/dc/elements/1.1/title</sem:predicate>
<sem:object datatype="http://www.w3.org/2001/XMLSchema#string">Anna's Homepage</sem:object>
</sem:triple>
</sem:triples>

**Comment by sammefford** [comment]
Throwing ResourceNotFoundException is expected and consistent with the rest of the Java Client API
