### ISSUE TITLE
Add RDFMimeTypes.CSV

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#344]
application/sparql-results+csv is a format that will soon be supported at the REST layer, and should be supported also by the Java layer.  While, of course, users can call:

    StringHandle handle = new StringHandle().withMimetype("application/sparql-results+csv");
    sparqlQueryManager.executeSelect(sparqlQueryDef, handle);

We'd prefer instead that they call:

    StringHandle handle = new StringHandle().withMimetype(SPARQLMimetypes.SPARQL_CSV);
    sparqlQueryManager.executeSelect(sparqlQueryDef, handle);

**Comment by sammefford** [comment]
As long as we're creating SPARQLMimeTypes we'll add the constants SPARQL_JSON (application/sparql-results+json) and SPARQL_XML (application/sparql-results+xml)

**Comment by sammefford** [comment]
Ajit, since I already have a unit test testing these, you don't need to add any tests.  Please just verify that my tests run fine for you.

**Comment by jhoy** [comment]
Adding a comment to see if I can trigger pull.

**Comment by georgeajit** [comment]
Verified Jenkins Build #384 (Aug 25, 2015 10:28:43 AM) . SPARQLManagerTest runs fine.

**Comment by jhoy** [comment]
Testing pullthrough - please disregard
