### ISSUE TITLE
Remove values and tuples directly on fields

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#345]
While values and tuples can draw from field range indexes, it is not valid to draw values or tuples directly from fields.  This was determined in the Search API layer and the schema was tightened to throw an error in that scenario.

**Comment by sammefford** [comment]
Ajit, this change was necessary to resolve failing unit test QueryOptionsBuilderTest.testRootOptions

**Comment by georgeajit** [comment]
Scanned existing QA tests and found couple of tests that draw values from range indexes. Here are a couple of options used:

<options xmlns="http://marklogic.com/appservices/search">
  <values name="pop-aggr">
    <range type="xs:int">
      <element ns="" name="popularity"/>
    </range>
  </values>
  <values name="score-aggr">
    <range type="xs:decimal">
      <element ns="http://test.aggr.com" name="score"/>
    </range>
  </values>
  <tuples name="pop-rate-tups">
    <range type="xs:int">
      <element ns="" name="popularity"/>
    </range>
    <range type="xs:int">
      <element ns="http://test.tups.com" name="rate"/>
    </range>
  </tuples>
</options>

And 
<search xmlns="http://marklogic.com/appservices/search">
	<options xmlns="http://marklogic.com/appservices/search">
	<values name="grandchild">
		<range type="xs:string">
			<element ns="" name="grandchild"/>
		</range>
	<values-option>limit=2</values-option>
	</values>
	<tuples name="co">
		<range type="xs:double">
			<element ns="" name="double"/>
		</range>
		<range type="xs:int">
			<element ns="" name="int"/>
		</range>
	</tuples>
	<tuples name="n-way">
		<range type="xs:double">
			<element ns="" name="double"/>
		</range>
		<range type="xs:int">
			<element ns="" name="int"/>
		</range>
		<range type="xs:string">
			<element ns="" name="string"/>
		</range>
		<values-option>ascending</values-option>
	</tuples>
		<return-metrics>true</return-metrics>
		<return-values>true</return-values>
	</options>
</search>

Test names are TestAggregates.java, TestBug21159.java  and TestBug19144. We do not have tests that draw values or tuples directly from fields, while using tuples() or values() methods on a QueryManager object.
