### ISSUE TITLE
Allow auto-generated URIs in bulk document operations

### ISSUE THREAD

**Issue by malteseduck** [marklogic/java-client-api#352]
It would be nifty if DocumentWriteSet had additions similar to these:

``` java
public DocumentWriteSet add(DocumentUriTemplate template, AbstractWriteHandle contentHandle);
public DocumentWriteSet add(DocumentUriTemplate template, DocumentMetadataWriteHandle metadataHandle, AbstractWriteHandle contentHandle);
```

so that we can have URIs generated in the database.  That would cause issues with `DocumentWriteOperation` since that only deals with uris and would need to store the template information.  

Then in `JerseyServices postBuilkDocuments` there can be logic to check for uri vs. extension (and potentially directory) and add the appropriate content disposition for the REST endpoint, something like:

```
attachment; extension="json"; directory="/where/I/want/it"
```

In the end, I dig through too much code for my own good and however it is implemented is not important, I would just love being able to do bulk operations yet have the URIs auto generated like I am able to do with a single document.

**Comment by sammefford** [comment]
Thanks, Chris.  Looks to me like we support Bulk write with URI generation in the REST layer, so this shouldn't be too hard to add to the Java layer.  I've assigned to Justin so he can prioritize.

**Comment by malteseduck** [comment]
Wonderful, thank you, Sam.
