### ISSUE TITLE
add setBaseUri() and getBaseUri() to querydef

### ISSUE THREAD

**Issue by xquery** [marklogic/java-client-api#354]
now that the REST server supports a base url param which will sets base uri via $options in sem:sparql-update we would like to expose this via the java client.

adding setBaseUri(String uri) and getBaseUri() on SPARQLQueryDefinition would minimally support this.

**Comment by georgeajit** [comment]
Added tests to check base URI functionality in executeConstruct, executeUpdate and then select triples.
Handling valid base uri strings, strings with multibyte characters, null and empty strings.
