### ISSUE TITLE
Don't ship logback.xml with the jar.

### ISSUE THREAD

**Issue by grechaw** [marklogic/java-client-api#359]
logback.xml should not be in src/main/resources.

probably moving it to src/test/resources will work to keep it out of the distribution.

**Comment by gvaidees** [comment]
I have marked this for  java-client-api-3.0.4. Not sure if that is the right milestone

**Comment by sammefford** [comment]
This isn't a bug, AFAICT.  Since we're past code freeze and this just came in, I would say let's ship this in the next release.

**Comment by grechaw** [comment]
OK with me

**Comment by gvaidees** [comment]
Can you please assign a milestone for this? java-client-api-3.0.5?

**Comment by sammefford** [comment]
Ajit, there's nothing new to test here.  Just be aware that I removed src/main/resources/logback.xml and keep that in mind if new failing tests or regressions arise.

**Comment by georgeajit** [comment]
Sure. Thank you for the update. Will look for regressions for two days and then close this issue, if none are related to this.

**Comment by georgeajit** [comment]
No regressions observed due to this issue. Verified regression results for 02/28/2016 and 02/27/2016.
