### ISSUE TITLE
Add RDFType

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#362]
Looks like I missed adding RDFType.  It is an enumeration of supported RDF binding types, for which toString() creates the appropriate REST parameter.  Here are the supported types: http://www.w3.org/TR/rdf11-concepts/#xsd-datatypes

**Comment by georgeajit** [comment]
Any reason why we have 
```
INTEGER            ("integer"),
```
and 

```
 INT                ("int"),
```

**Comment by sammefford** [comment]
These come from http://www.w3.org/TR/rdf11-concepts/#xsd-datatypes and those are two different datatypes.  xsd:int is 32-bit (like Java's int) whereas xsd:integer is arbitrary-sized (like Java's BigInteger).

**Comment by georgeajit** [comment]
Binding tests have been modified.
