### ISSUE TITLE
respect load balancer cookies

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#364]
JerseyServices is currently only resending HostId cookies but should respect other session cookies for the duration of the transaction.  This will allow us to respect load balancer session affinity cookies so requests for the same transaction get automatically routed to the same host by the load balancer configured to use session affinity cookies.

**Comment by sammefford** [comment]
We used to support all session cookies but cut back to just the HostId cookie for two reasons:
1) session lifecycle was undefined so cookies were shared promiscuously through the HTTP connection pool
2) we started talking to the /v1/eval endpoint which sent back transaction-related cookies which caused havoc with (1) above

I have not found any standard REST definition for the lifespan of a session cookie.  However, I'm thinking we can allow back in all session cookies (so we will respect any load balancer session cookies) as long as we define the lifespan of a cookie "session" to be the lifespan of a multi-statement transaction.

**Comment by kkanthet** [comment]
As discussed , assigning back to you while we decide on the [RFE 3557](https://rfetrack.marklogic.com/detail/3557)

**Comment by sammefford** [comment]
I thought it was #381 we discussed.  I'm taking that one back because I need to supply a hotfix we can ask the reporter to test rather than all the related changes I made for this issue.

**Comment by bsdang** [comment]
Hello, can you please confirm if this fix is in java-client-api-3.0-5 ? we are facing this problem with a customer where AWS ELB is configured for session stickiness, and Java client api is used via marklogic sesame api to one a transaction and send multiple requests over that transaction, and we can see that requests are not going to same node, even though ELB is properly configured.

**Comment by sammefford** [comment]
I can see that commit https://github.com/marklogic/java-client-api/commit/b7defc3f105ce790fba2ae0acee35a6279581e95 is tagged with 3.0.5.  So this fix is there.  Can you share the details of your AWS ELB configuration?  Have you confirmed that it is using session cookies?  If you look at the HTTP wire trace, this should be working if the HTTP requests coming from the Java client API pass the session cookies sent by the load balancer in the previous response that was part of the same transaction.

**Comment by kkanthet** [comment]
Did one round of tests with AWS ELB and found one issue, need further testing 
With stickiness set to: LBCookieStickinessPolicy, noExpiration time explicitly set
1) We see that, DocumentManager write(set, transaction) and then a "readstatus" on that same transaction, the requests go to different hosts. This happens on the uberServer (port 8000).

2) On non-uber server (regular REST server), we do see that the stickiness works in the case of a multi-statement transaction. We tested on a transaction, a write, read and then delete documents.

We need to fix 1) and need more tests on 2)

**Comment by georgeajit** [comment]
One of the QA test class tested was TestDatabaseClientConnection, (found in the develop branch of test-complete)  with test method : testTransactionReadStatus

This reproduces in the issue reported by 1) in the above comment.

**Comment by sammefford** [comment]
An internal write-up on support for load balancers can be referenced here: https://wiki.marklogic.com/display/ENGINEERING/Client+API+Support+for+Load+Balancer+Server+Affinity

That might help describe what we think we should do.
