### ISSUE TITLE
Clean up code to pass linter and remove -Xdoclint:none from pom.xml

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#366]
Java 8 linter is overly-aggressive.  But there's no reason we can't clean up our code to pass clean according to the linter.  Let's do that.  Then we can remove "-Xdoclint:none" from the pom.xml

**Comment by sammefford** [comment]
I removed the section from pom.xml with -Xdoclint:none and it appears that in the latest version of Java the overly-aggressive linter is gone because no doclint messages appear when I run "mvn clean compile test-compile".

**Comment by sammefford** [comment]
I'd still like to clean up the code to remove at least all the warnings in Eclipse, so I'll keep this task and move it to 4.0-ea2.

**Comment by sammefford** [comment]
It turns out the fixes were needed not for compile but for javadoc creation.  I'm going to go ahead and fix all the issues the linter finds when generating javadocs.

**Comment by sammefford** [comment]
Ajit,

Again this is not one you'll need to test.  Just be aware this includes hundreds of small changes to javadoc comments and re-enabling the javadoc linter which throws errors on missing javadoc details.  All those javadoc warnings and errors have now been addressed and we'll keep up with those as we add new methods.

**Comment by georgeajit** [comment]
1) Checked out the latest Java Client API 3.0 develop branch. (Java Home was set to JDK 1.8)
 2) Run the following command:
```mvn -Dmaven.test.skip=true install```
3) The Jars were created and installed in the M2 repository.
4) Extracted the Java Docs Jar contents into a local directory.
5) Was able to browse various class' documentation and packages.
6) Verified the pom.xml file. It has the lint parameter; turning off aggressive linting for JDK 8.
```
<profiles>
		<profile>
			<id>Java 8</id>
			<activation>
				<jdk>1.8</jdk>
			</activation>
			<properties>
				<!-- Disable Java 8 overly strict javadoc linter when building with Java 8
					http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html
					-->
				<additionalparam>-Xdoclint:none</additionalparam>
			</properties>
		</profile>
	</profiles>
```

**Comment by sammefford** [comment]
I'm sorry, I haven't moved any changes over to 3.0-develop yet.  Could you check out from develop instead?  Sorry for the confusion.

**Comment by georgeajit** [comment]
Will this be fixed for 3.0 branch? Or should we change the milestone for this issue to "develop" and open a new one for 3.0, if it is going in.

Will verify with develop branch and post the results.

**Comment by sammefford** [comment]
I'm thinking we should overwrite the 3.0-develop branch from develop.  There's nothing on the develop branch that needs to be only for 4.x.

**Comment by georgeajit** [comment]
Tested on "develop" branch. The Java Docs Jar file is created. Was able to browse to class  pages after jar file extraction to a local directory.
