### ISSUE TITLE
ML Java Client v2.0.5 - POM dependency artifact version (ch.qos.logback v1.1.12) does not exist

### ISSUE THREAD

**Issue by davidbcollins** [marklogic/java-client-api#369]
http://developer.marklogic.com/maven2/com/marklogic/client-api-java/2.0.5/java-client-api-2.0.5.pom

The following dependency version does not exist:

```xml
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.1.12</version>
</dependency>
```

**Comment by sammefford** [comment]
That's not the right pom.xml.  The logback version was changed many months before that release.  I'm really confused where that pom.xml is coming from.  I'll track down an answer to that question.  Here's the released pom.xml: http://central.maven.org/maven2/com/marklogic/java-client-api/2.0.5/java-client-api-2.0.5.pom

You can get the 2.0.5 binary release here: http://developer.marklogic.com/download/binaries/java/MarkLogic-Java-API-2.0.5.zip or vi maven:

<dependency>
    <groupId>com.marklogic</groupId>
    <artifactId>java-client-api</artifactId>
    <version>2.0.5</version>
</dependency>
