### ISSUE TITLE
JAXB context should be cached for improved performance

### ISSUE THREAD

**Issue by robsman** [marklogic/java-client-api#371]
While doing some profiling I noticed a considerable amount of time is spent initializing JAXB context. In my scenario this mostly happens in the ctor of `QueryOptionsHandle` but other handles (e.g. `ValuesHandle`, `ValuesListHandle` and `TuplesHandle` seem to show a similar pattern).

According to the [JAXB maintainers](https://jaxb.java.net/guide/Performance_and_thread_safety.html) it is safe to create the JAXB context only once as long as threads use private marshaller/unmarshaller instances.

Any objections to push the JAXB context into a static member and only create marshaller/unmarshaller per handle instance? I would be glad to take this up.

**Comment by grechaw** [comment]
Looks like a good optimization to me.

**Comment by sammefford** [comment]
@robsman I agree, good suggestion.  I'll let you run with it since you volunteered.  Please make your changes on the develop branch.

**Comment by robsman** [comment]
Please see PR 433 addressing this. The change was performed against `3.0-develop` as `develop` seems to require 9.0-EA and I wasn't sure how much of a rolling baseline this is right now. Still, the commit merges cleanly into `develop`, too.

**Comment by sammefford** [comment]
Ok, I merged the PR.  Thanks for speaking up and even better, contributing!
