### ISSUE TITLE
browser window title is incorrect for the javadoc

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#379]
The default window title generated by the maven javadoc plugin has this form:

${pom.name} ${pom.currentVersion} API

Since we have "API" in our pom.name, that means we get a redundant title like this:

MarkLogic Java Client **API** 4.0 **API**

My proposal is to add a config property for "windowtitle" to override the default. We already do this for the "doctitle" property, which controls the title "banner" you see on the initial javadoc landing page. Like this:

```
diff --git "a/C:\\Users\\kcoleman\\AppData\\Local\\Temp\\TortoiseGit\\pom2CDB.tmp\\pom-756f055-left.xml" "b/C:\\git\\java-client-api\\pom.xml"
index 7f86883..65a975e 100644
--- "a/C:\\Users\\kcoleman\\AppData\\Local\\Temp\\TortoiseGit\\pom2CDB.tmp\\pom-756f055-left.xml"
+++ "b/C:\\git\\java-client-api\\pom.xml"
@@ -70,6 +70,7 @@
 					<overview>${basedir}/src/main/javadoc/overview.html</overview>
 					<show>public</show>
 					<doctitle>${javadoc-title}</doctitle>
+					<windowtitle>${javadoc-title}</windowtitle>
 					<use/>
 				</configuration>
 				<executions>
```

If we set windowtitle to the same variable, then at least they'll be consistent. Note that, depending on QA's release procedure, this proposal might still not end up with what you want, given the current definition of javadoc-title. 

All I ask is that we solve this in a way that makes it possible to override both doctitle and windowtitle from the maven command line, which implies using a config variable of some kind.

**Comment by sammefford** [comment]
Done.  Could you test?

**Comment by kcoleman-marklogic** [comment]
Sorry, I got dragged off to lunch, kicking and screaming, before I could explain why using "javadoc-title" might still not have quite desired result:

If you pull the download off DMC and look at the javadoc in that bundle, which gets generated as part of the standard build, the title (in the content) still includes the build date, like this:

MarkLogic Java Client API 3.0.4 2015-11-24

Maybe that's OK, maybe it's not. It is because "javadoc-title" is defined as follows in pom.xml:

```xml
<javadoc-title>${project.name} ${project.version} ${maven.build.timestamp}</javadoc-title>
```
QA modified project.version to remove the "SNAPSHOT", but maven.build.timestamp still gets in there.

This is not a problem for the version that ends up on docs.marklogic.com because I override the definition of "javadoc-title" on the maven command line, but it is the reason I temporized my suggested fix.

**Comment by kcoleman-marklogic** [comment]
I verified that the window title and the page title (in the content) are now consistent and can both be overridden from the command line. In the downloadable package, the text will now be as follows for both, instead of only for the page titie:

MarkLogic Java Client API *version* *datestamp*

If you're OK with that, this change can be propagated to other branches and the issue closed. (Note that that's what it was in the content before. Only the page title is different.)

If you're not OK with it, then QA might night to adjust their packaging build process or we'll need a different solution to the problem.

Returning to you for that decision, Sam.

**Comment by sammefford** [comment]
Kim, all sounds right here.  Do we need to do anything else to propagate this to other branches?  I'm thinking 3.0.5 and 4.x will pull from the develop branch.

**Comment by kcoleman-marklogic** [comment]
You should be able to propagate the change to 3.0-develop and any other branches safely, if that's your question. 

I think as long as it is only on develop like it is now, it will only affect 4.x and forward. S'up to you whether you think it is worth the effort of a backport.
