### ISSUE TITLE
typo: setOptimzeLevel should be setOptimizeLevel

### ISSUE THREAD

**Issue by xquery** [marklogic/java-client-api#380]

**Comment by grechaw** [comment]
This is actually fixed in develop already

**Comment by sammefford** [comment]
It looks to me like this is not fixed in develop.  Sorry I missed this...

**Comment by sammefford** [comment]
this is implemented both on develop and on 3.0-develop

**Comment by georgeajit** [comment]
Verified on develop and 3.0-develop. The typo has been fixed.
