### ISSUE TITLE
no hostId when writing 1 document

### ISSUE THREAD

**Issue by ltnd** [marklogic/java-client-api#381]
When writing 1 document with JAVA REST API 3.0.4, the cookie is never set with the hostId. In a cluster configuration, it causes the request to be routed to the wrong node (where the transaction does not exist).

Bug only on PUT : DocumentManager.write(uri...), not on POST : DocumentManager.write(writeSet...) The cookie (addHostCookie(builder, transaction)) is never set in the method JerseyServices.putPostDocumentImpl (method used when writing one document) For multiple documents (POST), the method used is JerseyServices.postResources() which call addHostCookie(builder, transaction);

**Comment by sammefford** [comment]
Thanks for reporting!  I've duplicated the issue.  I'm working on a fix.

**Comment by sammefford** [comment]
I'm going to try a simpler fix for this.  The fix I submitted before was the "wholistic fix" which included changes I needed to support #364.  But we're not ready to provide full QA for that as it would require testing on load balancers which are not yet integrated into our QA environment.  So I'll no create a minimal fix (like a hot fix) which you @ltnd  should be able to test.

**Comment by sammefford** [comment]
@ltnd could you build https://github.com/marklogic/java-client-api/tree/3.0.4.1-develop which contains 3.0.4 plus only this minimal fix and see if it resolves the issue for you?

**Comment by sammefford** [comment]
Since I've seen no response, I'll close this.  The full change is committed to the develop branch so it will ship in 8.0.5.
