### ISSUE TITLE
Flesh out SuggestDefinition

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#387]
SuggestDefinition is missing setQuery(QueryDefinition def) to enable the full functionality of search:suggest.  Adding this would also open up the possibility for client-side options (e.g. RawCombinedQueryDefinition) like we have opened with other aspects of the search API.

**Comment by maffelbaffel** [comment]
I'd also really appreciate if this would be implemented. At the moment, the java `suggest` api is kind of restricted in functionality. As soon as you have some kind of dynamic options, you need to have a xquery module. Are there any plans for this?

**Comment by maffelbaffel** [comment]
The REST API already supports this, wouldn't this be just like "adding another parameter and passing it through"? I see how Data Services are a lot more powerful, but require a lot more work and overhead. You kind of also force users to use Gradle.

**Comment by ehennum** [comment]
The feature is possible -- the concern is more that, for most adopters, it may not be that useful. In other words, it may have less priority.

As well as providing much more flexibility, Data Services require less overhead than the REST API.

We haven't received much pushback on the embrace of Gradle -- most Java developers seem to prefer it to Maven (or, farther back, Ant).  Is there a reason that Gradle is an obstacle in your environment?

**Comment by maffelbaffel** [comment]
We do use Gradle, but only for configuration/deployment purposes at the moment. Might change in the future, but I am not sure about this.

> Data Services require less overhead than the REST API
By less overhead, do you mean less performance overhead? I have not yet had the time to look into Data Services. Will definitely do this soon.
