### ISSUE TITLE
StructuredQueryBuilder output missing a namespace

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#388]
I've copied the following bug report that came in from another source.

I am using the StructuredQueryBuilder to build a structured query.  See below Java snippet.    

```
StructuredQueryBuilder qb = new StructuredQueryBuilder("default");  
StructuredQueryDefinition querydef = qb.containerConstraint("jobInstance", qb.valueConstraint("jobName", jobInstance.getJobName()));  
SearchHandle results = queryMgr.search(querydef, new SearchHandle());  
```

I already have a default options loaded in the database.  
default.xml  

```
< options xmlns="http://marklogic.com/appservices/search" >  
  < constraint name="jobInstance" >  
    < element-query name="jobInstance" ns="http://projects.spring.io/spring-batch" / >  
  < /constraint >  
  < constraint name="jobName" >  
    < value >  
        < element name="jobName" ns="http://projects.spring.io/spring-batch" / >  
    < /value >  
  < /constraint >  
< /options >  
```

The query that is generated is invalid because it is missing a namespace.  The problem is related to the lack of a default namespace.   

```
< query **xmlns:search="http://marklogic.com/appservices/search"** xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >  
    < container-constraint-query >  
        < constraint-name>jobInstance</constraint-name>  
        < value-constraint-query>  
            < constraint-name>jobName</constraint-name>  
            < text>sampleJob</text>  
        < /value-constraint-query>  
    < /container-constraint-query>  
< /query>
```

**Comment by sammefford** [comment]
I created the following class:

    public class Issue388 {
      public static void main(String[] args) {
        DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, "admin", "admin", DIGEST);
        StructuredQueryBuilder qb = new StructuredQueryBuilder("default");
        StructuredQueryDefinition querydef = qb.containerConstraint("jobInstance", qb.valueConstraint("jobName", "theJobName"));
    System.out.println("DEBUG: [Issue388.java] querydef.serialize()=[" + querydef.serialize()  + "]");
      }
    }

But it gives me the following output which does not duplicate the issue:

```
DEBUG: [Issue388.java] querydef.serialize()=[<query xmlns="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:search="http://marklogic.com/appservices/search" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><container-constraint-query><constraint-name>jobInstance</constraint-name><value-constraint-query><constraint-name>jobName</constraint-name><text>theJobName</text></value-constraint-query></container-constraint-query></query>]
Exception in thread "main" com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: No configured options: default
        at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2273)
        at com.marklogic.client.impl.JerseyServices.search(JerseyServices.java:2049)
        at com.marklogic.client.impl.JerseyServices.search(JerseyServices.java:2022)
        at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:198)
        at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:162)
        at Issue388.main(Issue388.java:14)
```

I'm using Java 1.8.0_71 on Windows 10.  Here's my minimized classpath.  I suspect there's something different about your classpath (like perhaps Woodstox on the classpath).

.;e:/installs/marklogic/java-client-api-3.0.4/lib/java-client-api-3.0.4.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/commons-codec-1.7.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/commons-logging-1.1.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-apache-client4-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-client-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-core-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-multipart-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/httpclient-4.1.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/httpcore-4.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/logback-core-1.0.12.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/slf4j-api-1.7.4.jar;C:/Users/Sam/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar;C:/Users/Sam/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.jar

**Comment by sammefford** [comment]
Thanks, Scott.  I noticed your build.gradle has woodstox 4.4.1 as a dependency.  So I added that to my classpath ...

export CLASSPATH=".;e:/installs/marklogic/java-client-api-3.0.4/lib/java-client-api-3.0.4.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/commons-codec-1.7.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/commons-logging-1.1.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-apache-client4-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-client-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-core-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/jersey-multipart-1.17.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/httpclient-4.1.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/httpcore-4.1.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/logback-core-1.0.12.jar;E:/installs/marklogic/java-client-api-3.0.4/lib/slf4j-api-1.7.4.jar;C:/Users/Sam/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar;C:/Users/Sam/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.jar;C:/Users/Sam/.m2/repository/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar;C:/Users/Sam/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar"

and I can now duplicate the issue.

**Comment by a-flammarion** [comment]
@sammefford we also do have woodstock in our classpath. We however need it as it is used by another dependency of our code.

What are our options?

Thanks.

**Comment by sammefford** [comment]
We have to dance around incompatibilities between the default XMLStreamWriter and the Woodstox XML stream writer.  In this case I found a way that works for both.  On line 2456 of StructuredQueryBuilder.java we just need to call writeStartElement with a namespace that matches the default namespace rather than no namespace.  I can do that, but in validating the fix I've found other querks due to using Woodstox, so I'm fixing those at the same time.

**Comment by a-flammarion** [comment]
Ok Awesome. Thanks. We'll wait on an update from you then.

**Comment by sammefford** [comment]
The fixes are done and all unit tests are passing with woodstox in the pom.xml as follows:

    <dependency>
      <groupId>org.codehaus.woodstox</groupId>
      <artifactId>woodstox-core-asl</artifactId>
      <version>4.4.1</version>
    </dependency>

and without woodstox in the pom.xml (default).

We now need to run this through regression tests before we can decide if it's ready to ship.  But anyone anxious to get the latest changes can always build the develop branch.

**Comment by a-flammarion** [comment]
@sammefford I've tested this with the develop branch (4.0-SNAPSHOT) and I am no longer seeing the issue I was seeing previously. The default namespace is added.

What's an ETA for this to be released?

**Comment by sastafford** [comment]
@sammefford, I was also able to confirm the fix using 4.0-snapshot.  Thanks for the assist.

**Comment by a-flammarion** [comment]
@Sam: can we have an eta?

Thanks.

**Comment by sammefford** [comment]
@Adrien I'm looking into that.  As you've confirmed, the fix is in github and available to you already.  But before we release & distribute it we want it to receive full QA.  If this is something urgent for you, please reach out to support@marklogic.com and they can help you escalate.

**Comment by grechaw** [comment]
Hi @a-flammarion , our release schedule is coordinated with the team that releases MarkLogic Server, and a date has not been set.  When this change goes into the 3.0-develop branch it will be available, and it's expected to release sometime mid-march with MarkLogic 8.0-5

**Comment by georgeajit** [comment]
Refer to https://github.com/marklogic/java-client-api/issues/390 for test/tasks done.
