### ISSUE TITLE
REGR - com.marklogic.client.test.SPARQLManagerTest.testInference test in Java API fails

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#393]
This is related to Bug Track Issue 35433. This code snippet produces empty results, instead of asserting null.

```
 gmgr.write("/ontology", new StringHandle(ontology).withMimetype("application/n-triples"));
        SPARQLQueryDefinition qdef = smgr.newQueryDefinition(
                "SELECT ?s { ?s a <http://example.org/C1>  }");
        qdef.setIncludeDefaultRulesets(false);
        StringHandle handle = new StringHandle().withMimetype(SPARQLMimeTypes.SPARQL_CSV);
        String results = smgr.executeSelect(qdef, handle).get();
        assertNull(results);
```

Sesame and Jena have similar issues with NullPointerException being thrown. 
See 
https://github.com/marklogic/marklogic-jena/issues/36

**Comment by grechaw** [comment]
I'll take a look, thanks.

**Comment by sammefford** [comment]
Ajit, what is the behavior you're expecting?  I'm thinking if we used to return null (if the snippet above used to work) that was less desirable than returning an empty result set (empty string in this case).

**Comment by georgeajit** [comment]
Need to run it through the Semantics QA person to see what their tests are expecting now. I think the old values were (null in this case) incorrect, as per the comments posted on the Bug Track Issue 35433.

**Comment by grechaw** [comment]
I'm just about set to reproduce -- I agree thuough that an empty results is preferable to null.  I'd like to know where we were previously returning null though.

**Comment by grechaw** [comment]
OK, the results did change.  This test now passes:
        assertEquals("%0D%0A", URLEncoder.encode(results, "utf8"));

So it's a   CR and LF.    This actually does not parse with the 'parseCsv' method so it may be a [different] bug than before.

**Comment by grechaw** [comment]
It seems that sparql results, even when empty, should have the header row.  I think I can fix this in the REST layer.

**Comment by grechaw** [comment]
Oh.  It occurs to me that, for empty results, we don't have access to the variables for a header row.  So the best we can do in this situation is exactly what we do here.   It's actually not ideal, but still where we are for sparql results until we have truly separate parse/execute steps.

**Comment by grechaw** [comment]
submitted a PR (assigned to @georgeajit ) with a test adjustment for this bug.

**Comment by grechaw** [comment]
Opened bug 38312 to address the issue of header row for CSV, and bindings for XML and JSON query results.

**Comment by grechaw** [comment]
Hi @georgeajit I just pushed changes that modified the test.  Passes in 3.0-develop and develop

**Comment by georgeajit** [comment]
The test passes. Verified on today's nightly run.
