### ISSUE TITLE
Seeing 38% Performance degradation in Performance tests for bulk read using eval

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#397]
Seeing 38 % Performance degradation in Performance tests for 
•	bulk read using eval :
          Actual = 0.5809 docs/ms (38% degradation )        ||   Baseline = 0.942 docs/ms 

For reference, see Email "9.0-ea2 Weekly Server Performance Report || 9.0-20160228" sent on 
Mon 3/7/2016 1:46 AM.

![bulkreadusingeval](https://cloud.githubusercontent.com/assets/8634482/13655096/d69a9448-e611-11e5-8c28-2738e3b71884.jpg)

**Comment by sammefford** [comment]
This problem appears to have been a one-off.  It hasn't continued in more recent performance reports.
