### ISSUE TITLE
Implement Double Precision and Geo Polygon Search

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#402]

**Comment by vivekmuniyandi** [comment]
public enum GeoSpatialOperator {
       EQUALS, DISJOINT, TOUCHES, CONTAINS, COVERS,
       INTERSECTS, WITHIN, COVEREDBY, CROSSES, OVERLAPS;
}

public interface GeospatialRegionIndex {
}

// Two methods added for region queries
public StructuredQueryDefinition geospatial(GeospatialRegionIndex index, GeoSpatialOperator operator, Region... regions)
public StructuredQueryDefinition geospatial(GeospatialRegionIndex index, GeoSpatialOperator operator, FragmentScope scope, String[] options, Region... regions)

// new method to create GeospatialRegionIndex to pass to the above functions
public GeospatialRegionIndex geoRegionPath(PathIndex pathIndex)

// new method which adds a geo spatial region constraint
public StructuredQueryDefinition geospatialRegionConstraint(String constraintName, GeoSpatialOperator operator, Region... regions)

// class for building a region constraint
class GeospatialRegionConstraintQuery extends AbstractStructuredQuery {
	GeoSpatialOperator operator;
	public GeospatialRegionConstraintQuery(String constraintName, GeoSpatialOperator operator, Region... regions) 
    public void innerSerialize(XMLStreamWriter serializer)
}

// base class for geo spatial queries
abstract class GeospatialBaseQuery extends AbstractStructuredQuery {
	GeospatialBaseQuery(FragmentScope scope, Region[] regions, String[] options)
}

// GeospatialQuery changed to GeospatialPointQuery
class GeospatialPointQuery extends GeospatialBaseQuery 

// class for constructing Geospatial region queries
class GeospatialRegionQuery extends GeospatialBaseQuery {
	GeoSpatialOperator operator;
    GeospatialRegionQuery(GeoRegionPathImpl index, GeoSpatialOperator operator, FragmentScope scope, Region[] regions, String[] options) 
	public void innerSerialize(XMLStreamWriter serializer)
}

// base class for creating path index implementation
private class GeoBasePathImpl extends IndexImpl {
    GeoBasePathImpl(PathIndex pathIndex)
    public void innerSerialize(XMLStreamWriter serializer)
}

// GeoPathImpl changed to GeoPointPathImpl
private class GeoPointPathImpl extends GeoBasePathImpl implements GeospatialIndex { 
    GeoPointPathImpl(PathIndex pathIndex) 
}

// Implementation class for Range path index
private class GeoRegionPathImpl extends GeoBasePathImpl implements GeospatialRegionIndex {
    GeoRegionPathImpl(PathIndex pathIndex)
}

**Comment by georgeajit** [comment]
Moving this task to EA4. Need to know how to generate index for Circle with @ , box with [] and Polygon in Java.

**Comment by vivekmuniyandi** [comment]
Ajit raised this issue https://github.com/marklogic/java-client-api/issues/466 and I have pointed him to the right unit tests for the same. 

QueryManager queryMgr = Common.client.newQueryManager();
StructuredQueryBuilder qb = new StructuredQueryBuilder();
String options[] = new String[1];
options[0] = "coordinate-system=wgs84/double";
StructuredQueryDefinition qdef;
qdef = qb.geospatial(qb.geoElementPair(qb.element("point"), qb.element("lat"), qb.element("lon")), null,
options, qb.box(0, 0, 10, 10));
SearchHandle results = queryMgr.search(qdef, new SearchHandle());

This is how we do it in the Java API. 

 public void testDoublePrecisionCoordinateSystem() and public void testDoublePrecision() in GeoSpatialRegionQueriesTest.java are the tests we have to look at. Thanks.

**Comment by georgeajit** [comment]
Test are available in develop branch. Please refer to ```TestDoublePrecisionGeoOps``` in the QA functional tests.
