### ISSUE TITLE
Add Kerberos Support

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#404]

**Comment by vivekmuniyandi** [comment]
// sample digest usage
DatabaseClient client =
  DatabaseClientFactory.newClient("localhost", 8012, new DigestAuthContext("admin", "admin"));

// sample kerberos+ssl usage
DatabaseClient client =
  DatabaseClientFactory.newClient("localhost", 8012, new KerberosAuthContext()
    .withSSLContext(sslContext));


DatabaseClientFactory {
  // keep these two
  newClient(String host, int port)
  newClient(String host, int port, String database)

  // add these two
  newClient(String host, int port, SecurityContext security)
  newClient(String host, int port, String database, SecurityContext security)

  // deprecate these which are rendered obsolete
  newClient(String host, int port, String user, String password, Authentication type) {
  newClient(String host, int port, String database, String user, String password,
    Authentication type) {
  newClient(String host, int port, String user, String password, Authentication type,
    SSLContext context) {
  newClient(String host, int port, String database, String user, String password,
    Authentication type, SSLContext context) {
  newClient(String host, int port, String user, String password, Authentication type,
    SSLContext context, SSLHostnameVerifier verifier) {
  newClient(String host, int port, String database, String user, String password,
    Authentication type, SSLContext context, SSLHostnameVerifier verifier) {
}

interface DatabaseClientFactory.SecurityContext {
  private SecurityContext() // you can only instantiate the subclasses
  SSLContext      getSSLContext()
  setSSLContext(SSLContext context)
  SecurityContext withSSLContext(SSLContext context)
  DatabaseClientFactory.SSLHostnameVerifier getSSLHostnameVerifier()
  setSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
  SecurityContext withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
}
DatabaseClientFactory.BasicAuthContext implements SecurityContext {
  BasicAuthContext(String user, String password)
  String getPassword()
  String getUser()
  BasicAuthContext withSSLContext(SSLContext context)
  BasicAuthContext withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
}
DatabaseClientFactory.DigestAuthContext implements SecurityContext {
  DigestAuthContext(String user, String password)
  String getPassword()
  String getUser()
  DigestAuthContext withSSLContext(SSLContext context)
  DigestAuthContext withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
}
DatabaseClientFactory.KerberosAuthContext implements SecurityContext {
  KerberosContext()
  KerberosContext(String externalName)
  KerberosAuthContext withSSLContext(SSLContext context)
  KerberosAuthContext withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
}
DatabaseClientFactory.CertificateAuthContext implements SecurityContext {
  CertificateAuthContext(?) // TBD
  CertificateAuthContext withSSLContext(SSLContext context)
  CertificateAuthContext withSSLHostnameVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)
}

DatabaseClientFactory.Bean {
  DatabaseClientFactory.Bean()

  // only four new methods
  String getExternalName()
  void   setExternalName(String externalName)
  // I missed adding database in ML8
  String getDatabase()
  setDatabase(String database)

  // deprecate the following which are now part of SecurityContext subclasses
  DatabaseClientFactory.Authentication      getAuthentication()
  SSLContext                                getContext()
  String                                    getPassword()
  String                                    getUser()
  DatabaseClientFactory.SSLHostnameVerifier getVerifier()
  setAuthentication(DatabaseClientFactory.Authentication authentication)
  setAuthenticationValue(String authentication)
  setContext(SSLContext context)
  setPassword(String password)
  setUser(String user)
  setVerifier(DatabaseClientFactory.SSLHostnameVerifier verifier)

  // the rest are unchanged
  DatabaseClientFactory.HandleFactoryRegistry getHandleRegistry()
  String                                      getHost()
  int                                         getPort()
  SecurityContext                             getSecurityContext()
  DatabaseClient newClient()
  registerDefaultHandles()
  setHost(String host)
  setPort(int port)
  setSecurityContext(SecurityContext context)
}

// the following are necessary for DMSDK to create cloned clients pointed to a different host
DatabaseClient {
  String          getHost()
  int             getPort()
  String          getDatabase();
  SecurityContext getSecurityContext()
}

@Deprecated DatabaseClientFactory.Authentication

**Comment by georgeajit** [comment]
Have checked in TestDatabaseClientWithKerberos.java. The test runs fine on platforms where Kerberos Client Tools have been installed in MarkLogic QA test harness' nightly runs.
