### ISSUE TITLE
copyright year is incorrect in pom.xml

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#407]
The problem is here:

https://github.com/marklogic/java-client-api/blob/3.0-develop/pom.xml#L65

It causes the javadoc to have an incorrect copyright in the footer, so we need to address it before releasing 3.0.5.

**Comment by sammefford** [comment]
Ajit, no new tests needed here.  Just know I modified most files but only in comments or docs, so no code should have changed or broken.  Let me know if I'm wrong.

**Comment by sammefford** [comment]
I made the change on both develop and 3.0-develop branches.

**Comment by georgeajit** [comment]
Do we need this change to go into the Tests?

**Comment by sammefford** [comment]
good idea, Ajit.  I'd say yes.

**Comment by georgeajit** [comment]
Verified today's regression. There are no issues related to this change. Verified the POM file from today's build (using mvn commands) in QA regression / build system, it has 2016 in the copyrights section.

**Comment by kcoleman-marklogic** [comment]
I also verified that the javadoc generated by last night's doc build picked up the correct copyright, t hanks to this change.
