### ISSUE TITLE
Document properties are not removed when the DocumentMetadataHandle.DocumentProperties is cleared.

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/java-client-api#408]
How to reproduce?

1. Add a property to any document.
2. Load the document and property using java API.
3. Clear the properties (set to null)
4. And save the document along with properties. 
5. Properties are not removed from the document.

**Comment by sammefford** [comment]
This is expected behavior.  DocumentProperties can add or update properties but not remove them.

To remove properties, see DocumentMetadataPatchBuilder.deleteProperty.  There are examples in GenericDocumentTest and JSONDocumentTest.

**Comment by sanjuthomas** [comment]
@sammefford  Thank You!

**Comment by sammefford** [comment]
Anytime!
