### ISSUE TITLE
clean out master branch to only a README.md

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#409]
To avoid confusion we'll clean out the master branch to have only a README.md file explaining what the other branches are.  We've changed the default branch to currently be 3.0-master since that's our most recent release.  Since different git methodologies treat master differently, we'll side-step the issue and not use master.

**Comment by sammefford** [comment]
Due to bug load right now, I need to push this to 4.0.1

**Comment by georgeajit** [comment]
Verified the master branch.
