### ISSUE TITLE
DatabaseClient reuse in examples

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#411]
There seems to be lots of confusion about if/how/when you reuse a `DatabaseClient`. Each of the examples that we ship is designed to be independent. However, this gives the impression that you need to create a new `DatabaseClient` for each request. We should put a note in each example to disabuse copy-pasters of this notion.

**Comment by sammefford** [comment]
Due to bug load right now, I need to push this to 4.0.1

**Comment by sammefford** [comment]
This is no longer necessary since we've decoupled DatabaseClient from the http connection pool in 3.0.8 and 4.0.2 https://github.com/marklogic/java-client-api/issues/470
