### ISSUE TITLE
Send forest-name parameter through on queries when it's set on QueryManager

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#412]
Data movement needs the ability to run forest-specific queries.  We've added the capability to the REST layer.  Now the Java client API layer needs to pass along the forest-name parameter to queries when the forest is set on QueryManager.

**Comment by sammefford** [comment]
We'll no longer be setting it on DatabaseClient (see #418) but we will still need to test that when we set it on QueryManager that it works.  So I'll change the title and summary of this issue.

**Comment by georgeajit** [comment]
see #418

**Comment by sammefford** [comment]
Yeah, this is somewhat a dup of #418.
