### ISSUE TITLE
Add support for metadata

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#413]
We need to support the new name-value string pairs called metadata just like we already support document properties, quality, permissions, and collections

**Comment by vivekmuniyandi** [comment]
DocumentMetadataHandle {
    DocumentMetadataHandle.DocumentMetadataValues getMetadataValues()
    setMetadataValues(DocumentMetadataHandle.DocumentMetadataValues map)
    withMetadataValue(String name, String value)
}

DocumentMetadataHandle.DocumentMetadataValues extends Map<String,String> {
    put(String name, String value)
    // all the other Map methods
}

DocumentMetadataPatchBuilder {
    addMetadataValue(String name, String value)
    deleteMetadataValue(String name)
    replaceMetadataValueApply(String name, DocumentMetadataPatchBuilder.Call call)
    replaceMetadataValue(String name, String newValue)
}

The public methods to test are

DocumentManager.readMetadata  // 2 overloads
DocumentManager.read          // 8 overloads
DocumentManager.readAs        // 2 overloads
BinaryDocumentManager.readAs
BinaryDocumentManager.read    // 8 overloads
DocumentRecord.getMetadata
DocumentWriteOperation.getMetadata
DocumentWriteSet.add          // 2 overloads
DocumentWriteSet.addDefault
DocumentManager.create        // 4 overloads
DocumentManager.createAs      // 2 overloads
DocumentManager.write         // 8 overloads
DocumentManager.writeAs       // 2 overloads
DocumentManager.writeMetadata // 2 overloads
TemporalDocumentManager.write // 6 overloads
