### ISSUE TITLE
Remove forestName from DatabaseClientFactory, add to QueryManager

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#418]
I recently added newClient overloads to DatabaseClientFactory on the assumption it would help data movement SDK devs to have a DatabaseClient already pointed at he forest for the batch.  While this is true of a DatabaseClient already pointed to the host for the batch, forest has a drawback.  I don't want devs to be surprised if their queries don't match the expected results because they didn't realize their query is scoped to only one forest.

For example, if I insert two documents:
A.xml ends up in forest1
B.xml is related to A.xml but ends up in forest2

Then I run 

```
dmMgr.start(
  dmMgr.newQueryHostBatcher(query1)
    .onUrisReady( (client, batch) ->
      for ( DocumentRecord doc : client.newDocumentManager().search(query2) ) {
        // do something with each matching doc
      }
)
```

where query1 matches B.xml and query2 matches A.xml.  Devs would be surprised that query2 would not match B.xml since B.xml is in forest2 but client is limited to matches in forest1.

Instead, I'll make client just point to the correct host for the batch so queries will be slightly more efficient.  But if they want to restrict subsequent searches to a particular forest they'll need to create a new DocumentManager or QueryManager and call setForestName on that instance, then run their search.

**Comment by sammefford** [comment]
I was tempted to avoid get/setForestName on DocumentManager and QueryManager because not all operations performed by those will currently be restricted to a forest since most underlying REST endpoints don't support the forest-name parameter.  For example, any read* or delete* will not be scoped to a forest.

But my main concern with only including this where it will be used is the explosion of method overloads it would create.  Here's what we'd need to add:

    DocumentManager {
      DocumentPage search(QueryDefinition querydef, long start, String forestName)
      DocumentPage search(QueryDefinition querydef, long start, SearchReadHandle searchHandle, String forestName)
      DocumentPage search(QueryDefinition querydef, long start, SearchReadHandle searchHandle, Transaction transaction, String forestName)
      DocumentPage search(QueryDefinition querydef, long start, Transaction transaction, String forestName)
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, String forestName)
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, ServerTransform transform, String forestName)
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, ServerTransform transform, Transaction transaction, String forestName)
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, Transaction transaction, String forestName)
      write(String docId, W contentHandle, String forestName)
      write(String docId, W contentHandle, ServerTransform transform, String forestName)
      write(String docId, W contentHandle, ServerTransform transform, Transaction transaction, String forestName)
      write(String docId, W contentHandle, Transaction transaction, String forestName)
      writeAs(String docId, DocumentMetadataWriteHandle metadataHandle, Object content, String forestName)
      writeAs(String docId, DocumentMetadataWriteHandle metadataHandle, Object content, ServerTransform transform, String forestName)
      writeAs(String docId, Object content, String forestName)
      writeAs(String docId, Object content, ServerTransform transform, String forestName)
    }

    TemporalDocumentManager {
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, ServerTransform transform, Transaction transaction, String temporalCollection, String forestName)
      write(String docId, DocumentMetadataWriteHandle metadataHandle, W contentHandle, ServerTransform transform, Transaction transaction, String temporalCollection, Calendar systemTime, String forestName)
    }

    QueryManager {
      search(QueryDefinition querydef, T searchHandle, String forestName)
      search(QueryDefinition querydef, T searchHandle, long start, String forestName)
      search(QueryDefinition querydef, T searchHandle, long start, Transaction transaction, String forestName)
      search(QueryDefinition querydef, T searchHandle, Transaction transaction)     }
      tuples(ValuesDefinition valdef, T tupleHandle, String forestName)
      tuples(ValuesDefinition valdef, T tupleHandle, long start, String forestName)
      tuples(ValuesDefinition valdef, T tupleHandle, long start, Transaction transaction, String forestName)
      tuples(ValuesDefinition valdef, T tupleHandle, Transaction transaction, String forestName)
      values(ValuesDefinition valdef, T valueHandle, String forestName)
      values(ValuesDefinition valdef, T valueHandle, long start, String forestName)
      values(ValuesDefinition valdef, T valueHandle, long start, Transaction transaction, String forestName)
      values(ValuesDefinition valdef, T valueHandle, Transaction transaction, String forestName)
      valuesList(ValuesListDefinition valdef, T valueHandle, String forestName)
      valuesList(ValuesListDefinition valdef, T valueHandle, Transaction transaction, String forestName)
    }

Instead, I'm more comfortable just adding:

    QueryManager {
      String getForestName()
      void setForestName()
    }

Plus, DocumentManager has had get/setForestName for many years, so it's an established pattern.  The only new thing is QueryManger get/setForestName, which will apply to findOne, search, tuples, values, and valuesList operations.  Even delete might be covered since it still goes to the search endpoint.  If they specify a RawQueryByExampleDefinition which hits the qbe endpoint it will still support the forest-name parameter.  I do not believe we need forest-name to affect the convert, optionsList, or validate operations.  Given this context, I think it's straightforward to add get/setForestName to QueryManager.

DocumentManager, on the other hand, may be more confusing for devs since only single-document write* methods and search methods will support the forest-name endpoint.  write(DocumentWriteSet) will not support the forest-name endpoint since it's not supported for bulk (POST) payloads at the REST layer.  Yet DocumentManager.search will limit results based on the forestName.  But as I mentioned, DocumentManager.get/setForestName has been there for some time, so even if we decided to remove it we'd need to first deprecate it.  For now I'll leave it there since it's consistent with what I'd like to do with QueryManager.

**Comment by kcoleman-marklogic** [comment]
How will this interact with the forest query option? This guy:

http://docs.marklogic.com/guide/search-dev/appendixa#id_97358

**Comment by sammefford** [comment]
The rest side of this generates those, server-side.

**Comment by kcoleman-marklogic** [comment]
Sorry, I should have been less vague. That's an extant query option. Users can already set it themselves. 

If I use QueryManager.setForestName, is that equivalent to setting it in my query options? Does it replace what I might have in my query options, or vice versa? Or does it merge them in some fashion?

Just because you're adding it on behalf of DMSDK does not mean that's the only way it has been or will be used, so I just wanted to understand the expected interaction with the exist forest placement/scoping capabilities.

**Comment by sammefford** [comment]
> If I use QueryManager.setForestName, is that equivalent to setting it in my query options?

Yes.  The REST side adds those to your query options.

> Does it replace what I might have in my query options, or vice versa? Or does it merge them in some fashion?

It just adds <search:forest> elements.  So if you already have the same forest elements, they'll be there twice.  And if you have other forest elements you'll now have more.

> Just because you're adding it on behalf of DMSDK does not mean that's the only way it has been or will be used, so I just wanted to understand the expected interaction with the existing forest placement/scoping capabilities.

Yes, of course.  Thank you for asking!  And if I'm still leaving gaps, please don't hesitate to keep asking until I provide clear answers.

**Comment by kcoleman-marklogic** [comment]
That is clear. Thank you, Sam.

**Comment by sammefford** [comment]
Two things have changed:

1. we don't want to write with forestName
2. while I can see a need to search a forest, it's less of a need to export full documents from a forest because one can just read a batch of documents from one forest by ids obtained from the search result
3. the need to get values or tuples from a forest is very niche, and can be supported by eval or server-side scripts

Therefore we don't need to support the write methods on DocumentManager, the bulk search methods on DocumentManager, nor the values or tuples methods on QueryManager.  That means the only methods we're enabling here with forestName are:

```
QueryManager {
  search(QueryDefinition querydef, T searchHandle, String forestName)
  search(QueryDefinition querydef, T searchHandle, long start, String forestName)
  search(QueryDefinition querydef, T searchHandle, long start, Transaction transaction, String forestName)
  search(QueryDefinition querydef, T searchHandle, Transaction transaction, String forestName)
}
```

Somehow that strikes me as few enough overloads that I'm ok just adding them and avoiding the confusion that would come with adding set/getForestName on QueryManager.  Also, since get/setForestName on DocumentManager never worked, let's just remove those to avoid confusion.

**Comment by georgeajit** [comment]
Did a pull of the latest and built all jars. Java Docs do not have the set and get methods. Test TestSearchMultipleForests corrected and added.
```
queryMgr.search(querydef, sHandleOnForest1, fNames[0]);
```

**Comment by sammefford** [comment]
Yes, javadocs are not ready yet.

**Comment by georgeajit** [comment]
Sam,  Can you confirm that the required Java Docs will be available for EA3?

**Comment by sammefford** [comment]
I'm not sure what I meant by javadocs are not ready yet.  It looks like my commit had the javadocs for the modified search methods with it.  I'm also not sure what your comment means, Ajit, "Java Docs do not have the set and get methods".  

In any case, I see that you are testing the three-argument version of QueryManager.search.  Would it make sense to also test the three other overloads?

**Comment by georgeajit** [comment]
This will be tested in EA4.

**Comment by georgeajit** [comment]
Test in Post EA4.
