### ISSUE TITLE
Support point-in-time queries

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#420]
To support a DMSDK requirement for point-in-time queries, REST will support point-in-time query on the following endpoints:
-     /v1/qbe
-     /v1/search
-     /v1/values/{name}
-     /v1/graphs?graph={graph}
-     /v1/graphs?default=
-     /v1/graphs/sparql
-     /v1/rows
-     /v1/documents

Java Client API should also support these capabilities.  Since QueryHostBatcher is designed to allow clients to do any operation they want on each batch of matching uris, they will use Java Client API to read documents, update them, delete them, etc.

**Comment by sammefford** [comment]
The only way to get the opaque server timestamp value required for subsequent requests is to first make a request.  REST will provide the timestamp as a response header.  We need a way to surface this timestamp through the java client.  Even the following simple methods need a way to surface the server timestamp:

    <T extends AbstractReadHandle> T DocumentManager.read  (String uri, T handle)
    <T extends TriplesReadHandle>  T GraphManager   .read  (String uri, T handle)    
    DocumentPage                     DocumentManager.search(QueryDefinition query, long start)
    <T extends SearchReadHandle>   T QueryManager   .search(QueryDefinition query, T handle)
    <T extends TuplesReadHandle>   T QueryManager   .values(ValuesDefinition query, T handle)
    <T extends ValuesReadHandle>   T QueryManager   .values(ValuesDefinition query, T handle)
    
We could restrict the availability of the timestamp to calls which return DocumentPage, SearchHandle, TuplesHandle, and ValuesHandle.  But that does not offer a solution for DocumentManager.read nor GraphManager.read which can not be used with any of those specific handles.  

Therefore I propose we make the timestamp available on any handle which implements 

    PointInTimeHandle<H> {
        String getServerTimestamp()
        H withServerTimestamp(String timestamp)
    }

We can make all built-in handles implement this interface.  This will be a consistent and easy way to retrieve the server timestamp from the response to any of the above methods.  This will also offer an easy and consistent way to specify the timestamp to any of the above methods.      While one might expect to provide the timestamp as part of the query, that's not the way the REST API is implemented and that is not possible on DocumentManager.read nor GraphManager.read which do not and will not have a query argument.  

Does anyone see a better API option?

**Comment by sammefford** [comment]
I'm realizing my proposal doesn't address the simplest DocumentManager.search(QueryDefinition, long) since there is no handle argument.  We could require they use DocumentManager.search(QueryDefinition, long, SearchReadHandle) ...

**Comment by sammefford** [comment]
Erik proposed we could follow the model of optimistic write using DocumentDescriptor.setVersion.  If we did, we would obviously need to do the same on QueryDefinition and ValuesDefinition.  I like that idea for query/read requests, however, we would still need to find a solution to get the timestamp from query/read responses.  I think that would lead us directly back to the original proposal where we add a getServerTimestamp() method to all handles.  Is it better to read the server timestamp from the handles but then send the server timestamp via DocumentDescriptor, QueryDefintion, or ValuesDefinition?

**Comment by ehennum** [comment]
ContentDescriptor bundles up some gettable / settable properties of handles, which inherit from ContentDescriptor.

Would it be consistent to call this a TimestampedContentDescriptor and derive ContentDescriptor from it (assuming that anything that can be timestamped also can have a mimetype)?

**Comment by sammefford** [comment]
Great idea.  That sounds similar to what we did with TemporalDescriptor, except that extends ContentDescriptor.  I think we can go ahead and add 

    interface TimestampedContentDescriptor {
        String getServerTimestamp()
        void setServerTimestamp(String timestamp)
    }

I'm hesitant to make ContentDescriptor extend it on the odd chance that someone has implemented ContentDescriptor and would now have their builds break until they add these methods.  Instead, I propose we have BaseHandle implement this interface which will trickle it down to all the handles we've created.

**Comment by sammefford** [comment]
On further reflection, I'm not seeing a need for another interface, so I'll scrap TimestampedContentDescriptor and instead just add the methods to BaseHandle so then all our handles will have them.

**Comment by sammefford** [comment]
Ok, this is all implemented except for /v1/values and /v1/rows.  We'll add support for those later.

**Comment by georgeajit** [comment]
Have written basic test and other stubs. Will flesh out the test when Git 457 is completed. Assigning this back to development.

**Comment by sammefford** [comment]
Can we make a few tweaks to the basic tests?
1. use getServerTimestamp not getPointInTimeQueryTimestamp (that's for internal use only, like everythign in the impl package)
2. could we try reading the document after update using insTimeStamp and verify that we don't see the update?
3. why is the test looking at fragment counts?  I'm not seeing a need for that.
4. why is the test looking at whether the patch update worked?  I'm not seeing a need for that.
5. I see the comment "Sleep for some time. Read again with new point In time."  that seems like a good idea, but I don't think it will work if nothing else is updating the db because I'm not sure the server timestamp advances unless something performs an update.  
6. in general, let's not wait for 457 as that's a separate round of development.  Can we dig in and verify what we have and that it works even if it's not polished?

**Comment by georgeajit** [comment]
Thanks Sam, Will work on the review comments.

**Comment by georgeajit** [comment]
Have changed the test to verify:
use getServerTimestamp not getPointInTimeQueryTimestamp (that's for internal use only, like everythign in the impl package)
could we try reading the document after update using insTimeStamp (pass via setServerTimestamp on the read handle) and verify that we don't see the update?

I have left the fragment counts check. Based on how #457 is fleshed out, might remove them later.
