### ISSUE TITLE
Some of the read handlers do not populate properly formats and mime-types

### ISSUE THREAD

**Issue by miguelrgonzalez** [marklogic/java-client-api#421]
Currently It's not possible to retrieve format and mime-types properties for a known resource in MarkLogic.

  RequestParameters params = new RequestParameters();
  params.put("uri", uri);
  ReaderHandle output = this.getServices().get(params, new ReaderHandle()); //FileHandle behaves the same
  logger.debug("Returning document with type : " + output.getMimetype());

This code is calling a rest extension which I verified is setting the content type accordingly:

  HTTP/1.1 200 OK
  Content-type: application/xml; charset=UTF-8
  Server: MarkLogic
  Content-Length: 74
  Connection: Keep-Alive
  Keep-Alive: timeout=5

**Comment by georgeajit** [comment]
Tested  getFormat()  and getMimetype() on a Handle (JacksonHandle) that reads the list of resource service extensions installed on the server.
