### ISSUE TITLE
Remove logback dependency

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#424]
We wisely use slf4j so our customers can choose their preferred logging framework (log4j, commons logging, java.util.logging, or logback). But we mistakenly include logback-classic in our pom.xml dependencies, thus forcing our clients to use logback-classic. This is incorrect usage of slf4j according to this page: http://www.slf4j.org/manual.html

We should remove logback-classic from our pom.xml. While at it, we should see if we can remove commons-logging.

**Comment by georgeajit** [comment]
Verified the POM file.
