### ISSUE TITLE
REGR: FileHandle getByteLength method doe not return length of the content in bytes.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#431]
Here is the test snippet that uses extensions manager to store a binary file and then read it back. Then after a read back getByteLength method returns -1. 
Tested on MarkLogic 9.0 Server Build 20160722.
 
Tried to use a ReaderHandle instead with proper FORMAT, that also returns the length as -1
```
// read it back
//FileHandle f = new FileHandle(new File("src/test/java/com/marklogic/client/functionaltest/data/binary.jpg"));
ReaderHandle f = new ReaderHandle(new FileReader(new File("src/test/java/com/marklogic/client/functionaltest/data/binary.jpg"))).withFormat(Format.BINARY);
f.close();
```
Here is the test.
```
public void testXQueryModuleCRUDBinaryFile() throws KeyManagementException, NoSuchAlgorithmException, IOException {
		
		DatabaseClient client = getDatabaseClient("rest-admin", "x", Authentication.DIGEST);
		
		// get a manager
		ExtensionLibrariesManager libsMgr = client.newServerConfigManager().newExtensionLibrariesManager();
		
		String Path = "/ext/my/path/to/my/module.xqy";
		
		// write XQuery file to the modules database
		libsMgr.write(Path, new FileHandle(new File("src/test/java/com/marklogic/client/functionaltest/data/binary.jpg")).withFormat(Format.BINARY));

		// read it back
			FileHandle f = new FileHandle(new File("src/test/java/com/marklogic/client/functionaltest/data/binary.jpg"));
		assertEquals(f.getByteLength(),libsMgr.read(Path, new StringHandle()).getByteLength());
		
		// get the list of descriptors
		ExtensionLibraryDescriptor[] descriptors = libsMgr.list();
		assertEquals("number of modules installed", descriptors.length, 1);
		
		for (ExtensionLibraryDescriptor descriptor : descriptors) {
			assertEquals(descriptor.getPath(), Path);
		}

		// delete it
		libsMgr.delete(Path);
		
		try {
			// read deleted module
		    libsMgr.read(Path, new StringHandle()).get();
		} catch (ResourceNotFoundException e) {
			// pass;
		}
		
	}
```

**Comment by sammefford** [comment]
Yeah, getByteLength is only populated when reading something from the server, not when reading it from anything local.  I'll update the javadoc to say this.  You'll notice that the getByteLength of the handle you read from libsMgr is populated.

On a related topic: do we need to test sending a binary to ExtensionLibrariesManager?  That doesn't seem like a valid use case to me.

**Comment by kcoleman-marklogic** [comment]
> On a related topic: do we need to test sending a binary to ExtensionLibrariesManager? That doesn't seem like a valid use case to me.

It is a valid use case, assuming this is the wrapper around /v1/ext. That endpoint is for sticking pretty much anything in the modules database, and there's not reason one of the assets required by an extension can't be, for example, an image or a 3rd party library.

**Comment by sammefford** [comment]
I believe you, but I'd like to understand.  Why would one stick an image in the modules database?  I totally understand why install a 3rd-party library.

**Comment by kcoleman-marklogic** [comment]
If you don't like image, [consider video](http://docs.marklogic.com/guide/app-dev/binaries#id_64526). It doesn't really matter if it is an image, a video, a library, or a zip file. It's all binary at the end of the day. In for a penny, in for a pound.

When these interfaces were added, we had no database param on the CRUD endpoints, so this was the only way to interact with the modules db remotely. Though the motivation for adding the endpoint was managing required assets for REST extensions, it's just modules db CRUD, when all is said and done.

**Comment by sammefford** [comment]
Hmm, maybe I'm just blind on this subject.  I still can't understand the valid reason to insert a video or a zip file or any binary into the modules database.  Server-side code can't directly import code libraries contained in a zip file can it?  In any case, it's ok if I can't see it.  If you both think there's a valid use case and we should test it, I can support that.
