### ISSUE TITLE
Fix support for Date range queries

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#437]
Right now the following does not match anything but it should match the lion:

    catRepo.write(new ManagedCat("houseCat", 10, new Date()));
    Date inBetween = new Date();
    catRepo.write(new ManagedCat("lion", 45, new Date()));

    PojoQueryDefinition newestCatQuery =
        catRepo.getQueryBuilder().range("created", GE, inBetween);
    for ( Cat cat : catRepo.search(newestCatQuery, 1) ) {
      System.out.println("cat=[" + cat + "]");
    }

Where Cat is:

```
public class Cat {
    private String id;
    private int averageHeight;
    private Date created;

    public Cat() {}

    public Cat(String id, int averageHeight) {
        this.id = id;
        this.averageHeight = averageHeight;
    }

    public Cat(String id, int averageHeight, Date created) {
        this.id = id;
        this.averageHeight = averageHeight;
        this.created= created;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getAverageHeight() {
        return averageHeight;
    }

    public void setAverageHeight(int averageHeight) {
        this.averageHeight = averageHeight;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created= created;
    }

    public String toString() {
        return "id=[" + id + "] averageHeight=[" + averageHeight +
            "] created=[" + created + "]";
    }
}
```

And ManagedCat is:

```
public class ManagedCat extends Cat {
    public ManagedCat(String id, int averageHeight, Date createdDate) {
        super(id, averageHeight);
        super.setCreated(createdDate);
    }

    @Id
    @Override
    public String getId() {
        return super.getId();
    }

    @PathIndexProperty(scalarType = ScalarType.STRING)
    @Override
    public int getAverageHeight() {
        return super.getAverageHeight();
    }

    @JsonTypeInfo(use=JsonTypeInfo.Id.NONE, include=JsonTypeInfo.As.EXTERNAL_PROPERTY)
    @PathIndexProperty(scalarType = ScalarType.DATE)
    @Override
    public Date getCreated() {
      return super.getCreated();
    }
}
```

**Comment by sammefford** [comment]
There are two immediate work-arounds:
1) use a numeric timestamp (range index scalar type=long) instead of Date (range index scalar type=dateTime)
2) override java.util.Date.toString so it prints an ISO 8601 formated date string, like so:

    catRepo.write(new ManagedCat("houseCat", 10, new Date()));
    Calendar cal = Calendar.getInstance();
    Date inBetween = new java.util.Date() {
      public String toString() {
        return DatatypeConverter.printDateTime(cal);
      }
    };
    catRepo.write(new ManagedCat("lion", 45, new Date()));

    PojoQueryDefinition newestCatQuery =
        catRepo.getQueryBuilder().range("created", GT, inBetween);
    for ( Cat cat : catRepo.search(newestCatQuery, 1) ) {
      System.out.println("cat=[" + cat + "]");
    }

**Comment by sammefford** [comment]
Ajit, see the unit test and index config in bootstrap.xqy I added for an example of how to setup a date range query with a Date or Calendar type.

**Comment by sammefford** [comment]
Ajit, can you make sure to test this with range index queries and pass in both Date and Calendar types?  As I look at the commit, it looks like my implementation failed to account for passing in a Date.

**Comment by sammefford** [comment]
Oh, haha, I see how I accounted for Date.  Oh well, if you test it anyway we'll be sure :)

**Comment by georgeajit** [comment]
Test Committed for Calendar type  in 3.0-develop https://github.com/marklogic/java-client-api/commit/4c332a4a0328062b40a33d691e9bea6522a0cae6

A similar test with Date type will be committed.

**Comment by georgeajit** [comment]
Commit for develop branch https://github.com/marklogic/java-client-api/commit/b0a111302bc8db1b3be63e81b08175cc958badce
