### ISSUE TITLE
initial JavaDoc for the Optic API

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#455]
Core classes need some initial JavaDoc

**Comment by ehennum** [comment]
JavaDoc for the row package should be complete -- also the expression/XsValue, RdfValue, and SemValue interfaces

**Comment by georgeajit** [comment]
Did an initial read and check on the new Classes and methods. But could like to spend more time in digging through the text.
Moving the task into EA4.

**Comment by georgeajit** [comment]
Did a check on classes and methods.
