### ISSUE TITLE
Flesh out point-in-time query

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#457]
In #420 we added support for point-in-time queries to support DMSDK requirement for pagination and export at a consistent snapshot.  But since the new methods are public, we should flesh out the implementation.
1. support /v1/values
2. support /v1/rows
3. support /v1/graphs
4. add a simple way to get the server timestamp (right now you have to do a search or a read)
5. throw an error if a handle is sent to a write method with a server timestamp set (since that's not allowed)

**Comment by sammefford** [comment]
Also, take a look at why we need the "long serverTimestamp" parameter on DocumentManager.search but not QueryManager.search . . . I can understand why we need it on the DocumentManager bulk read methods, because we don't pass those a QueryDefinition.  But it seems like that parameter is unnecessary on DocumentManager.search because we could set the server timestamp on the QueryDefinition.

**Comment by sammefford** [comment]
We'll be hiding this feature in 9.0.1, so QA won't need to write any tests.

**Comment by georgeajit** [comment]
Note to QA: Please write tests in ```TestPointInTimeQuery.java```
