### ISSUE TITLE
Client object details returned as null when using certificate based authentication

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#459]
I just want to bring to attention that once client object is obtained after authenticating with certificate, the client object returns null for the following methods. I just wanted to make sure if this is by design.

```
 client = DatabaseClientFactory.newClient("hp1040-3505.marklogic.com", 8009, new CertificateAuthContext(getSslContext("C:/tmp/test.p12","abc")));
    System.out.println(client.getUser());
    System.out.println(client.getPassword());
    System.out.println(client.getDatabase());
```

**Comment by vivekmuniyandi** [comment]
Java API doesn't have any way to get the username, password and database unless the user who creates the client passes while creating the authentication context. For certificate based authentication, we certainly rely on certificates and the username, password would be null. The database would certainly be null unless you use the appropriate overload to create a client with database variable passed as well. Thanks.
