### ISSUE TITLE
Need coordSystem method on StructuredQueryBuilder to set Geo coordinate system

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#466]
In a QA functional test, we were trying to set the coordinate system to 

```
wgs84/double
```

in a RegionPathIndex and the test throws exception when a search is executed.

REST and XQuery supports "wgs84/double" coordinate system. But client APIs do not. However on NodeJS client they have a method on query builder to provide the coordinate system as an option. See the NodeJS script below for 

```
q.coordSystem('wgs84/double')
```

Here is a NodeJS test script that sets this option in the builder.

```
var q = marklogic.queryBuilder;
...
...
..

it('TEST 3 - geospatial region box contains polygon', function(done){
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/box', q.coordSystem('wgs84/double')),
          'contains',
          q.polygon(q.point(-5, -70), q.point(4, -70), q.point(3, -60), q.point(-3, -65), q.point(-5, -70))
        )
      )
    ).
    result(function(response) {
      //console.log(JSON.stringify(response, null, 2));
      response.length.should.equal(2);
      response[0].uri.should.equal('/geo/region/test/Equator.xml');
      response[1].uri.should.equal('/geo/region/test/Equator-json.json');
      done();
}, done);
```

Now executing a Java test after a range index of this type has been setup for a database will not work and could throw an exception.

The REST payload used to create the GeoSpatial Region Path Index is

```
"geospatial-region-path-index": 
     * [
        {
          "path-expression": "/root/item/box",
          "coordinate-system": "wgs84/double",
          "geohash-precision": 2,
          "invalid-values": "reject"
         }
       ]
```

The Java test used is

```
public void testBoxContainsPolygon() throws KeyManagementException, NoSuchAlgorithmException, IOException, ParserConfigurationException, SAXException, XpathException, TransformerException
    {   
        System.out.println("Running testBoxContainsPolygon");
        client = getDatabaseClient("rest-admin", "x", Authentication.DIGEST);

        QueryManager queryMgr = client.newQueryManager();

        // create query def
        StructuredQueryBuilder qb = queryMgr.newStructuredQueryBuilder();
        StructuredQueryDefinition t = qb.geospatial(qb.geoRegionPath(qb.pathIndex("/root/item/box")), GeoSpatialOperator.CONTAINS, 
                qb.polygon(qb.point(-5,-70), qb.point(4, -70), qb.point(3, -60), qb.point(-3, -65), qb.point(-5,-70)));
        // create handle
        JacksonHandle resultsHandle = new JacksonHandle();
        queryMgr.search(t, resultsHandle);

        // get the result
        JsonNode resultNode = resultsHandle.get();
        JsonNode jsonPointNodes = resultNode.path("results");

        // Should have 2 nodes returned.
        assertEquals("Two nodes not returned from testCircleContainsCircle method ", 2, resultNode.path("total").asInt());
        assertTrue("URI returned from testCircleContainsCircle method is incorrect", jsonPointNodes.get(0).path("uri").asText().contains("/Equator-json.json") ||
                jsonPointNodes.get(1).path("uri").asText().contains("/Equator-json.json"));
        assertTrue("URI returned from testCircleContainsCircle method is incorrect", jsonPointNodes.get(0).path("uri").asText().contains("/Equator.xml") ||
                jsonPointNodes.get(1).path("uri").asText().contains("/Equator.xml"));   
        client.release();
    }
```

Using the wgs84/double coordinate system in Java Test, the test throws an exception while doing the search.

```
com.marklogic.client.FailedRequestException: Local message: search failed: Internal Server Error. Server Message: XDMP-GEOREGIONIDX-NOTFOUND: cts:geospatial-region-path-reference("/root/item/box", "coordinate-system=wgs84") --  /root/item/box wgs84 . See the MarkLogic server error log for further detail.
    at com.marklogic.client.impl.JerseyServices$JerseySearchRequest.getResponse(JerseyServices.java:2221)
    at com.marklogic.client.impl.JerseyServices.search(JerseyServices.java:1990)
    at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:199)
    at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:163)
    at com.marklogic.client.functionaltest.TestDoublePrecisionGeoOps.testBoxContainsPolygon(TestDoublePrecisionGeoOps.java:182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The StructuredQueryBuilder class does not have a method to set coordinate system just like the script in NodeJS client. We need a similar method to set it as an option for the query on the builder.

**Comment by georgeajit** [comment]
Assigned to Vivek.

**Comment by kcoleman-marklogic** [comment]
The `geoPath` index constructor for point queries has the same requirement.

**Comment by vivekmuniyandi** [comment]
The way Java API does is different from Node API. We would have to pass those as options. There is a overload of the StructuredQueryBuilder.geospatial which allows a string array to be passed. We would need to populate the string array in order to use the co-ordinate system as wgs84/double. 

See this example:

QueryManager queryMgr = Common.client.newQueryManager();
        StructuredQueryBuilder qb = new StructuredQueryBuilder();
        String options[] = new String[1];
        options[0] = "coordinate-system=wgs84/double";
        StructuredQueryDefinition qdef;
        qdef = qb.geospatial(qb.geoElementPair(qb.element("point"), qb.element("lat"), qb.element("lon")), null,
                options, qb.box(0, 0, 10, 10));
        SearchHandle results = queryMgr.search(qdef, new SearchHandle());

If we were to change in the constructor, we would have to change it for all the constructors which creates an index (including geoelementpair index etc). I followed up with Erik and he too feels the same.

**Comment by georgeajit** [comment]
On applying the options to the query, as suggested above, we are seeing an exception:
```
XDMP-GEOREGIONIDX-NOTFOUND: cts:geospatial-region-path-reference("/root/item/circle", "coordinate-system=wgs84") --  /root/item/circle wgs84
```
while executing a search in the snippet
```
JacksonHandle resultsHandle = new JacksonHandle();
		queryMgr.search(t, resultsHandle);
```

**Comment by kcoleman-marklogic** [comment]
Here is the problem I perceive with the instructions Ajit was given earlier, and which a quick peek at the implementation only reinforces for me:

For region queries, the coordinate system is a property of the index reference fed to `cts:geospatial-region-query`. It is NOT an option on the constructed query as it is for other geo queries.  As such, you cannot just lump it in blindly with options like units and kick the can down the road.  

The structured query schema makes exactly this distinction. A `search:geo-region-path-query` contains BOTH a `geo-options` child and a `coord` attribute. The latter holds the coord sys+precision info for the index reference.

In order for the suggested solution to work properly, something in the Java API implementation would have to explicitly pick the `coordinate-system` option off from the options passed to the query builder and bind it to `geo-region-path-query/@coord` in the structured query. I do not see anything in the implementation that does this, though perhaps I just overlooked it as I'm not familiar with the impl.

The structured path region query has to end up looking something like this: 
```
<search:geo-region-path-query coord="wgs84/double">
  ....
</search:geo-region-path-query>
```

**Comment by sammefford** [comment]
Makes sense to me.  Thanks for continuing to dig in here Ajit & Kim!

**Comment by vivekmuniyandi** [comment]
Thanks Kim and Ajit for the explanation and the bug! Sorry, I didn't understand it completely. Working on the fix.

**Comment by vivekmuniyandi** [comment]
After talking with Erik, Alex and Jake, it is confirmed that it is a design bug and this needs to be consistent with the rest of the queries. Here, geospatial region queries alone behave differently where we cannot set the precision as query options. 

Erik confirmed that it is a design bug and it might have been neglected in the specifications. So I went ahead and logged bug https://bugtrack.marklogic.com/42783 against the REST layer. This doesn't need a fix anymore and fixing it in the REST layer should fix this issue. Thanks.

**Comment by vivekmuniyandi** [comment]
Understood the rationale behind the design and Erik just confirmed that it is not a design bug from https://bugtrack.marklogic.com/42783. So will make the changes in Java API and will send the diff for review to Sam and Erik and will commit it in the next few days. Thanks
