### ISSUE TITLE
Connections are left in CLOSE_WAIT after DatabaseClient.release is called - 3.0-develop

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#468]
Commit 62f3bfc4ba6ec72c4664ce379b79e0e2892d7b5d fixes #467 on the 3.0-develop branch.  Please test.

**Comment by georgeajit** [comment]
The issue is fixed. Ran the tests on release-3.0.5.1 branch of Java Client API on MarkLogic Server build 8.0-5.8 version.
