### ISSUE TITLE
Share connection pools across DatabaseClient instances

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#470]
While we have [a clear recommendation](https://help.marklogic.com/Knowledgebase/Article/View/435/0/notes-on-using-the-java-client-api-effciently) to use DatabaseClient instances efficiently, devs new to Java Client API don't always know to do that at first.  It's a common mistake to open too many DatabaseClient instances.  I'd like to find ways to share the underlying http connection pool across DatabaseClient instances with the same route (host, port, user, database).  

If possible, I'd even like to go the next step and share the http connection pool across different users and database since those are not really part of an http connection.  The database part seems easy as that's just an http parameter we pass each time.  But the user is tangled in authentication which is tangled in http: digest, ssl, or kerberos.  So I'm not sure if it's possble to keep user auth at a layer above http connections, but it seems to me that it should be possible.

**Comment by jmakeig** [comment]
Is this related to #737? If not, could we move it out of 3.0.8? That’s not to say we shouldn’t work on it, just not as part of 3.0.8.

**Comment by sammefford** [comment]
This has been done as part of #737.

**Comment by sammefford** [comment]
I'm taking this back for testing since it can't really be tested in unit or functional tests.  I think all we can do is stress tests to make sure it doesn't have any scalability issues.  Also, while running those I could do some manual testing to validate that it's faster.  Anecdotally, @tdiepenbrock has already reported that in his testing  with this change it's 3ms to create a DatabaseClient vs 30ms before.

**Comment by sammefford** [comment]
I've incorporated a stress test for this.  I had to make a fix, but now it's working well.
