### ISSUE TITLE
Retrieve search results in a JSON format

### ISSUE THREAD

**Issue by sastafford** [marklogic/java-client-api#471]
As a developer
I want to TITLE
So that I can process JSON search results instead of XML

I am applying a transform to search results from the /v1/search endpoint.  Using a ServerTransform class.  I want to store the search results in a JacksonHandle. 

``` Java
JacksonHandle results = queryMgr.search(querydef, new JacksonHandle());
```

But I'm getting an XQuery error returned.  Below is the XQuery transform that transforms search results to JSON. 

```
xquery version "1.0-ml";

module namespace transform = "http://marklogic.com/rest-api/transform/json-search";

import module namespace json = "http://marklogic.com/xdmp/json" at "/MarkLogic/json/json.xqy";

declare namespace search = "http://marklogic.com/appservices/search";

declare function transform(
        $context as map:map,
        $params as map:map,
        $content as document-node()
) as document-node()
{
    let $c := json:config("custom") ,
        $cx := map:put( $c, "whitespace", "ignore" ),
        $cx := map:put( $c, "text-value", "label" ),
        $cx := map:put( $c, "camel-case", fn:true() ),
        $cx := map:put( $c, "json-attributes", ("snippet-format", "total", "start", "page-length")),
        $cx := map:put( $c, "array-element-names", (xs:QName("search:result")))
    let $_ := map:put($context, "output-type", "text/json")
    let $json := json:transform-to-json(  $content ,$c )
    return $json
};
```

**Comment by sammefford** [comment]
Ok, I've tested this, and I'm getting the following server error:

  testIssue471(com.marklogic.client.test.TransformTest): Local message: search failed: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $src as node() -- Invalid coercion: () as node() . See the MarkLogic server error log for further detail.

Is that what you're seeing?  What you're doing looks correct and seems like it should work.

**Comment by sastafford** [comment]
Yes that is the message I received.

**Comment by sammefford** [comment]
Scott, if you don't transform the results, does this work as expected?  I would expect that using JacksonHandle is enough to tell the REST endpoint to send us the serach results in JSON format.  I'm not sure why you're having your transform convert to JSON.  It might be better to just do whatever transforms you need on the XML then let the REST endpoint convert it all to JSON.

**Comment by kcoleman-marklogic** [comment]
Unless something has changed (or I misunderstood back at the birth of the API), that's not how transforms work in the REST API. What gets returned from the transform is what gets returned to the client. If he wants to send back JSON, then his transform needs to return JSON.

**Comment by sastafford** [comment]
I haven't verified, but I think if you specify the format parameter as JSON and try to shove the results into a JacksonHandle then you get the error.
