### ISSUE TITLE
Add request origination self identifier for Java API metrics

### ISSUE THREAD

**Issue by popzip** [marklogic/java-client-api#473]
Using Telemetry, we can track feature usage at a granular level. For example, the Optic API will be tracking # of joins. We need a way to track where a request originated when coming from the Client APIs. Each client API must include some sort of identifier that the server can use to increment the correct metric (e.g. optic-joins-javascript vs optic-joins-java).

This task is not for a specific metric - just adding the JAVA identifier that can be used by feature tracking mechanism.

**Comment by sammefford** [comment]
I verified this is working by running the RowManagerTest, then looking in the meters database at all ".../features.xml" files, and seeing that some of them had features that had "java" in the name.  For example, I saw this:

    <feature-metrics xmlns="http://marklogic.com/xdmp/usage-meters">
      <start-time>2017-02-02T14:00:00.861079-08:00</start-time>
      <end-time>2017-02-02T15:00:00.37058-08:00</end-time>
      <cluster-id>18318090550103575909</cluster-id>
      <host-id>1152935850970130845</host-id>
      <group-id>12708412972638519771</group-id>
      <cluster-name>smefford-z620.marklogic.com-cluster</cluster-name>
      <host-name>smefford-z620.marklogic.com</host-name>
      <group-name>Default</group-name>
      <features>
        <feature name="op.doc.qry.rest.sjs">2</feature>
        <feature name="op.rows.groupbys.rest.sjs">1</feature>
        <feature name="op.views.java.sjs">6</feature>
        <feature name="op.views.rest.sjs">3</feature>
        <feature name="xdmp.sql.queryCount">7</feature>
        <feature name="op.triples.rest.sjs">1</feature>
        <feature name="op.lexicons.java.sjs">2</feature>
        <feature name="op.rows.groupbys.java.sjs">2</feature>
        <feature name="cts.plugin.icu.ta.lexerCount">2</feature>
        <feature name="op.doc.qry.java.sjs">4</feature>
        <feature name="op.results.java.sjs">377</feature>
        <feature name="temporal.doc">12</feature>
        <feature name="temporal.protect">6</feature>
        <feature name="cts.plugin.bitext.en.stemmerCount">76</feature>
        <feature name="op.results.rest.sjs">26</feature>
        <feature name="op.lexicons.rest.sjs">1</feature>
        <feature name="op.triples.java.sjs">2</feature>
        <feature name="sem.sparql.queryCount">31</feature>
        <feature name="temporal.version">44</feature>
      </features>
    </feature-metrics>

**Comment by sammefford** [comment]
I used this xquery to see all features.xml files in the Meters database: doc(cts:uri-match("*/features.xml"))

**Comment by georgeajit** [comment]
Telemetry is enabled for Optics only in Java Client API, i.e. only the Optics requests are currently recording meters.
After all the QA functional tests for Optics are run, the following XQuery script was run in the QConsole and 
a list of features related to Optics are available.
XQuery script file is available in the SVN repository and will be running at the end of the Java Client QA functional tests in the suite.
```
<h:script xmlns:h='http://marklogic.com/xdmp/harness'>
  <h:test h:output-result="true">
    <h:name>Java API telemetry test</h:name>
    <h:comment-expected-result>Should run all tests</h:comment-expected-result>
    <h:query>
      <![CDATA[
        xquery version "1.0-ml";
      
        let $script := "xdmp:feature-metric-status()//*:features"
        let $eval-result :=
          xdmp:eval(
            $script,
            (),
            <options xmlns="xdmp:eval">
              <database>{xdmp:database("Meters")}</database>
            </options>
          )
        for $metric in $eval-result//@name
        order by $metric
        return fn:concat($metric, " ")
      ]]>
    </h:query>
  </h:test>
</h:script>
```

Output of the above script from QConsole
```
cts.plugin.bitext.en.stemmerCount
op.doc.qry.java.sjs
op.lexicons.java.sjs
op.results.java.sjs
op.rows.groupbys.java.sjs
op.rows.joins.java.sjs
op.triples.java.sjs
op.views.java.sjs
tde.indexedDocuments
tde.indexedDocuments.templates
```

**Comment by popzip** [comment]
Ajit, could you add queries to also test for existence of these two Optic metrics? (you can reference internal task https://bugtrack.marklogic.com/42835 for full list):

op.doc.joinids.java.sjs
op.doc.joinuris.java.sjs

And please consult Erik if need to figure out how to add test for these.

**Comment by popzip** [comment]
did the extra tests get added? @georgeajit

**Comment by georgeajit** [comment]
Plan is to do this in 4.0.2 / 9.0-2 release.

**Comment by popzip** [comment]
is there a new task or should this one be re-opened?

**Comment by sammefford** [comment]
I removed th

**Comment by georgeajit** [comment]
This is the latest code to be run against ```Meters``` database.

```
xquery version "1.0-ml";
      
        let $script := "fn:doc()//@name"
        let $eval-result :=
          xdmp:eval(
            $script,
            (),
            <options xmlns="xdmp:eval">
              <database>{xdmp:database("Meters")}</database>
            </options>
          )
          
        for $metric in fn:distinct-values($eval-result)
        order by $metric
        return
        if (fn:starts-with($metric, "op"))
        then fn:concat($metric, " ")
        else ()
```

Result after execution of above script:
```
op.doc.joinids.java.sjs
op.doc.joinuris.java.sjs 
op.doc.qry.java.sjs
op.lexicons.java.sjs
op.results.java.sjs
op.rows.groupbys.java.sjs
op.rows.joins.java.sjs
op.triples.java.sjs
op.views.java.sjs
