### ISSUE TITLE
Frequent invocation of javax.xml.stream.XMLOutputFactory::newInstance negatively impacts performance

### ISSUE THREAD

**Issue by robsman** [marklogic/java-client-api#474]
While profiling a client application, it showed that there are lots of `javax.xml.stream.XMLOutputFactory.newInstance()` invocations, specifically when a client retrieves extracted document data from search results. In our use case, this almost totaled to the same amount of CPU time as the actual search.

**Comment by robsman** [comment]
I have applied a hotfix in the client project but still need to beef it up into a proper pull request. 

The problematic code in our use case is in `Utilities::writeEvents`. However, there are other places that retrieve XML factories, e.g. `SearchHandle::receiveContent`, `StructuredQueryBuilder::makeSerializer` and `SearchResponseImpl::handleMetrics`.

My suggestion is to consolidate retrieval and caching of expensive factories into a utility class (maybe `XmlFactoriesAccess` ?) and adjust client code accordingly.

**Comment by sammefford** [comment]
Thanks Rob!

**Comment by sammefford** [comment]
We'll let you submit your patch first, then we'll use that as a model for the rest.

**Comment by robsman** [comment]
Hi Sam, after some further research it turned out the various XML factories are not guaranteed to be thread-safe. To address this I have reworked the pull request #477 to use instance-per-thread caching.

The code is a bit verbose as the _develop-3.0_ branch is still Java 6. But nevertheless it should be relatively straightforward.
We're running a copy of this in our project for some days now, so far, so good.

**Comment by sammefford** [comment]
Thanks Rob!

**Comment by sammefford** [comment]
@georgeajit as long as this didn't create any issues in unit tests, I think we're good on this

**Comment by georgeajit** [comment]
Don't see any regressions as of now (01/25/2018) on the develop branch. Shipping this issue.
