### ISSUE TITLE
Cannot add a rule with a Not-query

### ISSUE THREAD

**Issue by sastafford** [marklogic/java-client-api#475]
com.marklogic.client.FailedRequestException: Local message: /alert/rules write failed: Bad Request. Server Message: XDMP-ARGTYPE: (err:XPTY0004) cts:not-query(()) -- arg1 is not of type cts:query

	at com.marklogic.client.impl.JerseyServices.putPostValueImpl(JerseyServices.java:3031)
	at com.marklogic.client.impl.JerseyServices.putValue(JerseyServices.java:2881)
	at com.marklogic.client.impl.RuleManagerImpl.writeRule(RuleManagerImpl.java:168)

```java
public void addQueryTest() {
        StructuredQueryBuilder qb = new StructuredQueryBuilder("default");
        //StructuredQueryDefinition geoQueryRule = qb.not(qb.geospatialConstraint("geo", qb.circle(90.0, 90.0, 5.0)));
        String rawXMLQuery =
                "<query xmlns='http://marklogic.com/appservices/search'>"+
                    "<not-query>"+
                        "<geospatial-constraint-query>"+
                        "<constraint-name>geo</constraint-name>"+
					        "<circle>"+
					            "<radius>3.5674162949999997</radius>"+
					            "<point>"+
					                "<latitude>-15.766</latitude>"+
					                "<longitude>33.829</longitude>"+
                        		"</point>"+
                            "</circle>"+
                        "</geospatial-constraint-query>"+
                    "</not-query>"+
                "</query>";
        StringHandle rawHandle = new StringHandle(rawXMLQuery);
        RuleDefinition rule = new RuleDefinition("sample", "sample");
        //StringHandle queryHandle = new StringHandle(geoQueryRule.serialize());
        rule.importQueryDefinition(rawHandle);
        ruleMgr.writeRule("sample", rule);
    }
```

**Comment by sastafford** [comment]
Constraint for the default options

```xml
 <constraint name="geo">
    <geo-elem>
      <element ns="" name="point"/>
      <geo-option>coordinate-system=wgs84</geo-option>
    </geo-elem>
  </constraint>
```

**Comment by sastafford** [comment]
Workaround seems to be to pass in raw JSON for the rule. 

```java
   @Test
    public void addRawJsonRuleTest() {
        String ruleName = "rule123";
        String rawRule =
                "{\n" +
                        "\t\"rule\" : {\n" +
                        "\t\t\"name\" : \"rule123\",\n" +
                        "\t\t\"search\" : {\n" +
                        "\t\t\t\"query\": {\n" +
                        "\t\t\t\t\"queries\": [{\n" +
                        "\t\t\t\t\t\"not-query\": {\n" +
                        "\t\t\t\t\t\t\"term-query\": {\n" +
                        "\t\t\t\t\t\t\t\"text\": [ \"dog\" ]\n" +
                        "\t\t\t\t\t\t}\n" +
                        "\t\t\t\t\t}\n" +
                        "\t\t\t\t}]\n" +
                        "\t\t\t}\n" +
                        "\t\t},\n" +
                        "\t\t\"description\" : \"rule description\",\n" +
                        "\t\t\"rule-metadata\" : { \n" +
                        "\t\t\t\"author\" : \"me\" \n" +
                        "\t\t}\n" +
                        "\t}\n" +
                        "}";
        StringHandle handle = new StringHandle();
        handle.withFormat(Format.JSON).set(rawRule);
        ruleMgr.writeRule(ruleName, handle);
    
    }
```

**Comment by grechaw** [comment]
Hi @sastafford , the bug might be associated with `geospatial-constraint-query`, not XML vs. JSON.

**Comment by sastafford** [comment]
@grechaw - It doesn't matter what query is inside the not query.  Plus, if I pass the same structured query to search there is no complaint.

**Comment by sastafford** [comment]
I just verified that JSON doesn't work either.  Same error I just tried passing a RawJSON rule in with a structured query with a not-query.  

Is there a workaround on this?

**Comment by sastafford** [comment]
```java
rawJsonRule =
                    "{" +
                        "\"rule\" : {" +
                            "\"name\" : \"" + ruleName + "\"," +
                            "\"search\" : {" +
                                "\"query\": {" +
                                    "\"queries\": [{" +
                                        "\"not-query\": {\n" +
                                            "\"geospatial-constraint-query\": {" +
                                                "\"constraint-name\": \"geo\"," +
                                                    "\"circle\": [{" +
                                                        "\"radius\": " + String.valueOf(distance) + "," +
                                                        "\"point\": [{" +
                                                            "\"latitude\": " + String.valueOf(lat) + "," +
                                                            "\"longitude\": " + String.valueOf(lon) +
                                                        "}]" +
                                                    "}]" +
                                            "}" +
                                        "}" +
                                    "}]" +
                                "}" +
                            "}," +
                            "\"description\" : \"rule description\"," +
                            "\"rule-metadata\" : {" +
                                "\"author\" : \"me\" " +
                            "}" +
                        "}" +
                    "}";
```

**Comment by grechaw** [comment]
I think we need to investigate, would not be at all surprised if you've found a bug or gap in alerting.  It has not been significantly refreshed since 8, and may not even support JSON.  (need to consult specs and history)

**Comment by kcoleman-marklogic** [comment]
FWIW, Scott's original XML query + options seems to work fine through the REST API. Or at least, doesn't cough up a hairball.

**Comment by sastafford** [comment]
@kcoleman-marklogic - Yes, the query and options work fine on the /search endpoint

**Comment by sammefford** [comment]
@kcoleman-marklogic do you mean a PUT to the REST API endpoint /v1/alert/rules/{name}?

**Comment by kcoleman-marklogic** [comment]
Yes, I tried both POST /v1/search and PUT /v1/alert/rules/{name}.

Here's the rule payload I used:
```
<rapi:rule xmlns:rapi="http://marklogic.com/rest-api">
  <rapi:name>scott</rapi:name>
  <rapi:description>An example rule.</rapi:description>

<search xmlns='http://marklogic.com/appservices/search'>
<query>
  <not-query>
    <geospatial-constraint-query>
      <constraint-name>geo</constraint-name>
      <circle>
        <radius>3.5674162949999997</radius>
        <point>
          <latitude>-15.766</latitude>
          <longitude>33.829</longitude>
        </point>
      </circle>
    </geospatial-constraint-query>
  </not-query>
</query>
<options>
  <constraint name="geo">
    <geo-elem>
      <element ns="" name="point"/>
      <geo-option>coordinate-system=wgs84</geo-option>
    </geo-elem>
  </constraint>
</options>
</search>
</rapi:rule>
```
Unlike Scott, though, I put the options inside the combined query because I didn't want to dirty my default options.

**Comment by grechaw** [comment]
Yeah, i had a hunch this could be an issue with reverse query

**Comment by sastafford** [comment]
@kcoleman-marklogic - I have verified that when you include the options in the search query it works.  Damn, that was tricky.  So in my original code, I was creating my query using a StructuredQueryBuilder

```java
StructuredQueryBuilder qb = new StructuredQueryBuilder(OPTIONS_NAME);
```

Requires an options file.  I was then importing that into my rules defintion

```java
StructuredQueryDefinition querydef = qb.and( userIdRule, geoQueryRule, timeRule);
StringHandle queryString = new StringHandle(querydef.serialize());
rule.importQueryDefinition(queryString);
```
I made the mistake of assuming that the rule would just know the options file would be there.  Does that make sense?

**Comment by kcoleman-marklogic** [comment]
The problem is that the underlying REST call requires a combined query (even if it contains no options), not just a structured query.  That is, a `<search:search/>`, rather than a `<search:query/>`. It does say so in the javadoc for `importRuleDefinition`, but it is easily overlooked:

"Imports an XML *combined search definition* that defines the matching criteria for this rule."

**Comment by grechaw** [comment]
Oh, so this works.  the problem was a constraint query with no constraint to point to.

What about JSON ?  Does JSON work?

**Comment by kcoleman-marklogic** [comment]
This is not an unreasonable assumption if you were using an interface that accepts StructuredQueryDefinition:

> I made the mistake of assuming that the rule would just know the options file would be there. Does that make sense?

However, once you serialize the query to a string, any knowledge of options is completely lost. I don't even really understand why `StructuredQueryBuilder` accepts a persisted option name since the options name is associated with the operation, not with the query. That's a _"Things that make you go 'hmmm'"_ question for Sam or Charles, I guess.

In addition, the underlying REST API for alerting does not support specifying persisted query options when you create a rule.

Based on what you've said, @sastafford, I think you should construct a combined query that contains your structured query + your options. You can still use `StructuredQueryBuilder`, but some assembly is required to wrap it up into a `RawCombinedQueryDefinition`. Take a look at this topic:

http://docs.marklogic.com/guide/java/searches#id_50826

**Comment by sastafford** [comment]
In conclusion, this is not a bug, but a misunderstanding on my part.  @kcoleman-marklogic your comments were a fantastic help and I was able to get things working based on your guidance.  Thanks for your help.  

This is the code snippet I ended up using.  getDefaultOptions() is a StringHandle from the QueryOptionsManager.  

```java
//And-Query with 3 rules
StructuredQueryDefinition querydef = qb.and(userIdRule, geoQueryRule, timeRule);
    
RawStructuredQueryDefinition rsq = qb.build(querydef);
String comboq =
                        "<search xmlns=\"http://marklogic.com/appservices/search\">" +
                                rsq.toString() +
                                getDefaultOptions().get() +
                                "</search>";
rule.importQueryDefinition(new StringHandle(comboq));
```

**Comment by sammefford** [comment]
@kcoleman-marklogic to answer your question about "the options name is associated with the operation, not with the query", it turns out that the options name can be set on any [QueryDefinition](http://docs.marklogic.com/javadoc/client/com/marklogic/client/query/QueryDefinition.html) as specified in the core interface.  I would guess that the rationale is that a QueryDefinition represents the parts necessary to get a result from a search request, not just the search query part.
