### ISSUE TITLE
add databaseClient.newMoveManager() and remove DataMovementManager.newInstance()

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#482]
We should now get DataMovementMangager from databaseClient.newMoveManager rather than "new DataMovementManager().withClient(databaseClient)".  That will align with the other managers in the Java Client API, and remove the step of setting the client.

**Comment by sammefford** [comment]
Srinath, when you look at this, can you make sure all functional tests no longer use DataMovementManager.newInstance?  Then I'll remove that capability.  Hmm, I'll just make a PR for that and you can merge it...

**Comment by srinathgit** [comment]
Verified that databaseClient.newMoveManager works fine
