### ISSUE TITLE
make an ExportToWriterListener equivalent for Optic API

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#483]
UrisToWriterListener makes it easy to send uris matching a query to an aggregate output file.  ExportToWriterListener makes it easy to send many documents matching a query to an aggregate output file.  Do either of these allow us to also do an Optic query and send those results to an aggregate output file?

**Comment by vivekmuniyandi** [comment]
OpticExportListener from package com.marklogic.client.example.cookbook.datamovement enable us to apply a Function which would take a QueryBatch as argument and return a plan, which would be iterated and processed by each listener registered with it. 

and OpticExportToWriterListener from the same package enable us to do the same but the records from the plan would be written to a Writer Output stream.

**Comment by sammefford** [comment]
Vivek, I'm reminded that we still need a more general-purpose solution, and these iterate over search results, requiring a CTS query first
