### ISSUE TITLE
Export to ZIP

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#499]
Issue a query and bulk export the matching documents to a ZIP, optionally passing them through a transformation on the way out.

Note there may be issues connecting `ExportToWriterListener` to a `ZipOutputStream`. [See also](http://stackoverflow.com/a/17190212/563324).

**Comment by sammefford** [comment]
Is this resolved by https://github.com/marklogic-community/ml-gradle/wiki/Exporting-data#exporting-data-to-a-zip?

**Comment by jmakeig** [comment]
Enough for now.
