### ISSUE TITLE
Demonstrate how to combine facts and dimensions

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#500]
As a developer, I need to load millions of fact records from an existing data warehouse in order to integrate them with other silos. (The objective is _not_ to reproduce the warehouse one-to-one, but get additional value by operationalizing it with other data.) 

Each of the facts references multiple dimensions. In order to better leverage MarkLogic’s universal index, I need to denormalize the dimensions into the resulting fact documents. Both facts and dimensions come in as CSV. In general the facts change more often than the dimensions. However, both can change in any update.

Updates come in as batches initially and then diffs come in as a stream. The same denormalization logic needs to be used in both scenarios.

**Comment by sammefford** [comment]
Would this be a good scenario to apply the following transform design?

1. many tuples from input can form a document as the output
2. tuples come in any order
3. the transform contains logic to know when all required tuples are available to form a document
4. if a tuple isn't the last required to form a document, the transform writes it to a staging collection
5. if a tuple is the last required to form a document, the document is formed and written and all the tuples for that document are deleted from the staging collection

Hmm, I think all but the last step work with a transform.  But while the transform can write a separate document and delete all the related tuples in the staging collection, I don't know how a transform can stop the creation of the last tuple.  I guess we could let it get written but spawn a task to then delete it?

**Comment by jmakeig** [comment]
Yes, this is a great use case. Similar to what @rjrudin has demonstrated with Spring Batch. 

> the transform contains logic to know when all required tuples are available to form a document

I think that’s the tricky part. That logic is going to be very dependent on the data, especially the cardinalities of joined rows. (I think Rob made some assumptions about the order of tuples in order to simplify this logic, i.e. so you’d know that all of the rows for a given entity were grouped together.)

The next step, after the initial bulk load, would then be listening to a stream of tuples and figure out which entities need to be updated.
