### ISSUE TITLE
Provide release notes for 3.0.5, 3.0.6, 3.0.7

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#503]

**Comment by sammefford** [comment]
Justin, please take a look at CHANGELOG.md and let me know if there is anything I can improve.

**Comment by jmakeig** [comment]
See #727

**Comment by sammefford** [comment]
I incorporated your PR.  Let me know if there's anything else.

**Comment by jmakeig** [comment]
Thanks for pulling this together, @sammefford. This is exactly what I’d envisioned.
