### ISSUE TITLE
Invalid values for 'Min Hosts'

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#512]
The following test was run with a single node server with a db associated with a single forest. When the documents were being written, the host was shutdown but job kept running. DO we want to handle these scenarios to ensure the value for 'Suspend Time for Host Unavailability'  is greater than or equal to 1 ?

```
ihb2.setBatchFailureListeners(
 new HostAvailabilityListener(dmManager, ihb2)
 .withSuspendTimeForHostUnavailable(Duration.ofMinutes(2))
  .withMinHosts(0)
);
```

**Comment by sammefford** [comment]
I don't understand the question.  In this scenario, I would think that in this scenario every two minutes the withForestConfiguration on the batcher should be called with an updated ForestConfiguration from the server.

**Comment by srinathgit** [comment]
I am sorry, I meant the values for 'minHosts'. Will it make sense to have 'minHosts' set to 0 or a negative number ? Should we restrict its values to >=1  (or >=0 ? ) ?

**Comment by sammefford** [comment]
yes, I'll put a check in that minHosts must be > 0

**Comment by srinathgit** [comment]
Verified that an exception is thrown if minHosts < = 0
