### ISSUE TITLE
PlanBuilder.xs qname method overloads' name needs to be same 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#514]
Currently for PlanBuilder.Xs type's qname method have the following names. These are seen in the IDE.

qname(parameter list)
QName(parameter list)
qName(parameter list)

These methods need to have a homogeneous method naming convention.

**Comment by ehennum** [comment]
The QName constructors should all capitalize the first two letters now (which also aligns with the  names of expression functions that take a QName argument).

I also removed the prefix argument because that's thrown away during import.

**Comment by georgeajit** [comment]
Works fine.
