### ISSUE TITLE
Host not added back to rotation after "host unavailability interval" expires

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#523]
A. The following test is performed on 3 node cluster with a db associated with 3 forests.
```
21:37:23.074 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-5.marklogic.com, rh7v-intel64-90-test-6.marklogic.com, rh7v-intel64-90-test-4.marklogic.com] hosts with forests for "WriteHostBatcher"
21:37:23.749 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "rh7v-intel64-90-test-5.marklogic.com" to the rotation
21:37:24.076 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "rh7v-intel64-90-test-6.marklogic.com" to the rotation
21:37:24.076 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "rh7v-intel64-90-test-4.marklogic.com" to the rotation
```
B.Before documents are loaded (and after WB is initiated and 3 hosts are added to rotation) , one of the host "rh7v-intel64-90-test-6.marklogic.com" is stopped
```
21:40:26.896 [pool-1-thread-1] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-6.smarklogic.com", black-listing it for PT50S
```

C. Forest failover occurs in 30 seconds after node shutdown and approximately at the same time node "rh7v-intel64-90-test-6.marklogic.com" is restarted.
D. After 50 seconds, elapse, the following message is seen in the log. The host "rh7v-intel64-90-test-6.marklogic.com" is not added to the rotation 

```
21:41:16.995 [pool-2-thread-1] INFO  c.m.c.d.HostAvailabilityListener - it's been PT50S since host rh7v-intel64-90-test-6.marklogic.com failed, opening communication to all server hosts [[rh7v-intel64-90-test-4.marklogic.com, rh7v-intel64-90-test-5.marklogic.com]]
21:41:17.068 [pool-3-thread-1] INFO  c.m.c.d.HostAvailabilityListener - it's been PT50S since host rh7v-intel64-90-test-6.marklogic.com failed, opening communication to all server hosts [[rh7v-intel64-90-test-4.marklogic.com, rh7v-intel64-90-test-5.marklogic.com]]
```
The entire log file is attached.
[exception.txt](https://github.com/marklogic/java-client-api/files/565765/exception.txt)

Test:

```
@Test
		public void testFailOver() throws Exception{
			try{
				final String query1 = "fn:count(fn:doc())";
			 	
		       	final AtomicInteger successCount = new AtomicInteger(0);
		       	
		       	final MutableBoolean failState = new MutableBoolean(false);
		       	final AtomicInteger failCount = new AtomicInteger(0);
		    			        
				WriteBatcher ihb2 =  dmManager.newWriteBatcher();
				ihb2.withBatchSize(20);
				ihb2.withThreadCount(2);
				dmManager.startJob(ihb2);
				
				ihb2.setBatchFailureListeners(
						  new HostAvailabilityListener(dmManager)
						    .withSuspendTimeForHostUnavailable(Duration.ofSeconds(50))
						    .withMinHosts(1)
						);	
				ihb2.onBatchSuccess(
				        (client, batch) -> {

				        	successCount.addAndGet(batch.getItems().length);
				        	System.out.println("Success Job number: "+ batch.getJobWritesSoFar());
				        	 System.out.println("Success Job writes so far: "+ batch.getJobWritesSoFar());
				          }
				        )
				        .onBatchFailure(
				          (client, batch, throwable) -> {
				        	  System.out.println("Failed batch number: "+ batch.getJobBatchNumber());
				        	  try{
				        		  System.out.println("Retrying batch: "+ batch.getJobBatchNumber());
				        		  ihb2.retry(batch);
				        	  }
				        	 catch(Exception e){
				        		 System.out.println("Retry of batch "+ batch.getJobBatchNumber()+ " failed");
				        		 e.printStackTrace();
				        	 }
				        	 
				        	  throwable.printStackTrace();
				        	  failState.setTrue();
				        	  failCount.addAndGet(batch.getItems().length);
				          });
				
				
 
		       
		       	
				for (int j =0 ;j < 50000; j++){
					String uri ="/local/ABC-"+ j;
					ihb2.add(uri, stringHandle);
				}
			
				
			    ihb2.flushAndWait();
			   
			    
		    	System.out.println("Fail : "+failCount.intValue());
		    	System.out.println("Success : "+successCount.intValue());
		    	System.out.println("Count : "+ dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());
		  
		    	Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue()==50000);
		    	
			}
			catch(Exception e){
				e.printStackTrace();
			}
		}
```

**Comment by sammefford** [comment]
This is expected behavior.  The forestinfo endpoint will add openReplicaHost to any forest that is still failed over to the replica.  In my testing I saw that frequently it just seems to get stuck on the replica host after a fail over.  After the main forests are back online, I have to restart the replica forests.  But as long as the server says to use the replica forest, DMSDK will.

**Comment by srinathgit** [comment]
1. If I understand correctly, you are saying that due to the failover, the forest would be available either in one of configured available nodes "rh7v-intel64-90-test-4.marklogic.com" or "rh7v-intel64-90-test-5.marklogic.com" and will continue to be available in those nodes until "rh7v-intel64-90-test-6.marklogic.com"  and the replica forest is restarted in that order. Hence "rh7v-intel64-90-test-6.marklogic.com"  will not be added to the list of available hosts after expiration of "host unavailability interval"
2.Let's consider the scenario where in my original bug description, in step C, consider that in addition to restarting node "rh7v-intel64-90-test-6.marklogic.com", a new forest has been created in this host and attached to the db before "host unavailability interval" expires. Will this host then be included in rotation and documents written to this forest after "host unavailability interval" expires?
3. If not, what is the point of "host unavailability interval" having this parameter then ?

**Comment by sammefford** [comment]
> If I understand correctly, you are saying that due to the failover, the forest would be available either in one of configured available nodes "rh7v-intel64-90-test-4.marklogic.com" or "rh7v-intel64-90-test-5.marklogic.com" and will continue to be available in those nodes until "rh7v-intel64-90-test-6.marklogic.com" and the replica forest is restarted in that order. Hence "rh7v-intel64-90-test-6.marklogic.com" will not be added to the list of available hosts after expiration of "host unavailability interval"

Actually, if you've restarted rh7v-intel64-90-test-6.marklogic.com and the replica forests, then rh7v-intel64-90-test-6.marklogic.com **will** be added to the list of available hosts after expiration of "host unavailability interval".  Or more simply, after "host unavailability interval" the HostAvailabilityListener will call dataMovementManager.readForestConfiguration() and pass that to batcher.withForestConfig().  So at that point the batcher will do whatever the server tells it to do.  If the server says it has fully recovered from the failover, then rh7v-intel64-90-test-6.marklogic.com will be back in the mix.  You can always check your database status page to see the status of all the forests.  And you can check /v1/forestInfo to see what readForestConfiguration will see.

> Let's consider the scenario where in my original bug description, in step C, consider that in addition to restarting node "rh7v-intel64-90-test-6.marklogic.com", a new forest has been created in this host and attached to the db before "host unavailability interval" expires. Will this host then be included in rotation and documents written to this forest after "host unavailability interval" expires?

Yes, any new forests or hosts will be included in the rotation when the results of readForestConfig ar passed to withForestConfig.

**Comment by srinathgit** [comment]
When the job was running, the node is shut down and started again after 25 seconds. As you can see in the [log](https://github.com/marklogic/java-client-api/files/1357640/temp.txt), the forest config is not obtained after 25 seconds. 
```
16:13:51.166 [pool-3-thread-34] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-9", black-listing it for PT25S
16:13:47.332 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-9, rh7v-intel64-90-test-7.marklogic.com, rh7v-intel64-90-test-8.marklogic.com] hosts with forests for "WBFailover"
16:13:51.209 [pool-3-thread-34] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-7.marklogic.com, rh7v-intel64-90-test-8.marklogic.com] hosts with forests for "WBFailover"
```

```
	@Test
	public void testStopOneNode() throws Exception {
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
		final AtomicInteger successCount = new AtomicInteger(0);
		final AtomicBoolean failState = new AtomicBoolean(false);
		final AtomicInteger failCount = new AtomicInteger(0);
		try {
			WriteBatcher ihb2 = dmManager.newWriteBatcher();
			ihb2.withBatchSize(2);
			ihb2.withThreadCount(99);

			HostAvailabilityListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(25))
					.withMinHosts(2);
			NoResponseListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(25))
					.withMinHosts(2);
			ihb2.onBatchSuccess(batch -> {
				successCount.addAndGet(batch.getItems().length);
			}).onBatchFailure((batch, throwable) -> {
				throwable.printStackTrace();
				failState.set(true);
				failCount.addAndGet(batch.getItems().length);
			});

			writeTicket = dmManager.startJob(ihb2);
			AtomicBoolean isRunning = new AtomicBoolean(true);
			for (int j = 0; j < 50000; j++) {
				String uri = "/local/ABC-" + j;
				ihb2.add(uri, stringHandle);
			/*	if (dmManager.getJobReport(writeTicket).getSuccessEventsCount() > 200 && isRunning.get()) {
					isRunning.set(false);
					serverStartStop(hostNames[hostNames.length - 1], "stop");
				}*/
			}
			ihb2.flushAndWait();

		} catch (Exception e) {
			e.printStackTrace();
		}
		Thread.currentThread().sleep(5000L);
		System.out.println("Fail : " + failCount.intValue());
		System.out.println("Success : " + successCount.intValue());
		System.out.println("Count : " + dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 50000);
	}
```

**Comment by srinathgit** [comment]
I think the scenario mentioned in the previous comment is different from the one that I had originally reported. The original issue is fixed, so I will open a new bug with previous comment for fixing.
