### ISSUE TITLE
Fix dmsdk markdown javadocs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#524]
When DMSDK was a separate project we used a markdown gradle javadoc plugin so the javadocs had less HTML in them.  But now the javadocs don't look right because that plugin isn't installed in the maven javadocs used to build java-client-api.  We need to either install a maven equivalent markdown plugin or we need to reformat the dmsdk javadocs so they render correctly with standard javadocs build.

**Comment by sammefford** [comment]
@srinathgit if the javadocs on the com.marklogic.client.datamovement package and the classes in that package look good, and the other javadocs look good then this is working.

**Comment by kcoleman-marklogic** [comment]
FWIW, I don't think they're right. I'm not sure which parts do and don't have Javadoc content, so IDK if it is correct that some of the Interfaces (Batch, etc.) haven't so much as a one line description, but I am positive that formatting is wrong for most of the things that do have real content. Things like class descriptions are coming out as one big paragraph.

At minimum, I would guess you're missing some code tags. I recall you've had this issue in the past.

**Comment by kcoleman-marklogic** [comment]
Contrast, for example, [GraphManager](http://pubs.marklogic.com:8011/9.0/javadoc/client/com/marklogic/client/semantics/GraphManager.html) with [ApplyTransformListener](http://pubs.marklogic.com:8011/9.0/javadoc/client/com/marklogic/client/datamovement/ApplyTransformListener.html).

**Comment by sammefford** [comment]
@kcoleman-marklogic can you make sure you're using the latest to build those javadocs?  Those look like the javadocs we had before I made commit 	e64978b to fix this task.

I haven't yet fixed https://github.com/marklogic/data-movement/issues/130 but that only applies to Eclipse.

**Comment by kcoleman-marklogic** [comment]
You're right, Sam. It looks much better now that your latest changes were picked up. My apologies for not paying attention.

**Comment by srinathgit** [comment]
Sam,

In all the code snippets, (->) is rendered as -&gt;. Similar issue also occur when specifying type arguments  in the code snippet

**Comment by kcoleman-marklogic** [comment]
I think what Srinath is saying is that arrows in your code samples are showing up with the greater than symbol entity encoded, like this: `-&gt;`. That's how they are in the source, too. I'm kinda surprised they're not being rendered properly (decoded), TBH.

There's an example in WriteBatcher. Perhaps you'd have better/different results with \@code? I really don't know.

**Comment by srinathgit** [comment]
Thanks Kim for clarifying ... In addition, you can also see  the same issue when rendering angled brackets for type arguments; `ArrayList<String>` is being rendered as `ArrayList-&lt; String-&gt;`. There's an example in QueryBatcher doc

**Comment by sammefford** [comment]
One more related commit: 3bb01330b66b77c38bf3d3c5cd6d4acb9ac94e69

**Comment by srinathgit** [comment]
The doc looks good after the fix.
