### ISSUE TITLE
Add explicit support for load balancers to DMSDK

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#534]
It seems there are scenarios in AWS where load balancers are really hard to avoid.  If that's the case, we could explicitly support load balancers even though that's less performant with DMSDK.  We could add a method withHosts(String... hosts) which accepts a list of load balancer host names which we should use instead of the hosts we get from the ForestConfiguration.  We could then make sure the logic in QueryBatcher and WriteBatcher and HostAvailabilityListener always use only those hosts and not the hosts from the ForestConfiguration.

**Comment by sammefford** [comment]
For now, the work-around (which has been [tested by QA](https://github.com/marklogic/java-client-api/issues/617) on Amazon AWS with ELB) is to call `batcher.withForestConfig(new FilteredForestConfiguration(dataMovementManager.readForestConfig()).withWhiteList(elbHost))` where elbHost is the hostname of the ELB server, so it is the only valid server the batcher will talk to.  This works the same on WriteBatcher and QueryBatcher.  Make sure the client used to instantiate dataMovementManager is using the same hostname (elbHost) so it lines up with what you pass to withWhiteList.

**Comment by derms** [comment]
FYI the above does not work for me.

I've been able to get it to work by explicitly calling the withRenamedHost method with the available hosts - i.e.

```
ForestConfiguration forestConfig = dataMovementManager.readForestConfig();
FilteredForestConfiguration filteredForestConfig = new FilteredForestConfiguration(
    forestConfig
).withWhiteList(lbHost);
for (String preferredHost : forestConfig.getPreferredHosts()) {
    filteredForestConfig.withRenamedHost(preferredHost, lbHost);
}
batcher.withForestConfig(forestConfig);
```

**Comment by ehennum** [comment]
Fixed by supplying DatabaseClient.ConnectionType enum to factory method.  See

https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClientFactory.html#newClient-java.lang.String-int-com.marklogic.client.DatabaseClientFactory.SecurityContext-com.marklogic.client.DatabaseClient.ConnectionType-

and

https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClient.ConnectionType.html
