### ISSUE TITLE
Decouple bulk processing from document transformation

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#538]
_Clone of marklogic/data-movement#142._

Today, ApplyTransformListener assumes a URI in and a document out. That’s good for a default, but not flexible enough.

As a developer, I have a list of unique identifiers of employees. I might get that list from a document in a MarkLogic database or from somewhere else in my ETL app (e.g. live query to a remote database, file on the file system, piped from stdin). I want to run a bulk process, such that for each employee ID, I call some JavaScript/XQuery on the server to gather all the data related to that employee, apply some merge/transformation logic, and save a new, harmonized XML or JSON document for that employee. If the sources don't exist for a given employee (or another assertion failure during merge/transform) I might want to store a “marker” document and/or bubble up an exception/warning such that the orchestration (i.e. Java app) would be aware of an issue.

**Comment by jmakeig** [comment]
This has a dependency on the REST API. We agreed to address this post-9.0-1.

**Comment by sammefford** [comment]
Here's some of the relevant discussion we'll need to think about when we work on this:

In my tests, if the REST /v1/internal/apply-transform endpoint is called with a non-existent uri, the server-side transform script is never run. It shouldn't be too hard to add an option for it to run the transform with context.uri set to the non-existent uri specified in the endpoint but the content set to undefined or empty-sequence(). Once we add that option to the REST endpoint and we can add a parallel option to ApplyTransformListener so devs can choose to have the transform run even if the uri is non-existent in the db.

**Comment by ehennum** [comment]
Superseded by DHF.
