### ISSUE TITLE
Provide a direct way to override HostAvailabilityListener

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#539]
When HostAvailabilityListener was the only pre-registered Listener, we recommended you replace it by:

    batcher.setBatchFailureListeners(
      new HostAvailabilityListener(moveMgr)
        .withSuspendTimeForHostUnavailable(Duration.ofMinutes(60))
        .withMinHosts(2)
    );

But that no longer works because that will not only override HostAvailabilityListener, but also remove the pre-registered JobReportListener which accumulates for JobReport.  Rather than ask users to do something fancy like this:

    WriteBatchFailureListener[] listeners = Stream.of(batcher.getBatchFailureListeners())
      .map(listener ->
        if (listener instanceof HostAvailabilityListener) {
          return new HostAvailabilityListener(moveMgr)
            .withSuspendTimeForHostUnavailable(Duration.ofMinutes(60))
            .withMinHosts(2)
        } else {
          return listener;
        }
      );
    batcher.setBatchFailureListeners(listeners);

let's do the work for them in a method they could call like:

    WriteBatcher.replaceBatchFailureListener(HostAvailabilityListener.class, 
        return new HostAvailabilityListener(moveMgr)
            .withSuspendTimeForHostUnavailable(Duration.ofMinutes(60))
            .withMinHosts(2)
    );

**Comment by sammefford** [comment]
Related to #570

**Comment by sammefford** [comment]
I'm thinking the benefit of this convenience is not worth the expanded surface area.  We're realizing there may be more than one listener of the same type, so we'd perhaps need a replaceFirstBatchFailureListener and replaceBatchFailureListeners.  Also, we sometimes would like a getBatchFailureListeners and getFirstBatchFailureListener and all the same methods for onUrisReady listeners.  And of course, the same on WriteBatcher.  These are nice conveniences, but a lot of surface area with no new functionality other than convenience.  The only time this is likely to be common is on HostAvailabilityListener.  So we've proposed instead adding a convenience method 

    static HostAvailabilityListener HostAvailabilityListener.getInstance(BatchFailureListener[])

For the rest of the needs I think we should recommend the fancy code in the original comment on this issue.

**Comment by sammefford** [comment]
To change minHosts or suspendTimeForHostUnavailable you can do this:

    HostAvailabilityListener.getInstance(BatchFailureListener[])
        .withSuspendTimeForHostUnavailable(Duration.ofMinutes(60))
        .withMinHosts(2)

**Comment by srinathgit** [comment]
Verified that the new API works for changing minHosts or suspendTimeForHostUnavailable
HostAvailabilityListener.getInstance(batcher)
    .withSuspendTimeForHostUnavailable(Duration.ofMinutes(60))
    .withMinHosts(2)
