### ISSUE TITLE
DocumentMetadataPatchBuilder insertFragment(uri, positon, string) method not found

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#540]
As of 11/11/2016 on develop branch, I do not see on the develop branch the functionality for insert fragment.

Is this feature slated for a post 9.0 - EA4 release or dropped?

**Comment by sammefford** [comment]
Ajit, I'm familiar with tasks to add document patch features related to bitemporal.  But this looks like a non-bitemporal feature.  Can you explain why you're raisint this now?  Is there a PRD or func spec related to ML9 you're looking at?

**Comment by georgeajit** [comment]
https://wiki.marklogic.com/display/ENGINEERING/Java+Client+API+Delta+for+9.0+Test+Plan

This document has the plan to test.

**Comment by sammefford** [comment]
I'm sorry this fell off my radar.  I think you're looking for DocumentPatchBuilder.insertFragment.  If there were a DocumentMetadataPatchBuilder.insertFragment, I'm not sure what it would do.  Does DocumentPatchBuilder.insertFragment meet your needs?

**Comment by georgeajit** [comment]
We have tests for DocumentPatchBuilder.insertFragment.  Closing this issue.
