### ISSUE TITLE
3.0.6 maven jar is corrupt

### ISSUE THREAD

**Issue by bsdang** [marklogic/java-client-api#543]
Using latest 3.0.6 jar

<dependency>
    <groupId>com.marklogic</groupId>
    <artifactId>java-client-api</artifactId>
    <version>3.0.6</version>
</dependency>

maven build fails  error reading /Users/bdang/.m2/repository/com/marklogic/java-client-api/3.0.6/java-client-api-3.0.6.jar; error in opening zip file.

Jar is downloaded to maven repository, but seems to be corrupt

bdang:api bdang$ ls -ltr /Users/bdang/.m2/repository/com/marklogic/java-client-api/3.0.6/
total 872
-rw-r--r--  1 bdang  1258547899     352 Nov  9 20:43 java-client-api-3.0.6.pom.lastUpdated
-rw-r--r--  1 bdang  1258547899   12098 Nov  9 20:43 java-client-api-3.0.6.pom
-rw-r--r--  1 bdang  1258547899  421888 Nov  9 20:44 java-client-api-3.0.6.jar
-rw-r--r--  1 bdang  1258547899     352 Nov  9 20:44 java-client-api-3.0.6.jar.lastUpdated
-rw-r--r--  1 bdang  1258547899     253 Nov 10 10:22 _remote.repositories
bda

**Comment by sammefford** [comment]
I got the same error when I tried the jar from http://developer.marklogic.com/maven2/com/marklogic/java-client-api/3.0.6/.  I'll report that.  In the mean-time, could you remove your repository identifier from your pom.xml?  That should let it pull the version from maven central.  I don't get the error with the jar from https://mvnrepository.com/artifact/com.marklogic/java-client-api/3.0.6
