### ISSUE TITLE
data types on parameter binding 

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#545]
Not tagged correctly in the Optic client.

**Comment by ehennum** [comment]
Parameters should be binding correctly now.  

For sem.iri values, I had to check in a fix to the REST API as well.  You should, however, be able to test bindings on Xs*Val values without needing a new server build.

**Comment by georgeajit** [comment]
Refer to issue https://github.com/marklogic/java-client-api/issues/528
