### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#546]
In the interest of being more like other GitHub projects, we should put release-specific notes on each release’s landing page and the most important general info about the project in the README.

README:
- What is this thing? 
- How do I install it? 
- What’s the Day 0 “Hello, world!” interaction
- Where can I go for more information?
- Legal disclaimers

Release landing page:
- One or two-sentence blurb about the release
- Specific features with links to issues/PRs/commits

**Comment by jmakeig** [comment]
@sammefford Should this belong to docs, dev, QA?

**Comment by sammefford** [comment]
I was planning to keep this in dev

**Comment by sammefford** [comment]
@jmakeig could you please review [README.md](https://github.com/marklogic/java-client-api/blob/develop/README.md) and [release_4.0.0.md](https://github.com/marklogic/java-client-api/blob/develop/release_notes/release_4.0.0.md)?  My idea was that we'd post the contents of release_4.0.0.md in the github release description when we create it.

**Comment by jmakeig** [comment]
Instead of `release_M.m.p.md`, why not just a top-level `CHANGELOG.md` that we append to each release? That seems to be the more broadly adopted technique.

**Comment by sammefford** [comment]
I'm ok with that.  Is there any advantage other than broadly adopted?  Would it be reasonable to add each release to the top rather than the bottom?

**Comment by jmakeig** [comment]
> Is there any advantage other than broadly adopted?

That’s sufficient enough for me.

> Would it be reasonable to add each release to the top rather than the bottom?

Yes, I’d expect to read the document in reverse chronological order, interspersing major versions potentially out of order, i.e. a minor release to a previous major version.

**Comment by sammefford** [comment]
> Yes, I’d expect to read the document in reverse chronological order, interspersing major versions potentially out of order, i.e. a minor release to a previous major version.

I don't understand.  Could you elaborate?

**Comment by jmakeig** [comment]
v3.2.0
* Baz (#️⃣333)
* Blah (#️⃣334)

v4.0.1
* Things (#️⃣223)
* Stuff (#️⃣344)

v3.1.7
* Foo (#️⃣123)
* Bar (#️⃣99)

**Comment by sammefford** [comment]
ok, I get it.  You're saying keep it chronological even though that's not always the order someone might expect for minor versions.

**Comment by sammefford** [comment]
Justin, please take a look at CHANGELOG.md and let me know if there is anything I can improve.

**Comment by gvaidees** [comment]
Can this be closed?
