### ISSUE TITLE
Add support for Capability "node-update"

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#550]
A new capability has been added in support of element level security.  It's called "node-update".  We need to add it to [DocumentMetadataHandle.Capability](https://docs.marklogic.com/javadoc/client/com/marklogic/client/io/DocumentMetadataHandle.Capability.html).  I'm thinking we'll call it NODE_UPDATE.

**Comment by grechaw** [comment]
:+1:

**Comment by sammefford** [comment]
Ajit, I don't have a unit test that validates this as working through to the rest layer.  Could you make a regression test for that?

**Comment by sammefford** [comment]
For QA we need to write a document with metadata that says a permission gives a specific role the node-update capability.  Also we should read the metadata for the document and see that it has that permission with that roles assigned node-update capability.
