### ISSUE TITLE
Write job metadata by default

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#552]
When bulk loading data it’s helpful (and often required) to track metadata about the load itself. For example to identify a job by name, track the source system, etc.

DMSDK should add the job name as a metadata field for every update, including inserts and transformations. (The latter can be tricky in the case of updating multiple documents.) It must be possible for a user to override this to _not_ insert any metadata or extend the default with her own.

Related tangentially to #441.

**Comment by jmakeig** [comment]
Related to #612.

**Comment by jmakeig** [comment]
Need to start with a how-to recipe on how you’d do this today and then later automate something out-of-the-box.

**Comment by ehennum** [comment]
Superseded by DHF.
