### ISSUE TITLE
Emit JavaDoc for generated interfaces and methods

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#555]
The build process that generates proxy functions should extract the documentation for the proxied functions and emit JavaDoc.

Similarly, the build process should generate JavaDoc for interfaces and other methods, possibly using a lookup file.

**Comment by sammefford** [comment]
Could you comment on what the generated javadocs might look like?  Usually I'm not a fan of generated javadocs because they can't communicate anything the javadoc tool already knows from the code.  But I'm guessing you have something in mind here that will enlighten people who read these javadocs.

**Comment by ehennum** [comment]
We'll need to do a review to catch holes and, per Sam's comment, tolerate a few rough edges for now.  (It is clear that the documentation explains the equivalent server function.)

But, in general, the documentation of the Optic expression functions and pipeline methods provides a lot of good guidance.

**Comment by georgeajit** [comment]
Able to generate Java docs for different Optics types, methods in client.expression package. Doc defects found on individual pages will be in Bug Track / Git as separate issues.
