### ISSUE TITLE
Removing the canonical  class name from the document when using PojoRepository

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/java-client-api#558]
This is a question - 

I was testing the PojoRepository.write and noticed that the documents are created with the canonical name of the class. Is there a way I can use the simple name of the class?

Say for example, instead of having this

```json
{
  "org.sanju.ml.client.odm.pojo.QuoteRequest": {
    "id": "Q-12-01-2015-123-123",
    "symbol": "AAPL",
    "quantity": 120,
    "client": {
      "org.sanju.ml.client.odm.pojo.Client": {
        "id": "C110",
        "account": {
          "org.sanju.ml.client.odm.pojo.Account": {
            "id": "A-100-1100"
          }
        }
      }
    }
  }
}
```

Can I have this?

```json
{
  "id": "Q-12-01-2015-123-123",
  "symbol": "AAPL",
  "quantity": 120,
  "client": {
    "id": "C110",
    "account": {
      "Account": {
        "id": "A-100-1100"
      }
    }
  }
}
```

Also, how do I control the URI of the document when I use PojoRepository?

**Comment by sammefford** [comment]
> Is there a way I can use the simple name of the class?

You definitely can.  I would recommend you use JacksonDatabindHandle for that.  That way you'll have full control over the serialization.  PojoRepository, on the other hand, is more useful when you don't care about the structure of the persisted content, and are looking at things from a pure POJO perspective.

Please let us know if you find that using JacksonDatabindHandle together with JSONDocumentManager is significantly more difficult than using PojoRepository.  For some related explanation, see [this blog post about io shortcuts](http://www.marklogic.com/blog/io-shortcut-marklogic-java-client-api/), the javadoc section "[Registering New IO Representations for Shortcut Methods](https://docs.marklogic.com/javadoc/client/index.html)", and [JacksonDatabindTest.beforeTest](https://github.com/marklogic/java-client-api/blob/develop/src/test/java/com/marklogic/client/test/JacksonDatabindTest.java#L55-L63) and [JacksonDatabindTest.JsonCityWriter ](https://github.com/marklogic/java-client-api/blob/develop/src/test/java/com/marklogic/client/test/JacksonDatabindTest.java#L74-L96).

> Also, how do I control the URI of the document when I use PojoRepository?

Again, that's more in your control when you use JSONDocumentManager.  With PojoRepository you only control which property to annotate with @Id and the values in those properties.  If you need more control over the url, please try JSONDocumentManager.

**Comment by sanjuthomas** [comment]
Thanks @sammefford , I will check and confirm.

**Comment by sammefford** [comment]
@sanjuthomas, I'm just checking in--could you use any more help on this issue?

**Comment by sanjuthomas** [comment]
@sammefford  thanks for checking. As you said, there are other ways to achieve what I wanted.
