### ISSUE TITLE
Bulk export to JDBC

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#562]
- Specify a `cts.query` to scope data in MarkLogic
- Transform documents to rows (via Objects?)
- Load into JDBC
- Verify results

Migrated from marklogic/data-movement#11.

**Comment by arthi-ramachandran** [comment]
@sammefford , 4.0.3 release date is Oct 23rd , next Monday. Should this be assigned to to the right tester for ship ?

**Comment by sammefford** [comment]
@arthi-ramachandran , yes, thanks for catching that.  

@vivekmuniyandi, could you take a look at the docs (including the in-line comments) for src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkExportToJdbc.java and see if you have any feedback to improve it?

**Comment by vivekmuniyandi** [comment]
@sammefford Looks good. Shipping it.
