### ISSUE TITLE
Incremental load from JDBC

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#563]
*TODO*

Migrated from marklogic/data-movement#10.

**Comment by sammefford** [comment]
There are at least four scenarios for incremental load:

1. source provides a version number (or last-updated timestamp) with each record
2. source provides a delta file listing the records that changed
3. source provides nothing, so we overwrite everything
4. source provides nothing, but we develop ways to calculate a delta

**Comment by sammefford** [comment]
One big challenge IMO is calculating (in scenario 4) the documents that have been deleted from the source system.  Most solutions only work well on small datasets, but I'd like a solution that works on billions of docs in the dataset.

**Comment by arthi-ramachandran** [comment]
@sammefford , should this be marked as ship for 4.0.3 ?

**Comment by sammefford** [comment]
@arthi-ramachandran, I had to update the docs first.
