### ISSUE TITLE
Move data out of one MarkLogic database and into another

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#567]
As an ETL developer, I want to efficiently move data from one MarkLogic database into another, for example to transform data from a staging environment to production.

* Databases may or may not share the same cluster
* In-database filter/map/reduce on egress and/or ingest
* JVM filter/map/reduce in between

**Comment by georgeajit** [comment]
Verified on nightly regression dated 03/20/2018 on Linux platform. The test ran fine.
