### ISSUE TITLE
convert tabs to spaces in Optic sources

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#572]
The shame of it.

**Comment by jmakeig** [comment]
You should do that in emacs, not vi.

**Comment by kcoleman-marklogic** [comment]
vi > emacs :P

**Comment by ehennum** [comment]
Moral of the story: in Eclipse, it's not enough to set the general tab preference. You must also edit the code template.

Other edifying conclusions can also be made. 

Sending this one your way, Ajit, for form's sake.  The unit tests ran green, so If there are no regressions, the bug can be shipped.

**Comment by georgeajit** [comment]
Ran the tests on MarkLogic Build 02212017 on the local linux box.. PlanGeneratedTest, RowManagerTest and RowRecordTest tests passed.
