### ISSUE TITLE
Verify public release distributions 

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#580]
We had some hiccups in EA3, likely around the merging of the marklogic/data-movement project into this one. Let’s make sure our i's are dotted and t's crossed as we ramp up for GA.

* Compiled code
  * using maven
  * using gradle
* JavaDoc
* Source code
* “Just works” in Eclipse and IntelliJ smoke test

**Comment by kkanthet** [comment]
Verified that we can download the jars from ML maven
