### ISSUE TITLE
GeoSpatialOperator should be GeospatialOperator

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#587]
You're going to hate me for this, but I think camel-casing the word "geospatial" makes us look derpy. It's one word, "geospatial", not "geo spatial". This capitalization is also inconsistent with our other uses of "geospatial", such as `GeospatialIndex` and `GeospatialRegionIndex`.

I'm referring to `com.marklogic.client.StructuredQueryBuilder.GeoSpatialOperator`. 

I apologize for not noticing it before. IDK if this occurs anywhere else in the new interfaces, but if so, those places should also be fixed. 

Maybe it's already too late to fix this, but it'll definitely be too late after 4.0-1 is released. Your call.

**Comment by sammefford** [comment]
Great catch!  I don't hate you :)

**Comment by georgeajit** [comment]
The changes are available in Java Docs and tests on develop branch with source checked on 01/16/2017.
