### ISSUE TITLE
retry() triggering callbacks

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#588]
The test does the following:

1. With batch size set to 3000, adds 200 docs
2. Disables the db
3. Calls flushAsync()
4. Since db is disabled, the writes fail and trigger onBatchFailure callback. The db is enabled after 10 seconds
5. In onBatchFailure callback, the thread is set to sleep for 20 seconds (to make sure the thread wakes up only after the db is enabled)
6. After 20 seconds, retry is called on failed batch.
7. The batch succeeds now but it triggers the onBatchSuccess callback as can be seen in the [client log](https://github.com/marklogic/java-client-api/files/638407/exception.txt). The test fails at line Assert.assertFalse(successCalled.get());

```
@Test
	public void testRetry() throws Exception{
		
		final String query1 = "fn:count(fn:doc())";
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue()==0);
		AtomicBoolean successCalled = new AtomicBoolean(false);
	 	Map<String,String> properties = new HashMap<>();
      	
	 	ihbMT =  dmManager.newWriteBatcher();
	 	ihbMT.withBatchSize(3000);
		
	 	ihbMT.onBatchSuccess(
		        batch -> {
		        	successCalled.set(true);
		         	System.out.println("Success Batch size "+batch.getItems().length);
		        	for(WriteEvent w:batch.getItems()){
		        		System.out.println("Success "+w.getTargetUri());
		        	}
		        })
		        .onBatchFailure(
		          (batch, throwable) -> {
		        	  	throwable.printStackTrace();
		        	 	System.out.println("Failure Batch size "+batch.getItems().length);
			        	for(WriteEvent w:batch.getItems()){
			        		System.out.println("Failure "+w.getTargetUri());
			        	}
			        	try {
							Thread.currentThread().sleep(20000L);
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
			        	ihbMT.retry(batch);
		          });
		
		dmManager.startJob(ihbMT);
		for (int j =0 ;j < 200; j++){
			String uri ="/local/json-"+ j;
			ihbMT.add(uri, stringHandle);
		}

		properties.put("enabled", "false");
		changeProperty(properties,"/manage/v2/databases/"+dbName+"/properties");
		Thread.currentThread().sleep(2000L);
		ihbMT.flushAsync();
		Thread.currentThread().sleep(10000L);
		
		properties.put("enabled", "true");
		changeProperty(properties,"/manage/v2/databases/"+dbName+"/properties");
		ihbMT.awaitCompletion();
	Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue()==200);
		Assert.assertFalse(successCalled.get());
    }
```

**Comment by srinathgit** [comment]
Also , if the snippet below if removed from onBatchFailure callback, the retry fails but it doesn't trigger the onBatchFailure callback again
```
try {
	Thread.currentThread().sleep(20000L);
	} catch (Exception e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
```

**Comment by sammefford** [comment]
It is intended behavior that retry calls the success callbacks.  I'm wondering if that's too confusing to have it not call the failure callbacks but to still call the success callbacks.  In general, retry is meant to be called in a failure callback when a failure has prevented the success callbacks from being called.  So the success callbacks should only be called once per batch no matter how many retries it takes to finally succeed with a batch.

**Comment by sammefford** [comment]
It is also intented behavior that a failure on retry does not call the onBatchFailure callback again.  The design is that failure callbacks that want to rety should directly handle any throw exceptions and call retry again as needed, like HostAvailabilityListener does.

**Comment by jmakeig** [comment]
Pinging @kcoleman-marklogic. This sounds like something particularly important to document.

**Comment by sammefford** [comment]
I'll make sure it's in the func spec
