### ISSUE TITLE
Add ability to cancel running Tasks by id

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/java-client-api#596]
Rather than having to have the object in hand, I'd like to be able to cancel a running task by providing the id.

This allow me to cancel long running tasks from a User Interface.

**Comment by sammefford** [comment]
@paxtonhare  is this resolved by #752 and #690?

**Comment by sammefford** [comment]
can't you call `dataMovementManager.stopJob(dataMovementManager.getActiveJob(jobId))`?

**Comment by paxtonhare** [comment]
@sammefford Looks like this will work. I'll just have to make sure and keep that datamovementManager around in memory.

**Comment by sammefford** [comment]
Actually, we're just about to push a change that makes the list of active jobs static so all DataMovementManager instances can access the same list.  We generally try not to keep instance-specific state other than configuration in managers, so this will better align with that approach.

In summary, you should be able to create a new DataMovementManager instance and access the same list of active jobs.
