### ISSUE TITLE
Create an easy-to-use API to specify Facets

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#60]
Including bucketed facets.

The first step is to design this.   Let's create a separate task for implementation, and use this one just for the design.  The design needs to be reviewed by feature team and java-sig community members.

**Comment by sammefford** [comment]
Does this only involve generating options?  What else could this be?

**Comment by grechaw** [comment]
Could this be related to cts query builder rather than Search API?
We know there is a kind of missing functionality for making buckets and ranges

**Comment by sammefford** [comment]
We'd like to think through not just specifying facet options, but also specifying which value or bucket was selected by the end-user on the interactive search application.

**Comment by gvaidees** [comment]
Sam, which milestone should this belong to?

**Comment by sammefford** [comment]
Milestone is TBD

**Comment by jmakeig** [comment]
Part of #732

**Comment by jmakeig** [comment]
Part of ENG-41
