### ISSUE TITLE
NullPointerException counted as failure in Job report

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#601]
The following test uses a 'null' QueryDefinition object and it causes a NullPointerException which is counted as a failure. Is the result correct ?

```
	@Test
	public void testQueryBatcherFailures() throws IOException, InterruptedException
	{	
		QueryManager queryMgr = dbClient.newQueryManager();
		StringQueryDefinition querydef = queryMgr.newStringDefinition();

		querydef = null;

		QueryBatcher batcher = dmManager.newQueryBatcher(querydef).withBatchSize(32).withThreadCount(20);
		batcher.onUrisReady(batch->{
			System.out.println("Success: "+dmManager.getJobReport(queryTicket).getSuccessEventsCount());
			System.out.println("Failure: "+dmManager.getJobReport(queryTicket).getFailureEventsCount());
		});
		batcher.onQueryFailure((throwable)->{
			throwable.printStackTrace();
			System.out.println("Success: "+dmManager.getJobReport(queryTicket).getSuccessEventsCount());
			System.out.println("Failure event: "+dmManager.getJobReport(queryTicket).getFailureEventsCount());
			System.out.println("Failure batch: "+dmManager.getJobReport(queryTicket).getFailureBatchesCount());
		});
		
		queryTicket = dmManager.startJob(batcher);
		batcher.awaitCompletion();
	}
```

Client log:

16:51:55.412 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as admin
16:51:56.380 [main] DEBUG c.m.client.impl.JerseyServices - Getting forestinfo as application/json
16:51:57.801 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - (withForestConfig) Using [localhost] hosts with forests for "ApplyTransform"
16:51:57.802 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Starting job batchSize=32, threadCount=20, onUrisReady listeners=2, failure listeners=3
com.marklogic.client.datamovement.QueryBatchException: java.lang.NullPointerException
Success: 0
Failure event: 1
Failure batch: 1
16:51:57.833 [pool-1-thread-1] WARN  c.m.c.d.impl.QueryBatcherImpl - Error iterating to queue uris
16:51:57.833 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Job complete, jobBatchNumber=0, jobResultsSoFar=0
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1.run(QueryBatcherImpl.java:598)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1.run(QueryBatcherImpl.java:537)
	... 3 more

**Comment by srinathgit** [comment]
I get similar result when query execution fails due to 'com.marklogic.client.FailedRequestException' (In this case, the db was momentarily disabled causing the query to fail). The result that I get seem to contradict the definitions for these methods.

- `getFailureEventsCount()` 
   - `QueryBatcher`: the number of batches that we failed to get multiplied by `batchSize`.
- `getFailureBatchesCount()` 
  - `QueryBatcher`: the number of batches that we failed to get.

Client log snippet:

18:07:05.534 [pool-2-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with string query "John AND Bob"
18:07:05.534 [pool-2-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
Success event: 715
Success batch: 143
18:07:05.597 [pool-2-thread-1] DEBUG c.m.client.impl.JerseyServices - Query uris with string query "John AND Bob"
18:07:05.612 [pool-2-thread-1] DEBUG c.m.client.impl.JerseyServices - Getting internal/uris as text/uri-list
DB disabled
com.marklogic.client.datamovement.QueryBatchException: com.marklogic.client.FailedRequestException: Local message: failed to read resource at internal/uris: Internal Server Error. Server Message: XDMP-DATABASEDISABLED: Database ApplyTransform is disabled
Failure event: 1
Failure batch: 1
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to read resource at internal/uris: Internal Server Error. Server Message: XDMP-DATABASEDISABLED: Database ApplyTransform is disabled
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4268)
	at com.marklogic.client.impl.JerseyServices.getResource(JerseyServices.java:2967)
	at com.marklogic.client.impl.JerseyServices.uris(JerseyServices.java:2942)
	at com.marklogic.client.impl.QueryManagerImpl.uris(QueryManagerImpl.java:203)
	at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:446)
	... 3 more
18:07:06.534 [main] INFO  c.m.c.d.impl.QueryBatcherImpl - Job complete, jobBatchNumber=144, jobResultsSoFar=715

**Comment by gvaidees** [comment]
@sammefford, I am not sure if this is a candidate for EA4. Should this be marked for 1.0-1? @srinathgit, Do you agree?

**Comment by srinathgit** [comment]
@gvaidees I agree. Also, I think this issue should be classified as a 'question' . I don't see that label .

**Comment by sammefford** [comment]
Counting these both as failures is expected behavior.  But the NullPointerException is undesirable, so I'll fix that.

**Comment by srinathgit** [comment]
So in case of query failure, is there a scenario where values of getFailureEventsCount() and getFailureBatchesCount()  be different  ?

**Comment by sammefford** [comment]
No, I expect them to always be the same.

**Comment by sammefford** [comment]
Ok, I addressed the NullPointerException in commit 401b5858950b26ae4cbf1e07561d84afbe87170e .  Now you will get an IllegalArgumentException if you try to pass null to newQueryBatcher (as well as many other methods)

**Comment by srinathgit** [comment]
Verified that exception is thrown when 'querydef ' is null

**Comment by sammefford** [comment]
you mean IllegalArgumentException is thrown when 'querydef' is null, correct?

**Comment by srinathgit** [comment]
yes, I meant "IllegalArgumentException "
