### ISSUE TITLE
rename sequence factory methods from *s() to *Seq()

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#605]
Per decision at the feature team.

**Comment by ehennum** [comment]
This commit finishes the rename started as part of the refactored code generation.

To fix up tests, the following global search and replace regex should work:

match:
    (\.(?:aggregate|col|joinKey|object|pattern|predicate|sortKey|subject|xmlAttribute))s\(

replace:
    $1Seq(

If you run into issues with the regex global search and replace, here are the individual renames:
 
    .aggregates( -> .aggregateSeq(
    .cols( -> .colSeq(
    .joinKeys( -> .joinKeySeq(
    .objects( -> .objectSeq(
    .patterns( -> .patternSeq(
    .predicates( -> .predicateSeq(
    .sortKeys( -> .sortKeySeq(
    .subjects( -> .subjectSeq(
    .xmlAttributes( -> .xmlAttributeSeq(

Hoping that simplifies the test fixup.

**Comment by georgeajit** [comment]
Thanks Erik for the RegEx.
Made the required changes to tests.
