### ISSUE TITLE
Create an easy-to-use API to specify Sorts for search

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#61]
The first step is to design this. Let's create a separate task for implementation, and use this one just for the design.  The design needs to be reviewed by feature team and java-sig community members.

**Comment by nikos** [comment]
Any chances to get this implemented in the near future?

Cross-reference to an discussion about a related topic on stackoverflow: http://stackoverflow.com/questions/31162556/specify-dynamic-sort-order-with-structuredquerybuilder

**Comment by jmakeig** [comment]
[Specify dynamic sort order with StructuredQueryBuilder](http://stackoverflow.com/questions/31162556/specify-dynamic-sort-order-with-structuredquerybuilder)

**Comment by gvaidees** [comment]
Sam,which milestone should this belong to?

**Comment by sammefford** [comment]
Milestone is TBD

**Comment by jmakeig** [comment]
Part of #732

**Comment by jmakeig** [comment]
Part of ENG-41
