### ISSUE TITLE
Add some fields to JobReport

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/java-client-api#612]
I'd like to see:

- startTime
- endTime
- jobId
- a map for me to put my generic stuff. perhaps Map<String, String>

With start and end time I can compute how long a job ran.

With jobId i can update a job in MarkLogic based on the jobId. Let's say I start a job and insert the JobReport immediately into MarkLogic. Now clients can see that the job has started. Then when it finished I update the doc in MarkLogic with a finished time.

The map lets me put arbitrary stuff into the Report. Perhaps I want to store a description. Or maybe I want to store my favorite color.

**Comment by jmakeig** [comment]
Should we add persisting this as a baked in option, rather than rolling it yourself?

**Comment by sammefford** [comment]
I like the idea of Map<String,String> rather than Map<String,Object> so we could persist that metadata in the server document metadata values.  

As far as persisiting this, we could persist it once at job start and once at job end.  And we could perhaps allow configuration options to persist at an interval.  We just need to be clear that we don't want to expect the persisted JobReport counts to be real-time up-to-date.

**Comment by jmakeig** [comment]
There are two related issues here:

1. Tracking the metadata with the job (this is different than per-document metadata, to state the obvious)
1. Persisting the job report to the database

A clever developer could figure out how to do 2 if we provide an easy way to get to this data, such as the `JobReport`. We might want to roll this into an optional feature, such that the Java API could automatically persist this data. I think 1 is useful even without 2, though. (What’s in `JobReport` today, i.e. 4.0-1?)

**Comment by jmakeig** [comment]
Note that `Map<String,String>` can also serialize losslessly to the new document metadata fields, though I'm not sure that would be the implementation.

**Comment by sammefford** [comment]
Here's what's in JobReport for EA4, and most likely for 4.0.1:

```
/**
 * A Job report is used to report status on a {@link WriteBatcher} or a {@link QueryBatcher}
 * job at any point of time after it is started and provide a
 * snapshot of the job's status at that time.
 */
public interface JobReport {
  /**
   * {@link WriteBatcher} : gets the number of documents written to the database<br>
   * {@link QueryBatcher} : gets the number of uris read from the database_
   * @return the number of events that succeeded
   */
  long getSuccessEventsCount();
  /**
   * {@link WriteBatcher} : gets the number of documents that were sent but failed to write<br>
   * {@link QueryBatcher} : gets the number of query attempts that failed
   * @return the number of events that failed
   */
  long getFailureEventsCount();
  /**
   * {@link WriteBatcher} : gets the number of batches written to the database<br>
   * {@link QueryBatcher} : gets the number of batches of URIs read from the database
   * @return the number of batches that succeeded
   */
  long getSuccessBatchesCount();
  /**
   * {@link WriteBatcher} : gets the number of batches that the job failed to write<br>
   * {@link QueryBatcher} : gets the number of batches of URIs that the job failed to retrieve
   * @return the number of batches that failed
   */
  long getFailureBatchesCount();
  /**
   * Gets the status of the job whether it has been completed or not
   * @return the completion status of the job
   */
  boolean isJobComplete();
  /**
   * Gets the timestamp at which this instance of JobReport was created
   * @return the timestamp of the JobReport
   */
  Calendar getReportTimestamp();
}
```

**Comment by sammefford** [comment]
I broke out persisting into a separate task: #852

**Comment by sammefford** [comment]
For this one I think all we're missing is job start time and end time.  Let's add the Map<String,String> to whatever we create for #852.
