### ISSUE TITLE
Update copyrights to 2017

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#613]

**Comment by kcoleman-marklogic** [comment]
Do we not need to do this for EA4?

**Comment by sammefford** [comment]
I don't think so.  We usually only ship binaries for EA4, and this is just about the copyrights in the sources.

**Comment by kcoleman-marklogic** [comment]
There's also this, which is what prompted me to ask:

https://github.com/marklogic/java-client-api/blob/develop/pom.xml#L65

It's the footer on the javadoc pages. I'll leave it to you to sort, one way or another. I am always confused about which things get the lawyers in a dither and which things do not.
