### ISSUE TITLE
Add onCompletion support

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#614]
Right now the only way to know that a QueryBatcher is finished is to  call awaitCompletion().  But in some asynchronous apps this is not desirable.  Instead, it is desirable to be able to register a listener with something like onCompletion.

**Comment by sammefford** [comment]
@paxtonhare requested this for [Data Hub Quickstart](https://marklogic.github.io/marklogic-data-hub/).  Here's the temporary work-around I offered in the meantime:

```
new Thread(() -> {
  batcher.awaitCompletion();
  ... do something ...
}.start();
```

**Comment by sammefford** [comment]
At first I thought this wouldn't be needed for WriteBatcher because the calling application presumably knows when it's done calling add/addAs.  However, I can see a scenario where after done calling add/addAs one might want to call flushAsync then wait for an onCompletion listener to trigger rather than call flushAndWait or awaitCompletion.  So I'm suggesting we could also have this on WriteBatcher.  We should document, however, that this could be triggered multiple times for a WriteBatcher (every time the queue is emptied) vs only one time on a QueryBatcher (when the query matches or iterator items are exhausted)

**Comment by sammefford** [comment]
Related to #612

**Comment by ehennum** [comment]
Implemented by QueryBatcher.onJobCompletion().  See:

https://docs.marklogic.com/javadoc/client/com/marklogic/client/datamovement/QueryBatcher.html#onJobCompletion-com.marklogic.client.datamovement.QueryBatcherListener-
