### ISSUE TITLE
Allow QueryBatcher to be restarted

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#616]
Currently QueryBatcher only supports a consistent snapshot for a single successful run.  If a job is stopped and needs to be re-run, it has no way to run at the same snapshot as a previous run.  While in the future we may specify the server timestamp on the QueryDefinition (#457), there's currently no way to guarantee the forests will be queried in the same order, so batch numbers won't match. Let's provide a way so a job can be restarted and pick back up where it left off with confidence that the documents will come back in the same order if queried with the same server timestamp.

We'll need a way to provide a query batcher with the server timestamp and a start per forest.  That way it can use the provided server timestamp rather than get the server timestamp from the first response.  And it can start per-forest pagination at the start for each forest.  Perhaps we should do this in conjunction with [built-in job status tracking](https://github.com/marklogic/java-client-api/issues/612#issuecomment-268379179).

**Comment by sammefford** [comment]
As part of adding this capability we should add a recipe showing how to use it

**Comment by jmakeig** [comment]
The more interesting pause/restart scenario for me is when the JVM goes away.
