### ISSUE TITLE
QA FilteredForestConfig

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#617]
Load-balancing support keeps coming up in support cases, particularly ELB.  Let's verify that using FilteredForestConfig.withWhiteList and withRenamedHosts works as expected in an ELB environment.

**Comment by kkanthet** [comment]
* Sticky transactions -- using xcc and java-client
* Requests via ELB to multi-node cluster using mlcp, dmsdk(write & read)

**Comment by kkanthet** [comment]
waiting for the bug#642 to be fixed to test read and write using ELB.

**Comment by srinathgit** [comment]
Verified that requests (read and write) via ELB  to multi node cluster works with FilteredForestConfig.withWhiteList and withRenamedHosts .
