### ISSUE TITLE
Create an easy-to-use API to specify Projections & Snippets for search

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#62]
Initial output is just the design

**Comment by sammefford** [comment]
Maybe we just start with extract-document-data.

**Comment by gvaidees** [comment]
Sam, I have assigned 3.0-6 as the milestone for this. Please change it milestone  as appropriate

**Comment by sammefford** [comment]
Milestone is TBD

**Comment by jmakeig** [comment]
Part of #732

**Comment by jmakeig** [comment]
Part of ENG-41
