### ISSUE TITLE
DeleteListener doesn't delete all documents

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/java-client-api#623]
Only a portion of the documents is being deleted using this code:

```
 Set<String> uris = new HashSet<>();

        BufferedReader reader = new BufferedReader(new FileReader(file));
        QueryBatcher performDelete = dataMovementManager.newQueryBatcher(reader.lines().iterator())
                .withThreadCount(2)
                .withBatchSize(99)
                .withConsistentSnapshot()
                .onUrisReady(new DeleteListener())
                .onUrisReady(batch -> uris.addAll(Arrays.asList(batch.getItems())))
                .onQueryFailure(exception -> exception.printStackTrace());

        JobTicket ticket = dataMovementManager.startJob(performDelete);
        performDelete.awaitCompletion();

        dataMovementManager.stopJob(ticket);
```

**The size of the uris set is 491 (which matches the number of uris that the iterator provides from the file on disk) while I only see 61 documents being deleted after the job is done. Any ideas? Using the code on develop branch from today.**

My unit test:
```
...
DataExport export = new DataExport(dbClient);


StringQueryDefinition qd = queryMgr.newStringDefinition();
String queryPizzaRestaurant="Type:restaurant pizza";
...

 @Test
    void deletePizzeriaRestaurants() throws IOException {
        String pathname="uriCache.txt";

        qd.setCriteria(queryPizzaRestaurant);
        qd.setOptionsName("all");

        ArrayList foundUris =export.getUris(qd);

        export.writeUrisToDisk(qd);

        File file = new File(pathname);
        assertTrue(file.exists());

        ArrayList deletedUris = export.deleteDocuments(qd,pathname);

        assertTrue(foundUris.size()==deletedUris.size());

        file.delete();
    }
```

My DataExport class (has the method called from the unit test):

```
package com.marklogic.se.dach.dmsdk;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.datamovement.*;
import com.marklogic.client.query.StringQueryDefinition;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by smitrovi on 11/01/2017.
 */
public class DataExport {
    private DataMovementManager dataMovementManager;
    public DataExport(DatabaseClient dbClient) {
        dataMovementManager = dbClient.newDataMovementManager();
    }

    public ArrayList getUris(StringQueryDefinition query) {

        Set<String> uris = new HashSet<>();

        QueryBatcher getUris = dataMovementManager.newQueryBatcher(query)
                .withBatchSize(5000)
                .onUrisReady(batch -> uris.addAll(Arrays.asList(batch.getItems())))
                .onQueryFailure(exception -> exception.printStackTrace());
        JobTicket getUrisTicket = dataMovementManager.startJob(getUris);
        getUris.awaitCompletion();
        dataMovementManager.stopJob(getUrisTicket);
        return new ArrayList(uris);
    }

    public ArrayList writeUrisToDisk(StringQueryDefinition query) throws IOException {
        Set<String> uris = new HashSet<>();

        FileWriter writer = new FileWriter("uriCache.txt");
        QueryBatcher getUris = dataMovementManager.newQueryBatcher(query)
                .withBatchSize(100)
                .onUrisReady( new UrisToWriterListener(writer) )
                .onUrisReady(batch -> uris.addAll(Arrays.asList(batch.getItems())))
                .onQueryFailure(exception -> exception.printStackTrace());
        JobTicket getUrisTicket = dataMovementManager.startJob(getUris);
        getUris.awaitCompletion();
        dataMovementManager.stopJob(getUrisTicket);
        writer.flush();
        writer.close();

        return new ArrayList(uris);
    }

    public ArrayList deleteDocuments(StringQueryDefinition query, String file) throws FileNotFoundException {
        Set<String> uris = new HashSet<>();

        BufferedReader reader = new BufferedReader(new FileReader(file));
        QueryBatcher performDelete = dataMovementManager.newQueryBatcher(reader.lines().iterator())
                .withThreadCount(2)
                .withBatchSize(99)
                .withConsistentSnapshot()
                .onUrisReady(new DeleteListener())
                .onUrisReady(batch -> uris.addAll(Arrays.asList(batch.getItems())))
                .onQueryFailure(exception -> exception.printStackTrace());

        JobTicket ticket = dataMovementManager.startJob(performDelete);
        performDelete.awaitCompletion();

        dataMovementManager.stopJob(ticket);

        return new ArrayList(uris);
    }
}
```

**Comment by sammefford** [comment]
Side-note, you can't use an unsynchronizred collection such as HashSet in a listener, since the listener code must be thread-safe.  I'm not saying that is the primary problem, but it may throw things off a bit.

**Comment by sammefford** [comment]
How many nodes?  How many forests?  Do you have your merge timestamp set as in https://docs.marklogic.com/guide/app-dev/point_in_time#id_32468 ?

**Comment by sammefford** [comment]
I see that my javadocs are partially at fault.  While I do have a section describing the need to use synchronized collections in listeners, I had an example breaking that rule and using an unsynchronized collection in the QueryBatcher javadocs.  I'll fix that.

**Comment by sashamitrovich** [comment]
Yes, took the example from javadocs. 1 node, 3 forests, timestamp is set.

**Comment by sashamitrovich** [comment]
Not sure what you mean with unsynchronized collections - the collections return correct number of elements. If you mean the BufferReader iterator is unsynchronized, I'd agree with that. 

Do you have a sample code that will fix this, or I should wait for the next release (when?).

**Comment by srinathgit** [comment]
Sasha,

Please change your deleteDocuments method as provided below. This test passes for me.

```
 public ArrayList deleteDocuments(StringQueryDefinition query, String file) throws FileNotFoundException {
        Set<String> uris = Collections.synchronizedSet(new HashSet<String>());

        BufferedReader reader = new BufferedReader(new FileReader(file));
        QueryBatcher performDelete = dataMovementManager.newQueryBatcher(reader.lines().iterator())
                .withThreadCount(2)
                .withBatchSize(99)
                .withConsistentSnapshot()
                .onUrisReady(new DeleteListener())
                ..onUrisReady((batch) -> {
                	  synchronized(uris){
                		  uris.addAll(Arrays.asList(batch.getItems()));
              		}
                })
                .onQueryFailure(exception -> exception.printStackTrace());

        JobTicket ticket = dataMovementManager.startJob(performDelete);
        performDelete.awaitCompletion();

        dataMovementManager.stopJob(ticket);

        return new ArrayList(uris);
    }
```

**Comment by sammefford** [comment]
+1 to Srinath's example, you need to wrap your HashSet constructor with Collections.synchronizedSet().  I believe, however, that you won't need the explicitly synchronized block because addAll should be synchronized by the synchornizedSet wrapper.  You don't need to worry about the iterator (or the BufferedReader which backs it) because it's only read by one thread, so it doesn't need to be thread-safe like the code in the listeners.  I'm adding mention of that to the javadocs.  Please let us know if Srinath's suggestion resolves this issue for you.

**Comment by sashamitrovich** [comment]
@sammefford, @srinathgit, the test passes when using the synchronizedSet. The number of lines in the static file with uris matches the number of elements in the uris collection.

However, the documents do not get deleted. I must be doing something wrong.

@srinathgit , can you please check if your documents actually do get deleted form the database?

**Comment by sashamitrovich** [comment]
I've narrowed down my issue: it's with the document URIs. Checked the access log and realized that the some of the special characters that I have in my URIs (space, '&'...) was causing the rest delete calls to fail.

So, guys, I apologize for panicking, the issue is on my side.

One side-note to think about: I was able to add documents with "funny" URIs using the DMSDK and I'm not able to delete them using DMSDK.

**Comment by sammefford** [comment]
I see two potential issues, then.  

1. You should see an error that says "Exception thrown by an onUrisReady listener" in the logging if a document is not deleted.  Are you seeing this?
2. As you mention, if you can insert the docs, you should be able to delete them using DeleteListener.

**Comment by sashamitrovich** [comment]
1. No, not seeing this.
2. Agreed.

**Comment by sammefford** [comment]
I've committed a fix to the develop branch.  The delete REST call was double-encoding uris.  For uris that didn't need encoding, it worked fine.  But it explains why your uris with special characters weren't working.  I found some related issues, including #634 which will require more testing to see what's happening with accented characters in uris.  And I logged an issue against the REST API to throw an error when a DELETE request can't find the docs requested.

Please let me know if you have what you need WRT this issue.

**Comment by srinathgit** [comment]
Shipping the bug as the documents are deleted after using synchornizedSet .
