### ISSUE TITLE
Building a query with the extract-document-data element specified in the query options causes Warn level messages to be logged

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#627]
Port [fix](https://github.com/marklogic/java-client-api/commit/d852f3bda86f99f5a4f8f3e3f4700e3b32c1bc8b) for #423 to 3.x branch

**Comment by sammefford** [comment]
Fixed in 7ee7589e5c68526a87bd98ea7359cb4c76ee55fa

**Comment by georgeajit** [comment]
Closed.
