### ISSUE TITLE
move getServerTimestamp from QueryEvent to QueryBatch

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#629]
getServerTimestamp is never set when a query fails, but that's what QueryEvent is used for when it's not a QueryBatch.  So let's just keep getServerTimestamp on QueryBatch since that's the only place it's used.

**Comment by georgeajit** [comment]
Test in this commit. 

https://github.com/marklogic/java-client-api/commit/d6e540fa20d4695c60cd16e50ae267257fa50976
