### ISSUE TITLE
Create an easy-to-use API to specify QText (end-user search box input) for search

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#63]
This is the ability to specify both end-user search from a search box and programmatic structured queries built using StructuredQueryBuilder.  Right now a user cannot do that.  The work-arounds are to either 
1. build their own RawCombinedQueryDefinition from scratch, or
2. piece together a RawCombinedQueryDefinition with a portion injected from structuredQueryDefinition.serialize() as described [here](http://stackoverflow.com/questions/31162556/specify-dynamic-sort-order-with-structuredquerybuilder), or
3. use the undocumented/unsupported [CombinedQueryBuilder](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/impl/CombinedQueryBuilder.java)

**Comment by sammefford** [comment]
Implementation detail: we'd need to decide whether to send this over as a "q" parameter or as a "qtext" element in a combined query.

**Comment by grechaw** [comment]
Not completely an implementation detail -- including in payload is more forward compatible.

**Comment by sammefford** [comment]
By payload I'm guessing you mean the qtext element in a combined query?  Could you describe how that would be more forward-compatible?

**Comment by georgeajit** [comment]
To be tested in post EA 4.

**Comment by sammefford** [comment]
QA: we need to test the following:

1. create a StructuredQueryDefinition (using StructuredQueryBuilder) and add a string query by calling setCriteria and withCriteria 
2. create a RawStructuredQueryDefinition and add a string query by calling setCriteria and withCriteria 
3. create a RawCombinedQueryDefinition and add a string query by calling setCriteria and withCriteria 
4. create a PojoQueryDefinition (using PojoQueryBuilder) and add a string query by calling setCriteria and withCriteria 

In each case, make sure setCriteria, getCriteria, and withCriteria work.  Make sure a query using those query definitions selects only documents that match both the query definition and the string query.

**Comment by sammefford** [comment]
@georgeajit , your tests look good.  I added one comment on them.  Also, do you think it would make sense to also add a test of PojoQueryDefinition?

**Comment by georgeajit** [comment]
Assigning this back back Sam, after discussing about PojoQueryDefinition. Need to add ```setCriteria getCriteria  withCriteria``` methods to ```PojoQueryDefinition```

**Comment by sammefford** [comment]
Thanks for pointing this out.  I was confused.  We don't want those methods on PojoQueryDefinition.  We just want them on the types of queries returned by PojoQueryBuilder.  Could you just add at least one test that validates that you can call withCriteria and setCriteria on a StructuredQueryDefinition returned by PojoQueryBuilder?
