### ISSUE TITLE
Support international chars in uris in bulk API

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#634]
Something isn't lining up right when I attempt to write a uri with an accented char in it.

        String uri = "test with accents:á.txt";
        DocumentWriteSet writeSet = docMgr.newWriteSet();
        writeSet.addAs(uri, uri);
        docMgr.write(writeSet);
        DocumentPage docs = docMgr.read(new String[] {uri});
        assertEquals("You should have one and only one doc with uri=[" + uri + "]", 1, docs.size());
        DocumentRecord doc = docs.next();
        assertEquals(uri, doc.getUri());

Here's the wire trace and the assert failure:

```
[DEBUG] wire - >> "POST /v1/documents HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Content-Type: multipart/mixed; boundary=Boundary_31_375466577_1484771172864[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="rest-writer",realm="public",nonce="4357d91933c61edd3537e00a37800740",opaque="b5a6b557ce127c82",qop=auth,uri="/v1/documents",cnonce="e2c82ca5",nc=0000003d,response="07ec8c2959ece7b0db79b4d3187ffb1f"[\r][\n]"
[DEBUG] wire - >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire - >> "Host: localhost:8012[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "9f[\r][\n]"
[DEBUG] wire - >> "--Boundary_31_375466577_1484771172864[\r][\n]"
[DEBUG] wire - >> "Content-Disposition: attachment; filename="BulkReadWriteTest_3888/test with accents:[0xe1].txt"[\r][\n]"
[DEBUG] wire - >> "Content-Type: text/plain[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "5a[\r][\n]"
[DEBUG] wire - >> "BulkReadWriteTest_3888/test with accents:[0xc3][0xa1].txt[\r][\n]"
[DEBUG] wire - >> "--Boundary_31_375466577_1484771172864--[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "0[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 200 Bulk Change Written[\r][\n]"
[DEBUG] wire - << "vnd.marklogic.document-format: xml[\r][\n]"
[DEBUG] wire - << "Content-type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 296[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
[DEBUG] wire - << "<rapi:documents xmlns:rapi="http://marklogic.com/rest-api"><rapi:document><rapi:uri>BulkReadWriteTest_3888/test with accents:[0xc3][0xa1].txt</rapi:uri><rapi:category>metadata</rapi:category><rapi:category>content</rapi:category><rapi:mime-type>text/plain</rapi:mime-type></rapi:document></rapi:documents>[\n]"
13:26:12.890 [main] INFO  c.m.client.impl.DocumentManagerImpl - Reading metadata and content for multiple uris beginning with BulkReadWriteTest_3888/test with accents:▒.txt
13:26:12.890 [main] DEBUG c.m.client.impl.JerseyServices - Getting documents as null
[DEBUG] wire - >> "GET /v1/documents?category=content&uri=BulkReadWriteTest_3888/test%20with%20accents:%C3%A1.txt HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Accept: multipart/mixed; boundary=Boundary_32_1423983012_1484771172894[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="rest-writer",realm="public",nonce="4357d91933c61edd3537e00a37800740",opaque="b5a6b557ce127c82",qop=auth,uri="/v1/documents",cnonce="451fc37d",nc=0000003e,response="1230d669d494e5aa7e2a472ccaa0037c"[\r][\n]"
[DEBUG] wire - >> "Host: localhost:8012[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 200 OK[\r][\n]"
[DEBUG] wire - << "Content-type: multipart/mixed; boundary=Boundary_32_1423983012_1484771172894[\r][\n]"
[DEBUG] wire - << "ML-Effective-Timestamp: 14847739722624270[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 303[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
[DEBUG] wire - << "--Boundary_32_1423983012_1484771172894[\r][\n]"
[DEBUG] wire - << "Content-Type: text/plain[\r][\n]"
[DEBUG] wire - << "Content-Disposition: attachment; filename="BulkReadWriteTest_3888/test with accents:[0xc3][0xa1].txt"; category=content; format=text[\r][\n]"
[DEBUG] wire - << "Content-Length: 47[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
[DEBUG] wire - << "BulkReadWriteTest_3888/test with accents:[0xc3][0xa1].txt[\r][\n]"
[DEBUG] wire - << "--Boundary_32_1423983012_1484771172894--[\r][\n]"
[DEBUG] wire - >> "DELETE /v1/search?directory=/cities/ HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="rest-writer",realm="public",nonce="4357d91933c61edd3537e00a37800740",opaque="b5a6b557ce127c82",qop=auth,uri="/v1/search",cnonce="3c67821e",nc=0000003f,response="efd1023ef657a3be58c48c95a46da770"[\r][\n]"
[DEBUG] wire - >> "Host: localhost:8012[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 204 Deleted[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 0[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
13:26:13.672 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
13:26:13.672 [main] DEBUG c.m.client.impl.JerseyServices - Releasing connection
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.178 sec <<< FAILURE!
test_issue_623(com.marklogic.client.test.BulkReadWriteTest)  Time elapsed: 6.139 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<test with accents:[▒].txt> but was:<test with accents:[á].txt>
```

**Comment by sashamitrovich** [comment]
Had the same issue, had to "normalize" the URIs as a workaround.

**Comment by sammefford** [comment]
It turns out "normalize" (if you mean percent-encode) is the right answer.  According to [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt) a uri should not contain accented (non-ascii) characters unless they are percent-encoded.  So what I need to do here is throw an error when one attempts to create a document with invalid characters in the uri.

**Comment by sammefford** [comment]
Actually, on further reflection, there's nothing to do here in the client layer.  The REST layer chose by design to prevent creation of docs with invalid chars in the uri.  Yet XQuery unfortunately allows uris with invalid chars, so the REST layer allows read/update/delete of those docs, just not create.  The REST layer can determine whether to throw an error because a request is attempting to create a new document, or allow the request because the document was already created via another means (e.g. XQuery).  Java doesn't know whether a write is an update or a create, so an error client-side would be premature.  Therefore, I'm closing this issue.

**Comment by kcoleman-marklogic** [comment]
For mlcp, we just tell people "don't put beans up your nose": http://docs.marklogic.com/guide/mlcp/import#id_29822. I'm planning to do something similar in the DMSDK documentation.

The situation is _slightly_ different because mlcp has knobs for URI construction that don't apply here, but the ultimate answer is the same: Unless mlcp is constructing the URI, the burden is on the user not to feed in values that are not legit URIs.

**Comment by jmakeig** [comment]
> “don't put beans up your nose”

Where should I put them…? Wait, never mind.

**Comment by sammefford** [comment]
Interesting, I read that docs snippet the opposite way.  It seems like mlcp explicitly allows anything (including beans) because it will encode whatever they send on the way in, and decode it on the way out.  I have no nose analogy for an encoded uri, because I'm not sure what is a valid thing to stick up your nose.  DMSDK has two big differences:

1) It is never in charge of writing anything to the file system (even on export), so it doesn't worry about what might be a valid file system file name.  If a DMSDK app wants to write to the file system, they should create their own FileWriter from within an ExportListener onSuccess callback.
2) DMSDK builds on Java client API which builds on REST API which have no history of encoding uris for you, so we probably shouldn't start that now.

So I agree the message should be "don't put beans up your nose", but I'm guessing the docs will look pretty different from the mlcp docs.

**Comment by kcoleman-marklogic** [comment]
DMSDK is a much simpler scenario since it doesn't get into the business of constructing URIs, applying regular expressions to them, blah, blah, blah.

I think all we need to say for DMSDK is that your input URI must be a legitimate URI, which means URI encoding _by the client application_, as needed. Essentially, the following part of what we say for mlcp, suitably adjusted for DMSDK:

> If you supply a URI or URI component, you are responsible for ensuring the result is a legitimate URI. No automatic encoding takes place.

**Comment by jmakeig** [comment]
Can [`java.net.URI`](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) be of assistance in creating a “legitimate URI” or is that overkill?

**Comment by kcoleman-marklogic** [comment]
That's up to the dev. I was playing with it this morning and found it a bit clunky, but that's probably because I'm lazy. 

Which is to say, since we're dealing with URIs and not URLs, I found this mildly annoying, complete with exception handling and so forth.

`new URI(null, null, "/foo/b ar/baz")`

It is probably the surgeon general approved way to deal with it, though.

**Comment by jmakeig** [comment]
@kcoleman-marklogic That’s what I figured. Thanks for the due diligence.
