### ISSUE TITLE
Test connection

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#636]
As a developer I want to debug connection issues. I don't want to have to do any real work (i.e. run a dummy query or test the existence of a document) because that's extra work and potentially introduces other errors. I just want to see if my auth*n and network are configured correctly. 

As an ETL tool maker, I want to provide a "Test Connection" button in my UI.

We should be able to return more than just a Boolean pass/fail. Something like server and client version would be useful. (What else?)

The Client REST API has the undocumented (?) `/v1/ping` endpoint that might be related.

Related to marklogic/node-client-api#346.

**Comment by jmakeig** [comment]
```java
package com.marklogic.datamovement.examples;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.SecurityContext;
import com.marklogic.client.document.DocumentDescriptor;
import com.marklogic.client.document.DocumentManager;

public class TestDefaultLocalhostConnection {

  public static void main(String[] args) {
    final SecurityContext auth = new DatabaseClientFactory.DigestAuthContext(
        "user", "********");
    final DatabaseClient marklogic = DatabaseClientFactory.newClient("localhost",
        8000, auth);
    System.out.println(marklogic.getHost());
    final DocumentDescriptor doc = marklogic.newDocumentManager().exists("¯\_(ツ)_/¯");
    System.out.println(doc); // null
  }

}
```

**Comment by sharpau** [comment]
I was looking for this very thing in the Java API. Something like exposing the /v1/ping endpoint is exactly what I want.

**Comment by georgeajit** [comment]
Tests run fine.

**Comment by rjrudin** [comment]
Can this be closed since the "checkConnection" method now exists in DatabaseClient?

**Comment by ehennum** [comment]
Most definitely.
