### ISSUE TITLE
support DocumentManager.setReadTransform for DocumentManager.search calls

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#639]
Just as we support QueryDefinition.setResponseTransform when a call is made to DocumentManager.search(QueryDefinition, long), we should also support DocumentManager.setReadTransform for those calls.  We should throw an error if both are specified but with different transforms.

**Comment by ltnd** [comment]
+1 on this. 
DocumentManager.setReadTransform is a method available on the Java API but the transform parameter is not sent when calling the search. This should be good as the REST API on ML side allows it.

**Comment by sammefford** [comment]
Ajit, I added a unit test which tries
1) with only documentManager.setReadTransform
2) with both documentManager.setReadTransform and queryDefinition.setResponseTransform set to the same transform

I haven't tested with documentManager.setReadTransform and queryDefinition.setResponseTransform set to different transforms.  I also didn't test using documentManager.setReadTransform and passing in a SearchReadHandle to verify it gets transformed also.  Other than that I'm not seeing anything else to test here.

**Comment by georgeajit** [comment]
Shipping the Task. Pending Git issues on this feature will be handled separately.
