### ISSUE TITLE
QueryBatcher interface missing withForestConfig(ForestConfiguration forestConfig) method

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#640]
Also the interface QueryBatcher.java is missing the method

QueryBatcher withForestConfig(ForestConfiguration forestConfig);

**Comment by sammefford** [comment]
This is because the method is on the parent interface "Batcher".

**Comment by srinathgit** [comment]
The WriteBatcher interface has withForestConfig(ForestConfiguration forestConfig); method. It would be convenient to similarly add the method to QueryBatcher interface as well

**Comment by srinathgit** [comment]
'withForestConfig' method has been added to QueryBatcher interface
