### ISSUE TITLE
startJob(batcher) and stopJob(batcher) can be called multiple times

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#643]
Currently startJob(batcher) and stopJob(batcher) can be called multiple times. Should the user be restricted to call it only once ?

**Comment by sammefford** [comment]
I've never understood why API designers would prevent one from calling something multiple times.  IMO opinion that's pushing unnecessary checking (noise code) into an application.  So I'd like to keep it so they can be called multiple times.
