### ISSUE TITLE
Polling for records past end of results  causes error

### ISSUE THREAD

**Issue by laquereric** [marklogic/java-client-api#644]
I’ve been running some additional tests on the MarkLogic Java API using the 3.0-develop code and I’ve noticed an odd behavior.  It seems as though whenever MarkLogic is queried for a page of results with an index greater than the number of held records (i.e. asking for the XXX Codes with a startIndex of 1mil when only 50k records are present), the MarkLogic server doesn’t populate the extract-resolution-time field in its response. This causes the MarkLogic Java API to throw an error when it attempts to convert the non-existent value of that field into a time.  This commit ( https://github.com/marklogic/java-client-api/commit/7ee7589e5c68526a87bd98ea7359cb4c76ee55fa ) appears to be the cause of the error on the MarkLogic Java API side as before it there was no support the extract-resolution-time element.

**Comment by sammefford** [comment]
Yes, I noticed that, and [fixed it on develop branch](https://github.com/marklogic/java-client-api/commit/484d15ca157a47450dfaac2bf569f46540c0da37).  I'll add a fix to 3.0-develop branch.

**Comment by laquereric** [comment]
The test passes in my machine.

**Comment by georgeajit** [comment]
The unit test passes in nightly regressions. Verified on MarkLogic 8.0 nightly build with Java Client API on develop branch (after 3.0.8 was tagged).
