### ISSUE TITLE
Write a DocumentWriteOperation using WriteHostBatcher

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#647]
As a Java Client user
I want to (issue title)
So that I can write a library that abstracts whether `WriteBatcher` is used or just a `DocumentManager` so that either ML8 or ML9 can be used

- I noticed that `WriteBatcher`, at least on master, does not have a method that takes a `DocumentWriteOperation`.
- I think `DocumentWriteOperation` is one of the better features of the Java Client, since it encapsulates a write request in a single object. Could an `add(DocumentWriteOperation)` method be added to `WriteBatcher`?

**Comment by vivekmuniyandi** [comment]
### QA and Docs:

Have added an overload in WriteBatcher for adding a DocumentWriteOperation

WriteBatcher add(DocumentWriteOperation writeOperation);

**Comment by vivekmuniyandi** [comment]
@georgeajit please assign to Srinath if he is the one responsible for DMSDK. I am not sure who is responsible. Hence I assigned it to you. Thanks.

**Comment by georgeajit** [comment]
Assigning to Kim for documentation.

**Comment by kcoleman-marklogic** [comment]
I don't think this needs additional documentation, beyond what's in the javadoc.

Rob said it is "one of the better features of the Java Client API", but I do not find it referenced ANYWHERE in the javadoc before 4.0.4. That is, it is not passed or returned in any public interface, other than the new overload added by this bug.

It feels almost like an internal interface that  "leaked", which is fine, but it doesn't require extra emphasis in the dev guide, IMO.
