### ISSUE TITLE
Upgrade or remove Jersey

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#65]
Overcome mimepull issues and simplify code
perhaps take advantage of new capabilities such as caching
Will it offer support for POST without a body?

Other option: remove Jersey to reduce dependency conflict with customers who require a different version of Jersey or httpclient or other required libraries

**Comment by jmakeig** [comment]
@sammefford Did anything happen with this? If not, should we move it out of the 3.0-4 milestone?

**Comment by sammefford** [comment]
I should have commented on this issue.  I started the upgrade but was halted by this bug: https://java.net/jira/browse/JERSEY-2882

This issue is not part of the 3.0.4 milestone.

**Comment by bsdang** [comment]
+1 When do we expect this ticket to be implemented?

**Comment by grechaw** [comment]
We already determined that we cannot upgrade jersey -- newer versions have digest auth bugs and development is moribund (?)

I'd take a peek at the referenced #391 -- maybe suggest a path forward.

**Comment by bsdang** [comment]
Ok, then we should move away from Jersey and use Apache HTTPClient. Sooner the better.

**Comment by georgeajit** [comment]
Ran tests with OKHttp in 5.0-SNAPSHOT.jar. The tests run fine. Used MarkLogic Server build 0801 due to REST layer issues in the server side.
