### ISSUE TITLE
Come up with forward and backward compatibility policy for java-client-api

### ISSUE THREAD

**Issue by kkanthet** [marklogic/java-client-api#653]

**Comment by jmakeig** [comment]
As a Java developer, I want to be able to upgrade my MarkLogic applications without having to upgrade both the server and the client at the same time. I want to upgrade one thing at a time, test that everything works, and then move onto the next component, rolling back if necessary. 

**Proposal:** Given that version `X` of the client supports version `A` of MarkLogic, it must be possible for version `Y` of the client (i.e. `X+1`) to run against both versions `A` and `B` (`A+1`) of the Server. This would require a user to upgrade the Server and then the client. There is no requirement the older version of the client, `X`, to support newer functionality of the server supported in `B`. For example, if `B` introduces a new query type. There is no requirement for client `X` to support that. However, there is a requirement for Server `B` not to break backward compatibility for client `X`.

| Client Major Version | Supported Server Major Version |
| -------------------- | -------------------------------- |
| 3.\*.\*  | 8.\*.\* and 9.\*.\*  |
| 4.\*.\*  | 9.\*.\* and 10.\*.\*  |
| 5.\*.\* | 10.\*.\* and 11.\*.\* |

**Comment by kkanthet** [comment]
Attaching the version example matrix, there might be more scenarios to be considered and added to this example.

[client-compatability.xlsx](https://github.com/marklogic/java-client-api/files/859488/client-compatability.xlsx)

**Comment by kkanthet** [comment]
[client-compatability-test-matrix.xlsx](https://github.com/marklogic/java-client-api/files/974857/client-compatability-test-matrix.xlsx)
Updated the reviewed and agreed matrix.
