### ISSUE TITLE
enable dynamic options with a values query

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#659]
I think I'm probably overlooking something really obvious, but I was trying to help someone trying to replicate cts:element-values from Java, and couldn't figure out how to do so without using persistent query options. Combined query doesn't come into it because values isn't A Thing in structured query.

`POST /v1/values{name}` enables you to use dynamic options for a values query. It seems a shame we don't expose a similar ability through the Java API.

Or I'm overlooking something, as I said.

**Comment by sammefford** [comment]
@kcoleman-marklogic Have you tried a RawCombinedQueryDefinition?  I'm thinking that should work, and that's the normal way to supply runtime options.

**Comment by sammefford** [comment]
To be clear, I think you'd pass the RawCombinedQueryDefinition to ValuesDefinition.setQueryDefinition.  I see that we have a unit test for this in RawQueryDefinitionTest.java

**Comment by kcoleman-marklogic** [comment]
OK, so you use the combined query to just define options. Weird, but I agree it should work fine. Thank you.
