### ISSUE TITLE
RawCombinedQueryDefinition does not have setCriteria and withCriteria

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#660]
The RawCombinedQueryDefinition  type does have setCriteria and withCriteria methods.

**Comment by sammefford** [comment]
I must have mis-spoken when I said it should.  The original intent of #63 was to allow use of StructuredQueryBuilder plus a string query without requiring use of RawCombinedQueryDefinition which could always combine a structured query with a string query.  So while it wouldn't hurt to add setCriteria and withCriteria to RawCombinedQueryDefinition, I'm not sure it would actually help.  So let's not worry about adding it if it's not needed.
