### ISSUE TITLE
getCriteria returns the last criteria set on query definition when multiple criteria are set.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#661]
For a query definition such as:
```
// With multiple withCriteria - negative
StructuredQueryDefinition strutdDefNeg = (qb.valueConstraint("popularity", "5")).withCriteria("Vannevar").withCriteria("England");
```
Calling ```strutdDefNeg.getCriteria()```  returns ```England```

Similarily for
```// create query def2 with both criteria methods and check fluent return
StructuredQueryDefinition strutdDef2 = qb.valueConstraint("popularity", "5");
strutdDef2.withCriteria("Vannevar").setCriteria("Bush");
```
Calling ```strutdDef2.getCriteria()``` returns ```Bush```

**Comment by georgeajit** [comment]
Note to QA:
When this issue is fixed/resolved, work on the testcriteria and testwithCriteria methods of TestStructuredQuery.java class, TestRawStructuredQuery class and TestPOJOQueryBuilderContainerQuery class

**Comment by sammefford** [comment]
Calling withCriteria more than once just overwrites the criteria.  There is only one criteria string that you can set.  The REST API only accepts one "q" parameter, so there's no option for Java to send or receive more than one.
