### ISSUE TITLE
atomic parameters of cts.query constructors should be values instead of expressions

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#672]
In particular, column references aren't allowed for cts.query constructors.

**Comment by ehennum** [comment]
Before this fix, atomic parameters of CtsQuery, CtsRegion, and CtsReference constructors in the CtsExpr module were typed as expressions.

After this fix, the atomic parameters are typed as values.

Because the server only accepts values for these constructors, the queries should still work.  The only potential for regression that I can think of would be if the parameters were captured in variables with an expression type.

This fix doesn't require any additional testing. It is just tightening the types to match the actual restrictions on the server and thus prevent one class of error.

**Comment by georgeajit** [comment]
No regressions. Shipping the issue.
