### ISSUE TITLE
add unit test for json-seq

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#675]
use a line reader and parse each line with Jackson

**Comment by ehennum** [comment]
Simply added a unit test for getting the rows as application/json-seq (and, while I was at it, a case for getting text/csv with a data type style of RowSetPart.HEADER).

The expansion of the unit test shouldn't require any additional functional tests, so if there are no regressions, please ship this bug.

**Comment by georgeajit** [comment]
Test runs fine. Test with MarkLogic Server build 20170303.
