### ISSUE TITLE
Race Condition when using withBlackList and withWhiteList methods in FilteredForestConfiguration

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#677]
If two different threads modify forest configuration say one white listing a host and another blacklisting the same host, it could lead to race condition where the host could be added to both white and black list

**Comment by sammefford** [comment]
That should not be the case, of course.  But you've been able to duplicate this?  Can you please share steps to reproduce?

**Comment by sammefford** [comment]
By the way, FilteredForestConfiguration isn't thread safe.  There should never be multiple threads calling one instance of FilteredForestConfiguration.

**Comment by srinathgit** [comment]
FilteredForestConfiguration  isn't thread safe
