### ISSUE TITLE
Too many HTTP 401 Unauthorized responses

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#678]
I observe that WriteBatcher is getting an HTTP 401 Unauthorized response on almost every request.  This is undesirable and will have a large performance impact.  The reason is two-fold:

1. Jersey, our underlying HTTP library [uses ThreadLocal to store the reusable authentication token](https://java.net/jira/browse/JERSEY-542)
2. WriteBatcher.flush* creates a new ThreadPoolExecutor, thus recreating all the internal threads

Therefore, each time someone calls flush* they will lose all their reusable authentication tokens.  Ideally, the authentication token would be stored with the DatabaseClient instance to be reusable cross-thread.

**Comment by grechaw** [comment]
Isn't this expected for digest auth?

Although there's overhead, with large numbers of docs per request the overhead is small.

I don't dispute that there's extra latency and overhead here, but I wonder about measuring impact, and seeing whether alternate auth might work around.  This issue is certainly not new.

**Comment by grechaw** [comment]
Also you might want to just put a link in here that says "moving away from Jersey will solve"

**Comment by sammefford** [comment]
You're right, that when we [replace Jersey](https://github.com/marklogic/java-client-api/issues/65), the replacement might not have this issue.

As far as whether this is expected, yes, to some extent it is.  However, DMSDK uses many more threads than most Java Client API applications have.  Plus, each DMSDK thread might talk to each host in the cluster, so there's a multiplication factor there.  But the main issues here are the clash of (1) and (2) above, where the design of WriteBatcher.flush is a problem because of the way Jersey stores the auth token.

**Comment by grechaw** [comment]
Ah, yes, I see why you might want to fix that

**Comment by sammefford** [comment]
It required a complete rewrite of the logic for awaitCompletion, but I believe the new version fixes this issue and is an all-around improvement.  All unit tests and stress test pass.

**Comment by georgeajit** [comment]
Run the QA functional tests multiple times. Did not see any issues related. Except for known JobReport test and a blacklist test (https://github.com/marklogic/java-client-api/issues/686) , all tests ran fine. Tested on local windows machine.

The nightly regression of 03/08/2017 looks good.
