### ISSUE TITLE
Validate compatibility

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#679]
As a developer, I want a light-weight way to check that I’m able to connect to my MarkLogic cluster (network, authentication) and that my client has been certified to work against the version of the Server to which I’m connecting. (Imagine a UI ETL application implementing a “Test Connection” screen.)

As a Support Engineer, I want to quick way to verify compatibility between a client and a server. 

Closely related to #653.

**Comment by sammefford** [comment]
The main challenge I see is that we may validate an old client version to work against a new server version that didn't exist when the old client version was released.  And vice-versa.  So I wonder if we'd need the compatibility matrix stored in both and a client-server version combination is compatible if either the server or client says it is.

**Comment by jmakeig** [comment]
We can validate the lower bound and report the Server version. The dependency tracking should only be one direction, from client to server.

**Comment by damonfeldman** [comment]
Do we know the expected compatibility yet, particularly of MLSDK with ML X.y where X<9?

**Comment by jmakeig** [comment]
DMSDK requires new server-side functionality and thus will only work against MarkLogic 9. The 4.0 version of the Java Client will run against an 8 version of MarkLogic, but only for the capabilities available in 8, allowing you to upgrade the clients and server independently.

**Comment by ehennum** [comment]
Implemented by DatabaseClient.checkConnection​().  See:

https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClient.html#checkConnection--

and

https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClient.ConnectionResult.html
