### ISSUE TITLE
bad links in javadoc

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#683]
```
[ERROR] ...src\main\java\com\marklogic\client\expression\package-info.java:22: warning - Tag @link: reference not found: com.marklogic.row.RowManager

[ERROR] ...\src\main\java\com\marklogic\client\expression\package-info.java:22: warning - Tag @link: reference not found: com.marklogic.expression.PlanBuilder

[ERROR] ...\src\main\java\com\marklogic\client\row\package-info.java:23: warning - Tag @link: reference not found: com.marklogic.expression.PlanBuilder
```

The javadoc build is also behaving very strangely (on Windows) as of today. It went from taking virtually no time to sitting around contemplating its navel for 3 min. and horking up 3.2G of memory before finally deigning to generate the javadoc. I see no checkins that might explain this, but I've seen it on 2 hosts now. The JVM actually ran out of memory on the doc build machine. (Yes, I know we can give it more.)

I'm hoping (with little reason) that fixing the bad links might sooth the savage beast.

**Comment by sammefford** [comment]
Yes, Erik [added back in the type interfaces to the javadoc](https://github.com/marklogic/java-client-api/commit/af23be58af7f96729514cc459c2693c018f54c52).  That's why it's taking longer and more memory.  Let us know if you're not able to add the extra memory to accommodate.

**Comment by kcoleman-marklogic** [comment]
I cannot seem to give the JVM enough memory to make it succeed on our build machine. I'm sure it's pilot error, but I'm not familiar enough with the ins and outs to figure out what it is. Perhaps something will jump out at you. 

I am doing the following, based on reading that that's how I can pass JVM options through Maven:

`mvn -DjvmArgs="-Xmx4000m" -Dmaven.test.skip javadoc:javadoc`

It is not maven itself that's running out of memory, btw, but javadoc:

` javadoc: error - java.lang.OutOfMemoryError: Please increase memory.`

Perhaps this is not something I can fix outside of the pom?

**Comment by sammefford** [comment]
I tried for myself and I also encountered OutOfMemoryError.  I added <maxmemory>3500m</maxmemory> to the javadoc section in pom.xml and it resolved the issue for me so I committed the change: 25f6fa7a9b8df8d0d6f749ce3addce3f370cb724.  This also resolves part of #674.

**Comment by ehennum** [comment]
Strange -- the JavaDoc builds without issue on my laptop.  Thanks for fixing it, Sam.  Kim, if the POM change that Sam made didn't fix it for you, please send the bug back to me.

**Comment by kcoleman-marklogic** [comment]
It builds on mine without running out of memory, too, though it sure uses up a lot of it.

In any case, my polluting this bug with the memory issue aside, the `@link` issue is still real, so you're going to get this back tomorrow regardless. :)

**Comment by ehennum** [comment]
Thanks, I'll clean up the @ link warnings

**Comment by ehennum** [comment]
That ought to learn me.  I assumed it was bad syntax, but I had left out the .client.  So clever.

Should be good now.

**Comment by kcoleman-marklogic** [comment]
Looks good. I see neither warnings nor out-of-memory errors now. Thank you both very much.
