### ISSUE TITLE
HostAvailabilityListener throws connection refused exception when existing stress test setup is used

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#684]
Java client Stress test was setup with existing workflow / procedures. The restTests.xml includes tests to be run for Datamovement featutre.

The Java client program that runs the stress test produces the following exception:
```
4:15:21.415 [pool-2-thread-1] ERROR c.m.c.d.HostAvailabilityListener - Exception during retry
com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connection to http://rh7v-intel64-90-java-stress-3.marklogic.com:8011 refused
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://rh7v-intel64-90-java-stress-3.marklogic.com:8011 refused
Caused by: java.net.ConnectException: Connection refused
```

This exception is due to the fact that stress test environment consisting of 1 E Node and 2 D Nodes do not have a REST Server running on the 2 D Nodes.

**Comment by sammefford** [comment]
Can you give me client host and server connection details?

**Comment by sammefford** [comment]
Ok, Ajit, try it now.  I made the change in svn and also directly on rh7v-intel64-90-java-stress-1.marklogic.com.  The fix was to pull alternateHosts from all available e-nodes, not just the ones with forests for this database.  In your case, your e-node had no forests for the database, so it wasn't available as an alternateHost.

**Comment by georgeajit** [comment]
The latest stress test changes in SVN fixed this issue. Tested on 03/23/2017 with MarkLogic Server 20170321 build on a 3 node cluster with 2 nodes setup for failover/replication. The Java client program's log file does not have this issue.

HostAvailabilityListener does log an exception when one of the data node goes down via the kill command executed through cron job.
This is the log output of above scenario when cron job kills a node at 15:00 and 16:00 hours.
```
15:00:49.239 [pool-18-thread-1] ERROR c.m.c.d.HostAvailabilityListener - Encountered [com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connection to http://rh7v-intel64-90-java-stress-2.marklogic.com:8011 refused] on host "rh7v-intel64-90-java-stress-2.marklogic.com" but black-listing it would drop job below minHosts (1), so stopping job "unnamed"
16:00:04.539 [pool-49-thread-2] ERROR c.m.c.d.HostAvailabilityListener - Encountered [com.marklogic.client.datamovement.QueryBatchException: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connection to http://rh7v-intel64-90-java-stress-3.marklogic.com:8011 refused] on host "rh7v-intel64-90-java-stress-3.marklogic.com" but black-listing it would drop job below minHosts (1), so stopping job "unnamed"
```

**Comment by sammefford** [comment]
I believe this was actually 4.0.1
