### ISSUE TITLE
Unable to blacklist host "localhost"

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#686]
1. In the following test, I am trying to blacklist "localhost". When I create client with hostname "localhost" and initialize a WriteBatcher, the following is the forest config

17:22:03.124 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [localhost] hosts with forests for "WriteHostBatcher"

2. After I blacklist "localhost", the forest config becomes 

17:22:03.171 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [hp1040-3505.marklogic.com] hosts with forests for "WriteHostBatcher"

which is the alternate hostname

3. If I try to blacklist "hp1040-3505.marklogic.com, it has no effect and the WriteBatcher continues to run with [localhost] .

```
	@Test
	public void WBBlackList() throws Exception{
		DatabaseClient db = DatabaseClientFactory.newClient("localhost", 8000, "admin", "admin", Authentication.DIGEST);
		DataMovementManager dmManager = db.newDataMovementManager();
		
		final String query1 = "fn:count(fn:doc())";
			
		FilteredForestConfiguration forestConfig = null;
		DocumentMetadataHandle meta6 = new DocumentMetadataHandle().withCollections("NoHost").withQuality(0);
		
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
		
		WriteBatcher ihb2 =  dmManager.newWriteBatcher();
		forestConfig  = new FilteredForestConfiguration(dmManager.readForestConfig()).withBlackList("localhost");
			
		
		ihb2.withBatchSize(50).withForestConfig(forestConfig);
		
		
			
		ihb2.onBatchSuccess(
		        batch -> {
		        	}
		        )
		        .onBatchFailure(
		          (batch, throwable) -> {
		        	  throwable.printStackTrace();
		          
		          }
		);
		for (int j =0 ;j < 1000; j++){
			String uri ="/local/string-"+ j;
			ihb2.addAs(uri, meta6 , jsonNode);
		}
		
	
		ihb2.flushAndWait();
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 1000);
				
	}

```

Logs:

17:22:02.202 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as admin
17:22:02.609 [main] DEBUG c.m.client.impl.JerseyServices - Getting internal/forestinfo as application/json
17:22:02.827 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8000 as admin
17:22:03.015 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
17:22:03.093 [main] DEBUG c.m.client.impl.JerseyServices - Getting internal/forestinfo as application/json
17:22:03.124 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [localhost] hosts with forests for "WriteHostBatcher"
17:22:03.139 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "localhost" to the rotation
17:22:03.139 [main] DEBUG c.m.client.impl.JerseyServices - Getting internal/forestinfo as application/json
17:22:03.171 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [hp1040-3505.marklogic.com] hosts with forests for "WriteHostBatcher"
17:22:03.171 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to hp1040-3505.marklogic.com at 8000 as admin
17:22:03.249 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - Adding DatabaseClient on port 8000 for host "hp1040-3505.marklogic.com" to the rotation
17:22:03.264 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - threadCount=1
17:22:03.264 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - batchSize=50
17:22:03.312 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:03.312 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:03.312 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:03.312 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.319 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.319 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.335 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.335 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.507 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.507 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.616 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.616 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.726 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.726 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.772 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.772 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.838 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.838 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.901 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.901 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:05.947 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:05.947 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.025 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.025 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.072 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.072 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.135 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.135 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.181 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.181 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.244 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.244 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.275 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.275 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.335 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - flushing 0 queued docs
17:22:06.388 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.388 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.467 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.467 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.545 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Posting documents
17:22:06.545 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
17:22:06.608 [main] DEBUG c.m.client.impl.JerseyServices - Posting eval
S is true
WriteHostBatcher-1

**Comment by sammefford** [comment]
When you black-list a host, it's going to try to use any valid host for the available forests.  That includes the host, alternate host, or replica host.  

Could you try black-listing both localhost, and hp1040-3505.marklogic.com?

**Comment by srinathgit** [comment]
I am able to blacklist after including both the hostname and alternate hostname in the blacklist
