### ISSUE TITLE
Create a JobTicket by ID

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#690]
This would allow a GUI to present a list of jobs, and then manage those jobs by id without needing to keep a handle on the JobTicket or Batcher instance.  Data Hub Quick Start requested this feature.

**Comment by sammefford** [comment]
We should perhaps at the same time implement #648

**Comment by sammefford** [comment]
The API could be:

```
/**
 * Gets the JobTicket for an active job (one that has not been stopped by calling stopJob).
 */
DataMovementManager {
  JobTicket getActiveJob(String jobId)
}
```

**Comment by vivekmuniyandi** [comment]
```
JobTicket DataMovementManager.getActiveJob(String jobId)
```	

     - This would allow the user to get the JobTicket for the job whose jobId is known.
