### ISSUE TITLE
Run the Java API including DMSDK against MarkLogic 8

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/java-client-api#692]
As a tools developer, I would like to build tools using DMSDK that are generically useful to on most MarkLogic installations.

MarkLogic 7 will also be helpful, but the bulk of installs now are probably ML 8+. If there can be a compatibility mode to change approach to not use new ML 9 server features, or throw sensible errors when some, hopefully small, subset of DMSDK functionality is invoked and that subset is documented, it may satisfy the need.

**Comment by sammefford** [comment]
I'm guessing this would work if you installed the /v1/internal/forestinfo and /v1/internal/uris endpoints on your MarkLogic 8 or 7 instance.

Step 1) copy from ML9 Modules/MarkLogic/rest-api/endpoints/forest-info.xqy, Modules/MarkLogic/rest-api/models/forest-info-model.xqy, Modules/MarkLogic/rest-api/endpoints/internal-uris.xqy, and Modules/MarkLogic/rest-api/models/internal-uris-model.xqy 

Step 2) add the following to your rewriter.xml, rewriter-noxdbc.xml, and 8000-rewriter.xml: 

        <match-path matches="^/(v1|LATEST)/internal/forestinfo$">
            <match-query-param name="database">
                <set-database checked="true">$0</set-database>
            </match-query-param>
            <dispatch>/MarkLogic/rest-api/endpoints/forest-info.xqy</dispatch>
        </match-path>
        <match-path matches="^/(v1|LATEST)/internal/uris$">
            <match-query-param name="txid">
                <set-transaction>$0</set-transaction>
                <set-transaction-mode>query</set-transaction-mode>
            </match-query-param>
            <match-query-param name="database">
                <set-database checked="true">$0</set-database>
            </match-query-param>
            <match-query-param name="timestamp">
                <set-transaction-timestamp>$0</set-transaction-timestamp>
            </match-query-param>
            <dispatch>/MarkLogic/rest-api/endpoints/internal-uris.xqy</dispatch>
        </match-path>

Step 3) And this to Modules/MarkLogic/rest-api/endpoints/config.xqy

```
declare function conf:get-uris-request-rule() as element(rest:request) {
    <rest:request allow-post-alias="true">
        <rest:param name="q"                             required="false"/>
        <rest:param name="qbe"                           required="false"/>
        <rest:param name="structuredQuery"               required="false"/>
        <rest:param name="start"       as="unsignedLong" required="false" />
        <rest:param name="pageLength"  as="unsignedLong" required="false" />
        <rest:param name="options"     as="string"       required="false"/>
        <rest:param name="collection"  as="string"       required="false" repeatable="true"/>
        <rest:param name="directory"   as="string"       required="false"/>
        <rest:param name="txid"        as="string"       required="false"/>
        <rest:param name="database"    as="string"       required="false"/>
        <rest:param name="forest-name" as="string"       required="false" repeatable="true"/>
        <rest:param name="timestamp"   as="unsignedLong" required="false"/>
        <rest:http method="GET"></rest:http>
        <rest:http method="POST"></rest:http>
    </rest:request>
};
```

Step 4) And this to Config/security.xml:

     <amp namespace="http://marklogic.com/rest-api/forestinfo" local-name="get-forest-info"
         document-uri="/MarkLogic/rest-api/models/forest-info-model.xqy" database="0">
         <role>rest-reader-internal</role></amp>

**Comment by sammefford** [comment]
You'd need to use the 4.0.x release of Java Client API to get DMSDK, and be careful to only use features that work on ML8 or ML7 (no guarantees about what will work).  But the list above are the only changes to the server required for DMSDK, and I don't believe they depend on any changes to built-ins in ML9, so in theory they might work the same on ML8 or ML7, or with minor tweaks.

**Comment by sammefford** [comment]
Oops, I'll need to modify the above to also include /v1/internal/apply-transform

**Comment by jmakeig** [comment]
Removed 7, which will have EOL announced soon.

**Comment by jmakeig** [comment]
A solution will require changes to 8.0. Need to align this with a future 8.0 maintenance release. (And that would still require customers upgrade to that release.)

**Comment by sammefford** [comment]
After more consideration, the decision is to recommend customers upgrade to ML 9 to benefit from DMSDK.

**Comment by jmakeig** [comment]
I understand the usefulness as customers transition to MarkLogic 9. However, even if the actual code changes are not the large, back-porting a significant capability like DMSDK is a very large testing and maintenance commitment. My inclination is that this investment would be much better spent in making it more attractive to upgrade to MarkLogic 9 (and eventually beyond). 

@damonfeldman, let me know if there’s an angle that we’re missing.
