### ISSUE TITLE
Document how to create a recipe

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#696]
Add a README.md to the cookbook folder so people can add recipes and get them tested by unit tests

**Comment by sammefford** [comment]
Vivek, could you take a look at the [writeup](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/example/cookbook/README.md) and let me know if you see anything I should change?

**Comment by vivekmuniyandi** [comment]
This looks good to me Sam.

**Comment by jmakeig** [comment]
A recipe recipe, if you will.
