### ISSUE TITLE
Use new streaming multi-part

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#697]
We've added a streaming multi-part to REST. This is in support of optic API for now. But I'm guessing it could benefit DMSDK ExportListener by extension.  The goal would be to enable faster time-to-first-byte for export consuming applications.  For ExportListener this would allow sending the first documents to onDocumentReady listeners while the rest of the batch of documents is still being read.

**Comment by ehennum** [comment]
Performance engineering didn't find the expected benefits.
