### ISSUE TITLE
Load, merge, and harmonize source data to entities using Entity Services

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#700]
From https://github.com/marklogic/data-movement/issues/133

Load two halves of a Customer (or some other business entity) from two separate systems, for example, Billing and Marketing into a staging collection. For each logical instance, merge the two halves into a whole and materialize the canonical view, based on the entity model. 

Introduce some merge logic to determine instance identity for matching. Put some flutter in the data such that there are instances from either set that don’t match. Build a report for each batch that shows the ones that don’t have matches. “Move” the processed documents out of staging into production and the exceptions into another bucket and produce a summary report of the work done.

For example, `smefford.json` from Billing and `123, Sam Mefford, UT, 9.5` from `marketing.csv`.

**Comment by ehennum** [comment]
Superseded by DHF.
