### ISSUE TITLE
Create a cookbook example using Optic API

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#701]
From https://github.com/marklogic/data-movement/issues/132

Demonstrate using the Optic API from DMSDK. I'd recommend we use a query to narrow the set of matching documents, then the optic API to join those documents to triples and tuples which contain additional metadata that we want to export. A realistic scenario would be document data plus transactional (tuples) data from separate systems brought together into MarkLogic acting as an operational warehouse. Some triples can add relationship information between the documents. Our process could run a nightly report with rollups and aggregations and export to a CSV. Possible data sets could be movies plus daily box office take (perhaps also by time of day). Or classic retail sales by store or category.

**Comment by vivekmuniyandi** [comment]
To test, please have a quick look at the code and run it. Please let me know if you have any concerns. THanks.

**Comment by georgeajit** [comment]
The test ran fine.

**Comment by georgeajit** [comment]
Added milestone to sync with internal bug tracking system.

**Comment by popzip** [comment]
Who is the audience for the cookbook example, where is this published/shared/linked?

**Comment by sammefford** [comment]
@popzip [BulkExportOpticResults.java](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkExportOpticResults.java) is a stand-alone example showing how to use DMSDK to export data from a large Optic query.  Because it is multi-threaded, uses all available e-nodes, and has DMSDK orchestration it can be used to efficiently conduct a very large export.  Since it is stand-alone it should hopefully show how DMSDK and Optic can interweave.

[BulkExportOpticResultsToWriter.java](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkExportOpticResultsToWriter.java) on the other hand, shows a more extensible and reusable approach.  The associated listeners could be used in production applications.  It's more of a starting point for serious DMSDK+Optic applications.

We don't have any good way to advertise our cookbook examples.  All we're doing right now is including them in the [example/cookbook](https://github.com/marklogic/java-client-api/tree/develop/src/main/java/com/marklogic/client/example/cookbook) folder.

**Comment by popzip** [comment]
Thanks for the clarification
