### ISSUE TITLE
add support for ad-hoc "eval" transforms

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#705]
Please prioritize, @jmakeig

**Comment by sammefford** [comment]
From https://github.com/marklogic/data-movement/issues/75

**Comment by jmakeig** [comment]
@sammefford, do you remember any more details on this? Is it the ability to specify a transformation at runtime and not have to pre-load it?

**Comment by sammefford** [comment]
yeah, that's all it is
