### ISSUE TITLE
Allow inserting triples with WriteBatcher

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#708]
From https://github.com/marklogic/data-movement/issues/32

@srinathgit: I am currently unable to insert triples with WriteHostBatcher. I used the following code snippet. The data is inserted as document and not as a triple

```
WriteHostBatcher ihb = dmManager.newWriteHostBatcher();
 ihb.withBatchSize(1);

dmManager.startJob(ihb);

 String ntriple5 = "<http://example.org/s5> <http://example.com/p2> <http://example.org/o2> .";
 StringHandle sh = new StringHandle(ntriple5).withMimetype("application/n-triples");
  ihb.add("/local/triple", sh);
  ihb.flush();
```

**Comment by ehennum** [comment]
The best approach is either to convert to the canonical representation before writing or to use TDE.
