### ISSUE TITLE
Update build plugins to the latest versions available

### ISSUE THREAD

**Issue by hansenmc** [marklogic/java-client-api#710]
A number of the build plugins are out of date or do not have explicit entries or versions in the POM. Update the POM to use the latest versions available for the following plugins:

|Dependency |	Resolved |	Newest|
|---|---|---|
|maven-compiler-plugin	| 2.3.2 |	 3.6.1 |	
|maven-javadoc-plugin |	2.8.1 |	 2.10.4|	
|maven-jar-plugin |	2.4	 | 3.0.2	|
|maven-source-plugin |	2.1.2 |	 3.0.1|	
|maven-deploy-plugin |	2.8.1 |	 2.8.2|	
|site-maven-plugin |	0.10	| 0.12	|
|exec-maven-plugin | 1.5.0 | 1..6.0 |
|maven-assembly-plugin | NO VERSION SPECIFIED | 3.0.0|
|maven-project-info-reports-plugin | NO VERSION SPECIFIED, resolving to 2.8.1 | 2.9 |

**Comment by georgeajit** [comment]
Have updated ```org.apache.httpcomponents:httpclient:4.5.3```. Rest of QA dependencies for running the functional tests will be updated to the latest versions when work OKHttp is being handled.
