### ISSUE TITLE
Add a RawCtsQueryDefinition to parallel RawCombinedQueryDefinition and RawStructuredQueryDefinition

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#720]
It looks like you currently can use QueryManager.newCombinedQueryDefinition or newStructuredQueryDefinition  and pass in a raw serialized cts query.  But it's confusing to do a raw cts query that way.  Therefore I propose we add RawCtsQueryDefinition and have it extend RawQueryDefinition and work just like RawCombinedQueryDefinition and RawStructuredQueryDefinition.

**Comment by sammefford** [comment]
Here's an example work-around that works fine in 4.0.1:

```java
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.DigestAuthContext;
import com.marklogic.client.io.Format;
import com.marklogic.client.io.StringHandle;
import com.marklogic.client.query.QueryManager;
import com.marklogic.client.query.RawQueryDefinition;

public class CtsQueryTest {
  public static void main(String[] args) {
    System.setProperty("org.apache.commons.logging.simplelog.log.org.apache.http.wire", "debug");
    DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, new DigestAuthContext("admin", "admin"));
    QueryManager queryMgr = client.newQueryManager();
    RawQueryDefinition query = queryMgr.newRawCombinedQueryDefinitionAs(Format.XML,
      "<cts:word-query xmlns:cts=\"http://marklogic.com/cts\">" +
      "  <cts:text>someSearchTerm</cts:text>" +
      "</cts:word-query>");
    StringHandle results = queryMgr.search(query, new StringHandle());
    System.out.println(results.get());
  }
}
```

**Comment by sammefford** [comment]
Here are the API changes:

    com.marklogic.client.io.marker.CtsQueryWriteHandle extends AbstractWriteHandle {
    }

    // this parallels RawStructuredQueryDefinition except
    // this doesn't yet extend ValueQueryDefinition until that's implemented in the REST layer
    com.marklogic.client.query.RawCtsQueryDefinition extends RawQueryDefinition {
      String getCriteria(String criteria)
      void setCriteria()
      RawCtsQueryDefinition withCriteria(String criteria)
      CtsQueryWriteHandle getHandle()
      void setHandle(CtsQueryWriteHandle handle)
      RawCtsQueryDefinition withHandle(CtsQueryWriteHandle handle)
    }

    QueryManager {
      RawCtsQueryDefinition newRawCtsQueryDefinition(CtsQueryWriteHandle handle
      RawCtsQueryDefinition newRawCtsQueryDefinition(CtsQueryWriteHandle handle, String optionsName)
      RawCtsQueryDefinition newRawCtsQueryDefinitionAs(Format format, Object query)
      RawCtsQueryDefinition newRawCtsQueryDefinitionAs(Format format, Object query, String optionsName)
    }

Add CtsQueryWriteHandle marker interface to these classes:

    BytesHandle
    DOMHandle
    FileHandle
    InputSourceHandle
    InputStreamHandle
    JacksonDatabindHandle
    JacksonParserHandle
    OutputStreamHandle
    ReaderHandle
    SourceHandle
    StringHandle
    XMLEventReaderHandle
    XMLStreamReaderHandle

**Comment by kcoleman-marklogic** [comment]
Values query support is in now.
