### ISSUE TITLE
Make TextDocumentManager and BinaryDocumentManager implement TemporalDocumentManager

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#721]
We need to make TextDocumentManager and BinaryDocumentManager implement TemporalDocumentManager so text and binary docs can be managed with bitemporal.

With ML8 bitemporal documents had to include the start and valid dates in elements or json properties, so text and binary docs couldn't be bitemporal.   With ML9 we now have DocumentMetadataValues, so text and binary documents can now be bitemporal also.

**Comment by kcoleman-marklogic** [comment]
It does, in fact, look like binary and text temporal docs are A Thing. The apidoc for `temporal:document-insert` says the following about it's `$root` param:

>The root node of the document. The root node can be one of XML format, JSON format, binary (BLOB) format, or text (CLOB) format.
