### ISSUE TITLE
add support for minimum distance on near-query

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#722]
I might just be overlooking this, in which case I apologize for the noise, but it does not look to me like `StructuredQueryBuilder.near` supports the "minimum-distance" option added to near query for ML9. I didn't see it mentioned in the Java API deltas spec, either. 

This feature manifests in structured query as a new `minimum-distance` element of `near-query`.

**Comment by sammefford** [comment]
@georgeajit I only added a test of the XML structure.  Could you add a test that runs a near-query against the server with minimumDistance and make sure it's working end-to-end?
