### ISSUE TITLE
Research and document Kerberos instructions

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#724]
This is a task in support of documenting our connection security features, to make sure Sam and I don't lose track of this open issue.

Initial requirement is for Sam to investigate what's required to really make Kerberos work, then let me know what needs to be changed in the current instructions. He's already been hard at work on that.

I'll update the docs once Sam is done.

**Comment by sammefford** [comment]
@kcoleman-marklogic as I read through http://pubs.marklogic.com:8011/9.0/guide/java/intro#id_43335 I think we should add steps 1-3 from [here](https://wiki.marklogic.com/x/GwZRAw) in place of the last step.  The current set of instructions only cover the server side, but there are clearly some steps to take to have the client side properly configured.

**Comment by kcoleman-marklogic** [comment]
Thanks, Sam. I'll give it a go and run it by you for review.

**Comment by kcoleman-marklogic** [comment]
One question about your guidance: You said to REPLACE the last step (which is about configuring ML for kerberos auth) with the information the wiki, which is about client configuration.

Does that mean that the App Server does not have to be configured for kerberos auth, as well?

**Comment by kcoleman-marklogic** [comment]
This task has no manifestation in bugtrack, so you'll have to trust me that I checked something. I'll send it to you for review tomorrow, Sam.

**Comment by kcoleman-marklogic** [comment]
All review comments incorporated. Shipping this.
