### ISSUE TITLE
ServerEvaluationCall.evalAs(Class<T>) closes underlying streams prematurely

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#725]
While a small response appears to return with no issues, a long response throws "IOException: Stream Closed" when trying to read from a returned Reader:

    String inputText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor " +
      "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation";
    String javascript =
      "var inputText;" +
      "var output = new String();" +
      "for ( i=0; i < 100; i++ ) {" +
      "  output = output + inputText;" +
      "}" +
      "output;";
    ServerEvaluationCall query = Common.evalClient.newServerEval()
      .javascript(javascript)
      .addVariable("inputText", inputText);
    Reader response = query.evalAs(Reader.class);
    String strVal = new BufferedReader(response).readLine();
    StringBuilder expectedOutput = new StringBuilder();
    for ( int i=0; i < 100; i++ ) {
      expectedOutput.append(inputText);
    }
    assertEquals(expectedOutput.toString(), strVal);

I see the following:

    org.jvnet.mimepull.MIMEParsingException: java.io.IOException: Stream Closed
        at org.jvnet.mimepull.WeakDataFile.read(WeakDataFile.java:84)
        at org.jvnet.mimepull.DataFile.read(DataFile.java:77)
        at org.jvnet.mimepull.FileData.read(FileData.java:68)
        at org.jvnet.mimepull.DataHead$ReadMultiStream.fetch(DataHead.java:250)
        at org.jvnet.mimepull.DataHead$ReadMultiStream.read(DataHead.java:212)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at com.marklogic.client.test.EvalTest.evalWithReader(EvalTest.java:124)
 
This line is failing  because it's attempting to read from a closed Reader: 

    String strVal = new BufferedReader(response).readLine();

**Comment by sammefford** [comment]
Here's [the problematic line](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/impl/ServerEvaluationCallImpl.java#L157): 

    } finally { iterator.close(); }

because this closes the EvalResultIterator as soon as ServerEvaluationCall.eval(T) or ServerEvaluationCall.evalAs(Class<T>) returns, thus closing the underlying resources before there's any chance to stream from them.  The challenge is that both methods return a class of any type, so there's no opportunity to implement the type with a wrapper that will close the underlying EvalResultIterator.  And we can't use java.lang.reflect.Proxy because the classes we need to implement are not always interfaces, they are sometimes concrete classes.

**Comment by sammefford** [comment]
Perhaps the solution is to just document that these methods should only be used with non-streaming handles (and their associated types).  We could then show that for streaming handles or types they could do something like:

    try { EvalResultIterator results = call.eval();
          InputStreamHandle handle = results.next().get(new InputStreamHandle()) )
    {
        ... do something ...
    }

or

    try { EvalResultIterator results = call.eval(); 
          InputStream stream = results.next().getAs(InputStream.class) )
    {
        ... do something ...
    }

**Comment by sammefford** [comment]
The documentation approach is addressed by commit f004c98

**Comment by sammefford** [comment]
@georgeajit I could use your help to validate that the [changes to javadocs for ServerEvaluationCall](https://github.com/marklogic/java-client-api/commit/f004c9821089b66c42c6b6c25f58b9d539c420d2#diff-360ef45d9aa71e9865dbef829edaf923) make sense.  Also, could you make sure we have some regression tests of evalAs(Class<T>) that return some non-streaming responses at least as long as the test above (17,400 chars)?  You could test String.class and JsonNode.class.

**Comment by sammefford** [comment]
@georgeajit , when you finish the review of the javadocs changes and add the regression tests I mention, could you assign this back to me?  I need to look at DocumentManager.read/readAs and QueryManager.search to see if those might have any related issues with underlying responses or connections not getting closed.

**Comment by sammefford** [comment]
Note to self: DocumentManager.read(uri, metadataHandle, contentHandle) is multi-part, just like ServerEvaluationCall.  So I can't say this doesn't affect DocumentManager.read calls because they're single payload.

**Comment by georgeajit** [comment]
I have added the following test.
```

    try {
      String query1 = 
           "var phrase = 'MarkLogic Corp';"
          + "var repeat = 10;"
          + "for (var i = 0; i < repeat; i++) {"
          + "phrase += phrase.concat(phrase);"
          + "}"          
          + "phrase;";
      
      String query2 = 
              "var phrase2 = 'Java Client API';"
             + "var repeat = 10;"
             + "for (var i = 0; i < repeat; i++) {"
             + "phrase2 += phrase2.concat(phrase2);"
             + "}"          
             + "var jsStr = JSON.stringify(phrase2);"
             + "jsStr;";

      ServerEvaluationCall evl = client.newServerEval().javascript(query1);
      
      // Using evalAs(String.class)
      String evr = evl.evalAs(String.class);
      
      int nLen = evr.length();
      String firstFiftyChars = evr.substring(0, 50);
      String lastTenChars = evr.substring(evr.length() - 10);
      
      // Make sure we can access results that are greater than 17,400 chars. See Git Issue 725.
      System.out.println("String length is " + nLen);
      System.out.println("First Fifty String output is " + firstFiftyChars);
      System.out.println("Last Ten String output is " + lastTenChars);
      
      assertTrue("String length incorrect", nLen==826686);
      assertTrue("First Fifty String output incorrect ", firstFiftyChars.equalsIgnoreCase("MarkLogic CorpMarkLogic CorpMarkLogic CorpMarkLogi"));
      assertTrue("Last Ten String output incorrect ", lastTenChars.equalsIgnoreCase("Logic Corp"));
      
      // Using evalAs(JsonNode.class)
      ServerEvaluationCall ev2 = client.newServerEval().javascript(query2);
      JsonNode jNode = ev2.evalAs(JsonNode.class);
      
      String jsonStr = jNode.asText();
      int nJLen = jsonStr.length();
      String firstFiftyCharsJson = jsonStr.substring(0, 50);
      String lastTenCharsJson = jsonStr.substring(jsonStr.length() - 10);
      
      // Make sure we can access results that are greater than 17,400 chars. See Git Issue 725.
      System.out.println("JSON String length is " + nJLen);
      System.out.println("First Fifty String JSON output is " + firstFiftyCharsJson);
      System.out.println("Last Ten String JSON output is " + lastTenCharsJson);
      
      assertTrue("JSON String length incorrect", nJLen==885735);
      assertTrue("First Fifty JSON String output incorrect ", firstFiftyCharsJson.equalsIgnoreCase("Java Client APIJava Client APIJava Client APIJava "));
      assertTrue("Last Ten JSON String output incorrect ", lastTenCharsJson.equalsIgnoreCase("Client API"));
      
    } catch (Exception e) {
      throw e;
    }
  ```

**Comment by sammefford** [comment]
As noted in #783 the issue is resolved by OkHttp and our use of javax.mail.internet.MimeMultipart.  Unfortunately that prevents streaming multipart responses, but at least they don't err anymore.
