### ISSUE TITLE
Reduce document search query types

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#733]
Reduce the query surface area of document query (as opposed to row or triple query) to: String, QBE, and `cts:query`. Think about how we might parameterize each of those to improve safety (injection) and usability (encapsulation).

**Comment by sammefford** [comment]
Some things to include in search queries that aren't yet incorporated in String query, QBE, or cts:query:

- facets
- match formatting (snippets, partial document extraction, metadata, transforms or alternative)
- response transform or alternative
- string query options (including pre-processing)

**Comment by georgeajit** [comment]
Closing the issue to keep Search API stablized.
