### ISSUE TITLE
Document how to get cookbook examples working in IDEs

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#741]
Step-by-step instructions to get a development environment set up to run the cookbook example code. Start with IntelliJ and then Eclipse. 

Should we consider moving the cookbook examples into a separate repo to more accurately represent how you’d work with the Java Client API in a real application? With the examples and main source in the same repo, the default configuration in pom.xml will be to compile your own Client API, rather than pull it in from Maven Central.

**Comment by sammefford** [comment]
Sounds reasonable that we'd separate the examples with the side-benefit you mention of a good sample pom.xml.  We'd need to make sure, however, that as part of this effort we keep running the cookbook examples as part of the unit tests and functional tests.  We can have two projects dependent on each other, no?

**Comment by rjrudin** [comment]
FWIW - Gradle file to get the examples compiling - not sure if every version is correct, but all the examples compiled and ran fine:

plugins {
  id "java"
}

repositories {
  mavenCentral()
}

dependencies {
  compile "com.marklogic:marklogic-client-api:4.0.1"
  compile "org.jdom:jdom2:2.0.6"
  compile "com.io7m.xom:xom:1.2.10"
  compile "org.parboiled:parboiled-scala_2.12:1.1.8"
  compile "net.sourceforge.htmlcleaner:htmlcleaner:2.20"
  compile "com.google.code.gson:gson:2.8.0"
  compile "org.dom4j:dom4j:2.0.0"
}

**Comment by georgeajit** [comment]
Cokkbook examples compile and each of them a test.
