### ISSUE TITLE
Javadoc of RawQueryByExampleDefinition is messed up

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#742]
See the code example [here](https://docs.marklogic.com/javadoc/client/com/marklogic/client/query/RawQueryByExampleDefinition.html).

**Comment by sammefford** [comment]
@kcoleman-marklogic could you take a look after this builds again in pubs, and make sure the code looks good to you?

**Comment by kcoleman-marklogic** [comment]
It looks good now, Sam.
