### ISSUE TITLE
DMSDK Batcher to take action when a job starts and when a job ends

### ISSUE THREAD

**Issue by sastafford** [marklogic/java-client-api#743]
As a developer
I want a TITLE
So that I can log data onto the filesystem OR back into MarkLogic upon these events occurring

Experimenting with creating custom listeners.  I created one listener that would write back documents to MarkLogic upon a batch success.  Developers would want notification when a job starts and ends in addition to the batch complete/failure events.

**Comment by sammefford** [comment]
Related to #612

**Comment by sammefford** [comment]
Looks like this is a dup of #614
