### ISSUE TITLE
dup words in javadoc

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#747]
There are some occurrences of "for for" in the javadoc for a few classes. Minor issue, obviously. It was picked up as part of a wider cleanup of such errors in the ML9 documentation.

I'll submit a pull req for it if I can sort out the how.

**Comment by sammefford** [comment]
The fixes look good.  I merged them.

**Comment by kcoleman-marklogic** [comment]
Looks good. Thanks.
