### ISSUE TITLE
readMetadata fails on stand-alone properties documents

### ISSUE THREAD

**Issue by sanderson-sfdc** [marklogic/java-client-api#751]
I have some stand-alone properties documents.  I can retrieve the properties using xquery with

`xdmp:document-properties($testURI)`

but 

`docMgr.readMetadata(testURI, metadataHandle)`

fails with the following message

`com.marklogic.client.ResourceNotFoundException: Local message: Could not read non-existent document. Server Message: RESTAPI-NODOCUMENT: (err:FOER0000) Resource or document does not exist:  category: metadata message: /topic/topic.2.208.6.0.en.us`

**Comment by sammefford** [comment]
Thanks, Steve.  I'll look into it.

**Comment by jmakeig** [comment]
@sanderson-sfdc, thanks for the feedback. Can you please help me understand your use case a little better? Would your properties make sense in an explicit document? The only real advantage properties have is that they share the URI with the document and thus are guaranteed to be stored in the same forest. Accessing properties requires a full fragment fetch and accessing a document and its properties still requires a join between two fragments, just like joins across documents. Today, properties also don't support JSON nodes, only XML. 

I’m not saying that we shouldn’t support “naked” properties (i.e. without a corresponding document fragment) in the Java API, I’d just like to make sure we’re doing it for the right reasons and there isn’t a more explicit and easier implementation for your use case with just documents.

**Comment by sanderson-sfdc** [comment]
I was following along with https://developer.marklogic.com/blog/managed-vs-unmanaged-triples and in the section, "Embedding in documents versus properties" it says, "The benefit though is that you have clean separation between document and triples automatically."

That spoke to me, so I created some documents with the unmanaged triples stored in the properties documents.  That worked well.  I then realized I also needed some triples that weren't associated with a document, so I pushed those into stand-alone properties documents.

It'd probably be better to store those triples as managed triples rather than as unmanaged triples in a stand-alone properties documents, but that wasn't my initial implementation.

It sounds like I should step back and do some redesign to use managed triples instead of unmanaged triples stored in properties, but I think this is still a bug.

**Comment by jmakeig** [comment]
Thanks, @sanderson-sfdc, for the details. Agreed that managed triples sounds like a better option here for triples that aren’t naturally associated with a particular document. 

I could buy that the asymmetry with the server-side APIs is bug here. However, generally we want to steer users away from “naked” properties for the reasons I listed above.

Again, thanks for your input.

**Comment by sammefford** [comment]
In internal conversations and the helpful comments from @jmakeig above, it seems the consensus is to seek alternatives to "naked" properties.  So for now let's not make any API changes.

**Comment by sanderson-sfdc** [comment]
I think it should at the very least be added to the documentation that readMetadata will not work with stand-alone properties documents.
