### ISSUE TITLE
Allow me to set the JobId for a JobTicket

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/java-client-api#752]
Rather than automagically setting the JobId to a UUID, please allow me to manually set it to whatever I like.

Why? you might ask...

My use case is that my "job" consists of 2 parts. I must first run a module to get a list of things to batch on. Then I use the QueryBatcher to do stuff. Both parts of the "job" need to use the jobId but currently I can only get a jobId from the querybatcher after I start it.

I'd like to do something like this:

```
String jobId = UUID.randomUUID().toString();

Collector c = new Collector();
Vector<String> uris = c.run(jobId);

QueryBatcher queryBatcher = dataMovementManager.newQueryBatcher(uris.iterator())
   .withJobId(jobId)
   .withThreadCount(4)
   ...

```

Hopefully that makes sense.

**Comment by sammefford** [comment]
Yes, that makes sense.  Do you think we should merge jobName (which currently you can set on a batcher calling withJobName(String)) with the concept of jobId (which currently you can get from a JobTicket)?  Or is it helpful in the long-run to have both jobName and jobId?

**Comment by paxtonhare** [comment]
@sammefford not sure I follow your question. For me personally, I am not using job names right now.

**Comment by sammefford** [comment]
I envision that a job dashboard might have something like this:

Actions | Job ID | Job Name
------- | ------- | -----------
[Status] [Stop] [Restart] | 5324 | Write docs from /tmp/employees/
[Status] [Stop] [Restart] | 2345 | Write docs from /hr/salaries/

Where the Job ID must be unique for job control purposes (and frankly, doesn't even need to show on the dashboard).  And the Job Name can be human readable text for understanding what the job is doing.

**Comment by vivekmuniyandi** [comment]
Batcher withJobID(String jobId)
String getJobId()
QueryBatcher withJobID(String jobId) 
WriteBatcher withJobID(String jobId)
	- This would enable the user to set and retrieve the job id. Should be called like this:
		QueryBatcher queryBatcher = dataMovementManager.newQueryBatcher(uris.iterator())
   									.withJobId("QueryjobId001")
   									.withThreadCount(4)
