### ISSUE TITLE
Try - with - resources support for BaseHandle

### ISSUE THREAD

**Issue by ramesh-mandaleeka** [marklogic/java-client-api#753]
The handles(implementations of com.marklogic.client.io.BaseHandle) are not auto closeable to make them work with try-with-resources statement. 

https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html 

Most of the examples I see (https://developer.marklogic.com/learn/java/crud) never mention that we need to close the handle explicitly to free the resources.  Will it be better if the BaseHAndle extends java.lang.AutoCloseable and close the read and write handles when used in try with resources statement?

**Comment by sammefford** [comment]
Thanks, @ramesh-mandaleeka for bringing this up!  It's such an important point to be diligent about and communicate clearly.  I believe the handles which need to be closed (such as InputStreamHandle and ReaderHandle) are AutoCloseable.  And they say in the javadoc description for each that you must "Either call close() or get().close() when finished with this handle to release the resources."  Are you finding any specific ones which should be AutoCloseable but aren't?  Not all handles need to be closed (such as StringHandle).

I'm wondering if the simple getting started page you're reading is an appropriate place to discuss closing handles.  I'm not even seeing any complete code examples there.  The complete code examples in the cookbook, however, must [demonstrate appropriately closing handles](https://github.com/marklogic/java-client-api/blob/develop/src/main/java/com/marklogic/client/example/cookbook/StringSearch.java#L161).  Please let us know if you find any that don't, and we'll get them fixed!

**Comment by ramesh-mandaleeka** [comment]
My bad. You are correct. The InputStreamHandle is autoCloseable.
