### ISSUE TITLE
This is a question - could one of you please look at the exception and help with it?

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/java-client-api#754]
For versions, refer to https://github.com/sanjuthomas/kafka-connect-marklogic/blob/ML-9-UPGRADE/pom.xml

I'm building an uber jar and dropping in the kafka, this could be the famous JAX-RS version conflict issue. Please note that in standalone mode, everything works fine. This should be quick for you guys - 

`SEVERE: A message body writer for Java class com.marklogic.client.impl.StreamingOutputImpl, and Java type class com.marklogic.client.impl.StreamingOutputImpl, and MIME media type application/json was not found
Jun 12, 2017 9:16:31 PM com.sun.jersey.api.client.RequestWriter$RequestEntityWriterImpl <init>
SEVERE: The registered message body writers compatible with the MIME media type are:
*/* ->
  com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider

[2017-06-12 21:16:31,172] ERROR A message body writer for Java class com.marklogic.client.impl.StreamingOutputImpl, and Java type class com.marklogic.client.impl.StreamingOutputImpl, and MIME media type application/json was not found (kafka.connect.marklogic.MarkLogicWriter:51)
com.sun.jersey.api.client.ClientHandlerException: A message body writer for Java class com.marklogic.client.impl.StreamingOutputImpl, and Java type class com.marklogic.client.impl.StreamingOutputImpl, and MIME media type application/json was not found
	at com.sun.jersey.api.client.RequestWriter$RequestEntityWriterImpl.<init>(RequestWriter.java:199)
	at com.sun.jersey.api.client.RequestWriter.getRequestEntityWriter(RequestWriter.java:248)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getHttpEntity(ApacheHttpClient4Handler.java:241)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getUriHttpRequest(ApacheHttpClient4Handler.java:197)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:153)
	at com.marklogic.client.impl.DigestChallengeFilter.handle(DigestChallengeFilter.java:34)
	at com.sun.jersey.api.client.filter.HTTPDigestAuthFilter.handle(HTTPDigestAuthFilter.java:493)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:537)
	at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1339)
	at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1206)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:919)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:757)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:687)`

**Comment by hansenmc** [comment]
I noticed when you execute the build, the shade plugin says that it is excluding a bunch of jars.

<details><summary>Click here for an example of the Maven Shade build exclude messages</summary>

```
--- maven-shade-plugin:3.0.0:shade (default) @ kafka-connect-marklogic ---
Excluding com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0 from the shaded jar.
Excluding com.fasterxml.jackson.core:jackson-core:jar:2.8.5 from the shaded jar.
Excluding com.marklogic:marklogic-client-api:jar:4.0.1 from the shaded jar.
Excluding com.sun.jersey:jersey-client:jar:1.17 from the shaded jar.
Excluding com.sun.jersey.contribs:jersey-apache-client4:jar:1.17 from the shaded jar.
Excluding org.apache.httpcomponents:httpclient:jar:4.1.1 from the shaded jar.
Excluding org.apache.httpcomponents:httpcore:jar:4.1 from the shaded jar.
Excluding commons-codec:commons-codec:jar:1.4 from the shaded jar.
Excluding com.sun.jersey.contribs:jersey-multipart:jar:1.17 from the shaded jar.
Excluding org.jvnet:mimepull:jar:1.6 from the shaded jar.
Excluding com.sun.jersey:jersey-core:jar:1.17 from the shaded jar.
Excluding org.jvnet.mimepull:mimepull:jar:1.9.4 from the shaded jar.
Excluding ch.raffael.pegdown-doclet:pegdown-doclet:jar:1.3 from the shaded jar.
Excluding com.google.guava:guava:jar:18.0 from the shaded jar.
Excluding net.sourceforge.plantuml:plantuml:jar:8032 from the shaded jar.
Excluding org.pegdown:pegdown:jar:1.6.0 from the shaded jar.
Excluding org.parboiled:parboiled-java:jar:1.1.7 from the shaded jar.
Excluding org.parboiled:parboiled-core:jar:1.1.7 from the shaded jar.
Excluding org.ow2.asm:asm:jar:5.0.3 from the shaded jar.
Excluding org.ow2.asm:asm-tree:jar:5.0.3 from the shaded jar.
Excluding org.ow2.asm:asm-analysis:jar:5.0.3 from the shaded jar.
Excluding org.ow2.asm:asm-util:jar:5.0.3 from the shaded jar.
Excluding commons-logging:commons-logging:jar:1.2 from the shaded jar.
Replacing original artifact with shaded artifact.
Replacing /var/tmp/mavenproject1/target/kafka-connect-marklogic-2.0.jar with /var/tmp/mavenproject1/target/kafka-connect-marklogic-2.0-shaded.jar

```

</details>
<br/>

It appears that when you put an explicit include in your artifactset for the marklogic-client-api and did not include any of those other jars, there is an implicit exclude of all those other jars.

Remove the include from your artifactset:

```xml
<artifactSet>
 <!--
<includes>
  <include>marklogic-client-api-4.0.1.jar</include>
</includes>
-->
<excludes>
  <exclude>org/xerial/**</exclude>
</excludes>
</artifactSet>
```

And then shade reports that it is now including those transitive dependencies:

```
--- maven-shade-plugin:3.0.0:shade (default) @ kafka-connect-marklogic ---
Including com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0 in the shaded jar.
Including com.fasterxml.jackson.core:jackson-core:jar:2.8.5 in the shaded jar.
Including com.marklogic:marklogic-client-api:jar:4.0.1 in the shaded jar.
Including com.sun.jersey:jersey-client:jar:1.17 in the shaded jar.
Including com.sun.jersey.contribs:jersey-apache-client4:jar:1.17 in the shaded jar.
Including org.apache.httpcomponents:httpclient:jar:4.1.1 in the shaded jar.
Including org.apache.httpcomponents:httpcore:jar:4.1 in the shaded jar.
Including commons-codec:commons-codec:jar:1.4 in the shaded jar.
Including com.sun.jersey.contribs:jersey-multipart:jar:1.17 in the shaded jar.
Including org.jvnet:mimepull:jar:1.6 in the shaded jar.
Including com.sun.jersey:jersey-core:jar:1.17 in the shaded jar.
Including org.jvnet.mimepull:mimepull:jar:1.9.4 in the shaded jar.
Including ch.raffael.pegdown-doclet:pegdown-doclet:jar:1.3 in the shaded jar.
Including com.google.guava:guava:jar:18.0 in the shaded jar.
Including net.sourceforge.plantuml:plantuml:jar:8032 in the shaded jar.
Including org.pegdown:pegdown:jar:1.6.0 in the shaded jar.
Including org.parboiled:parboiled-java:jar:1.1.7 in the shaded jar.
Including org.parboiled:parboiled-core:jar:1.1.7 in the shaded jar.
Including org.ow2.asm:asm:jar:5.0.3 in the shaded jar.
Including org.ow2.asm:asm-tree:jar:5.0.3 in the shaded jar.
Including org.ow2.asm:asm-analysis:jar:5.0.3 in the shaded jar.
Including org.ow2.asm:asm-util:jar:5.0.3 in the shaded jar.
Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
mimepull-1.6.jar, mimepull-1.9.4.jar define 31 overlapping classes: 
  - org.jvnet.mimepull.FileData
  - org.jvnet.mimepull.FinalArrayList
  - org.jvnet.mimepull.MIMEParser$1
  - org.jvnet.mimepull.InternetHeaders
  - org.jvnet.mimepull.MIMEPart
  - org.jvnet.mimepull.MIMEMessage$1
  - org.jvnet.mimepull.DataHead$ReadMultiStream
  - org.jvnet.mimepull.WeakDataFile
  - org.jvnet.mimepull.MIMEEvent$EndMessage
  - org.jvnet.mimepull.DataFile
  - 21 more...
maven-shade-plugin has detected that some class files are
present in two or more JARs. When this happens, only one
single version of the class is copied to the uber jar.
Usually this is not harmful and you can skip these warnings,
otherwise try to manually exclude artifacts based on
mvn dependency:tree -Ddetail=true and the above output.
See http://maven.apache.org/plugins/maven-shade-plugin/
Replacing original artifact with shaded artifact.
Replacing /var/tmp/mavenproject1/target/kafka-connect-marklogic-2.0.jar with /var/tmp/mavenproject1/target/kafka-connect-marklogic-2.0-shaded.jar
Dependency-reduced POM written at: /var/tmp/mavenproject1/dependency-reduced-pom.xml
```

Note that there are some warnings about duplicate classes from mimepull (and could be others). You should look at the dependency graph for the project and see if you need to set some excludes on your dependencies or customize the artifactset excludes.

**Comment by sanjuthomas** [comment]
@hansenmc thank you so much for taking the time to look into it. much appreciated! You were right, that was the issue. I'm closing this issue.
