### ISSUE TITLE
Calling a get method on EvalResult from a EvalResultIterator multiple times throws IllegalStateException

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#763]
Calling a get method on the ```EvalResult``` object of a ```EvalResultIterator``` instance, multiple times with OKHttp library inclusion causes the test to throw ```IllegalStateException: Content already retrieved ```.

In this exception case, we have in validateReturnTypes() method,  er.getString() being called more than once. 

This exception happens on both JS and XQuery based evals.

/* Test is intended to test different types of variable passed to javascript from java and check return types,data types, there is a bug log against REST 30209
	 * 
	 * Expected Result : JS variable myJsonNull in this test has value set to null.
	 * See Git issue # 317 for further explanation.
	 */
	@Test
	public void testJSDifferentVariableTypesWithNulls() throws Exception {
	
		DocumentBuilder db = DocumentBuilderFactory.newInstance().newDocumentBuilder();
		InputSource is = new InputSource();
		is.setCharacterStream(new StringReader("<foo attr=\"attribute\"><?processing instruction?>test1</foo>"));
		Document doc = db.parse(is);
		System.out.println(this.convertXMLDocumentToString(doc));
	 	try {
		String query1 = " var results = [];"
						+"var myString;"
						+"var myBool ;"
						+"var myInteger;"
						+"var myDecimal;"
						+"var myJsonObject;"
						+"var myNull;"
						+ "var myJsonArray;"
						+ "var myJsonNull;"
						+ "results.push(myString,myBool,myInteger,myDecimal,myJsonObject,myJsonArray,myNull,myJsonNull);"
						+"xdmp.arrayValues(results)";
		
		ServerEvaluationCall evl= client.newServerEval().javascript(query1);
		evl.addVariable("myString", "xml")
		.addVariable("myBool", true)
		.addVariable("myInteger", (int)31)
		.addVariable("myDecimal", (double)1.0471975511966)
		.addVariableAs("myJsonObject", new ObjectMapper().createObjectNode().put("foo", "v1").putNull("testNull"))
		.addVariableAs("myNull", (String) null)
		.addVariableAs("myJsonArray", new ObjectMapper().createArrayNode().add(1).add(2).add(3))
		.addVariableAs("myJsonNull", null )
		;
		System.out.println(new ObjectMapper().createObjectNode().nullNode().toString());
		EvalResultIterator evr = evl.eval();
		this.validateReturnTypes(evr);

		} catch (Exception e) {
			throw e;
		}
	}

/*
	 * This method is validating all the return values from java script, this
	 * method has more types than we test them here
	 */
	void validateReturnTypes(EvalResultIterator evr) throws Exception {

		while (evr.hasNext()) {
			EvalResult er = evr.next();			
			if (er.getType().equals(Type.JSON)) {

				JacksonHandle jh = new JacksonHandle();
				jh = er.get(jh);

				if (jh.get().isArray()) {
					System.out.println("Type Array :" + jh.get().toString());
					assertEquals("array value at index 0 ", 1, jh.get().get(0)
							.asInt());
					assertEquals("array value at index 1 ", 2, jh.get().get(1)
							.asInt());
					assertEquals("array value at index 2 ", 3, jh.get().get(2)
							.asInt());
				} else if (jh.get().isObject()) {
					System.out.println("Type Object :" + jh.get().toString());
					if (jh.get().has("foo")) {
						assertNull("this object also has null node", jh.get()
								.get("testNull").textValue());
					} else if (jh.get().has("obj")) {
						assertEquals("Value of the object is ", "value", jh
								.get().get("obj").asText());
					} else {
						assertFalse("getting a wrong object ", true);
					}

				} else if (jh.get().isNumber()) {
					System.out.println("Type Number :" + jh.get().toString());
					assertEquals("Number value", 1, jh.get().asInt());
				} else if (jh.get().isNull()) {
					System.out.println("Type Null :" + jh.get().toString());
					assertNull("Returned Null", jh.get().textValue());
				} else if (jh.get().isBoolean()) {
					System.out.println("Type boolean :" + jh.get().toString());
					assertTrue("Boolean value returned false", jh.get()
							.asBoolean());
				} else {
					// System.out.println("Running into different types than expected");
					assertFalse("Running into different types than expected",
							true);
				}

			} else if (er.getType().equals(Type.TEXTNODE)) {
				assertTrue("document contains",
						er.getAs(String.class).equals("test1"));
				// System.out.println("type txt node :"+er.getAs(String.class));

			} else if (er.getType().equals(Type.BINARY)) {
				FileHandle fh = new FileHandle();
				fh = er.get(fh);
				// System.out.println("type binary :"+fh.get().length());
				assertEquals("files size", 2, fh.get().length());
			} else if (er.getType().equals(Type.BOOLEAN)) {
				assertTrue("Documents exist?", er.getBoolean());
				// System.out.println("type boolean:"+er.getBoolean());
			} else if (er.getType().equals(Type.INTEGER)) {
				System.out.println("type Integer: "
						+ er.getNumber().longValue());
				assertEquals("count of documents ", 31, er.getNumber()
						.intValue());
			} else if (er.getType().equals(Type.STRING)) {
				// There is git issue 152
				System.out.println("type string: " + er.getString());
				assertTrue("String?",er.getString().contains("true")||er.getString().contains("xml")
						||er.getString().contains("31") ||er.getString().contains("1.0471975511966"));

			} else if (er.getType().equals(Type.NULL)) {
				// There is git issue 151
				// assertNull(er.getAs(String.class));
				System.out.println("Testing is empty sequence is NUll?"
						+ er.getAs(String.class));
			} else if (er.getType().equals(Type.OTHER)) {
				// There is git issue 151
				System.out.println("Testing is Others? "
						+ er.getAs(String.class));
				// assertEquals("Returns OTHERs","xdmp:forest-restart#1",er.getString());

			} else if (er.getType().equals(Type.ANYURI)) {
				// System.out.println("Testing is AnyUri? "+er.getAs(String.class));
				assertEquals("Returns me a uri :", "test1.xml",
						er.getAs(String.class));

			} else if (er.getType().equals(Type.DATE)) {
				// System.out.println("Testing is DATE? "+er.getAs(String.class));
				assertEquals("Returns me a date :", "2002-03-07-07:00",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.DATETIME)) {
				// System.out.println("Testing is DATETIME? "+er.getAs(String.class));
				assertEquals("Returns me a dateTime :",
						"2010-01-06T18:13:50.874-07:00", er.getAs(String.class));

			} else if (er.getType().equals(Type.DECIMAL)) {
				// System.out.println("Testing is Decimal? "+er.getAs(String.class));
				assertEquals("Returns me a Decimal :", "1.0471975511966",
						er.getAs(String.class));

			} else if (er.getType().equals(Type.DOUBLE)) {
				// System.out.println("Testing is Double? "+er.getAs(String.class));
				assertEquals(1.0471975511966, er.getNumber().doubleValue(), 0);

			} else if (er.getType().equals(Type.DURATION)) {
				System.out.println("Testing is Duration? "
						+ er.getAs(String.class));
				// assertEquals("Returns me a Duration :",0.4903562,er.getNumber().floatValue());
			} else if (er.getType().equals(Type.FLOAT)) {
				// System.out.println("Testing is Float? "+er.getAs(String.class));
				assertEquals(20, er.getNumber().floatValue(), 0);
			} else if (er.getType().equals(Type.GDAY)) {
				// System.out.println("Testing is GDay? "+er.getAs(String.class));
				assertEquals("Returns me a GDAY :", "---01",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.GMONTH)) {
				// System.out.println("Testing is GMonth "+er.getAs(String.class));
				assertEquals("Returns me a GMONTH :", "--01",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.GMONTHDAY)) {
				// System.out.println("Testing is GMonthDay? "+er.getAs(String.class));
				assertEquals("Returns me a GMONTHDAY :", "--12-25-14:00",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.GYEAR)) {
				// System.out.println("Testing is GYear? "+er.getAs(String.class));
				assertEquals("Returns me a GYEAR :", "2005-12:00",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.GYEARMONTH)) {
				// System.out.println("Testing is GYearMonth?1976-02 "+er.getAs(String.class));
				assertEquals("Returns me a GYEARMONTH :", "1976-02",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.HEXBINARY)) {
				// System.out.println("Testing is HEXBINARY? "+er.getAs(String.class));
				assertEquals("Returns me a HEXBINARY :", "BEEF",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.QNAME)) {
				// System.out.println("Testing is QNAME integer"+er.getAs(String.class));
				assertEquals("Returns me a QNAME :", "integer",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.TIME)) {
				// System.out.println("Testing is TIME? "+er.getAs(String.class));
				assertEquals("Returns me a TIME :", "10:00:00",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.ATTRIBUTE)) {
				// System.out.println("Testing is ATTRIBUTE? "+er.getAs(String.class));
				assertEquals("Returns me a ATTRIBUTE :", "attribute",
						er.getAs(String.class));

			} else if (er.getType().equals(Type.PROCESSINGINSTRUCTION)) {
				// System.out.println("Testing is ProcessingInstructions? "+er.getAs(String.class));
				assertEquals("Returns me a PROCESSINGINSTRUCTION :",
						"<?processing instruction?>", er.getAs(String.class));
			} else if (er.getType().equals(Type.COMMENT)) {
				// System.out.println("Testing is Comment node? "+er.getAs(String.class));
				assertEquals("Returns me a COMMENT :", "",
						er.getAs(String.class));
			} else if (er.getType().equals(Type.BASE64BINARY)) {
				// System.out.println("Testing is Base64Binary  "+er.getAs(String.class));
				assertEquals("Returns me a BASE64BINARY :", "DEADBEEF",
						er.getAs(String.class));
			} else {
				System.out
						.println("Got something which is not belongs to anytype we support "
								+ er.getAs(String.class));
				assertFalse("getting in else part, missing a type  ", true);
			}
		}
	}
```
Stack Trace:
```
java.lang.IllegalStateException: Content already retrieved
	at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContent(OkHttpServices.java:4367)
	at com.marklogic.client.impl.OkHttpServices$OkHttpResult.getContentAs(OkHttpServices.java:4389)
	at com.marklogic.client.impl.OkHttpServices$OkHttpEvalResult.getString(OkHttpServices.java:3462)
	at com.marklogic.client.functionaltest.TestEvalJavaScript.validateReturnTypes(TestEvalJavaScript.java:170)
	at com.marklogic.client.functionaltest.TestEvalJavaScript.testJSDifferentVariableTypesWithNulls(TestEvalJavaScript.java:476)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by sammefford** [comment]
Are you sure this behavior changed after commit f7643346dc909c7a0a7dbe45573605a5490fcb9c ?  I'm looking at the code for JerseyServices and it seems the same effect which you report should have happened before and after.
