### ISSUE TITLE
port jdbc examples to hsqldb

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#765]
We created four jdbc cookbook examples: `BulkLoadFromJdbcRaw`, `BulkLoadFromJdbcWithJoins`, `BulkLoadFromJdbcWithSimpleJoins`, and `IncrementalLoadFromJdbc`.  We used mysql (mariadb) to present a real-world scenario of migrating data between relational and MarkLogic.  

We also created unit test wrappers for them so we can ensure the cookbook examples work against the latest client & server.: `BulkLoadFromJdbcRawTest`, `BulkLoadFromJdbcWithJoinsTest`, `BulkLoadFromJdbcWithSimpleJoinsTest`, and `IncrementalLoadFromJdbcTest`.  However, that would require our Jenkins and regression environments to install mysql.  Rather than do that, let's try [hsqldb](http://hsqldb.org) since it can run embedded in the JVM.  Ideally, we'd run the tests off some data in src/main/resources/.  I'd like the code to work unmodified against mysql and hsqldb if possible.

**Comment by grechaw** [comment]
+1 I like this plan

**Comment by grechaw** [comment]
If there were a way to coordinate this work with ml-gradle, then you could deploy, run, and distribute code for a cookbook example as its own project, rather than embedded in the Client API repository.  That might be something to consider when a larger refactoring opportunity arises.

**Comment by sammefford** [comment]
I could see a github project containing just cookbook examples.  But would it make sense to have a separate project for each cookbook example?

Also, does ml-gradle help with managing java code?  I thought it was for MarkLogic.  Or did you mean gradle?

**Comment by jmakeig** [comment]
> But would it make sense to have a separate project for each cookbook example?

Probably not. Separate repo for *all* of the recipes is probably where I’d start.

> Also, does ml-gradle help with managing java code?

No, but gradle’s pretty good at that.

**Comment by grechaw** [comment]
ml-gradle helps if you have extensions (REST transforms, service extensions) to install.

**Comment by georgeajit** [comment]
The test passed after renaming.

```testsuite name="com.marklogic.client.test.example.cookbook.JdbcCookbookTest" time="12.055" tests="1" errors="0" skipped="0" failures="0"```
