### ISSUE TITLE
Implement SSLHostnameVerifier on OkHttp

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#772]
SSLHostnameVerifier was implemented as mostly a pass-thru from HttpClient.  Unfortuantely OkHttp doesn't offer the same interfaces.  We need to implement something to keep SSLHostnameVerifier available.

**Comment by georgeajit** [comment]
Functional tests written. Need manual intervention to setup MarkLogic Cerificate Authority, template and changes to REST App Server settings.
