### ISSUE TITLE
Implement Kerberos with Okhttp

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#776]
Implement Kerberos based authentication with Okhttp client. After moving on to Okhttp client from Jersey client, implement Kerberos based authentication through the new http client as well

**Comment by georgeajit** [comment]
Existing test ```TestDatabaseClientWithKerberos``` was used to verify with OKHttp. Security was enabled with changes to test.properties on the Java Client API side and a SSL enabled REST server was used. Tests ran fine.
