### ISSUE TITLE
test suite failures due to lack of xdmp:get-server-field privilege

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic/java-client-api#778]
Running the test suite from the develop branch yields 5 failures/132 errors.  Many of these errors are due to the request user not having the xdmp:get-server-field privilege.  Log is attached.

Tests were run in the following environment:

ML version: 9.0-1.1
OS: MacOS.  
Java version: 1.8.0_102-b14.  
Client API: develop branch at https://github.com/marklogic/java-client-api/commit/bdbfa6d2eff495000ac4b45b5b9385efabc4291c.  
Maven: Apache Maven 3.5.0

This was a brand new installation of everything except Java: I had freshly installed Maven for the first time, ML was a bare install of 9.0-1.1, and I had newly cloned the develop branch.  I ran mvn test-compile, followed by mvn exec:java@test-server-init, followed by mvn test..

When I gave the rest-writer role the xdmp:get-server-field privilege, most of the errors went away and I was left with errors that Sam Mefford was also getting, plus five semantics-related errors.

[java-client-api-develop-failures.txt](https://github.com/marklogic/java-client-api/files/1154196/java-client-api-develop-failures.txt)

**Comment by georgeajit** [comment]
@sammefford 

Why  should rest-writer be assigned  a xdmp:get-server-field? Isn't that a bug, then?  Or is this issue missing parts of user setup / other configurations?

**Comment by grechaw** [comment]
looks like a regression/bug to me.  accessing the rest error format should be amped. 
I'm surprised this is surfacing the Java tests and not trunk REST tests though.  Can you confirm that this is just 5.0-SNAPSHOT failures?

rest-writer should not have any privileges beyond the rest-writer and rest-reader privileges.

**Comment by grechaw** [comment]
There are a lot of errors in REST API unit tests today.  Looking into it.

**Comment by grechaw** [comment]
I see some notices that the nightly build was failing on mac and window last night.  Maybe this issue will be resolved underneath.

**Comment by sammefford** [comment]
@tdiepenbrock can you confirm that you didn't get any error when you ran `mvn exec:java@test-server-init`?  And you didn't change Common.java?  In other words, were you connecting to localhost port 8012?  And was the server left as normal with Digest auth?

**Comment by sammefford** [comment]
I ask because I don't know how to duplicate this.  When I follow the same steps I don't see the same errors

**Comment by sammefford** [comment]
Sorry, let me acknowledge that I haven't yet tried to fully duplicate your env.  I'd just be very surprised if this is env related . . . plus I don't have easy access to MacOS.
