### ISSUE TITLE
Add SUPPORT file

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#782]
https://help.github.com/articles/adding-support-resources-to-your-project/

Content TBD.

**Comment by georgeajit** [comment]
@rpelton ,

What do MarkLogic support like to see here?

**Comment by rpelton** [comment]
@georgeajit - the Support.md file would contain the same text as you currently have in the Support section of the readme.md file. 
I don't have an opinion as to whether you need it in both places, or just one.
