### ISSUE TITLE
Cannot stream when retrieving metadata 

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#783]
The following demonstrates that a large file fails to stream when metadata is also retrieved:

		XMLDocumentManager documentManager = client.newXMLDocumentManager();
		Transaction transaction = client.openTransaction();
		InputStreamHandle handle = new InputStreamHandle();
		DocumentMetadataHandle metadataHandle = new DocumentMetadataHandle();
		documentManager.writeAs("all_well.xml", new FileHandle(
			new File("test-complete/src/test/java/com/marklogic/client/functionaltest/data/all_well.xml")));
		documentManager.read("all_well.xml", metadataHandle, handle, transaction);
		InputStream stream = handle.get();
		while ( stream.read() > -1 ) {}

The last line just loops through reading the InputStream.  But this line will fail because the stream is closed.

**Comment by sammefford** [comment]
This is closely related to #725

**Comment by sammefford** [comment]
This was discovered from this SO post: https://stackoverflow.com/questions/45302832/read-and-write-using-documentmetadatahandle-and-inputstreamhandle

**Comment by sammefford** [comment]
As reported on SO, this was on the 3.0.7 release.  The 3.0.8 release (OkHttp replacement) appears to have resolved this issue.

**Comment by georgeajit** [comment]
Verified on nightly regression and Jenkins servers. Test ```testStack20170725``` in ```com.marklogic.client.test.DocumentMetadataHandleTest``` class runs fine and has passed.

**Comment by sammefford** [comment]
I should note that the error is no longer there, but we're not streaming.  OkHttp doesn't come with multi-part response processing so we had to use javax.mail.internet.MimeMultipart which does not stream.
