### ISSUE TITLE
Support HTTPS with Okhttp

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#784]
Add HTTPS support with OKhttp. We have to set the SSLContext and the Trustmanager to the client in order to support HTTPS connections.

**Comment by vivekmuniyandi** [comment]
Added new newClient methods and deprecated other newClient methods to include the TrustManager object as well. 

public DatabaseClient newClient(String host, int port, String user, String password, Authentication type, SSLContext context, TrustManager trustManager)

public DatabaseClient newClient(String host, int port, String database, String user, String password, Authentication type, SSLContext context, TrustManager trustManager) 

public DatabaseClient newClient(String host, int port, String user, String password, Authentication type, SSLContext context, TrustManager trustManager, SSLHostnameVerifier verifier)

public DatabaseClient newClient(String host, int port, String database, String user, String password, Authentication type, SSLContext context, SSLHostnameVerifier verifier)

Added the following method in RESTServices

public void connect(String host, int port, String database, String user, String password, Authentication type, SSLContext context, TrustManager trustManager, SSLHostnameVerifier verifier);

**Comment by sammefford** [comment]
I didn't think about needing all these new methods on the 3.x branch since we don't have *AuthContext objects.  Can we live without TrustManager on the 3.x branch?  It seems like we really only want for the future, but we don't anticipate more releases on the 3.x branch...

**Comment by georgeajit** [comment]
The OKHttp tests work with existing methods .
