### ISSUE TITLE
Support HTTPS with OKhttp

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#785]
Add HTTPS support with OKhttp. We have to set the SSLContext and the Trustmanager to the client in order to support HTTPS connections.

**Comment by sammefford** [comment]
It's probably worth clarifying that for the old (now deprecated) calls, we will use the deprecated OkHttp call sslSocketFactory(SSLSocketFactory sslSocketFactory) which says "SSLSocketFactory does not expose its X509TrustManager, which is a field that OkHttp needs to build a clean certificate chain. This method instead must use reflection to extract the trust manager. Applications should prefer to call sslSocketFactory(SSLSocketFactory, X509TrustManager), which avoids such reflection."  And this is the motivation for us to deprecate our *AuthContext.withSSLContext(SSLContext) method and replace it with *AuthContext.withSSLContext(SSLContext, X509TrustManager)

**Comment by kcoleman-marklogic** [comment]
When you guys sort all this out (for both 3.0-8 and 4.0-2), please create at least one doc task that summarizes the user visible changes, including any newly deprecated methods. This needs to be release noted.

**Comment by sammefford** [comment]
Thanks for the reminder, Kim.  I created https://github.com/marklogic/java-client-api/issues/786

**Comment by vivekmuniyandi** [comment]
public void connect(String host, int port, String database, String user, String password, Authentication type, SSLContext context, X509TrustManager trustManager, SSLHostnameVerifier verifier)

The old connect method is deprecated and is replaced with the above connect method which includes the X509TrustManager object as well.

SecurityAuthContext withSSLContext(SSLContext context, X509TrustManager trustManager) 
BasicAuthContext withSSLContext(SSLContext context, X509TrustManager trustManager) 
DigestAuthContext withSSLContext(SSLContext context, X509TrustManager trustManager) 
KerberosAuthContext withSSLContext(SSLContext context, X509TrustManager trustManager) 

For certificate auth context, we have included new constructors and deprecated the old ones
CertificateAuthContext(SSLContext context, X509TrustManager trustManager) 
CertificateAuthContext(SSLContext context, SSLHostnameVerifier verifier, X509TrustManager trustManager)
CertificateAuthContext(String certFile, X509TrustManager trustManager)
CertificateAuthContext(String certFile, String certPassword, X509TrustManager trustManager)

**Comment by georgeajit** [comment]
Turned on SSL on nightly regression runs. With naive TructManager (trust all certificates on the client side), the tests are running fine.

**Comment by georgeajit** [comment]
Identifying and adding CA root certificate to Java home.../security/cacerts, used by MarkLogic QA is ongoing. Will update as and when more information is received.

Plan is to have code that closely matches what customers should be and will be using.

**Comment by georgeajit** [comment]
Have tested with Naive TrustManager for QA tests. Vivek has tested with self signed certificate, with certificate being in the Java security cacert.

QA imported with existing ```ca.cer``` file into cacert and passed ```null``` into security context to test. But we still get the following exception.
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 65 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
```

Also tried to get ```SSLHostnameVerifier``` to verify what was being returned. The verifier values are null.
```
 final AtomicReference<String> certHostNames = new AtomicReference<String>();
        final AtomicReference<String[]> certCommontNames = new AtomicReference<String[]>();
        final AtomicReference<String[]> certSubjectAltNames = new AtomicReference<String[]>();
        
        SSLHostnameVerifier verifier = new SSLHostnameVerifier() {
            public void verify(String host, String[] cns, String[] alts) { 
                System.out.println("SSLHostnameVerifier verify is called.");
                //Verify the Certificate details
                certHostNames.set(host);
                certCommontNames.set(cns);
                certSubjectAltNames.set(alts);
            }
        };
      SSLContext sslcontext = null;
      if (IsSecurityEnabled()) {
        sslcontext = getSslContext();
        client = DatabaseClientFactory.newClient(getRestServerHostName(), getRestServerPort(), user, password, authType, sslcontext, verifier/*SSLHostnameVerifier.ANY*/);
        String hName = certHostNames.get();
        String[] altCN = certCommontNames.get();
...
...
```

Shiva is still trying to figure out the root and details.

**Comment by sammefford** [comment]
> we still get the following exception.
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Some good ideas here: https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

> The verifier values are null.

You'll need to first perform an operation that talks to the server, like a documentManager.exists(uri).
