### ISSUE TITLE
Document change to withSSLContext method

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#786]
We'll be deprecating *AuthContext.withSSLContext(SSLContext) and replacing it with *AuthContext.withSSLContext(SSLContext, X509TrustManager) so the HTTP client can have direct access to the TrustManager without resorting to a fragile reflection approach.  As always, the deprecated method will continue to work until the next major release.

**Comment by sammefford** [comment]
Here's another change I don't see any bug filed for. We'll be deprecating HttpClientConfigurator and publishing OkHttpClientConfigurator as a replacement.  That's because HttpClientConfigurator was tied to Apache HttpClient which we no longer ship or use.  If people keep using it, nothing should break but it will never be called.  That is as we've always stated in the javadocs.  The same will happen with OkHttpClientConfigurator if we ever deprecate it.

**Comment by kcoleman-marklogic** [comment]
Here are the release notes I added. Assigning to you for review, Sam. 

**Deprecation**:
>Java Client API 4.0.2 introduces the following deprecations.
>
>The com.marklogic.client.extra.httpclient.HttpClientConfigurator interface is deprecated and will be removed in a future release. Use the new com.marklogic.client.extra.okhttpclient.OkHttpClientConfigurator interface instead. Attaching a configurator based on HttpClientConfigurator to a DatabaseClientFactory object no longer has any effect on the HTTP configuration.
>
>The single parameter version of DatabaseClientFactory.SecurityContext.withSSLContext has been deprecated and will be removed in a future release. Instead, use the new version that requires an X509TrustManager as its second parameter. This change affects all classes that implement DatabaseClientFactory.SecurityContext, such as DatabaseClientFactory.CertificateAuthContext, DatabaseClientFactory.KerberosAuthContext, and DatabaseClientFactory.DigestAuthContext.

**Incompat**:
>Java Client API 4.0.2 Ignores HttpClientConfigurator
>
>As of version 4.0.2, the Java Client API uses OkHttp as its HTTP client for communicating with MarkLogic over HTTP. This change should be transparent to most applications, but imposes the following backward incompatibility on applications that customize their HTTP configuration:
>
>Attaching a configurator based on HttpClientConfigurator to a DatabaseClientFactory object no longer has any effect on the HTTP configuration. Use the new com.marklogic.client.extra.okhttpclient.OkHttpClientConfigurator interface instead. The HttpClientConfigurator interface is deprecated and will be removed in a future release.

**Comment by sammefford** [comment]
Those look great to me!
