### ISSUE TITLE
Edit the JDBC queries in examples in order to make it simple

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#789]
While porting to HSQLDB, we have written queries to handle HSQLDB and MYSQL db separately as the syntax changes. Clean up the code like inserting new tables rather than trying to update it which causes syntax differences.

**Comment by jmakeig** [comment]
> handle HSQLDB and MYSQL db separately as the syntax changes

Standards for the win!

**Comment by vivekmuniyandi** [comment]
Please make sure if the tests run fine. Thanks.

**Comment by georgeajit** [comment]
The tests run fine on Windows and Linux.
