### ISSUE TITLE
Configuration cannot be changed after starting this job or calling add or addAs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#793]
When I try to run the DMSDK code for #779 against develop branch, I get the error "Configuration cannot be changed after starting this job or calling add or addAs".  I see this stack trace embedded as a warning in the output:

07:53:59.050 [pool-1-thread-7] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.050 [pool-1-thread-7] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
07:53:59.061 [pool-1-thread-56] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.061 [pool-1-thread-56] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
07:53:59.062 [pool-1-thread-43] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.062 [pool-1-thread-43] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
[WARNING]
07:53:59.081 [pool-1-thread-27] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.081 [pool-1-thread-27] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
java.lang.IllegalStateException: Configuration cannot be changed after starting this job or calling add or addAs
        at com.marklogic.client.datamovement.impl.WriteBatcherImpl.requireNotInitialized(WriteBatcherImpl.java:343)
        at com.marklogic.client.datamovement.impl.WriteBatcherImpl.withJobId(WriteBatcherImpl.java:683)
        at com.marklogic.client.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:72)
        at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.startJob(DataMovementManagerImpl.java:80)
        at Issue779DMSDK.main(Issue779DMSDK.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)
07:53:59.131 [pool-1-thread-51] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.131 [pool-1-thread-51] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
07:53:59.131 [pool-1-thread-6] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.131 [pool-1-thread-6] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
07:53:59.140 [pool-1-thread-44] DEBUG c.m.client.impl.OkHttpServices - Posting documents
07:53:59.140 [pool-1-thread-44] DEBUG c.m.client.impl.OkHttpServices - Sending multipart for /v1/documents
07:53:59.160 [pool-1-thread-20] DEBUG c.m.client.impl.OkHttpServices - Posting documents

**Comment by sammefford** [comment]
It's clear to me now that the code in #779 was poorly constructed.  I shouldn't have been calling addAs before startJob.  But since that didn't cause errors for 4.0.1, no need to make it cause errors for 4.0.2.

**Comment by sammefford** [comment]
Ajit, to duplicate, see the unit test in the commit.  I'm validating that it's still ok to call add or addAs before startJob

**Comment by georgeajit** [comment]
Modified an existing test that had 
```
 dmManager.startJob(ihb1);
    ihb1.add("/doc/jackson", jacksonHandle).add("/doc/reader_wrongxml", readerHandle).add("/doc/string", docMeta1, stringHandle).add("/doc/file", docMeta2, fileHandle)
        .add("/doc/is", isHandle)
        .add("/doc/os_wrongjson", docMeta2, osHandle).add("/doc/bytes", docMeta1, bytesHandle).add("/doc/dom", domHandle);

    ihb1.flushAndWait();
```
to 
```
ihb1.add("/doc/is", isHandle);
    dmManager.startJob(ihb1);
    ihb1.add("/doc/jackson", jacksonHandle).add("/doc/reader_wrongxml", readerHandle).add("/doc/string", docMeta1, stringHandle).add("/doc/file", docMeta2, fileHandle)
        /*.add("/doc/is", isHandle)*/
        .add("/doc/os_wrongjson", docMeta2, osHandle).add("/doc/bytes", docMeta1, bytesHandle).add("/doc/dom", domHandle);

    ihb1.flushAndWait();
```
The test runs fine. Tested with ```develop``` (```5.0-SNAPSHOT.jar```) on MarkLogic Server build 20170828 using Eclipse IDE on Windows.
