### ISSUE TITLE
Document that everyone needs to now use jcenter

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#795]
Since we now depend on okhttp-digest which is only available via jcenter (not maven central), we need to update dev.marklogic.com, and everywhere else we teach people how to include java-client-api into their maven or gradle project.  They'll need to add the jcenter repository in addition to the marklogic-client-api dependency.

**Comment by sammefford** [comment]
For maven users we need to say:


Add this repository to your pom.xml repostories section:

		<repository>
			<id>jcenter</id>
			<url>http://jcenter.bintray.com</url>
		</repository>

**Comment by sammefford** [comment]
For gradle users we need to say:

Use gradle 1.7+ and add this to your build.gradle repositories section:

    jcenter()

**Comment by sammefford** [comment]
Kim, could you add a release note about this?

**Comment by kcoleman-marklogic** [comment]
This was addressed some time ago. This bug just never got closed. Mea cupla. See:

http://docs.marklogic.com/guide/java/intro#id_45280

**Comment by kcoleman-marklogic** [comment]
See previous comment.
