### ISSUE TITLE
Windows can't handle unix paths in examples

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#796]
BulkExportOpticResults.java and BulkExportOpticResultsToWriterTest.java reference /tmp/opticExampleOutput.txt but that's a path that doesn't work on windows.  Could you use File.createTempFile or System.getProperty("java.io.tmpdir") instead?

This causes the corresponding unit tests to fail for me on windows.

**Comment by sammefford** [comment]
Vivek, looks like we need another directory divider.  I see this error in last night's build: 

    java.io.FileNotFoundException: /tmpopticExampleOutput.txt (Permission denied)

http://jenkins.marklogic.com/job/JavaAPIUnitTest_develop_xdmp-trunk/lastBuild/testReport/com.marklogic.client.test.example.cookbook/BulkExportOpticResultsToWriterTest/testMain/

**Comment by vivekmuniyandi** [comment]
Strange.. In mac, it got me the '/' at the end and that's why I removed the extra '/' at the end. No offense adding an extra '/' at the end. Will do. Thanks for catching this.

**Comment by vivekmuniyandi** [comment]
Checked with Ajit and it passes in Linux.

**Comment by georgeajit** [comment]
Tested on Windows (through cygwin) and on Linux platforms. Used ```develop``` branch (```5.0-SNAPSHOT.jar```) on MarkLogic Server build 20170828.

Used  ```mvn test``` on both platforms to run the tests.
