### ISSUE TITLE
Write tests to handle negative / exception conditions for Kerberos 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#797]
Enhance existing Kerberos test to have newer tests that handle negative test cases and verify the error / exception messages.

**Comment by arthi-ramachandran** [comment]
@georgeajit , 4.0.3 release date is next Monday, Oct 23rd. Should this be shipped ?

**Comment by georgeajit** [comment]
Tests will be done in 4.0.4.

**Comment by arthi-ramachandran** [comment]
thanks
