### ISSUE TITLE
Need to close JDBC connections

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#801]
[Line 72](https://github.com/marklogic/java-client-api/blob/8a3f4f9012ac7eacbb303b6c87d577fae63e49a3/src/main/java/com/marklogic/client/example/cookbook/datamovement/BulkLoadFromJdbcWithJoins.java#L72) of BulkLoadFromJdbcWithJoins calls getConnection without closing the connection.  This creates a resource leak.  Can you call the close() method on that connection?

**Comment by sammefford** [comment]
Vivek, could you use try-with-resources or a try & do the close in a finally block?

**Comment by georgeajit** [comment]
Verified ```BulkLoadFromJdbcWithJoins```,  connection is within the try-with-resources.  ```BulkExportToJdbc``` does not have ```jdbcTemplate.getDataSource().getConnection()``` call and hence no ```java.sql.Connection``` instance.
