### ISSUE TITLE
SearchFacetTest failing with XDMP-BOUNDS

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#804]
I get the following test error:

com.marklogic.client.FailedRequestException: Local message: search failed: Internal Server Error. Server Message: XDMP-BOUNDS: cts:value-ranges(cts:element-attribute-reference(fn:QName("http://nwalsh.com/ns/photolib","view"),fn:QName("","date"),("type=date")), (xs:date("2017-08-25"), xs:date("2017-08-24"), xs:date("2017-08-25")), "concurrent", cts:word-query("Grand", ("lang=en"), 1), xs:double("1"), ()) -- Bounds must be in strictly ascending order . See the MarkLogic server error log for further detail.

This is because I have the following in options:

    <computed-bucket name="D0" ge="P0D"  lt="P1D" anchor="start-of-day"/>
    <computed-bucket name="D1" ge="-P1D" lt="P0D" anchor="start-of-day"/>
    <computed-bucket name="D2" ge="-P2D" lt="-P1D" anchor="start-of-day"/>
    <computed-bucket name="D3" ge="-P3D" lt="-P2D" anchor="start-of-day"/>
    <computed-bucket name="D4" ge="-P4D" lt="-P3D" anchor="start-of-day"/>
    <computed-bucket name="D5" ge="-P5D" lt="-P4D" anchor="start-of-day"/>
    <computed-bucket name="D6" ge="-P6D" lt="-P5D" anchor="start-of-day"/>

Which are not in ascending order.

**Comment by sammefford** [comment]
Ajit, we're good on this as long as the unit test passes

**Comment by georgeajit** [comment]
Verified on 08/28/2017 with ```develop``` branch (```5.0-SNAPSHOT```) on MarkLogic Server build 20170828. The test passed.
