### ISSUE TITLE
Unit test retry properties

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#806]
We have two properties that can influence retry behavior in Java Client API:

com.marklogic.client.maximumRetrySeconds
com.marklogic.client.minimumRetries

AFAIK, they aren't documented.  But in a support case a customer asked so I told them about the properties.  We need some unit tests or similar to verify these work as expected.

**Comment by ableasdale** [comment]
Based on my testing so far, these settings don't appear to influence the timeout aperture of a request. I set these values and ran the test we discussed yesterday.   I noticed that these values are configured in the JerseyServices class - could these have been broken when you made the move to OkHttp?

**Comment by sammefford** [comment]
Yes, they could have been broken. The code is there in OkHttpServices, that's why I told you to try them.  But I don't believe something is working unless we've tested it.  It's clear we need to test this.

**Comment by vivekmuniyandi** [comment]
Related bug track issue https://bugtrack.marklogic.com/47676
