### ISSUE TITLE
Check for minHosts > Available hosts in HostAvailabilityListener

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#807]
We don't do any checks if minHosts > Available hosts in cluster . I am not sure if we have to do that check. But, I am opening this bug just in case if we choose to do it.

This HostAvailabilityListener is created even though the server is a single node instance
```
failure.add( new HostAvailabilityListener(dmManager)
						.withSuspendTimeForHostUnavailable(Duration.ofSeconds(15))
						.withMinHosts(5));
```

**Comment by vivekmuniyandi** [comment]
The last time I spoke to Sam, he was a bit hesitant about the minHosts functionality and he said it is a functionality that is not so important. Validating this would have to call the forestInfo endpoint and throwing an error if the minHosts is greater than the number of hosts. So, I don't think this is necessary but I will check with Sam if he also feels the same way.

**Comment by sammefford** [comment]
What error do you get when you do this?  I'm guessing it says that the job was stopped because the number of hosts is less than minHosts.  Seems to me that addresses the issue because we're doing what they told us to do and telling them why we did it.

**Comment by srinathgit** [comment]
Sam,

The issue I mentioned is when creating an instance of HostAvailabilityListener. When instantiating, we don't check if available host > minHosts. We check only when the list of exceptions is thrown during job run.

**Comment by sammefford** [comment]
Yes.  I think it's fine if we only check when an exception is thrown during the job run.  I think it would be too surprising to users if we were making requests to the server just because they called withMinHosts.  We want our method names to make it clear when we're calling out to the server.  That's why those methods have action names like search, read, write, etc.
