### ISSUE TITLE
Replace images in testing folder with ones that are more obviously licensed

### ISSUE THREAD

**Issue by grechaw** [marklogic/java-client-api#808]
Hi @georgeajit ,

In reviewing our codebases, legal has found some data that should be replaced in any active develop branch.  These are images used in functional testing. Since they are on github, we'd prefer to replace them with images that are explicitly freely available to use.  Since they are just for testing, I assured Zak that it would be pretty straightforward to find new images that are not controversial.

To avoid false alarms in the future, a README in your test data folder that says all images are available for use -- that would help legal too.  Please let me know if you have questions.  Zak would like to see this done relatively quickly.

Here are the images flagged by the scan:

https://github.com/marklogic/java-client-api/blob/develop/test-complete/src/test/java/com/marklogic/client/functionaltest/data/JenoptikLogo.jpg

https://github.com/marklogic/java-client-api/blob/develop/test-complete/src/test/java/com/marklogic/client/functionaltest/data/Jenoptik_Logo.jpg

https://github.com/marklogic/java-client-api/blob/develop/test-complete/src/test/java/com/marklogic/client/functionaltest/data/Pandakarlino.jpg

https://github.com/marklogic/java-client-api/blob/develop/test-complete/src/test/java/com/marklogic/client/functionaltest/data/Sega-4MB.jpg

There are two other images in that folder which were not flagged by legal -- binary.jpg and Simple_ScanTe.jpg ..

**Comment by zakwhite** [comment]
binary.jpg and Simple_ScanTe.jpg should similarly be removed. Let me know if you have any questions.

**Comment by georgeajit** [comment]
@zakwhite 

Can this be done in next couple of weeks? We have a release on 09-11-2017 and do not want to have false alarms on test failures.

**Comment by zakwhite** [comment]
@georgeajit, yes that timeline is acceptable. Thanks for checking.

**Comment by kshitizmittal** [comment]
Hi Ajit,

I replaced below binary image file with our MarkLogic logo file and ran all dependent java tests which worked fine. I have made all changes to git repository and request to please take a look and review the same. 


Pandakarlino.jpg: TestBulkWriteMetadata1.java

JenoptikLogo.jpg: TestCRUDModulesDb.java

Jenoptik_Logo.jpg : Not used anywhere in java-client api tests

Sega-4MB.jpg: BinaryDocumentTest.java

Simple_ScanTe.png: TestMetadata.java, TestMetadataXML.java, TestRollbackTransaction.java

binary.jpg: UrisToWriterListenerFuncTest.java, TestCRUDModulesDb.java, TestLinkResultDocuments.java

Let me know for any clarification/concern. 


Thanks
Kshitiz
