### ISSUE TITLE
Sort on fitness or confidence

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#809]
New capabilities have been added to the search:search and REST API's as part of bugtrack issue 41610.  We need to add equivalent functionality to the Java Client API.

**Comment by grechaw** [comment]
It's some query builder work, indeed.  Note that although the vocabulary now supports these new options, they don't exhibit any different behavior from sorting on score.

**Comment by sammefford** [comment]
Thanks for the comment, Charles.  But I don't understand.  Shouldn't the values for fitness differ from confidence, and differ from score?  If the values for each result differ, shouldn't sorting on a particular value change the order of the results?
