### ISSUE TITLE
okhttp-digest unresolvable on maven central

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic/java-client-api#817]
Our customer is at a dead stop because com.burgstaller:okhttp-digest:jar:1.14 can't be resolved on maven central.

**Comment by hansenmc** [comment]
https://github.com/marklogic/java-client-api/issues/795

Add this repository to your pom.xml repostories section:

	<repository>
		<id>jcenter</id>
		<url>http://jcenter.bintray.com</url>
	</repository>

**Comment by sammefford** [comment]
@tdiepenbrock, are there better ways we can advertise such requirements?  We included it on http://developer.marklogic.com/products/java , but maybe we should have it somewhere else also...  Where did the customer go to download 4.0.2?

**Comment by hansenmc** [comment]
It's worth creating a ticket asking them to publish to Maven Central.Bintray makes it really easy. Then it would resolve and "just work" without custom repository config.

**Comment by tdiepenbrock** [comment]
Hi Sam,

It looks like the customer relies on Maven Central for everything.  They did not pull from the separate repo.  I’ll find out more tomorrow when we have our regularly scheduled conference call with them.

td


Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Sep 18, 2017, at 12:32 PM, Sam Mefford <notifications@github.com<mailto:notifications@github.com>> wrote:


@tdiepenbrock<https://github.com/tdiepenbrock>, are there better ways we can advertise such requirements? We included it on http://developer.marklogic.com/products/java , but maybe we should have it somewhere else also... Where did the customer go to download 4.0.2?

**Comment by jmakeig** [comment]
Is this still an issue? It’s not really in our control, as it’s a descendent ancestor.
