### ISSUE TITLE
Define HTTP Retry requirements

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#819]
The server has several scenarios where it throws retryable exceptions.  Currently the Java Client API only retries when the server responds with status code 503.  When else should we retry?

**Comment by sammefford** [comment]
This was prompted by Srinath stumbling on [this article](https://medium.com/inloop/okhttp-is-quietly-retrying-requests-is-your-api-ready-19489ef35ace).  At this point we can't say whether OkHttp is providing an improvement or regression because we're not clear what the requirements are.

**Comment by ehennum** [comment]
Retry has been enhanced for Load Balancer scenarios.
