### ISSUE TITLE
Java API TermQuery missing an options parameter

### ISSUE THREAD

**Issue by mwarnes** [marklogic/java-client-api#824]
The documentation describes the use of a term-option for a term query to distinguish it from a word query

https://docs.marklogic.com/guide/search-dev/structured-query#id_56027

However the TermQuery class does not take an options parameter as the ValueQuery does, in addition, the term() builder methods that are intended to be used in future also do not provide the necessary override methods.

http://docs.marklogic.com/8.0/javadoc/client/com/marklogic/client/query/StructuredQueryBuilder.TermQuery.html

> TermQuery(Double weight, String... terms)
> Deprecated.
> Use the term() builder method of StructuredQueryBuilder and type the object as an instance of the StructuredQueryDefinition interface.

term() builder methods

```
public StructuredQueryBuilder.TermQuery term(String... terms) {
return new StructuredQueryBuilder.TermQuery((Double)null, terms);
}

public StructuredQueryBuilder.TermQuery term(double weight, String... terms) {
return new StructuredQueryBuilder.TermQuery(weight, terms);
}
```

value() builder methods with String[] options overrides.

```
public StructuredQueryDefinition value(StructuredQueryBuilder.TextIndex index, Boolean value) {
return new StructuredQueryBuilder.ValueQuery(index, (StructuredQueryBuilder.FragmentScope)null, (String[])null, (Double)null, new Object[]{value});
}

public StructuredQueryDefinition value(StructuredQueryBuilder.TextIndex index, Number... values) {
return new StructuredQueryBuilder.ValueQuery(index, (StructuredQueryBuilder.FragmentScope)null, (String[])null, (Double)null, values);
}

public StructuredQueryDefinition value(StructuredQueryBuilder.TextIndex index, StructuredQueryBuilder.FragmentScope scope, String[] options, double weight, String... values) {
return new StructuredQueryBuilder.ValueQuery(index, scope, options, weight, values);
}

public StructuredQueryDefinition value(StructuredQueryBuilder.TextIndex index, StructuredQueryBuilder.FragmentScope scope, String[] options, double weight, Boolean value) {
return new StructuredQueryBuilder.ValueQuery(index, scope, options, weight, new Object[]{value});
}

public StructuredQueryDefinition value(StructuredQueryBuilder.TextIndex index, StructuredQueryBuilder.FragmentScope scope, String[] options, double weight, Number... values) {
return new StructuredQueryBuilder.ValueQuery(index, scope, options, weight, values);
}
```

Is the fact that the TermQuery Class does not take an options parameter an oversight or is there another method the customer should be using?
 collapse

**Comment by georgeajit** [comment]
Closing this issue to keep Search API stable.
