### ISSUE TITLE
Negative values for Host suspend time

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#834]
The withSuspendTimeForHostUnavailable method (HostAvailabilityListener class) takes an argument of type Duration . Duration allows negative values (Duration.ofDays(-100)). When such a value is set and a node is shut down, the new forest config is taken almost immediately. Since we throw IllegalArgumentException for negative minHosts value, should we do the same here ?

13:43:14.308 [pool-3-thread-41] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-9.marklogic.com", black-listing it for PT-2400H
13:43:14.328 [pool-3-thread-41] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-7.marklogic.com, rh7v-intel64-90-test-8.marklogic.com] hosts with forests for "WBFailover"

**Comment by sammefford** [comment]
I don't think that's necessary.
