### ISSUE TITLE
Host not added back to rotation after "host unavailability interval" expires 

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#835]
The process in HostAvailabilityListener which gets the updated forest config after a suspend time for host unavailable is only using one host to get the updated forest config.  If that host is down it fails to get the updated forest config.

When the WriteBatcher job was running in a 3 node cluster, node 3 is shut down . As you can see in the [log](https://github.com/marklogic/java-client-api/files/1357640/temp.txt), the forest config is not obtained after 25 seconds. This issue specifically happens by obtaining the database client object from a non bootstrap host and shutting down that host (you can choose to start the host again within 25 secs or allow the forest in that host to failover, it doesn't make any difference as far as getting another forest config  after 25 seconds is concerned).

dbClient = DatabaseClientFactory.newClient("rh7v-intel64-90-test-9", port, user, password, Authentication.DIGEST);
dmManager = dbClient.newDataMovementManager();
```
16:13:51.166 [pool-3-thread-34] ERROR c.m.c.d.HostAvailabilityListener - ERROR: host unavailable "rh7v-intel64-90-test-9", black-listing it for PT25S
16:13:47.332 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-9, rh7v-intel64-90-test-7.marklogic.com, rh7v-intel64-90-test-8.marklogic.com] hosts with forests for "WBFailover"
16:13:51.209 [pool-3-thread-34] INFO  c.m.c.d.impl.WriteBatcherImpl - (withForestConfig) Using [rh7v-intel64-90-test-7.marklogic.com, rh7v-intel64-90-test-8.marklogic.com] hosts with forests for "WBFailover"
```

```
	@Test
	public void testStopOneNode() throws Exception {
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 0);
		final AtomicInteger successCount = new AtomicInteger(0);
		final AtomicBoolean failState = new AtomicBoolean(false);
		final AtomicInteger failCount = new AtomicInteger(0);
		try {
			WriteBatcher ihb2 = dmManager.newWriteBatcher();
			ihb2.withBatchSize(2);
			ihb2.withThreadCount(99);

			HostAvailabilityListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(25))
					.withMinHosts(2);
			NoResponseListener.getInstance(ihb2).withSuspendTimeForHostUnavailable(Duration.ofSeconds(25))
					.withMinHosts(2);
			ihb2.onBatchSuccess(batch -> {
				successCount.addAndGet(batch.getItems().length);
			}).onBatchFailure((batch, throwable) -> {
				throwable.printStackTrace();
				failState.set(true);
				failCount.addAndGet(batch.getItems().length);
			});

			writeTicket = dmManager.startJob(ihb2);
			AtomicBoolean isRunning = new AtomicBoolean(true);
			for (int j = 0; j < 50000; j++) {
				String uri = "/local/ABC-" + j;
				ihb2.add(uri, stringHandle);
			/*	if (dmManager.getJobReport(writeTicket).getSuccessEventsCount() > 200 && isRunning.get()) {
					isRunning.set(false);
					serverStartStop(hostNames[hostNames.length - 1], "stop");
				}*/
			}
			ihb2.flushAndWait();

		} catch (Exception e) {
			e.printStackTrace();
		}
		Thread.currentThread().sleep(5000L);
		System.out.println("Fail : " + failCount.intValue());
		System.out.println("Success : " + successCount.intValue());
		System.out.println("Count : " + dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() == 50000);
	}
```

**Comment by sammefford** [comment]
I updated the summary since I think we'll want this issue to be easier for managers to grok.  The current behavior of HostAvailabilityListener only asking one host for updated forest config is expected behavior.  However, it doesn't seem congruent with the general failover support provided by HostAvailabilityListener.  In hind-sight I think we should add the ability to ask any available host in the cluster for the updated forest config.

Nevertheless, I think we can address this in 4.0.4.
