### ISSUE TITLE
Refactor code generation to be safe for javadocs

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#846]
Now that we're removing pegdown-doclet, the standard javadoc tool is being very picky about html errors in CtsExpr.java.  Let's figure out how the code generation can generate javadocs that don't generate errors or warnings.

**Comment by ehennum** [comment]
The code generation should now be replacing <, >, and & in comments with the equivalent HTML entities.

**Comment by sammefford** [comment]
Erik, can you also generate @param and @return lines for every member that has javadocs?  Right now `mvn javadoc:javadoc` generates a lot of warnings.

**Comment by ehennum** [comment]
Most of the lingering problems were fixed under #719 but I see that fragmentIdCol() is still missing @param.  Really, that's an XQY documentation bug, but the code generation should have a fallback.

**Comment by ehennum** [comment]
Also fixed a bug in off-by-one alignment of param documentation for chained methods like joinInner()
 (a bug detected originally for the code generated for the Optic Node.js API).

Should cause no regressions and should remove the Maven warning for the fragmentIdCol() @param
