### ISSUE TITLE
QueryBatcher getQuerySuccessListeners should have been onUrisReadyListeners

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#850]
It looks like a copy/paste bug crept in when I created getQuerySuccessListeners on WriteBatcher, then copied it to QueryBatcher and failed to rename it onUrisReadyListener.  We need to deprecate QueryBatcher.getQuerySuccessListeners, then create onUrisReadyListener, and replace in the javadocs for QueryBatcher the mention onQuerySuccess (there is no such thing) with onUrisReady.

**Comment by georgeajit** [comment]
Java docs examples have onUrisReady. QA tests also have the same.
