### ISSUE TITLE
java.lang.IllegalArgumentException on dmm.startJob(batcher);

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic/java-client-api#858]
```java
QueryManager qm = client.newQueryManager();

StructuredQueryBuilder sqb = qm.newStructuredQueryBuilder();
StructuredQueryDefinition query = sqb.collection(this.entity);

DataMovementManager dmm = client.newDataMovementManager();

QueryBatcher batcher = dmm.newQueryBatcher(query);

batcher.withConsistentSnapshot();

batcher.withBatchSize(100)
     .withThreadCount(20)
     .onUrisReady(batch -> {
        for ( String uri : batch.getItems() ) {
            System.out.println(uri);
        }
});

JobTicket ticket = dmm.startJob(batcher);
dmm.stopJob(ticket);
```

```
Exception in thread "main" java.lang.IllegalArgumentException
        at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1587)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl.initialize(QueryBatcherImpl.java:302)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl.start(QueryBatcherImpl.java:276)
        at com.marklogic.client.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:94)
        at com.marklogic.client.datamovement.impl.DataMovementManagerImpl.startJob(DataMovementManagerImpl.java:86)
        at com.marklogic.hadoop.metadata.BatchedUriReader.<init>(BatchedUriReader.java:128)
        at com.marklogic.hadoop.metadata.BatchedUriReader.main(BatchedUriReader.java:96)
```

**Comment by janmichaelyu** [comment]
I'm digging into QueryBatcherImpl.initialize() and in the setCorePoolSize() it's throwing an exception when the parameter is less than the maximumPoolSize.

`    public void setCorePoolSize(int corePoolSize) {
        if (corePoolSize < 0 || maximumPoolSize < corePoolSize)
            throw new IllegalArgumentException();
`

Inside the initialize() method the maxValue is being set after the corePoolSize so I think this needs to be called first. 
`
  private synchronized void initialize() {
    if ( threadCountSet == false ) {
      if ( query != null ) {
        Forest[] forests = getForestConfig().listForests();
        logger.warn("threadCount not set--defaulting to number of forests ({})", forests.length);
        withThreadCount(forests.length);
      } else {
        int hostCount = clientList.get().size();
        logger.warn("threadCount not set--defaulting to number of hosts ({})", hostCount);
        withThreadCount( hostCount );
      }
      // now we've set the threadCount
      threadCountSet = true;
    }
    logger.info("Starting job batchSize={}, threadCount={}, onUrisReady listeners={}, failure listeners={}",
      getBatchSize(), getThreadCount(), urisReadyListeners.size(), failureListeners.size());
    threadPool = new QueryThreadPoolExecutor(1, this);
    threadPool.setCorePoolSize(getThreadCount());
    threadPool.setMaximumPoolSize(getThreadCount());
  }`

I couldn't find any other way the threadPool was initialized so that the maxPoolSize is initialized before we can set the corePoolSize.

**Comment by vivekmuniyandi** [comment]
``` java
public void setCorePoolSize(int corePoolSize) {
        if (corePoolSize < 0 || maximumPoolSize < corePoolSize)
            throw new IllegalArgumentException();
```

In my source code, I don't see this. Also in the javadoc, I just checked for setCorePoolSize and it says they check for less than 0 for IllegalArgumentException. 
```
throws IllegalArgumentException - if corePoolSize < 0
```

I see something similar to what you say in setMaximumPoolSize.

```java
 public void setMaximumPoolSize(int maximumPoolSize) {
        if (maximumPoolSize <= 0 || maximumPoolSize < corePoolSize)
            throw new IllegalArgumentException();
```

Can you please let us know which version of Java are you using? Or am I missing something here? Please let us know. Thanks.

**Comment by janmichaelyu** [comment]
Hi,

I just checked and the java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize is on jdk-9.0.1. 

Which JDK is QueryBatcher compatible?

**Comment by vivekmuniyandi** [comment]
We haven't tested with JDK 9. All the tests currently run with JDK 8. I would suggest you to use that for now. We will address this when we test Java API's compatibility with JDK 9. Thanks.

**Comment by janmichaelyu** [comment]
Thank you!

**Comment by vivekmuniyandi** [comment]
@sammefford Please reopen if you want to keep this open to track this issue when we test Java 9. It would be obvious when we test this against Java 9, as the basic QueryBatcher fails. Your call. Thanks.

**Comment by sammefford** [comment]
Looks like Justin created #862, that will be fine
