### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#859]
https://github.com/blog/2111-issue-and-pull-request-templates

* Required info and how to get this information (e.g. `java -version`):
  * Java Client version
  * MarkLogic version
  * Java version (`java -version`)
  * OS and version
* Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
* Actual output: What did you observe? Were there errors? (Java logs, MarkLogic logs)
* Expected output: What specifically did you expect to happen? 
* Alternatives: What else have you tried, actual/expected?

**Comment by sammefford** [comment]
@jmakeig any feedback, or is this good as-is?

**Comment by jmakeig** [comment]
Suggestions:

* Show the actual commands to get the relevant software versions on Windows, macOS, and Linux
* Restructure the bullets into section headers, so it’s more like a template than a checklist
