### ISSUE TITLE
Make NOTICE.txt in distribution come from LEGALNOTICES.TXT

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#860]
I'm just finding that the NOTICES.txt file in the distribution is pulling from src/main/resources/NOTICE.txt not LEGALNOTICES.TXT.  We can leave LEGALNOTICES.TXT in the root directory to be prominent and visible on github, but let's make sure it's included in the distribution.  Since it now includes all the licenses for dependencies, we no longer need ASL-v2_0.txt, CDDL-v1_1.txt, EPL-v1_0.txt, nor MIT-X11.txt in the distribution.

We'll remove from src/main/resources the files ASL-v2_0.txt, CDDL-v1_1.txt, EPL-v1_0.txt, MIT-X11.txt, and NOTICE.txt.

**Comment by georgeajit** [comment]
The files have been removed.
