### ISSUE TITLE
Update copyright to 2018

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#872]
The pom.xml on develop, 4.0-master, etc. needs to be updated to use 2018 in the javadoc copyright. Until it is, any javadoc we release, such as with 9.0-4 or 8.0-8, will show a 2017 copyright.

In theory, this can be done for 4.0.4. In practice, it'd be very nice indeed to get it done before 9.0-4.

**Comment by vivekmuniyandi** [comment]
Sorry @kcoleman-marklogic I couldn't get to it previously. please check and let me know!

Added this [commit](https://github.com/marklogic/java-client-api/commit/91549afbb5b4566fefdfca494fa7c64962592a60)

**Comment by vivekmuniyandi** [comment]
@georgeajit please go through the commit and let me know if you see anything odd except for the copyright changes. Thanks.

**Comment by kcoleman-marklogic** [comment]
I checked the copyright on the 4.0.4 javadoc on pubs this morning. It looks good. 

@vivekmuniyandi Did you also change it on 3.0-develop? At least as far as the javadoc goes, it doesn't matter if we don't plan to ever release off that branch again, and it is certainly not urgent.
