### ISSUE TITLE
Change EvalResultIterator to implement java.io.Closeable

### ISSUE THREAD

**Issue by hansenmc** [marklogic/java-client-api#874]
Given the note in the JavaDocs for the ServerEvalIuationCall that the [EvalResultIterator must be closed](https://github.com/marklogic/java-client-api/blob/4.0-master/src/main/java/com/marklogic/client/eval/ServerEvaluationCall.java#L103)
>  * <p><b>NOTE: EvalResultIterator MUST BE CLOSED</b>.  If you call {@link #eval()} don't forget to call close() on the returned EvalResultIterator to free up the underlying resources.</p>

it would be useful if EvalResultIterator implemented java.io.Closeable.

If the EvalResultIterator implemented **Closeable**, it would be possible to use t[ry-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) to ensure that it is automatically called, and a bunch of finally blocks could be removed for cleaner and more simple code.

**Comment by sammefford** [comment]
Ajit, I made sure EvalTest runs w/out problem. If regression runs fine, I think we can ship this.
