### ISSUE TITLE
Use gradle rather than maven

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#877]
To be consistent with the regression tests and common best practice, we should use gradle rather than maven.

**Comment by vivekmuniyandi** [comment]
https://github.com/marklogic/java-client-api/pull/895 - The develop branch has the changes. 

QA:

Please run all the tests - both unit and functional with both 9.0 and 10.0. The pom.xml is still not removed. We can remove it later once we confirm that all the jars generated are same. Thanks!

**Comment by vivekmuniyandi** [comment]
The pom.xml and the distribution XMLs are removed.
