### ISSUE TITLE
"This instance has been stopped" in WriteBatcherTest

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#883]
* Version of MarkLogic Java Client API: _develop branch_ 
* Version of MarkLogic Server: _10.0-20180115_ 
* Java version: 1.8.0_161-b12
* OS and version: Win7 SP1
* Input: mvn test -Dtest=WriteBatcherTest
* Actual output: 
```
11:48:11.634 [Thread-3] DEBUG c.m.c.t.d.WriteBatcherTest - [testMultipleFlushAnStop_Issue109] flushAndWait threw expected exception since stopJob was called first: java.lang.IllegalStateException: This instance has been stopped
```
* Expected output: no exceptions unless it's explicit in the output that the exception is expected

**Comment by vivekmuniyandi** [comment]
@sammefford I'm not sure what needs to be done here. "flushAndWait threw expected exception since stopJob was called first" and the output says it's expected. Also, from the code, it catches the IllegalStateException and writes this message. Please let me know what I am missing. Thanks.

**Comment by sammefford** [comment]
You're seeing the wrong exception.  This exception is intermittent (I don't always see it).  I'm just trying to capture what I saw.  Well, kinda. I had a full stack trace when I started creating this, but somehow I lost it and couldn't reproduce with a stack trace, that's why this report only has the one line error.  If you're not seeing that error you perhaps had a clean run.

In any case, my concern is that I want to make sure this is just a test bug and not an indication of something that might happen in the field when people use DMSDK properly.

**Comment by sammefford** [comment]
As we discussed, I was running against a 3-node cluster with the db created by the unit test bootstrap script, I don't know if that makes a difference.  

I agree that my original error message is the wrong one because it says "expected".

Here are a couple more error messages I'm seeing that don't look ideal:

    1148 15:39:33.748 [pool-9-thread-1] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents     : Bad Request. Server Message: XDMP-DOCROOTTEXT: xdmp:get-request-part-body("xml") -- Invalid root text "this is not valid XML" at  line 1

     541 15:39:26.583 [pool-6-thread-18] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.MarkLogicIOException: Failed to serialize metadata

**Comment by sammefford** [comment]
Here's another:

    1618 15:39:39.566 [pool-19-thread-1] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at document     s: Bad Request. Server Message: XDMP-JSONDOC: xdmp:get-request-part-body("json") -- Document is not JSON

**Comment by sammefford** [comment]
Attaching the full test log:
[log.txt](https://github.com/marklogic/java-client-api/files/1701234/log.txt)

**Comment by vivekmuniyandi** [comment]
@sammefford All these are valid tests and there is nothing to be worried about. The Warnings happen only when the stop job is called or we purposely send an XML string as JSON in order to trigger the failure scenarios and test them. I went through all the WARN messages and everything looked valid and nothing seemed to be wrong. Thanks.

**Comment by sammefford** [comment]
ok, thanks for verifying. Sorry for the noise.
