### ISSUE TITLE
Type.STRING is not recognized in TableauDataExtractWriterTest file

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#884]
* Version of MarkLogic Java Client API : Branch issue839
* Version of MarkLogic Server : 9.0 Nightly server (9.0-20180130)
* Java version: Java 8
* OS and version : Windows with Eclipse IDE
* Tableau Extract API for Windows Zip download (filename) : Tableau-SDK-C-Java-64Bit-10-3-7.zip

Checked out ```issue839``` branch and imported as an existing maven project and built the project using the POM. 
Downloaded the Tableau Extract API  from https://onlinehelp.tableau.com/current/api/sdk/en-us/SDK/tableau_sdk_installing.htm.
The zip file (named as above in the bullet item) was extracted and the Jars were added as "External Jars" to the build path of the project. The following Jars were added:

```
jna.jar
tableaucommon.jar
tableauextract.jar
tableauserver.jar
```
The ```testTypes()``` method produces compile errors for ```Type.STRING```. Looks like we can use ```Type.CHAR_STRING```.

**Comment by georgeajit** [comment]
I see that there are two TableauDataExtractWriterTest files.

```package com.marklogic.client.moveToCommunity;```
and
```package com.marklogic.client.test.moveToCommunity;```

The above reported issue is in ```package com.marklogic.client.moveToCommunity;```

**Comment by sammefford** [comment]
Thanks for the find guys!  I had a change on my machine to remove that file that I didn't commit or push because I had never added that file, so I thought nobody else would see it.  In any case, I've removed it in commit dd766f19003210c0ac5386d5447820f043f30611

**Comment by georgeajit** [comment]
Use ```Type.UNICODE_STRING```. The tests are corrected.
