### ISSUE TITLE
Expose all SecurityContext details via getters

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#885]
We need to allow applications to get from a DatabaseClient everything that went into it.  Specifically, we currently don't expose a way to to get the X509TrustManager provided to SecurityContext.  I'm not sure what else we might not be exposing.

**Comment by sammefford** [comment]
This issue was by @paxtonhare who requested access to the HostnameVerifierAdapter in OkHttpServices because he has no way to create his own direct connection to MarkLogic using just the information provided by DatabaseClient.  Given the function of HostnameVerifierAdapter to translate  SSLHostnameVerifier to the more standard javax.net.ssl.HostnameVerifier, and the need for that to create a valid external HTTP connection, I think it also makes sense as part of this to make HostnameVerifierAdapter public.  I don't think it should be attached to OkHttpServices since that's an internal class only, so we should probably move it to a stand-alone class.  Maybe 

    public static javax.net.ssl.HostnameVerifier SecurityContext.adaptHostnameVerifier(SSLHostnameVerifier)?

**Comment by ehennum** [comment]
I'm also wondering whether the setter should have overloads and deprecations equivalent to the fluents:

https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClientFactory.SecurityContext.html#setSSLContext-javax.net.ssl.SSLContext-

**Comment by ehennum** [comment]
@anu3990 , can you investigate gaps in the getters exposed by SecurityContext and its implementations with special attention to the comment from Feb 5 above?  Thanks.

**Comment by ehennum** [comment]
@anu3990 , having taken a closer look, I'm wondering if a clean approach might be to refactor

    com.marklogic.client.impl.OkHttpServices.HostnameVerifierAdapter

as a private subclass of 

    com.marklogic.client.DatabaseClientFactory.SSLHostnameVerifier

and add the following method to SSLHostnameVerifier

    javax.net.ssl.HostnameVerifier asHostnameVerifier();

whose implementation constructs and returns HostnameVerifier.

That way, any instance of SSLHostnameVerifier can return itself.

It might also be worth considering whether the SecurityContext could take a HostnameVerifier.

What do you think?

**Comment by anu3990** [comment]
I guess com.marklogic.client.DatabaseClientFactory.SSLHostnameVerifier.HostnameVerifierAdapter will be the same as com.marklogic.client.impl.OkHttpServices.HostnameVerifierAdapter, I mean it will have both overloaded verify methods and the constructor.
Also will "javax.net.ssl.HostnameVerifier asHostnameVerifier();" take SSLHostnameVerifier as a parameter.? If yes, I found "connect" function in "com.marklogic.client.impl.OkHttpServices" which creates HostnameVerifier based on SSLHostnameVerifier. I guess the implementation of asHostnameVerifier() will be something similar. Am i correct.?
