### ISSUE TITLE
Add to ExtractViaTemplateListener an ability to use template from the filesystem

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#888]
* Version of MarkLogic Java Client API: 9.0.4

Currently ExtractViaTemplateListener has withTemplate(String templateUri) method which accepts the uri to a template in MarkLogic server.  Some may want to point to a file on the Filesystem.  We could add with Template(File templateFile) which would read the template from the client file system, upload it to MarkLogic Server with a temporary UUID uri, then run the job, then delete the template from MarkLogic server when the job is complete.

**Comment by ehennum** [comment]
Privileges to install a transform are different from the privileges to use a transform.
