### ISSUE TITLE
Accessing a database that isn't the REST server's default database can lead to unpredictable results

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#890]
* Java Client version - 4.0.3.1 (verified on 4.0.3 and 4.0.2 as well)
* ML version - verified on 9.0-3 and 9.0-4
* Java version - 1.8u131
* Mac 10.12.6

From a fresh ML install, run the following script in qconsole for both Documents and Triggers:

    for $i in 1 to 25000
    return xdmp:document-insert("/test/" || $i || ".xml", <hello>{$i}</hello>, (), "test")

Then, run this program with Documents first, and then modify Documents to be Triggers. It will successfully delete all 25k docs in Documents, but only about half in Triggers.

    DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8000, "Documents",
	new DatabaseClientFactory.DigestAuthContext("admin", "admin"));
    try {
	    DataMovementManager dmm = client.newDataMovementManager();
	    StructuredQueryDefinition query = client.newQueryManager().newStructuredQueryBuilder().collection("test");
	    QueryBatcher queryBatcher = dmm.newQueryBatcher(query);
	    queryBatcher.onUrisReady(new DeleteListener());
	    queryBatcher.withConsistentSnapshot();
	    dmm.startJob(queryBatcher);
	    queryBatcher.awaitCompletion();
	    dmm.stopJob(queryBatcher);
    } finally {
	    client.release();
    }

The issue is reproducible with any database that isn't the default content database for the REST port that's connected to.

**Comment by vivekmuniyandi** [comment]
Filed a bug against REST API for the same. https://bugtrack.marklogic.com/49116

We pass in the required options but it is somehow getting missed

With DB 

/v1/internal/uris?structuredQuery=<query xmlns="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:search="http://marklogic.com/appservices/search" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<collection-query><uri>test</uri></collection-query>
</query>&pageLength=1000
&forest-name=test-DBForest
&start=2001&timestamp=15184680602698090
&database=test-DB

Without DB 

/v1/internal/uris?structuredQuery=
<query xmlns="http://marklogic.com/appservices/search" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:search="http://marklogic.com/appservices/search" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<collection-query><uri>test</uri></collection-query>
</query>&pageLength=1000
&forest-name=Documents

&start=2001&timestamp=15184663803267300


For some reason, the point in time query is not working. When I try to delete the document and issue a point in time query, the deleted document doesn't show up.

**Comment by ehennum** [comment]
Closing because the fix to the server bug would be necessary and should be sufficient without additional work on the client.
