### ISSUE TITLE
Configure WriteBatcher to periodically flush itself

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#893]
In an environment like Apache Nifi, it's very useful to instantiate a `WriteBatcher` for other processors to send data to. So e.g. as files are read from disk or messages from a JMS queue, they can be handed off to a Nifi processor that uses `WriteBatcher` to perform batched writes to MarkLogic.

There's one catch though - that Nifi processor doesn't typically know when "all" the messages have been sent. For example, there's typically no "done" message from a JMS queue. And a processor that watches a directory doesn't know when no more files will show up. The issue - a `WriteBatcher` may then have a set of documents left to write, but they won't get flushed until enough new documents show up to force a flush. 

What I'm proposing then is a method on WriteBatcher that allows a user to specify a number of milliseconds to wait such that if that amount of time is reached without a new document being written, then `flushAsync` will automatically be called. This will address the scenario above, as well as scenarios featuring other tools like Nifi, such as Camel or any similar event-based mechanism. 

The syntax would be something like this:

```java
long timeToWait = 500;
writeBatcher.withAutomaticFlushPeriod(timeToWait);
```

**Comment by jmakeig** [comment]
Is there a workaround today to implement the timer in calling application?

**Comment by rjrudin** [comment]
I've been going back and forth on whether this should be a concern of DMSDK or not. I found a workaround with NiFi - there's a concept of "trigger this processor even when there's nothing to process", and that provides a hook for calling flushAsync periodically. 

In theory, any sort of event-based framework like Camel/NiFi/etc will provide some workaround like this. So I'm going to close this for now until I can come up with a better argument for why DMSDK should handle this concern itself.

**Comment by jmakeig** [comment]
One could argue that DMSDK can’t know when work is done and that’s the exclusive job of the caller, who presumably manages the other aspects of the stream as well. That nuance is subtle and easy to forget to handle in the caller, though.
