### ISSUE TITLE
Update dependencies for the release

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#897]
Update all the dependencies to the latest version

**Comment by vivekmuniyandi** [comment]
@georgeajit please update the dependencies in functional tests if needed. I have updated everything in the parent project and in marklogic-client-api project.

**Comment by georgeajit** [comment]
There was a space when QA committed changes to this issue, hence the changes are not reflected. Here are the changes done in test project's ```build.gradle``` file.

```
compile group: 'org.skyscreamer', name: 'jsonassert', version: '1.5.0'
compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.0'
compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.0'
compile group: 'commons-io', name: 'commons-io', version: '2.6'
```
