### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by itsshivaverma** [marklogic/java-client-api#899]
tried ./gradlew publish:

Logs:

21:44:02 Wed Feb 28 21:44:02 PST 2018 [DEBUG]: git clone -b develop https://github.com/marklogic/java-client-api.git java-client-api
21:44:02 /usr/bin/git
21:44:02 git version 1.8.3.1
21:44:08 Wed Feb 28 21:44:07 PST 2018 [DEBUG]: Executing command: cd /space/builder/builds/linux64/develop/java-client-api
21:44:08 Wed Feb 28 21:44:07 PST 2018 [DEBUG]: cd /space/builder/builds/linux64/develop/java-client-api
21:44:08 Wed Feb 28 21:44:07 PST 2018 [INFO]: creating java-client package, saving to /space/builder/builds/linux64/develop/logs.20180228.4/javaclient-build.logs
21:44:08 Wed Feb 28 21:44:08 PST 2018 [DEBUG]: ./gradlew publish
21:44:09 :marklogic-client-api:generatePomFileForMainJavaPublication
21:44:09 :marklogic-client-api:compileJavaPOM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
21:44:09 
21:44:09 Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
21:44:09 Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
21:44:15 Note: Some input files use or override a deprecated API.
21:44:15 Note: Recompile with -Xlint:deprecation for details.
21:44:15 Note: Some input files use unchecked or unsafe operations.
21:44:15 Note: Recompile with -Xlint:unchecked for details.
21:44:17 :marklogic-client-api:processResources
21:44:17 :marklogic-client-api:classes
21:44:17 :marklogic-client-api:jar
21:44:25 :marklogic-client-api:javadoc/space/builder/builds/linux64/develop/java-client-api/java-client-api/src/main/java/com/marklogic/client/datamovement/WriteBatcher.java:143: error: @param name not found
21:44:25    * @param DocumentWriteOperation the DocumentWriteOperation object containing 
21:44:25             ^
21:44:25 /space/builder/builds/linux64/develop/java-client-api/java-client-api/src/main/java/com/marklogic/client/datamovement/WriteBatcher.java:147: warning: no @param for writeOperation
21:44:25   WriteBatcher add(DocumentWriteOperation writeOperation);
21:44:25                ^
21:45:12 
21:45:12 1 error
21:45:12 1 warning
21:45:12 :marklogic-client-api:javadoc FAILED
21:45:12 
21:45:12 FAILURE: Build failed with an exception.
21:45:12 
21:45:12 * What went wrong:
21:45:12 Execution failed for task ':marklogic-client-api:javadoc'.
21:45:12 > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/space/builder/builds/linux64/develop/java-client-api/java-client-api/build/tmp/javadoc/javadoc.options'
21:45:12 
21:45:12 * Try:
21:45:12 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
21:45:12 
21:45:12 * Get more help at https://help.gradle.org
21:45:12 
21:45:12 BUILD FAILED in 1m 3s
21:45:12 5 actionable tasks: 5 executed
21:45:12 Wed Feb 28 21:45:11 PST 2018 [DEBUG]: ./gradlew pubZip
21:45:12 
21:45:12 FAILURE: Build failed with an exception.
21:45:12 
21:45:12 * What went wrong:
21:45:12 Task 'pubZip' not found in root project 'marklogic-client-api-parent'. Some candidates are: 'publish'.
21:45:12 
21:45:12 * Try:
21:45:12 Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
21:45:12 
21:45:12 * Get more help at https://help.gradle.org
21:45:12 
21:45:12 BUILD FAILED in 0s
21:45:13 Wed Feb 28 21:45:12 PST 2018 [ERROR]: FATAL!! java-client build FAILED
21:45:13 cat: /space/builder/builds/linux64/develop/logs.20180228.4/javaclient-build.txt: No such file or directory
21:45:13 Wed Feb 28 21:45:12 PST 2018 [ERROR]: 
[Pipeline] sh
21:45:13 [develop] Running shell script
21:45:13 + compgen -G '/space/builder/builds/linux64/develop//java-client-api/target/*zip'

**Comment by vivekmuniyandi** [comment]
Shiva,

The build failed because of javadoc. The name in the javadoc was not equal to the function parameter. I will commit the changes now. You should be able to do a ./gradlew publish after that. Also for generating the zip with dependencies, we need to run ./gradlew distZip. Let me know if it goes through. Thanks.

**Comment by grechaw** [comment]
For publishing snapshots I'd highly recommend skipping javadoc creation.  It takes a very long time for the Java Client API.    We also do not need snapshots of the jar with dependencies.  Might as well head off the huge disk space ballooning early.



Charles Greer
Lead Engineer
MarkLogic Corporation
cgreer@marklogic.com
Cell:  +1 707 318 0442
@grechaw
www.marklogic.com

________________________________

**Comment by kcoleman-marklogic** [comment]
Vivek, I already sent you mail about this, but just to the info where it belongs:

I need a way to override the javadoc title at javadoc build time. The default configuration appends "SNAPSHOT", which is not OK for the docs, so the doc build builds its own and stomps the javadoc title.

With maven, I could do this by adding something like  `-Djavadoc-title="${project.name} $VERSION"` to the maven command line when building the javadoc. The project name was a var set in the pom.xml. The version was set by us.

I'm sure there's a way to something equivalent using gradle, but I have no idea how. Please advise.

**Comment by hansenmc** [comment]
@kcoleman-marklogic the JavaDoc title is concatenating the `describedName` and `version` project properties:

    options.docTitle = "$rootProject.describedName $rootProject.version"

The `$rootProject.version` is set in the `gradle.properties` as `5.0-SNAPSHOT` at the root of the project, but you can override that value on the commandline:

    ./gradlew javadoc -Pversion=5.0

**Comment by kcoleman-marklogic** [comment]
Yes, I believe that's the result of the change Vivek made about an ago for my sake.  It appears to be working swimmingly.

BTW, shouldn't the default version on develop be 4.0.4 right now rather than 5.0? There's no 4.0-develop branch, so I certainly hope so!

**Comment by kcoleman-marklogic** [comment]
@vivekmuniyandi Is there a way in gradle to give the JVM more memory when it generates the javadoc? It's running out during the automated doc build.

I forgot we ran into this problem before. You can see how Sam got around it in the maven build here:

https://github.com/marklogic/java-client-api/blob/b3b618ca5f5bf2362b337fbd06c5633123ee5587/pom.xml#L91

**Comment by vivekmuniyandi** [comment]
@kcoleman-marklogic I will look into it today and make the changes. Thanks!

**Comment by vivekmuniyandi** [comment]
Made all the changes and the build has been successful in the past days.
