### ISSUE TITLE
javadoc build failing on develop

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#903]
There's an angle bracket that needs to be encoded near the end of this line:

https://github.com/marklogic/java-client-api/blob/9fb5ad3279302fe37f5b88b7f5dc16a3b089278e/marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/ExtractViaTemplateListener.java#L57

Just like in XML, you'll need to encode it as `&gt;`.

**Comment by kcoleman-marklogic** [comment]
(And while you're at it... That block should really get wrapped in an @code tag. Like the example here:

https://github.com/marklogic/java-client-api/blob/9fb5ad3279302fe37f5b88b7f5dc16a3b089278e/marklogic-client-api/src/main/java/com/marklogic/client/datamovement/DataMovementManager.java#L43-L50

Without that, the newlines get discarded, I believe.)

**Comment by vivekmuniyandi** [comment]
Thanks Kim! Will make the changes today and let you know. Thanks!

**Comment by kcoleman-marklogic** [comment]
It's working now. Thanks!
