### ISSUE TITLE
StructuredQueryBuild search throws exception when no results found

### ISSUE THREAD

**Issue by alan-johnson** [marklogic/java-client-api#908]
So we can address your issue, please include the following:
* Version of MarkLogic Java Client API (see Readme.txt)
MarkLogic 8 - Java API 3.0.1, 3.0.8
MarkLogic 9 - Java API 4.0.3, 4.0.3.1
* Version of MarkLogic Server (see admin gui on port 8001)
MarkLogic 8.0-3
MarkLogic 9.0-4
* Java version (`java -version`)
java version "1.8.0_111"
* OS and version
MacOS, High Sierra, 10.13.3
* Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
Structured queries throw an exception when the data queried is not found. If data is found, results are returned as expected and no exceptions are throws. I've included a .ZIP file that recreates the issue using ML9 and 4.0.3.1 of the Java Client API.

//DEFINE A QUERY MANAGER
        QueryManager queryMgr = client.newQueryManager();
		
		//DEFINE THE STRUCTURED QUERY BUILDER AND TELL IT WHICH SEARCH OPTIONS DOCUMENT TO USE
        StructuredQueryBuilder sQB = new StructuredQueryBuilder("Unit09-Exercise3-Options");
		
		//CREATE THE STRUCTURED QUERY
		//WE WANT "AND" LOGIC:  ARTIST AND GENRE AND OTHER-TERM AND NOT SOME-OTHER-TERM
		StructuredQueryDefinition queryDef = sQB.and(
				sQB.rangeConstraint("artist", Operator.EQ, qArtist),
				sQB.rangeConstraint("genre", Operator.EQ, qGenre),
				sQB.term(qOther),
				sQB.not(sQB.term(qNot))
                );
                
		//RUN THE QUERY, RETURNING RESULTS USING A SEARCH HANDLE
		SearchHandle results = queryMgr.search(queryDef, new SearchHandle());

* Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleResponse(SearchHandle.java:1157)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleTop(SearchHandle.java:1130)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.parse(SearchHandle.java:1098)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.access$100(SearchHandle.java:1061)
	at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:158)
	at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:82)
	at com.marklogic.client.impl.OkHttpServices.search(OkHttpServices.java:2062)
	at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:175)
	at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:139)
	at com.mlu.app.App.runSearch(App.java:52)
	at com.mlu.app.App.main(App.java:26)

* Expected output: What specifically did you expect to happen?
Expected no results but no exceptions thrown.
[mlu-test.zip](https://github.com/marklogic/java-client-api/files/1835764/mlu-test.zip)

* Alternatives: What else have you tried, actual/expected?

**Comment by vivekmuniyandi** [comment]
I don't have the options and so I changed the code like this
```
//DEFINE A QUERY MANAGER
QueryManager queryMgr = client.newQueryManager();
		
//DEFINE THE STRUCTURED QUERY BUILDER AND TELL IT WHICH SEARCH OPTIONS DOCUMENT TO USE
StructuredQueryBuilder sQB = new StructuredQueryBuilder();
		
//CREATE THE STRUCTURED QUERY
//WE WANT "AND" LOGIC:  ARTIST AND GENRE AND OTHER-TERM AND NOT SOME-OTHER-TERM
StructuredQueryDefinition queryDef = sQB.and(
	sQB.term(qOther),
	sQB.not(sQB.term(qNot)));

//RUN THE QUERY, RETURNING RESULTS USING A SEARCH HANDLE
SearchHandle results = queryMgr.search(queryDef, new SearchHandle());
		
//RUN SEARCH AGAIN BUT OUTPUT THE RESULTS IN THE CONSOLE USING A STRING HANDLE
System.out.println(queryMgr.search(queryDef, new StringHandle()).get());
		
return results;
```

This gave me nothing to match. I got the following output

```
<search:response snippet-format="snippet" total="0" start="1" page-length="10" xmlns:search="http://marklogic.com/appservices/search">
  <search:metrics>
    <search:query-resolution-time>PT0.001131S</search:query-resolution-time>
    <search:total-time>PT0.001351S</search:total-time>
  </search:metrics>
</search:response>

Hello World!
```
I get no exception.

Please paste the options. I will check again.

**Comment by alan-johnson** [comment]
Thanks for attempting to recreate! That helps narrow down the issue.  I've attached 3 .zip files to assist in further efforts. One is the search options and a curl command to load them. You'll probably have to adjust the curl call as it's targeting our course environment. Another .zip has a couple of test top-songs .XML documents to verify results. The final is the database index configuration that was used. I hope these are helpful.
[stuct-query-options.zip](https://github.com/marklogic/java-client-api/files/1839474/stuct-query-options.zip)
[top-songs-config.zip](https://github.com/marklogic/java-client-api/files/1839475/top-songs-config.zip)
[top-songs.zip](https://github.com/marklogic/java-client-api/files/1839476/top-songs.zip)

**Comment by vivekmuniyandi** [comment]
Thanks for passing those! Still unsuccessful. Can you paste me the full stack of the exception. The issue is missing some details of the exception. Also, doing a curl

```
curl --anyauth --user admin:admin -X PUT -d@"/Users/vmuniyan/Desktop/top-songs-config/database-config.json" -i -H "Content-type: application/json" "http://localhost:8002/manage/v2/databases/Documents/properties"
```

on the Documents database, gives me a 500 Internal server error

```
{"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"XDMP-AS", "message":"XDMP-AS: (err:XPTY0004) $localname as xs:string -- Invalid coercion: <localname xmlns=\"http://marklogic.com/manage/database/properties\">...</localname> as xs:string"}}
```

**Comment by alan-johnson** [comment]
Ok. I recreated everything from the app server, loading test songs, loading database index config and loading search options. These are attached in the attached .zip files. I've also included my code test app in the "mlu-test.zip" file. 

To setup my test bed:
- run the curl statement in the "top-songs-server-config" folder to create the rest instance, content and module databases.
- run the curl statement in the "top-songs-config" folder to load the index options to the "top-songs-content" database
- run the 2 curl statements in the "top-songs" folder to load the song documents. 
- run the curl statement in the "struct-query-options" to load the search option used.

Testing:
My success criteria was artist="eagles" genre="Rock" other="kid" and not condition="". My failure criteria changes genre="classic".

The results of the failure are as follows:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: 
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DurationImpl.<init>(DurationImpl.java:519)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DurationDayTimeImpl.<init>(DurationDayTimeImpl.java:106)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl.newDurationDayTime(DatatypeFactoryImpl.java:362)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.parseTime(SearchHandle.java:1615)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleMetrics(SearchHandle.java:1550)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleTop(SearchHandle.java:1140)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.collectTop(SearchHandle.java:1169)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleResponse(SearchHandle.java:1157)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.handleTop(SearchHandle.java:1130)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.parse(SearchHandle.java:1098)
	at com.marklogic.client.io.SearchHandle$SearchResponseImpl.access$100(SearchHandle.java:1061)
	at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:158)
	at com.marklogic.client.io.SearchHandle.receiveContent(SearchHandle.java:82)
	at com.marklogic.client.impl.OkHttpServices.search(OkHttpServices.java:2062)
	at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:175)
	at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:139)
	at com.mlu.app.App.runSearch(App.java:52)
	at com.mlu.app.App.main(App.java:26)

[mlu-test.zip](https://github.com/marklogic/java-client-api/files/1843729/mlu-test.zip)
[struct-query-options.zip](https://github.com/marklogic/java-client-api/files/1843730/struct-query-options.zip)
[top-songs-config.zip](https://github.com/marklogic/java-client-api/files/1843731/top-songs-config.zip)
[top-songs-server-config.zip](https://github.com/marklogic/java-client-api/files/1843732/top-songs-server-config.zip)
[top-songs.zip](https://github.com/marklogic/java-client-api/files/1843733/top-songs.zip)

**Comment by vivekmuniyandi** [comment]
Sorry, I lost this. Will try it out in the coming week and check. Thanks

**Comment by alan-johnson** [comment]
Any more info on this? Thanks much!

**Comment by ehennum** [comment]
@anu3990 , when you both have some time for a more extended investigation, please take a look at reproducing the issue with the zipfiles that Alan provided.  Feel free to talk to Akshay or myself to get an overview of what the setup is doing or if you run into any difficulties with the setup. Thanks.

**Comment by georgeajit** [comment]
Test added.
```
@Test
  public void testAndNotQuery() throws KeyManagementException, NoSuchAlgorithmException, IOException, ParserConfigurationException, SAXException, XpathException,
      TransformerException
  {
    System.out.println("Running testAndNotQuery");

    String[] filenames = { "constraint1.xml", "constraint2.xml", "constraint3.xml", "constraint4.xml", "constraint5.xml" };
    String queryOptionName = "valueConstraintWildCardOpt.xml";

    DatabaseClient client = getDatabaseClient("rest-admin", "x", getConnType());

    // set query option validation to true
    ServerConfigurationManager srvMgr = client.newServerConfigManager();
    srvMgr.readConfiguration();
    srvMgr.setQueryOptionValidation(true);
    srvMgr.writeConfiguration();

    // write docs
    for (String filename : filenames) {
      writeDocumentUsingInputStreamHandle(client, filename, "/structured-query-andnot/", "XML");
    }

    setQueryOption(client, queryOptionName);
    QueryManager queryMgr = client.newQueryManager();

    // create query def
    StructuredQueryBuilder qb = queryMgr.newStructuredQueryBuilder(queryOptionName);
    StructuredQueryDefinition termQuery1 = qb.term("Atlantic");
    StructuredQueryDefinition termQuery2 = qb.term("Monthly");
    StructuredQueryDefinition termQuery3 = qb.term("Bush");
    StructuredQueryDefinition andQuery = qb.and(termQuery1, termQuery2);
    StructuredQueryDefinition andNotFinalQuery = qb.andNot(andQuery, termQuery3);

    // create handle
    DOMHandle resultsHandle = new DOMHandle();
    queryMgr.search(andNotFinalQuery, resultsHandle);

    // get the result
    Document resultDoc = resultsHandle.get();
    System.out.println(convertXMLDocumentToString(resultDoc));

    assertXpathEvaluatesTo("1", "string(//*[local-name()='result'][last()]//@*[local-name()='index'])", resultDoc);
    assertXpathEvaluatesTo("0113", "string(//*[local-name()='result']//*[local-name()='id'])", resultDoc);
    
    // To test Git issue 908
    StructuredQueryDefinition termQuery11 = qb.term("Pacific");
    StructuredQueryDefinition termQuery21 = qb.term("Yearly");
    StructuredQueryDefinition termQuery31 = qb.term("DT");
    StructuredQueryDefinition andQuery1 = qb.and(termQuery11, termQuery21);
    StructuredQueryDefinition andNotFinalQuery1 = qb.andNot(andQuery1, termQuery31);
    SearchHandle results = null;
    StringBuilder searchHandleEx = new StringBuilder();
    try {
     results = queryMgr.search(andNotFinalQuery1, new SearchHandle());
    }
    catch (Exception ex) {
    	searchHandleEx.append(ex);
    }
    long res = results.getTotalResults();
    System.out.println("No query results available. Total Results should be zero: " + res);
    assertTrue("Exception should not have been thrown when no query results are available", searchHandleEx.toString().isEmpty());
    assertEquals("No query results available. Should be zero.", 0, res);

    // release client
    client.release();
  }
```
