### ISSUE TITLE
Add documentation when application developers need to close things

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#91]
Many io handles require application developers to close the InputStream or other entity received from get().  We need to clearly document when application developers have a responsibility to close connections.  Some handles off-hand to look at that might need this documentation: InputStreamHandle, ReaderHandle, InputSourceHandle, SourceHandle, JacksonParserHandle, XMLStreamReaderHandle, XMLEventReaderHandle, FileHandle, OutputStreamHandle,

**Comment by jhoy** [comment]
Milestone updated to java-client-api-3.0.3

**Comment by sammefford** [comment]
As I looked at this I found that we need new close methods, not just documentation.  So I logged #295.
