### ISSUE TITLE
Jenkins failure - add the host name to the directory to make it unique so that we can have multiple runs

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#913]
We are experiencing Jenkins failures because we have the same shared folder used by multiple runs in multiple hosts. Append host name to the folder so that they will be unique for each run and avoid failures.

**Comment by vivekmuniyandi** [comment]
We can use the same task to triage all the Jenkins failures with respect to functional tests as well and make it clean!

**Comment by vivekmuniyandi** [comment]
Ajit,

https://jenkins.marklogic.com/view/Java%20API/job/Java-client-api-develop-9.0-nightly/126/consoleFull

I see the same error and issue now as well.

chgrp: cannot access ‘/project/qa-netapp/space/dmsdk-failover/linux/java-client-api-2-1.marklogic.com-9/temp-1’: No such file or directory

The test failures are still there.

**Comment by vivekmuniyandi** [comment]
Also, can you include the changes for the other OS as well if that is applicable? It is done only for linux now.

**Comment by georgeajit** [comment]
The QA fail-over tests have been changed to use local disk fail-over. Tests are running on Jenkins environment on Linux platform. Jenkins on Windows environment will be added shortly.
