### ISSUE TITLE
Move ExtractViaTemplateListener and TypedRow to datamovement package

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#914]
Both the classes are present in example package and hence the run time jars wont have them. Move them to datamovement package.

**Comment by jmakeig** [comment]
Aside: @vivekmuniyandi, why is there a `Via` in the `ExtractViaTemplateListener` name?

**Comment by vivekmuniyandi** [comment]
We are extracting TypedRows via the TDE template supplied to the listener. Hence the name.. ExtractTemplate or ExtractRows would be ambiguous as we thought we would be extracting rows through optic queries as well in the future. Hence the name.

**Comment by vivekmuniyandi** [comment]
If it makes more sense, we can rename it to ExtractRowsViaTemplateListener?

**Comment by vivekmuniyandi** [comment]
Ajit, as a part of this, move the functional tests from the feature branch to develop and once Rob has merged the changes on to develop, create a jar out of the develop branches and make the functional tests run in the nightly regression.
