### ISSUE TITLE
Data Movement API doesn't return the results sorted

### ISSUE THREAD

**Issue by brunovianarezende** [marklogic/java-client-api#916]
* Version of MarkLogic Java Client API: 4.0.3.1
* Version of MarkLogic Server: 9.0-4
* Java version: 1.8.0_171
* OS and version: Ubuntu 16.04

I'm trying to use data movement API to export the results of a sorted query, but the returned URIs are not ordered, even inside a batch. Does data movement API support this use case?

**Comment by grechaw** [comment]
What is the query?  Did you sort by URI?

**Comment by brunovianarezende** [comment]
this is a code snippet similar to what I've done:

```
StructuredQueryDefinition query = ...
String sortOptionsXml = "<sort-order  direction=\"" + sortDirection + "\">" + "<path-index>" + sortIndex + "</path-index>" + "</sort-order>";
String queryAsXml = "<search xmlns=\"http://marklogic.com/appservices/search\">" + query.serialize()
                + "<options><search-option>filtered</search-option>\n" + sortOptions + "</options>" + "</search>"
RawCombinedQueryDefinition combinedQueryDefinition = queryManager
            .newRawCombinedQueryDefinition(new StringHandle().with(queryAsXml).withFormat(Format.XML));
```
we sort by 'sortIndex', which in our case points to a path range index, e.g. `/name`. This index is populated with string, not with URIs.

**Comment by grechaw** [comment]
From this query then, I would expect the URIs returned by the call to be in order of the value of the name element.

So are the URIs coming back in some other order?  It might be hard to tell that the URIs are indeed in the proper order.  The query seems to be valid.

**Comment by vivekmuniyandi** [comment]
While I am working to reproduce this with a small dataset, can you please confirm from where the variable sortOptions in the following line is coming from?

```
String queryAsXml = "<search xmlns=\"http://marklogic.com/appservices/search\">" + query.serialize()
                + "<options><search-option>filtered</search-option>\n" + sortOptions + "</options>" + "</search>"
```

Because we initialize the sort options to a variable called sortOptionsXml here

```
String sortOptionsXml = "<sort-order  direction=\"" + sortDirection + "\">" + "<path-index>" + sortIndex + "</path-index>" + "</sort-order>";
```

Thanks!

**Comment by vivekmuniyandi** [comment]
Since we are using filtered search, it is calling cts:search underneath and the sort order should be in effect at least at the batch level. I will create a small dataset and try and reproduce this.

**Comment by brunovianarezende** [comment]
sortOptions should actually be sortOptionsXml:

```
String queryAsXml = "<search xmlns=\"http://marklogic.com/appservices/search\">" + query.serialize()
                + "<options><search-option>filtered</search-option>\n" + sortOptionsXml + "</options>" + "</search>"
```

**Comment by vivekmuniyandi** [comment]
DMSDK splits the huge tasks into small chunks by directing the query to each forest and getting the URIs from each forest in batches. Even if we pass in the sort options, we would get an ordering per forest and not on the whole. Since we can't get a global ordering, we chose to drop the options and it doesn't make sense to have an ordering at the forest level. 

What's the use case of doing this? If this is a compelling use case, we can raise an RFE to support this in the future.

**Comment by brunovianarezende** [comment]
The use case is:

1. a user goes to a search screen and make a sorted search
2. the user see the results sorted
3. the user decides to export the results as a CSV file
4. when the user checks the CSV file, the objects are in the same order as in the search screen

However, we are not sure yet if our client would be ok with the results not sorted. We'll talk with them and if they aren't ok I'll add a comment on this ticket.
