### ISSUE TITLE
Tableau Post 4.0.4 Things 

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#917]
### PR Changes

Raise a PR against data movement components to have one final check and make changes to the README as well.

1. “testMismatchedTypes” depends on a class called “Common”; I’m assuming that’s from the src/test/java portion of marklogic-client-api, so I commented this class out - Remove Common
2. “testInvalidTypes” references “Type.SPATIAL”, but this is not part of the current develop branch of marklogic-client-test, so I commented out the part of that test that referenced SPATIAL - Add all 4 jars

### README Changes

We did add this line by mistake – “TODO Vivek, what's the best place for these?

We should include the link - https://onlinehelp.tableau.com/current/api/sdk/en-us/help.htm to guide them to the appropriate place where they can get the Tableau jars.

Nothing will be merged to java client API as development work

### QA work

Use the test we have created in the PR to accommodate that in our functional test repository. Once Rob releases it, we use that as a dependency and make changes to the test we use in the community to run it in our functional test rather than reusing what is there in our functional test. 

We do this because the community test includes all my tests as well as Ajit's test and it is the superset.

**Comment by vivekmuniyandi** [comment]
We need to make changes to this [line](https://github.com/marklogic/java-client-api/blob/4.0-master/marklogic-client-api/src/main/java/com/marklogic/client/example/cookbook/datamovement/ExtractRowsViaTemplate.java#L43) and this [line](https://github.com/marklogic/java-client-api/blob/4.0-master/marklogic-client-api/src/main/java/com/marklogic/client/datamovement/ExtractRowsViaTemplateListener.java#L80) and have a link to the actual Consumer from the data-movement-components repository once it is released!

**Comment by georgeajit** [comment]
Have a Jenkins job running on 9.0 nightly ML server. This discussion with Vivek has been implemented.

Install Tableau on the Jenkins server and install the Jars in the machine.- Set up the classpath.
Git Clone https://github.com/marklogic-community/marklogic-data-movement-components Develop repo
Move these this resources into src/main/java/com/marklogic/client/ext/datamovement/consumer folder 

``` WriteRowToTableauConsumer.java```
 
 Move these resources into ```src/test/java/com/marklogic/client/ext/datamovement/job``` folder 
```ExportRowsToTableauTest.java```
 Move into src/test/resources (the two tde files)
 https://github.com/marklogic-community/marklogic-data-movement-components/tree/master/src/tableau/test/resources
 
 Get the nighly Java Client API jar artifact into the same location as Tableau jars
 
 Modify the build.gradle to include the nightly Java Client API jar for the datamovement component project.- intead of ```compile "com.marklogic:marklogic-client-api:4.0.4"```
 
 Run the test ```ExportRowsToTableauTest``` using gradle test command.
