### ISSUE TITLE
Missing namespace in properties

### ISSUE THREAD

**Issue by brunovianarezende** [marklogic/java-client-api#918]
### OS and version: Cent0S version 7

Not sure if this is an issue in java-client-api or mlcp. I'll report it here, please correct me if I'm wrong.

I'm trying to save a document with properties by using java and after a lot of debugging I see that what is sent as metadata to MarkLogic rest api is something like:

```
<?xml version="1.0" encoding="utf-8"?><rapi:metadata xmlns:rapi="http://marklogic.com/rest-api" xmlns:prop="http://marklogic.com/xdmp/property" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"><prop:properties><schemaVersion xsi:type="xs:string">1.0</schemaVersion><test xsi:type="xs:string">my test1</test></prop:properties></rapi:metadata>
```

as you can see, the `xs:` prefix is defined in the document. If I go to query console and check the properties of the related document, by using `xdmp:document-properties`, I get:

```
<?xml version="1.0" encoding="UTF-8"?>
<prop:properties xmlns:prop="http://marklogic.com/xdmp/property">
  <schemaVersion xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">1.0</schemaVersion>
  <test xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">my test1</test>
</prop:properties>
```
note that there is no `xs` definition.

I then use mlcp to export the content from the database:

`mlcp.sh export -host localhost -port 8000 -username user -password password -output_file_path /var/opt/MarkLogic/path -output_type archive`

and when I try to re-import:

`mlcp.sh import -host localhost -port 8000 -username user -password password -input_file_path /var/opt/MarkLogic/path/ -input_file_type archive -input_compressed true`

I get the error `ERROR contentpump.DatabaseContentWriter: Error setting document properties for data://.../c6a13df8-6f85-e06c-0000-5ae9faffcbb0.json: No namespace binding for prefix`.

I reported this error at mlcp (https://github.com/marklogic/marklogic-contentpump/issues/76#issuecomment-386377504) and got as an answer: 

> In your property, you missed namespace declaration for xs.

I then changed the content of the document, by using query console and `xdmp:document-set-properties`:

```
return xdmp:document-set-properties(
  "data://development-tenant/info/340c82e5-1885-dc2b-0000-0000d4190e28.json",
<prop:properties xmlns:prop="http://marklogic.com/xdmp/property">
  <schemaVersion xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">1.0</schemaVersion>
  <test xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">my test1</test>
</prop:properties>)
```
note that I defined the `xs` prefix. And when I use  `xdmp:document-properties` I get exactly what I set:

```
<?xml version="1.0" encoding="UTF-8"?>
<prop:properties xmlns:prop="http://marklogic.com/xdmp/property">
  <prop:properties>
    <schemaVersion xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">1.0</schemaVersion>
    <test xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">my test1</test>
  </prop:properties>
</prop:properties>
```

besides that, now the mlcp export and import works without any problem.

Given the info above, I wonder who is the culprit:

1. mlcp for requiring the `xs` namespace definition
2. java-client-api for not sending some info (although I believe it sends all)
3. rest-api for not saving the `xs` namespace definition
4. me for being doing something wrong

**Comment by jmakeig** [comment]
mlcp does not use the Java Client API under the covers. It predates the Java Client and uses the lower-level [XCC](https://developer.marklogic.com/products/xcc) library. We’re tracking an issue internally to figure out how you got into this state. I’ll update the marklogic/marklogic-contentpump#76 when we come up with something. In the meantime, it sounds like explicitly declaring the `xs` namespace got you over the immediate hump. Sorry about the confusion.

**Comment by brunovianarezende** [comment]
Actually, explicitly declaring the `xs` namespace solves the problem for that document. But, then, this is just a workaround I've done in my test environment to be able to find out what is the problem. I can't explicitly set the namespace in all documents I have in production MarkLogic. Even if I could, when I create a new document, it will again miss the namespace in properties. What I fear is to have to write a in-house mlcp replacement.

Anyway, thanks for opening an internal ticket. I'll wait for a feedback from you.

**Comment by jmakeig** [comment]
Also, if this is happening on a production system and your license entitles you to support, please file a [request](https://help.marklogic.com).
