### ISSUE TITLE
Add ProgressListener to the list of Listeners

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#930]
A progress listener tracks the progress of the QueryBatcher and have the progress published to consumers registered with the listener.

[PR 928](https://github.com/marklogic/java-client-api/pull/928)

This will be used to track the PR and add functional tests and documentation

**Comment by vivekmuniyandi** [comment]
https://github.com/marklogic/java-client-api/pull/932

**Comment by vivekmuniyandi** [comment]
This is pushed in https://github.com/marklogic/java-client-api/tree/post4.1 branch

**Comment by georgeajit** [comment]
Information available in Java Client API documentation.
