### ISSUE TITLE
Change to Okhttp Connection Management

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#935]
We left this when we made the switch to Okhttp

https://docs.marklogic.com/guide/java/intro#id_51879

It still refers to old Apache ThreadSafeClientConnManager but we use Okhttp connection pool internally. 

A connection pool is configured to have 100 connections, which means a maximum of 100 HTTP socket connections per DatabaseClient object.

We make 5 idle connections initially and not 100. We would need to decide if we need to change this to how it was. 

" implementing HttpClientConfigurator and calling its configure method" - We use OkHttpClientConfigurator.

**Comment by kcoleman-marklogic** [comment]
This fix is in progress and will be released with 9.0-7. This issue never migrated into bugtrack for some reason, but it is fixed as part of 50253.

**Comment by georgeajit** [comment]
Verified the Java Client API Guide on 06/25/2019.  Shipping this issue. Milestone on server build was 9.0.7 for the docs team. Refer to 50253 on the internal bug tracking site.
