### ISSUE TITLE
Provide more helpful message when resource not found error occurs

### ISSUE THREAD

**Issue by rjrudin** [marklogic/java-client-api#939]
As a Java Client user, and specifically an ml-gradle user that is loading modules via the Java Client
I want the Java Client to suggest what the problem might be when e.g. loading REST modules and a 404 error occurs
So that I have a better idea of how to fix the situation and I don't have to bug the ml-gradle developers about it

- The code in OkHttpServices.java for handling a 404 currently has a message of 'type + " not found for write"', e.g. "/config/query not found for write"
- When this error occurs, it seems likely that the client is talking to an ML app server that doesn't use the REST rewriter, or that rewriter doesn't have /config/query mapped in it
- Thus, I think it's reasonable for the error message to suggest this - i.e. "/config/query not found for write; please verify that the app server that you're connecting to is using the REST API rewriter and that /config/query is mapped within the rewriter"
- Bonus points if the error message can include the port that the user is connecting to, though it wasn't clear to me if the port can be determined within OkHttpServices.java

**Comment by kcoleman-marklogic** [comment]
>"/config/query not found for write; please verify that the app server that you're connecting to is using the REST API rewriter and that /config/query is mapped within the rewriter"

That is addressing the problem at too low a level, IMO. User unit of user interaction is a REST API instance, and we should talk about it in those terms. 

Yes, it is possible for someone to totally screw themselves up by stomping all over the REST instance rewriter, but that's a pathological case, whereas simply attempting to connect on a vanilla HTTP app server port is not.

**Comment by rjrudin** [comment]
That's a good point about the modified REST rewriter. And if just saying something like "It's not a valid REST API instance" is understood, I'm good with that.

**Comment by georgeajit** [comment]
Closing the issue.
