### ISSUE TITLE
integration of base classes for API First into internal libraries

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#943]
Subtask of internal issue DHFPROD-619

**Comment by ehennum** [comment]
Sending over to you, Vivek, for the OKHttpServices integration.  When that's done, please send back to me for cleanup on the base class for API First.

**Comment by vivekmuniyandi** [comment]
Done with the integration and sending this back to you Erik!

**Comment by ehennum** [comment]
The Java test classes generated from the *.api files by API First will need to be regenerated.  

After that that, if there are no regressions, this issue can be closed.
