### ISSUE TITLE
contributing.md is only reachable from develop branch

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#944]
README.md refers the reader to CONTRIBUTING.md for contribution guidelines, but that link only works if you're on the develop branch. From 4.0-master or master, you get a 404. I confess I did not reach back as far as the 3.0 branches.

Maybe the source never made it on to those branches?

**Comment by vivekmuniyandi** [comment]
Yes, I think that was missed out when we did the merge from develop to 4.0 master. CONTRIBUTING.md was recently moved to .github folder when we created the issue template and the pull request template. I will add a commit to 4.1 branch to explicitly add the CONTRIBUTING.md and I will make sure that when we do the merging, CONTRIBUTING.md is added to the 4.0-master. 

We need to make sure after 4.1.1 is released, CONTRIBUTING.md is present when we do the merge. No change is required for develop branch though. 

@georgeajit please ship it once we make sure we have CONTRIBUTING.md in the 4.0-master branch after 4.1.1 release.

**Comment by georgeajit** [comment]
The link is available as of 4.1.1 release.
