### ISSUE TITLE
generate JavaDoc comments as part of API First class

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#950]
The desc properties of the service, function, parameter, and return value should appear in JavaDoc comments

Internal issue 1026

**Comment by ehennum** [comment]
The test is in 

marklogic-development-tools/src/test/java/com/marklogic/client/test/dbfunction/positive/DescribedBundleTest.java

Does that seem sufficient?

**Comment by georgeajit** [comment]
The desc properties of the service, function, parameter, and return value does appear in JavaDocs. When user hovers over the class declaration in Eclipse IDE, the descriptions are visible.
