### ISSUE TITLE
utility to generate main module stub from an API declaration

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#951]
A utility should produce an SJS or XQuery main module with externally assignable variables from an API First function declaration.
 
Internal issue 618

**Comment by ehennum** [comment]
The tests are in

marklogic-development-tools/src/test/java/com/marklogic/client/test/dbfunction/generated/ModuleInitSjsBundleTest.java

and

marklogic-development-tools/src/test/java/com/marklogic/client/test/dbfunction/generated/ModuleInitXqyBundleTest.java

Do those seem sufficient?

**Comment by georgeajit** [comment]
The tests are running fine. Performed the following manual tests.

Ran the module generation utility for SJS and XQY types.
Ran the utility when existing SJS or XQY file is present.
Ran the utility when either one of SJS or XQY file is present.
