### ISSUE TITLE
build jar for development tools providing API First

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#952]
The Gradle build should produce a jar so adopters can use the API First utilities without having to build the API First utilities.

Internal issue 1027

**Comment by ehennum** [comment]
The jar isn't published as a Gradle plugin yet, but once it is, it should be possible to use the API First utilities simply by adding a dependency on the plugin jar.

**Comment by georgeajit** [comment]
Able to generate the Jar. Publish to maven local repository and then run gradle tasks from a sample build.gradle of a project with dependency on the development jar.

Publish gradle plugin is yet to be done.
