### ISSUE TITLE
get error responses in a consistent format

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#955]
The Java API should set the X-Error-Accept header (my expectation would be to application/json) to get the server to return error messages in a consistent format.

That's especially important for API First.

Vivek, do you have the bandwidth to make this change?  If not, please send it back to me.

**Comment by vivekmuniyandi** [comment]
Have added the header to include in each API first call request to the server. However, there is a bug on the server which is not setting the response to the type set by X-Error-Accept (https://bugtrack.marklogic.com/50434). Hence I have made changes to accommodate json format and if there is another format of the response coming in, we check for the most common cases - 401, 403 and 404. 

This may get postponed to a subsequent release as well depending on the server bug.

**Comment by ehennum** [comment]
Sending this to test merely for awareness that the server bug cited in the previous comment was fixed -- in case any regressions in the error processing behavior appear.

**Comment by georgeajit** [comment]
No errors seen on 4.1.1-develop branch for Jenkins runs. Shipping the issue.
