### ISSUE TITLE
relax expression typing in the Optic builder

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#960]
Server-side expressions perform type coercion on arguments.  In addition, server-side expressions support operator overloading (as in numeric and temporal addition).  

Although strong types are desirable in a builder for better IDE support and error prevention, limiting server expressions is not acceptable.

The tasks to fix the issue by relaxing the expression typing:

*  Introduce a general ServerExpression type that's the base of all existing expression types.
*  Provide a of() varargs fluent on ServerExpression to build up a sequence of expressions and/or literal values.  
*  Change the type of all parameters of expression functions and operators to ServerExpression.
*  In the JavaDoc for expression functions, document the server data type for each parameter and the return value with links to JavaDoc pages for the server data types.
*  On the JavaDoc page for each server data type, provide links to more general and specific server data types as well as a list of expression functions that return the server data type.
*  Deprecate all expression types and literal value sequences in favor of ServerExpression.
*  Remove all expression types and literal value sequences in a future release.

Literal values still need to be strongly typed for unmarshalling on the server.  While literal value sequences must be deprecated, the literal value types must be retained as well as the constructors for literal value types and the overloads providing implicit casts on literal values.

This issue supersedes #927 

See also internal server bug 49892

**Comment by ehennum** [comment]
For 4.2 (assuming that the schedule for 4.1.1 is booked), it would be good to run the Java Optic tests against this branch before merging the branch into the Java API.

The changes should cause no regressions other than deprecation messages.

Ideally, we would also fork the existing Java Optic tests and do a global find-and-replace that substitutes ServerExpression as the data type of all variables that capture the return value of a function and currently have a *Expr name.  The modified tests should also not cause any regressions.

**Comment by georgeajit** [comment]
No regressions on develop with both 9.0.7.1 and nightly builds.

**Comment by ehennum** [comment]
@georgeajit , did the tests run without regression against the issue960 branch?  If so, I'll merge it into develop.

**Comment by georgeajit** [comment]
No Failures seen in ```issue960``` branch. Both ```RowMangerTest``` and ```RowRecordTest``` tests passed.

**Comment by ehennum** [comment]
Excellent.  I will merge.
