### ISSUE TITLE
renaming per terminology decisions

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#966]
As captured in internal issue DHFPROD-770

Old	New	Purpose
functionFile	endpointDeclarationFile	the property of the initializeModule task identifying a *.api file
generateProxy	generateEndpointProxies	the task to generate the service class
GeneratorTask	EndpointProxiesGenTask	the task type that implements generateProxy
serviceBundleFilename	serviceDeclarationFile	the property of the generateProxy task identifying the service.json
proxyConfig	endpointProxiesConfig	the configuration of the generateProxy task

**Comment by georgeajit** [comment]
No regressions on Jenkins due to terminolgy changes. Manual tests using new terms ran fine, while class generation from .api was being done.
