### ISSUE TITLE
Database Client request slow if the service idle for more than 2 minutes

### ISSUE THREAD

**Issue by Jacky20180725** [marklogic/java-client-api#967]
We are using springboot web application to read and write marklogic and there is only 1 Database Client created for the whole application. the first time access the service to read 1 doc need 2 more seconds but the following request response less than 100 ms. and if the service idle more than 2 minutes and then access again need 2 more seconds.
Is it because keepalive time out and the Okhttp client need to reinitialize?
anything I can do?

Thanks.
###########################
Version of MarkLogic Server : 8
Java version :     1.8
Linux 
Java client api : 4.04
Okhttp-digest : 1.15
###########################

**Comment by srinathgit** [comment]
Is the app server set to 'digest' authentication ?  In order to generate a pseudorandom number for client nonce in digest authentication, Java 8 by default uses /dev/random and it is a blocking call. If the entropy pool exhausts, it will block until sufficient entropy is available to return a pseudorandom number. A workaround is to make Java use /dev/urandom instead which is non-blocking. However, it can result in a lower quality random numbers if the entropy pool runs out.

**Comment by Jacky20180725** [comment]
Hi,

Actually I am not so sure which part costs the time. I want to add some log to the OkhttpClientConfigurator but don't know how to do it , any suggestions?
Thanks.

**Comment by vivekmuniyandi** [comment]
Before we debug this any further, can we have the workaround mentioned in https://github.com/marklogic/java-client-api/issues/967#issuecomment-407822829 in place and check if that solves the issue?

See this for more information - https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html

**Comment by Jacky20180725** [comment]
@vivekmuniyandi @srinathgit 
Thanks so much. already apply this. getting better now. but still some issue.
1. the first request after several minutes idle still takes around 500ms slower than the following request and it seems like it's from the marklogic rest server side.
2. sometimes there is Exception java.io.IOException: unexpected end of stream on Connection. see the second request.

**1 request after idle for several minutes**
07/26/2018 03:02:49.397  Reading metadata and content for /cvsearch/smartsearch/HG99740.xml
07/26/2018 03:02:49.424  HttpRequest :--> GET http://eqrml2s.nam.nsroot.net:10086/v1/documents?category=content&uri=/cvsearch/smartsearch/HG99740.xml&database=cvcontent http/1.1
07/26/2018 03:02:49.967  HttpRequest :<-- 200 OK http://eqrml2s.nam.nsroot.net:10086/v1/documents?category=content&uri=/cvsearch/smartsearch/HG99740.xml&database=cvcontent (542ms, 616-byte body)
07/26/2018 03:02:50.007  HttpRequest  [/cv-smartsearch-0.0.1/smart/queryUserProfile] costs 613 ms
**second request less than a minute**
07/26/2018 03:03:48.527  Reading metadata and content for /cvsearch/smartsearch/HG99740.xml
07/26/2018 03:03:48.530  HttpRequest :--> GET http://eqrml2s.nam.nsroot.net:10086/v1/documents?category=content&uri=/cvsearch/smartsearch/HG99740.xml&database=cvcontent http/1.1
07/26/2018 03:03:48.535  HttpRequest :<-- HTTP FAILED: java.io.IOException: unexpected end of stream on Connection{eqrml2s.nam.nsroot.net:10086, proxy=DIRECT hostAddress=xxxxxx.nam.nsroot.net/xxx.xxx.xx.xx:xxxx cipherSuite=none protocol=http/1.1}
07/26/2018 03:03:48.599  HttpRequest :--> GET http://eqrml2s.nam.nsroot.net:10086/v1/documents?category=content&uri=/cvsearch/smartsearch/HG99740.xml&database=cvcontent http/1.1
07/26/2018 03:03:48.622  HttpRequest :<-- 200 OK http://eqrml2s.nam.nsroot.net:10086/v1/documents?category=content&uri=/cvsearch/smartsearch/HG99740.xml&database=cvcontent (22ms, 616-byte body)
07/26/2018 03:03:48.627  HttpRequest  [/cv-smartsearch-0.0.1/smart/queryUserProfile] costs 101 ms

**Comment by georgeajit** [comment]
Closing this issue due to no further actions/inputs.
