### ISSUE TITLE
Deprecate XOMHandle

### ISSUE THREAD

**Issue by jmakeig** [marklogic/java-client-api#968]

**Comment by ehennum** [comment]
@anu3990 , I believe this fix:

    https://github.com/marklogic/java-client-api/issues/997

neglected to add the deprecated tag to 

    https://github.com/marklogic/java-client-api/blob/4.1.1-develop/marklogic-client-api/src/main/java/com/marklogic/client/extra/xom/XOMHandle.java

in the 4.1.1-develop branch.

**Comment by anu3990** [comment]
Added change - https://github.com/marklogic/java-client-api/pull/1005

**Comment by georgeajit** [comment]
Refer #997
