### ISSUE TITLE
rename com.marklogic.client.tools to com.marklogic.ml-development-tools for consistency

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#977]
Follow the pattern provided by com.marklogic.ml-data-hub and com.marklogic.ml-gradle

**Comment by ehennum** [comment]
Here's an example of what needs to change in the tests:

https://github.com/marklogic/java-client-api/commit/8f5af994d48fdd3c4ae51c3886e41e893d8a7450#diff-0e313d4c42335b5d4b4a0fa1db9a58ca

**Comment by georgeajit** [comment]
Done with building, publishing and testing the plugin.
