### ISSUE TITLE
update version number in gradle.properties

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#984]
from 4.0.4 to 4.1.0

**Comment by ehennum** [comment]
Should have no repercussions other than fixup on the version number

**Comment by kkanthet** [comment]
@ehennum  you don't have to do this . this is part of release step, i update the version usually from SNAPSHOT to the release version but in this case since its a branch it was not SNAPSHOT  , i updated from 4.0.4 to 4.1.0 before building the final packages
