### ISSUE TITLE
Throw Exception in DMSDK if the ML server we are contacting is not version 9

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#985]
When DMSDK is run with ML server 8, it throws a weird error as to forestinfo endpoint not found as it is supported only with ML server 9. 

We should throw a suitable exception accordingly if the contacted ML server is 8.0 version.

In DataMovementServices, readForestConfig() method, we make the actual call to internal/forestinfo endpoint. We need to either make a rest call for the first call to readForestConfig() (subsequent calls during failover need not make this call) to find out the version and throw an appropriate exception.

**Comment by ehennum** [comment]
Given that 9 is end of life, we no longer need to carry this issue.
