### ISSUE TITLE
Update batch's client for the QueryBatch during failover

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#986]
The IteratorTask iterates through the URIs and creates QueryBatches and add it to the threadpool queue. When we have a connection exception, the failed batch needs to be retried with the help of RetryListener. For the remaining batches that are queued, we need to update the the current client in the QueryBatch with an appropriate client. Else, it would connect, fail and retry. We want to avoid the failure part.

In cleanupExistingTasks() of QueryBatcherImpl, we drain the list of tasks in the queue and iterate through it and add them back. We need to make 'processBatch' of IteratorTask class in QueryBatcherImpl, a thread class instead of an anonymous Runnable and we should see if the task is an instance of 'ProcessBatch' and update the client accordingly if the batch has a client for the host which is not reachable.

Something similar to what we do in retryListener of QueryBatcherImpl.

**Comment by ehennum** [comment]
Alternatively, we could refactor with late binding between query batches and clients
