### ISSUE TITLE
Increase parallelism in QueryBatcher

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#987]
Right now, in QueryBatcher, what we do is create a Runnable task per forest to retrieve the first batch from each forest and that Runnable task is responsible for populating the Runnable task to get the subsequent batches.

If we have an estimate of total results per forest, we can spawn multiple threads to retrieve results parallelly. All we have right now is concurrency at a forest level. But within the forest, we retrieve the results sequentially. 

If we can do something to increase the parallelism in getting results parallely within the forest, we can increase the throughput of the retrieval. One example could be instead of launching 1 thread per forest, based on an estimate on the number of results in a forest, we can spawn multiple threads, each retrieving a part of results from the server. Since we are not worried about the order of retrieval here, spawning multiple threads at a forest level, won't affect here.

**Comment by vivekmuniyandi** [comment]
We need not even know the size of the results per forest. Assuming a evenly distributed load among the forests, we can split the number of threads (if a threadcount is given to the QueryBatcher) among the forests (lets say this count as forestThreadCount) and have forestThreadCount number of Runnable tasks spawned per forest and each will retrieve one batch.

For example, if there are 3 forests totally and if the threadCount specified is 11, we can assume an even load among the forest and have 3 Runnable (QueryTask Runnable) objects for the first forest, 4 for the second forest and 4 for the third. 

At the forest level, If there are 97 results in a forest, and the batch size is 10, the number of threads for this forest is 3, the first Runnable task will get 1-10, the second Runnable task will get 11-20 and the third will get 21-30.

The first Runnable task would be responsible for spawning the QueryTask Runnable task for getting the next batch 31-40, 61-70, 91-97 and it should stop since the batch size is not full.

The second Runnable task would be responsible for spawning the QueryTask Runnable task for getting the next batch 41-50, 71-80 and it should spawn the next batch from 101-110 but should stop when we get an exception from the server that there is no start value for 101.

Similarly for the third Runnable task. This way we efficiently utilize the threadpool in the QueryBatcher Query flow.

**Comment by vivekmuniyandi** [comment]
The above approach would be affected and the threads won't be evenly distributed if the number of forest results are skewed. Hence if the cost of calculating the total number of results per forest is small, then we can evenly distribute the threads based on the forest results and assign more threads to the forest having larger result set. I think the rest api does a search and retrieves a subsequence based on the start and batch size for every request, and it won't be a big overhead to calculate the size of the forest results.

**Comment by ehennum** [comment]
Superseded by internal issue JAVA-195
