### ISSUE TITLE
manage cookies for Transaction.readStatus() 

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#989]
The Transaction.readStatus() method does not work with a load balancer because it doesn't call addTransactionScopedCookies() to manage the cookies used for host affinity.

Tracked as server bug 50603

**Comment by ehennum** [comment]
Should cause no regressions.  

After ELB configuration to use hostId, GenericDocumentTest.testCommit() should run to completion successfully.

**Comment by ehennum** [comment]
With help from Matt and Hongyang, I confirmed that GenericDocumentTest.testCommit() now runs to completion successfully for an ELB configured for HostId.

**Comment by georgeajit** [comment]
Tested by Srinath. Will be testing one final round.
