### ISSUE TITLE
Determine the ideal value for maxIdleConnections in the ConnectionPool

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#990]
The Okhttp client uses a ConnectionPool internally to reuse existing connections instead of creating new connections every time. In OkhttpServices, we use the default setting for the maxIdleConnections of ConnectionPool which is 5. But when we use the QueryBatcher to do a large query job (Iterator code flow), we see a lot of time waits (TIME_WAIT) when queried against a cluster. This does not reproduce when we try against a single node. 

This issue is to track and decide if we need to change the underneath maxIdleConnections to a reasonable value which can avoid these TIME_WAITS. I don't see a considerable difference in performance. But it is good to have a reasonable number of maxIdleConnections to make sure we are having the right setting to accommodate large number of threads creating connections.

Akshay will talk with Silvano to get an idea of the performance hit with the time waits and update the issue.

**Comment by georgeajit** [comment]
This issue is being investigated internally by performance team.
