### ISSUE TITLE
run the DMSDK tests from the DHaaS middle tier

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#993]
To test early, it would be beneficial to run the tests with both middle tier and database cluster in the cloud before DHaaS is available.

The tests should use ALB, where the load balancer is specified as the white list for DMSDK.

**Comment by srinathgit** [comment]
Database client object was created with ConnectionType.GATEWAY.
The DMSDK tests were run from 
1. local machine against a provisioned MarkLogic cluster, a MarkLogic instance with full access to 8002.
2. from a client machine in a vpc against provisioned cluster in another VPC
The tests were run multiple times and the tests have passed without any issues.
