### ISSUE TITLE
Some documents not getting transformed after failover on AWS

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#996]
So we can address your issue, please include the following:
### Version of MarkLogic Java Client API
See Readme.txt

### Version of MarkLogic Server
9.0-nightly (08282018)
See admin gui on port 8001 or run xdmp:version() in Query Console - port 8000)

### Java version
8
Run `java -version`

### OS and version

For MAC, run `sw_vers`. \
For Windows, run  `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`\
For Linux, run `cat /etc/os-release` and `uname -r`

### Actual output: What did you observe? What errors did you see? Can you attach the logs? (Java logs, MarkLogic logs)
An ApplyTransformListener was added to QueryBatcher and a forest failover was triggered during the run. I see that not all documents were transformed. I will add the logs to the case soon.

### Expected output: What specifically did you expect to happen?
All document uris returned by  querybatcer has to be transformed

**Comment by georgeajit** [comment]
Can you revisit this issue and provide some more input?
