### ISSUE TITLE
provide XOM support as source only

### ISSUE THREAD

**Issue by ehennum** [marklogic/java-client-api#997]
Continue to provide the sources for XOM support without incurring a build dependency for the sake of adopters who are uncomfortable with the XOM license.

**Comment by ehennum** [comment]
There may be more to do to remove the XOM dependency.  I'm able to run Gradle builds without issue, but Intellij is reporting an error.

The cause of the error in Intellij might be something to do with the IDE-Gradle integration.

If you run into errors with the Gradle build, please send this issue back to me.

**Comment by georgeajit** [comment]
Compilation errors appear when dependency is not included. Following the instructions in ```build.gradle ``` makes a clean build.
